### ISSUE TITLE
Error message when saving png

### ISSUE THREAD

**Issue by lilive** [mypaint/mypaint#394] opened 2015-08-04 11:25 UTC
Hi,
First I want to say Bravo for MyPaint!
I've got an error message when saving a file as png:
```python
Mypaint version: 1.2.0-beta.0+gitexport.adc9031
System information: Windows-7-6.1.7601-SP1
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\share\mypaint/gui/filehandling.py", line 586, save_cb(self=<gui.filehandling.FileHandler object>, action=<Action object at 0x995f910 (GtkAction at 0x997b850)>)
            if not self.filename:
                self.save_as_cb(action)
            else:
  variables: {'action': ('local', <Action object at 0x995f910 (GtkAction at 0x997b850)>), 'self.save_as_cb': ('local', <bound method FileHandler.save_as_cb of <gui.filehandling.FileHandler object at 0x0000000009952d90>>)}
  File "C:\Program Files\MyPaint\share\mypaint/gui/filehandling.py", line 608, save_as_cb(self=<gui.filehandling.FileHandler object>, action=<Action object at 0x995f910 (GtkAction at 0x997b850)>)
            else:
                self.save_as_dialog(self.save_file, suggested_filename=current_filename)
  variables: {'suggested_filename': (None, []), 'self.save_file': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x0000000009952d90>>), 'self.save_as_dialog': ('local', <bound method FileHandler.save_as_dialog of <gui.filehandling.FileHandler object at 0x0000000009952d90>>), 'current_filename': ('local', '')}
  File "C:\Program Files\MyPaint\share\mypaint/gui/filehandling.py", line 670, save_as_dialog(self=<gui.filehandling.FileHandler object>, save_method_reference=<bound method FileHandler.save_file of <gui.filehandling.FileHandler object>>, suggested_filename='', start_in_folder=None, export=False, **options={'alpha': None})
                        else:
                            save_method_reference(filename, **options)
                        break
  variables: {'options': ('local', {'alpha': None}), 'save_method_reference': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x0000000009952d90>>), 'filename': ('local', u'E:\\Julie\\essais\\test.png')}
  File "C:\Program Files\MyPaint\share\mypaint/gui/drawwindow.py", line 83, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'E:\\Julie\\essais\\test.png',), **kwargs={'alpha': None})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'self': ('local', <gui.filehandling.FileHandler object at 0x0000000009952d90>), 'args': ('local', (u'E:\\Julie\\essais\\test.png',)), 'func': ('local', <function save_file at 0x00000000099e50c8>), 'kwargs': ('local', {'alpha': None})}
  File "C:\Program Files\MyPaint\share\mypaint/gui/filehandling.py", line 380, save_file(self=<gui.filehandling.FileHandler object>, filename=u'E:\\Julie\\essais\\test.png', export=False, **options={'alpha': None, 'render_background': True})
                thumbnail_pixbuf = self.doc.model.render_thumbnail(**options)
            helpers.freedesktop_thumbnail(filename, thumbnail_pixbuf)
  variables: {'thumbnail_pixbuf': ('local', <Pixbuf object at 0xa699550 (GdkPixbuf at 0xb7772a0)>), 'helpers.freedesktop_thumbnail': ('global', <function freedesktop_thumbnail at 0x0000000007eebe60>), 'filename': ('local', u'E:\\Julie\\essais\\test.png')}
  File "C:\Program Files\MyPaint\share\mypaint/lib/helpers.py", line 167, freedesktop_thumbnail(filename=u'E:\\Julie\\essais\\test.png', pixbuf=<Pixbuf object at 0xa699550 (GdkPixbuf at 0xb7772a0)>)
        uri = _filename2uri_freedesktop_canon(os.path.abspath(filename))
        logger.debug("thumb: uri=%r", uri)
  variables: {'os.path.abspath': ('global', <function abspath at 0x00000000021ce9b0>), '_filename2uri_freedesktop_canon': ('global', <function _filename2uri_freedesktop_canon at 0x0000000007ee60c8>), 'uri': (None, []), 'filename': ('local', u'E:\\Julie\\essais\\test.png')}
  File "C:\Program Files\MyPaint\share\mypaint/lib/helpers.py", line 308, _filename2uri_freedesktop_canon(path=u'E:\\Julie\\essais\\test.png', encoding='mbcs')
        path_bytes = path.encode(encoding)
        return GLib.filename_to_uri(path_bytes, None)
  variables: {'None': ('builtin', None), 'path_bytes': ('local', 'E:\\Julie\\essais\\test.png'), 'GLib.filename_to_uri': ('global', gi.FunctionInfo(filename_to_uri))}
Error: g-invoke-error-quark: Could not locate g_filename_to_uri: 'g_filename_to_uri': La procédure spécifiée est introuvable. (1)
```
To reproduce this I do:
- Launch MyPaint
- Draw a single stroke
- File > Save
- Choose folder E:\Julie\essais
- Choose file name test.png
- Hit Save button

I've got an error message but the file is correctly created.

**Comment by achadwick** [comment] 2015-08-04 11:31
Duplicate of #374 I think.

This should be gone in the most recent beta, v1.2.0-beta.0.73. Please [upgrade](https://github.com/mypaint/mypaint/releases/tag/v1.2.0-beta.0) and try again - that should fix the problem.

If upgrading doesn't resolve the problem for you, please reopen this issue and I'll take another look at it.

**Closed by achadwick** 2015-08-04 11:31 UTC

**Comment by achadwick** [comment] 2015-08-04 11:34
More keywords. I guess the search button in the exception dialog isn't working?

**Comment by achadwick** [comment] 2015-08-04 11:46
> I guess the search button in the exception dialog isn't working?

No, that seems OK. The "Search Tracker…" and "Report…" strings just aren't [translated into French](https://hosted.weblate.org/engage/mypaint/fr/) yet. (They're not very clear instructions anyway - but I had to keep them short for the sake of the dialog and horizontal space :unamused:. Sorry!)

**Comment by lilive** [comment] 2015-08-04 12:19
> This should be gone in the most recent beta, v1.2.0-beta.0.73. Please upgrade and try again - that should fix the problem.

Yes it fix the problem. It wasn't clear to me which version to choose in the [download page](https://github.com/mypaint/mypaint/releases). I could figure that beta.0.73 is after beta.0

>  I guess the search button in the exception dialog isn't working?

Yes it works. It doesn't give me any result when I tried it for another problem, so I forgot to use it again.
Instead I did a manual search before posting with the word 'save' and didn't find #374. I could try 'saving' too.

So, it appear to me that I wasn't very clever this time :flushed: 
Sorry about that...

**Comment by achadwick** [comment] 2015-08-04 12:28
Okay, not a problem really :smiley:
Thank you for confirming that it's fixed. I'll be sure to mark more clearly "little" point like that one releases which don't have their own tag as very minor bugfixes. Really I should be more frequent with the real timeline releases though...!
