### ISSUE TITLE
Keyboard Shortcuts stop working after a while

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#190] opened 2015-02-08 10:58 UTC
OS: Windows 8.1
Tablet: Monoprice 4x3" (Drivers are up to date)
MyPaint Version: 1.1, February 6th 2015 build by tumagonx from his website: http://opensourcepack.blogspot.com/2013/01/mypaint-and-pygi.html

I'm not really sure how to explain or how to duplicate this issue. After using quite a few keyboard shortcuts, MyPaint doesn't respond to keyboard strokes at all, and only responds to mouse clicks. Minimizing/restoring the window doesn't fix the issue.
Restarting the program works only for a short while, but after using many keypresses, the same thing happens again.
It's also not limited to only a select few shortcuts, it won't respond to ANY keystrokes.

Update: I'm not entirely sure how, but the program responded to my keystrokes again. It happened after I unchecked the "show background" box while I was drawing, and after I switched between my browser and the program to type this up. Not sure if the "show background" option is at all related to the issue coming and going.
Update 2: The issue appears to occur again after I pick a color from the "current color" button by the "current brush" button.

**Comment by achadwick** [comment] 2015-02-13 10:03
It has the sense of a keyboard grab or focus issue, but I can't figure out what. Anyone able to reproduce?

That's MyPaint version 1.1.1-alpha, right? Please have a look in the about box and paste the full version number including the hex number in the build bit on the end.

**Comment by AtsusaKaneytza** [comment] 2015-02-14 22:02
1.1.1-alpha.20150211+git.72d08ef

Is that it?

**Comment by achadwick** [comment] 2015-02-14 22:38
That's the one, thanks.

**Comment by achadwick** [comment] 2015-05-01 17:37
@AtsusaKaneytza is this still happening? Sorry for not chasing on this one.

**Comment by achadwick** [comment] 2015-05-01 17:40
Oh wait, just saw your updates @AtsusaKaneytza :+1: 

> Update: I'm not entirely sure how, but the program responded to my keystrokes again. It happened after I unchecked the "show background" box while I was drawing, and after I switched between my browser and the program to type this up. Not sure if the "show background" option is at all related to the issue coming and going.
> Update 2: The issue appears to occur again after I pick a color from the "current color" button by the "current brush" button.

@AtsusaKaneytza what do you mean by the ""current color" button by the "current brush" button"? Are those the two dropdowns in the toolbar?

-------------------------

Minor note: can you write updates as fresh comments in future please? Otherwise we don't get notified about them and start treating the issue report as stale :(

**Comment by achadwick** [comment] 2015-05-01 17:41
**Triage note:** hopefully just needs testing now: I think those are steps to reproduce, if my hunch is correct!

Bumping to the beta cycle since I doubt this will need any string fixes.

**Comment by AtsusaKaneytza** [comment] 2015-05-20 21:23
Sorry about the lack of feedback
I'm using the latest version for Windows from tumagonx's website: 1.2.0-alpha.20150504+git.a80a54b
The issue still persists: after picking a color this way, it results in the program becoming unresponsive to keyboard input for a little while.
![image](https://cloud.githubusercontent.com/assets/8382492/7736824/2e8da4c6-ff0c-11e4-9407-6281af9ba9c0.png)

**Comment by achadwick** [comment] 2015-05-21 19:57
Oh bother. I've just committed a bunch of code that moves the picker and details button down to the bottom left and gets rid of that dropdown (there's now a more featureful popup on the footer colour rectangles now, and a similar arrangement for picking "context" and choosing brushes on the right hand side...).

The grabs for the corner buttons got recoded, and that sounds like something that could screw up a windowing environment (there are (or rather were) keyboard grabs...). It's a bit late to reproduce it the way you mentioned now, sadly.

Can you do me a favour and test it out with the bottom-right "context" picker button too when you see something like

![image](https://cloud.githubusercontent.com/assets/61299/7757562/4d2d47fc-fffb-11e4-8bdf-9b7833f3bb68.png) - click it and pick a brushstroke off the canvas :)

appear in @tumagonx 's build? Look in the lower-right corner for it. If the picker grab there doesn't screw up your keyboard, that tells me we're onto the right approach here :D

(Apologies for this, code updates crossing this report...)

**Comment by achadwick** [comment] 2015-05-21 21:40
I can't reproduce this one in Win7 64bit using the "context" picker above (either click, or click-and-drag), or the same for this one on the toolbar

![image](https://cloud.githubusercontent.com/assets/61299/7759542/3252eb6c-000a-11e5-98d4-3623810e299e.png)

for the "are keys still working?" part of the test, I'm using the "X" key popup, i.e. colour history. That works fine after any picker is used on my system.

**Comment by AtsusaKaneytza** [comment] 2015-05-21 23:36
Same thing happens with the color pickers in the bottom left of the window. Doesn't respond to keystrokes, and the only fix is pressing "Esc" like you told me before.

**Comment by achadwick** [comment] 2015-05-22 09:08
@AtsusaKaneytza what specific version did you test with in [your last comment](#issuecomment-104450739) please? Could you go to the about box please (Help→About MyPaint) and paste the long version string you find there? Thanks.

(The way grabs are handled for that colour picker button changed quite a lot very recently, and the @tumagonx builds may not have them yet)

**Comment by AtsusaKaneytza** [comment] 2015-05-23 05:35
Version 1.2.0-alpha.20150504+git.a80a54b

**Comment by achadwick** [comment] 2015-05-23 15:42
Okay, a80a54b is from before the recent grab changes. Gives me a baseline to test with, anyway.

I can reproduce this in Win7 on a VM with the old a80a54b with this picker, and this one only:

![steps](https://cloud.githubusercontent.com/assets/61299/7784768/6e82a248-0169-11e5-94e1-e2deae28680e.png)

Start in a condition where the "L" key shows and hides the layers panel as normal.

1. Click the colour dropdown button.
   * Dropdown shows
   * Press "L" at this point to to and show/hide the layers tree.
      * This doesn't work, but at this point that is intentional - the dropdowns are supposed to eat keyboard input while they're showing
2. Click the picker button
   * Dropdown stays open, cursor changes
3. Hold/drag/release on the canvas to pick
   * When button1 is released, the dropdown folds away as it should
   * Press "L" at this point to to and show/hide the layers tree.
      *This should work again now, but it doesn't - 100% of the time for me

This looks like the dropdown's grab interacting badly with the picker's grab (menu/dropdown windows disappearing can be unhealthy for active grabs, and there are a few "grab broken" messages in the log hinting at this too). However for the development mainline it's not something to worry about - that particular dropdown has been replaced a few days ago, *after* a80a54b!

-------------------------

I cannot reproduce this in a80a54b with the bottom left picker, even tried clicking on it over and over again in case it was a focus thing. Trying again on master.

**Comment by achadwick** [comment] 2015-05-23 15:58
On master, as of eadce632012eb829bd2c8dbb17f1ff1675d085e1 (May 21 2015) now.
Can't reproduce this on Win7 with the bottom left colour picker or the bottom right brushstroke one (they share the same grab code, which is quite different from the older commit a80a54b above)

Version of GTK used for these tests:

    $ pkg-config --modversion gtk+-3.0
    3.16.3

This problem may have gone away in the most recent merges to the dev master, but I'd appreciate any testing at or after eadce632012eb829bd2c8dbb17f1ff1675d085e1 (May 21).

**Comment by AtsusaKaneytza** [comment] 2015-07-25 11:27
Appears to have been fixed in recent builds.

**Comment by achadwick** [comment] 2015-07-25 11:45
@AtsusaKaneytza thanks for verifying! Could you please paste in the exact version of MyPaint which you've been testing with please?

**Closed** 2015-07-25 11:45 UTC
Labels: UX, windows

**Comment by AtsusaKaneytza** [comment] 2015-07-25 12:27
the latest version is MyPaint 1.2.0-beta.0+gitexport.adc9032
