### ISSUE TITLE
UI renders without spacing between icons

### ISSUE THREAD

**Issue by samirosman** [mypaint/mypaint#975] opened 2019-02-14 13:58 UTC
#### Description of the problem

On opening MyPaint appimage (MyPaint---20190213.AppImage) the interface renders incorrectly. See screenshot. 
![my_paint2_ui_linux_mint_18](https://user-images.githubusercontent.com/6158674/52791093-329f7d80-3079-11e9-85c9-87d19165ccf1.png)

#### Basic system details

MyPaint version: 2.0.0-alpha+git.8f23c97 (Python 2.7.5, GTK 3.22.30, GdkPixbuf 2.36.12, Cairo 1.15.12, GLib 2.56.1)
Operating system: Linux Mint 18.3 
Desktop environment: Cinnamon 64-bit

#### Steps to reproduce

1. Download appimage from github release page, 
2. Execute
3. UI renders incorrectly.

#### Backtraces or error messages

```
No Backtrace as there is no crash.
```

**Comment by ilovepumpkin** [comment] 2019-03-03 08:53
I am using Ubuntu 16.04. When I am using Gnome 3, I can see the correct UI, but when I switch to i3wm, I got the same screen as above (all tool bar icons are displayed without spaces). 

Here is what I get when starting MyPaint---20190213.AppImage.
```

DIR: /tmp/.mount_MyPainLM1uqQ
AILIBDIR=/tmp/tmp.vxWxaSG79z
System stdc++ library: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
System stdc++ library version: "3.4.21"
Bundled stdc++ library version: "3.4.19"
Newest stdc++ library version: "3.4.21"
Using system stdc++ library
atomiclib: /usr/lib/x86_64-linux-gnu/libatomic.so.1
Checking versions of library "libfontconfig"
  system library: "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0" (libfontconfig.so.1.9.0)
  system library version: 1.9.0
  ailib: "/tmp/.mount_MyPainLM1uqQ/usr/lib/libfontconfig.so.1.11.1"
  bundled library: "/tmp/.mount_MyPainLM1uqQ/usr/lib/libfontconfig.so.1.11.1" (libfontconfig.so.1.11.1)
  bundled library version: 1.11.1
  newest library version: "1.11.1"
Checking versions of library "libfreetype"
  system library: "/usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1" (libfreetype.so.6.12.1)
  system library version: 6.12.1
  ailib: "/tmp/.mount_MyPainLM1uqQ/usr/lib/libfreetype.so.6.14.0"
  bundled library: "/tmp/.mount_MyPainLM1uqQ/usr/lib/libfreetype.so.6.14.0" (libfreetype.so.6.14.0)
  bundled library version: 6.14.0
  newest library version: "6.14.0"
GTK_PATH=/tmp/.mount_MyPainLM1uqQ/usr/lib/gtk-2.0
GTK_IM_MODULE_FILE=/tmp/.mount_MyPainLM1uqQ/usr/lib/gtk-2.0:/tmp/.mount_MyPainLM1uqQ/usr/lib/gtk-2.0
PANGO_LIBDIR=/tmp/.mount_MyPainLM1uqQ/usr/lib
/tmp/.mount_MyPainLM1uqQ/apprun-helper.sh: line 131: /tmp/.mount_MyPainLM1uqQ/startup_scripts/*.sh: No such file or directory
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/tmp/.mount_MyPainLM1uqQ/usr'
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE='en_US'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'en_US:C'
```
And after the above lines, there are lots of the following warnings. 

`(mypaint:8775): Gtk-WARNING **: 16:41:06.407: Theme parsing error: gtk-widgets-borders.css:31:18: The :insensitive pseudo-class is deprecated. Use :disabled instead.`

**Comment by Fandekasp** [comment] 2019-05-13 05:38
same issue on i3wm

**Comment by Fandekasp** [comment] 2019-05-13 06:18
I could fix the menu style using  [this gtk.css](https://wiki.archlinux.org/index.php/GTK+#Titlebar_background_color_mismatch)

**Comment by ilovepumpkin** [comment] 2019-06-06 05:33
Hi @Fandekasp, I created a gtk.css under ~/.config/gtk-3.0 with content from your link, but I still saw the same issue. Anything else should I do?

**Comment by Fandekasp** [comment] 2019-06-06 05:51
@ilovepumpkin maybe because mypaint is using gtk-2 in your case?
your log prints
```
GTK_PATH=/tmp/.mount_MyPainLM1uqQ/usr/lib/gtk-2.0
GTK_IM_MODULE_FILE=/tmp/.mount_MyPainLM1uqQ/usr/lib/gtk-2.0:/tmp/.mount_MyPainLM1uqQ/usr/lib/gtk-2.0
```
Other than that, I have no idea, sorry. I don't know much about gtk .

**Comment by ilovepumpkin** [comment] 2019-06-07 02:15
@Fandekasp do you mind to show your GTK_PATH in logs? do you mean in your case it is pointing to gtk-3.0?

**Comment by Fandekasp** [comment] 2019-06-07 06:52
@ilovepumpkin I'm very unclear about what mypaint is using. Looks like gtk2 with compatibility gtk3. You might want to dig into their code source, or ask the maintainers directly.

```console
mypaint -t | grep -i gtk3
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
INFO: gui.device: New device 'DLL075B:01 06CB:76AF Touchpad' (GDK_SOURCE_TOUCHPAD, axes:4, class=X11DeviceXI2, vendor='06cb', product='76af')
INFO: gui.device: New device 'ELAN Touchscreen' (GDK_SOURCE_TOUCHSCREEN, axes:4, class=X11DeviceXI2, vendor='04f3', product='20d0')
INFO: gui.device: New device 'Virtual core XTEST pointer' (GDK_SOURCE_MOUSE, axes:2, class=X11DeviceXI2, vendor=None, product=None)
INFO: gui.document: Initialized background from u'/usr/share/mypaint/backgrounds/10_soft_yellow.png'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendModeMenu'

(mypaint:3224): Gtk-WARNING **: 15:47:25.262: Theme parsing error: <data>:5:50: The style property GtkMenuBar:internal-padding is deprecated and shouldn't be used anymore. It will be remov
ed in a future version
INFO: lib.document: Using u'load_ora' to load u'/home/dori/.local/share/mypaint/scratchpads/autosave.ora' (kwargs={'feedback_cb': <function gtk_main_tick at 0x7f179ef5bcf8>})
INFO: lib.document: load_ora: u'/home/dori/.local/share/mypaint/scratchpads/autosave.ora'
INFO: lib.document: 0.123s load_ora total
INFO: gui.filehandling: Loaded scratchpad from u'/home/dori/.local/share/mypaint/scratchpads/autosave.ora'
WARNING: gui.accelmap: Not listing '<Actions>/DocumentActions/RotateLeft' (no tooltip, fix before release!)
WARNING: gui.accelmap: Not listing '<Actions>/DocumentActions/RotateRight' (no tooltip, fix before release!)
keyboard.py(106):         if gtk2compat.USE_GTK3:
keyboard.py(119):         keyval_offset = 1 if gtk2compat.USE_GTK3 else 0
```

**Comment by ilovepumpkin** [comment] 2019-06-07 08:48
@Fandekasp okay, thank you!

**Comment by ilovepumpkin** [comment] 2019-06-07 14:47
I fixed my issue in i3wm. The cause is that I have a problematic theme setting in ~/.config/gtk-3.0/settings.ini. After I reset settings.ini with the basic GTK3+ theme configuration from https://wiki.archlinux.org/index.php/GTK+#Basic_theme_configuration, my issue is gone. 

```
[Settings]
gtk-icon-theme-name = Adwaita
gtk-theme-name = Adwaita
gtk-font-name = DejaVu Sans 11
```

**Comment by jplloyd** [comment] 2019-07-21 10:22
Changing to a gtk3-compatible theme via Gnome Tweaks or manually (as described above) solves this. Not sure if it is something that can/should be addressed in the appimage build itself.

**Comment by jplloyd** [comment] 2019-10-09 17:51
This should now be fixed for all distros the appimages can run on. Check out the [latest builds](https://github.com/mypaint/mypaint-appimage/releases/tag/continuous) if you want to confirm it.

Note that the images will now use the built-in Adwaita theme by default, respecting dark/light settings **in the MyPaint preferences** (not system/user-settings, sorry). If you want to use another theme that is compatible with gtk 3.22, you can set GTK_THEME before running the appimage, e.g:
```
GTK_THEME=MyFavouriteTheme ./MyPaint.AppImage
```

**Closed by jplloyd** 2019-10-09 17:51 UTC
Labels: glitch, packaging

**Comment by samirosman** [comment] 2019-10-10 02:48
I can confirm that this is now fixed using the latest build. Thank you!
