### ISSUE TITLE
Exception: AttributeError: 'NoneType' object has no attribute 'get_child' in gui/workspace.py

### ISSUE THREAD

**Issue by greenhairedfae** [mypaint/mypaint#583] opened 2016-01-30 23:23 UTC
```python
Mypaint version: 1.2.0-beta.4+gitexport.ee1f5bc
System information: Windows-10.0.10586
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\share\mypaint/gui/workspace.py", line 1276, _deferred_remove_tool_widget(self=<_Notebook object at 0xd9f7140 (gui+workspace+_Notebook at 0xe709270)>, page=None)
            def _deferred_remove_tool_widget(self, page):
                tool_widget = page.get_child()
                self._toolstack.remove_tool_widget(tool_widget)
  variables: {'page': ('local', None), 'tool_widget': (None, [])}
AttributeError: 'NoneType' object has no attribute 'get_child'
```

I don't know what's up exactly but I'm using Mypaint in Windows 10. (I know how awful right?) 
But here's the thing. Also sometimes there is just massive lag for the brushes in spite of the fact that literally nothing else that I'm doing and there's plenty of RAM available to it.

**Comment by achadwick** [comment] 2016-01-30 23:54
Please limit issue reports to one problem per issue. I'm going to retitle this one to refer to the exception only, and ignore the lag issue. Lag with developer releases has already been reported: #390. Please check that one out, and add your voice there.

**Comment by achadwick** [comment] 2016-01-30 23:56
Regarding lag, please try the newer v1.2.0 stable. Many Windows users report that it doesn't suffer from the same problems because it uses an older libgtk/libgdk. Please check out the release notes too.

**Comment by achadwick** [comment] 2016-01-30 23:59
@greenhairedfae 
Sorry to be a pain, but please could you provide the following information:

* What you were doing when you saw the error message `AttributeError: 'NoneType' object has no attribute 'get_child'` ?
* Whether this problem still occurs in the most recent stable release, v1.2.0?

Thanks.

**Comment by greenhairedfae** [comment] 2016-01-31 04:21
I was just drawing, had just changed brushes and was also listening to
music with my web browser.

**Comment by greenhairedfae** [comment] 2016-01-31 04:21
Sorry about that. I didn't know if they were connected.

**Comment by achadwick** [comment] 2016-01-31 20:00
Hmm, OK. I guess the browser thing isn't relevant :smiley: 

Something else is going on here. Have you been able to cause the same problem to happen again at all? Do you have some clear steps to reproduce this problem?

If not, I can maybe patch up that bit of code to be more tolerant about its expectations not being met :grinning:

**Comment by achadwick** [comment] 2016-02-08 15:07
@greenhairedfae 
Please can you give me some clear steps to reproduce this problem starting with a fresh config? See <https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset> for instructions.

I also need to know whether it's happening with the most recent stable release, MyPaint 1.2.0.

**Comment by greenhairedfae** [comment] 2016-02-10 23:49
I actually just got a new computer and returned my old one. (my hard drive
was rubbing against the case and destroying itself) I haven't experienced
that problem, or any other problem, since.  Thank you for all of your help.
😃

**Comment by achadwick** [comment] 2016-02-11 00:15
Okay, for now I'll just patch up that code to be a bit more careful about setting up `_deferred_remove_tool_widget`, then close this issue. I'll target it for 1.3.0 so it receives a bit more testing: the error condition might be really tricky to reproduce.

**Comment by achadwick** [comment] 2016-02-11 00:21
Fixed. Or rather, probably fixed... not been able to repro this bug, so can't really verify the fix.

**Closed by achadwick** 2016-02-11 00:21 UTC
Labels: bug, needs-info, windows
