### ISSUE TITLE
Tooltips have a weird looking border or shadow in Windows 10

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#466] opened 2015-10-28 18:35 UTC
[[**EDIT: original subject: "Something wrong with borders (ui). Windows 10 x64, beta 2."]]

In beta 1 tooltips normal.

![1](https://cloud.githubusercontent.com/assets/13454470/10798973/1b1b20be-7dcc-11e5-96e2-41f32bbe0f28.jpg)
![2](https://cloud.githubusercontent.com/assets/13454470/10798979/1f27d4a4-7dcc-11e5-8752-35cdb04750c4.jpg)

**Comment by achadwick** [comment] 2015-10-28 19:20
Do they operate correctly?

**Comment by zb13y** [comment] 2015-10-29 09:31
Yes. Works fine.

**Comment by achadwick** [comment] 2015-10-29 10:37
Okay - we don't do anything special with tooltips, so this just looks like a cosmetic defect from upstream.

Please can you try [v1.2.0-beta.2](https://github.com/mypaint/mypaint/releases/tag/v1.2.0-beta.2) and tell me if it's still happening? If it is still happening, I'll make sure it gets reported to the GTK/GTK crew (or you can search for it yourself at <http://bugzilla.gnome.org>)

**Comment by achadwick** [comment] 2015-10-29 10:41
Sorry, I got confused :neutral_face:. I understand that you are using v1.2.0.beta.2, and I'll report it upstream against the GTK 3.18.2 which that build uses.

**Comment by achadwick** [comment] 2015-10-29 12:37
@zb13y 
You use a white canvas background, which makes it hard to distinguish what's going on in your bottom screenshot,

> ![2](https://cloud.githubusercontent.com/assets/13454470/10798979/1f27d4a4-7dcc-11e5-8752-35cdb04750c4.jpg)

↑ Is this just a floating shadow effect, or is there a white rectangle around the tooltip too?

**Comment by achadwick** [comment] 2015-10-29 12:37
@zb13y there is noting strange in the top screenshot as far as I can see.

**Comment by achadwick** [comment] 2015-10-29 12:46
I can't reproduce this under Windows 7 64-bit with GTK+ 3.18.2 (same version as aggregated alongside the MyPaint v1.2.0-beta.2 binary release this issue was reported with).

This might be already reported upstream as https://bugzilla.gnome.org/show_bug.cgi?id=746637

I have reported it as https://bugzilla.gnome.org/show_bug.cgi?id=757304 because it might be something new (the screenshots look sufficiently different to my eyes, and this one is only for Win10).

Closing because this is obviously an upstream bug, and it doesn't break MyPaint.

**Closed by achadwick** 2015-10-29 12:46 UTC
Labels: upstream, windows

**Comment by achadwick** [comment] 2015-10-29 12:58
From IRC:

> \<achadwick\> mclasen: is the commit that addressed [746637](https://bugzilla.gnome.org/show_bug.cgi?id=746637) included in 3.18.2 ?
> \<ofourdan\> yes, it was merged during pre 3.18 timeframe - btw, 746637 was not windows specific
> \<mclasen\> that was [a08ee01c6443a4890fc265e5976f91994379cc0b](https://git.gnome.org/browse/gtk+/commit/?id=a08ee01c6443a4890fc265e5976f91994379cc0b)

**Comment by tumagonx** [comment] 2015-10-29 17:26
I encounter this all stuff too, it roots in the use dwmapi by gdk which also effectively break XP support too, disabling it however will remove both the desired window border and the undesired weird drop shadow. apparently glib 2.46.x and gtk 3.18.x dropped XP https://bugzilla.gnome.org/show_bug.cgi?id=757291

**Comment by tumagonx** [comment] 2015-10-29 17:38
Note that this only happen to Win8.x and above where window compositing (dwmapi) enabled by default
