### ISSUE TITLE
"last color" toggle behaves oddly

### ISSUE THREAD

**Issue by mikshaw** [mypaint/mypaint#93] opened 2014-08-22 22:09 UTC
In MyPaint stable, pressing X to chose one of the last 5 colors works as expected: Press once and you toggle to the most recently used color, press once more to move to the previous color, etc. When you choose a new color, the one on the far left is bumped off.

In MyPaint git, i don't understand what it's doing when you press X...it seems definitely like a bug. Pressing X once doesn't choose the last color used...it seems like all the colors are pushed an extra slot or something, so you have to press X twice to select the last color used. Selecting a new color bumps off the wrong color.

Debian Testing (Jessie) 64-bit, Intel HD4000, dwm desktop

**Comment by achadwick** [comment] 2015-03-01 03:28
@mikshaw There's nothing inherently different in gtk3 to cause this. It looks like a misunderstanding of ours caused by recent big changes in the guts of MyPaint.

**Comment by achadwick** [comment] 2015-03-01 03:32
I think this one is fixed by 9acd8b85e2cc9dcd1a1437f90fcde2c0a1e77dfe and its recent ancestors. Could everyone please test the most recent master, ddd03d4ffc9453bcdd801b792a85603dd438cdcd, and see if this fixes colour history cycling to their satisfaction?

**Comment by mikshaw** [comment] 2015-03-01 03:57
I don't know enough about git to figure this out....it seems to think c510392 is the latest master

**Comment by 0ion9** [comment] 2015-03-01 05:35
@mikshaw: That doesn't make a difference, if you go to https://github.com/mypaint/mypaint/commits/master you can see that the only commit after ddd03d4 is one that fixes an unrelated bug concerning how mypaint is launched (this is c510392 , the commit you named). It would be extremely bizarre if that change effected this behaviour at all.

**Comment by mikshaw** [comment] 2015-03-01 15:07
If that's the case, then the color history bug still lives....or if not then the normal behavior of it is open to some unexpected results in certain situations.  With each new build i do a test in which i alternate a brush stroke and a press of the x key. What should happen is that you have color1, color2, color1, color2, etc., but what actually happens is a ping-pong through the 5 colors. 

However, i just noticed loentar showed in #168 that if you pause then it works properly. I have been running through the test quickly, without considering the possibility that's not common behavior in everyday use. So basically it's not fixed, but it's much better....probably good enough that i won't notice it.

I understand that Xkey may have a different result depending on whether the user presses once or multiple times, but i'm not sure that should require the difference to be time sensitive (if that has anything to do with why pausing gives the proper result). It seems like the only deciding factor in choosing the color (and what order the colors are arranged in the history) would be which color was hot when you stop cycling through them. Perhaps time is used to revert to the previous color, if you choose a new color and then don't use it. If so i would ask if that's necessary...if you accidentally swap colors, swapping them back means only another key press. I think that makes more sense than the program deciding for me that i didn't actually want the color i just chose. Maybe i'm wrong there, but i can't think of anything else that would require a pause.

**Comment by achadwick** [comment] 2015-03-01 15:36
I guess I was either pausing too much when testing using my [own recipe above](https://github.com/mypaint/mypaint/issues/93#issuecomment-66659454), or testing the wrong thing.

@mikshaw so you're saying you want the behaviours below?

1. **x, x, x, draw** → should cycle 3 colours back (it does, now!)
2. **x, draw, x, draw, x, draw, ...** → should flip between two most recent colours at the time this started (it currently doesn't)
3. **x, pause, draw, x, pause, draw, x, pause, draw, ...** → should flip between two most recent colours at the time this started (it currently does, if the pause is long enough)

It may be that the time-sensitivity we're experiencing right now (master at c510392c113526789ce7e8a211f57fc8a3c53f74) is there to allow 1. to happen, but given that we can detect _explicit_ drawing (button down/stroke/up) and _implicit_ drawing (splattering that causes pixel changes and undo stack commits) quite reliably now, I'm not sure why that's still needed.

**Comment by mikshaw** [comment] 2015-03-01 15:47
It's not so much a question of what i want now...what i wanted before was just to return to being able to use the xkey the way it works in mypaint stable, and it seems it effectively does that now.  I'm just curious (as you seem to be as well) about why the pause changes the behavior in my test situation. In a normal use case i doubt it would be noticed...just thinking if there's no reason for it then maybe it should eventually be removed.

Thank you for continuing to make mypaint the most enjoyable painting application in existence.

**Comment by mikshaw** [comment] 2015-03-01 21:12
hmmm...still behaving oddly. It's not nearly as bad as before, but i'm finding it frequently shifting to the wrong color if i don't consciously pause.

Usually when i start painting i initially work with 2 colors, a light and a dark, switching back and forth as the shape evolves. If i switch colors, quickly paint a few strokes, and then try to switch back it actually moves on to the third color instead of returning to the first. It's now easier to get back to having the original two colors in the 1st and 2nd slots than it was before this latest commit, but it requires a conscious effort to pause between painting and selecting the next color.

As long as i pause after painting, in a situation where i paint with a selected color for only a second, then it seems to work okay. But if i try to paint quickly, swapping colors frequently, things get messed up.

**Comment by achadwick** [comment] 2015-04-20 18:34
**Triage note:** severity has been reduced since the initial report. Looks like this is still biting people in a lesser way, and I think the [behaviour proposed on the 1st Mar](https://github.com/mypaint/mypaint/issues/93#issuecomment-76602284) is the way to go.

It'll (hopefully) be a fairly trivial change however, and it doesn't involve any string changes. I'll bump it to 1.2.0-beta and look at it in that development cycle.

**Closed** 2015-08-26 17:48 UTC
Labels: bug, UX

**Comment by mikshaw** [comment] 2015-09-11 18:32
i just now noticed this was fixed...apparently i haven't painted in 2 weeks =o\
Thank you @achadwick
