### ISSUE TITLE
Picker Color and Reposition Layer tools (top bar) and Tool Options focused

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#252] opened 2015-03-11 22:19 UTC
I've noted that when you use the picker or the reposition layer tools remains active or focused the last tool options used... Perhaps the behavior of current ink... 'no options available' is ideal in these cases.

**Comment by achadwick** [comment] 2015-03-12 00:50
This is the latest git master, right?

Good point. They were always intended as one-shot modes only, so the options of the mode under them on the stack would remain visible to avoid undue UI updates when moving the canvas around.

That's changed recently (commit 8f438497c0767b913649fb5cfdb97545ae769d2a), and they're sometimes temporary (middle button) and sometimes long-lasting (toolbar, menu) now.

**Comment by americogobbo** [comment] 2015-03-12 01:23
Yes the last git master.

**Comment by achadwick** [comment] 2015-04-20 22:46
Confirmed with master at c0c088b7391ecb9c70c1d21ab4d81b3bd0b0884d. This is likely to require some strings checking and updating, so assigning to the alpha phase of work for the release.

**Closed** 2015-04-29 18:25 UTC
Labels: bug, UX
