### ISSUE TITLE
Appimage crashes at start

### ISSUE THREAD

**Issue by dCo3lh0** [mypaint/mypaint#965] opened 2019-02-08 20:54 UTC
#### Basic system details

MyPaint version: 2.0.0 nightly, 2.0.0-alpha.2
Operating system: Mint 18.2, Ubuntu 16.04
Desktop environment: Xfce

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. Crash

#### Backtraces or error messages

```
 ~ $ /media/dco3lh0/opt/appimages/MyPaint.AppImage
DIR: /tmp/.mount_MyPainCmRGlB
AILIBDIR=/tmp/tmp.bh2mXFizoU
System stdc++ library: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
System stdc++ library version: "3.4.21"
Bundled stdc++ library version: "3.4.19"
Newest stdc++ library version: "3.4.21"
Using system stdc++ library
atomiclib: /usr/lib/x86_64-linux-gnu/libatomic.so.1
Checking versions of library "libfontconfig"
  system library: "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1" (libfontconfig.so.1.10.1)
  system library version: 1.10.1
  ailib: "/tmp/.mount_MyPainCmRGlB/usr/lib/libfontconfig.so.1.11.1"
  bundled library: "/tmp/.mount_MyPainCmRGlB/usr/lib/libfontconfig.so.1.11.1" (libfontconfig.so.1.11.1)
  bundled library version: 1.11.1
  newest library version: "1.11.1"
Checking versions of library "libfreetype"
  system library: "/usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1" (libfreetype.so.6.12.1)
  system library version: 6.12.1
  ailib: "/tmp/.mount_MyPainCmRGlB/usr/lib/libfreetype.so.6.14.0"
  bundled library: "/tmp/.mount_MyPainCmRGlB/usr/lib/libfreetype.so.6.14.0" (libfreetype.so.6.14.0)
  bundled library version: 6.14.0
  newest library version: "6.14.0"
GTK_PATH=/tmp/.mount_MyPainCmRGlB/usr/lib/gtk-2.0
GTK_IM_MODULE_FILE=/tmp/.mount_MyPainCmRGlB/usr/lib/gtk-2.0:/tmp/.mount_MyPainCmRGlB/usr/lib/gtk-2.0
PANGO_LIBDIR=/tmp/.mount_MyPainCmRGlB/usr/lib
/tmp/.mount_MyPainCmRGlB/apprun-helper.sh: linha 131: /tmp/.mount_MyPainCmRGlB/startup_scripts/*.sh: Arquivo ou diretório não encontrado
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/tmp/.mount_MyPainCmRGlB/usr'
/tmp/.mount_MyPainCmRGlB/AppRun: linha 44: 26778 Falha de segmentação  python $DIR/usr/bin/mypaint "$@"

```

**Comment by jplloyd** [comment] 2019-06-27 11:09
@dCo3lh0 I can't reproduce this when running xfce on my 16.04 system. 

Do you still get a segfault with most recent alpha?
(https://github.com/mypaint/mypaint/releases/download/v2.0.0-alpha.12/MyPaint---20190622.AppImage)

**Comment by jplloyd** [comment] 2019-07-21 10:25
Closing this with the assumption that the problem has been fixed in later alphas. If not, open a new issue for the new version.

**Closed by jplloyd** 2019-07-21 10:25 UTC
