### ISSUE TITLE
Build 3.71 on Windows 10 x64 (and x32) lagging on brush strokes... 

### ISSUE THREAD

**Issue by bluecd** [mypaint/mypaint#527] opened 2015-12-09 16:44 UTC
1)
.../mypaint/windows/build.sh needs "cd ../" 
before 
"./release.sh $release_opts -- "$tmp_root""

2) Build 3.64 still lagging on mouse/pen draw /sketching brushes/  while version 1.2.0a was OK.

**Comment by achadwick** [comment] 2015-12-16 14:32
Hi there, sorry to have not responded earlier. Just acknowledging that I have now seen this issue - there seems to have been a Github hiccup of some sort, and it's been resolved now. Sorry about that.

Thanks for bringing this issue to my attention in our forums: <http://community.mypaint.org/t/intro-dev-issues/83>. For other people reading this issue: we've been thrashing things out there too.

**Comment by Rolliboy** [comment] 2015-12-16 15:22
What about #514?

2015-12-16 15:32 GMT+01:00 Andrew Chadwick <notifications@github.com>:

**Comment by achadwick** [comment] 2015-12-27 14:38
Possibly. #537 was just reported, and might be related too.

Does the behaviour changes when you close all open brush group tabs?

**Comment by bluecd** [comment] 2015-12-28 15:05
Hi,

Build. beta2-111 much improved since last time. C_D brushes can do it although noticeable lagg w/bigger brushes, overall performance: not a speed daemon but can handle.;
Another thing: same C_D brushes tend to produce an unintended straight line from last 'Pen-up' occurence to 'Pen-down'. this is random , can t reproduce.

**Comment by achadwick** [comment] 2015-12-29 10:27
@bluecd Is the local build you tried 1.2.0-beta.3.111?

If it is that one (e0faa7f07ccdfdc43180c2b33c6a46d6f9e609fa), that's interesting given that commit 2dd4812da5e319a7d22d054285024ec584e74989 was introduced after "[b]uild 3.71".

**Comment by achadwick** [comment] 2015-12-29 10:28
@bluecd BTW, when reporting bugs, please paste:

* the long hexadecimal string from `git log` (looks like `e0faa7f07ccdfdc43180c2b33c6a46d6f9e609fa`)
* the *full* version number pasted in from **Help→About MyPaint** (looks like `1.2.0-beta.3.111+git.e0faa7f`)

**Comment by bluecd** [comment] 2015-12-29 10:58
OK.
 
I make builds on msys64, local, daily updated Git repo.
My log data as you wish - as you can see its the latest, as stated below:
 
e0faa7f07ccdfdc43180c2b33c6a46d6f9e609fa
Build: 1.2.0-beta.3.111+gitexport.e0faa7f.dirty
 
cheers,
 
 
W dniu 2015-12-29 11:28:36 użytkownik Andrew Chadwick <notifications@github.com> napisał:
@bluecd BTW, when reporting bugs, please paste:
the long hexadecimal string from git log (looks like e0faa7f07ccdfdc43180c2b33c6a46d6f9e609fa)
the full version number pasted in from Help→About MyPaint (looks like 1.2.0-beta.3.111+git.e0faa7f)

**Comment by achadwick** [comment] 2015-12-29 11:49
Thanks for the information. It looks like changing the event mask has helped here. Perhaps it might help with the other annoying Windows lag issues? I can hope! :innocent: 

The C_D brushes do a lot of work. They're very big, and need to read a lot for smudging before they write, so they will be slower than a write-only small sketching brush. They are also noticeably slower than other brush groups on Linux systems where we don't get reports of lag oddities.

I'll close this issue shortly after investigating the first sub-issue you reported (with windows/build.sh). I don't want issue threads to contain more than one issue.

With that in mind, if you find a way to reproduce

> Another thing: same C_D brushes tend to produce an unintended straight line from last 'Pen-up' occurence to 'Pen-down'. this is random , can t reproduce.
-- from https://github.com/mypaint/mypaint/issues/527#issuecomment-167585199

please report it as a separate issue. Many thanks: keeping separate issues separate keeps the tracker clean :smiley:

**Comment by bluecd** [comment] 2015-12-29 12:07
Ok, i will. Firstly, i have got and pointed out the build where in my oppinion c_d brushes did not cause noticeable lagging, will shiw build no. when come home from shopping )). Secondly: that strange issue w. Unintended straight lines primarily appeared to me when DID not click mouse pointer thus activating display i am workin on-i got dual display win 64setup, both same res. In that case w.out clicking mouse on the display where mypaint was opened caused producing a stake of aggregated,parallel lines on first pen-down occurence. Now similarily but only one and randomly. Still will try to investigate and reproduce thus issue but we have to narrow the problem to c_d brushes only as they re seem most demanding,ok? Otherwise too many possibilities to check )))
29 gru 2015 12:49 Andrew Chadwick <notifications@github.com> napisał(a):Thanks for the information. It looks like changing the event mask has helped here. Perhaps it might help with the other annoying Windows lag issues? I can hope!  

The C_D brushes do a lot of work. They're very big, and need to read a lot for smudging before they write, so they will be slower than a write-only small sketching brush. They are also noticeably slower than other brush groups on Linux systems where we don't get reports of lag oddities.

I'll close this issue shortly after investigating the first sub-issue you reported (with windows/build.sh). I don't want issue threads to contain more than one issue.

With that in mind, if you find a way to reproduce


Another thing: same C_D brushes tend to produce an unintended straight line from last 'Pen-up' occurence to 'Pen-down'. this is random , can t reproduce.
-- from #527 (comment)


please report it as a separate issue. Many thanks: keeping separate issues separate keeps the tracker clean

**Comment by bluecd** [comment] 2015-12-30 12:22
Hi,
 
Just playing w/another thing: have Innosetup installed, added to path yet mypaint.cmd is missing now, horrible to set manually  that parametered startup command.
Should I simply give Inno up by now? 
 
cheers,
 
 
W dniu 2015-12-29 12:49:31 użytkownik Andrew Chadwick <notifications@github.com> napisał:
Thanks for the information. It looks like changing the event mask has helped here. Perhaps it might help with the other annoying Windows lag issues? I can hope!
The C_D brushes do a lot of work. They're very big, and need to read a lot for smudging before they write, so they will be slower than a write-only small sketching brush. They are also noticeably slower than other brush groups on Linux systems where we don't get reports of lag oddities.
I'll close this issue shortly after investigating the first sub-issue you reported (with windows/build.sh). I don't want issue threads to contain more than one issue.
With that in mind, if you find a way to reproduce
Another thing: same C_D brushes tend to produce an unintended straight line from last 'Pen-up' occurence to 'Pen-down'. this is random , can t reproduce.
-- from #527 (comment)
please report it as a separate issue. Many thanks: keeping separate issues separate keeps the tracker clean

**Comment by bluecd** [comment] 2015-12-30 12:28
BTW of Innosetup: produced Mypaint 64 desktop icon gives me fatal python error so I cant run mypaint anyway.
 
bcd
 
 
 
W dniu 2015-12-29 12:49:31 użytkownik Andrew Chadwick <notifications@github.com> napisał:
Thanks for the information. It looks like changing the event mask has helped here. Perhaps it might help with the other annoying Windows lag issues? I can hope!
The C_D brushes do a lot of work. They're very big, and need to read a lot for smudging before they write, so they will be slower than a write-only small sketching brush. They are also noticeably slower than other brush groups on Linux systems where we don't get reports of lag oddities.
I'll close this issue shortly after investigating the first sub-issue you reported (with windows/build.sh). I don't want issue threads to contain more than one issue.
With that in mind, if you find a way to reproduce
Another thing: same C_D brushes tend to produce an unintended straight line from last 'Pen-up' occurence to 'Pen-down'. this is random , can t reproduce.
-- from #527 (comment)
please report it as a separate issue. Many thanks: keeping separate issues separate keeps the tracker clean

**Comment by achadwick** [comment] 2015-12-30 12:54
@bluecd 
Please please _please_ report these two new additional problems as separate issues, and give me more information in the new issues so that I can fix them. It's _genuinely_ impossible for me to keep track of things when you report every new problem you encounter in the same thread like this! :sob: 

Thanks once again for reporting the issues you have been having, and providing useful feedback but I am closing and locking this thread now. I am aware that this is quite rude, and I am sorry. I hate to have to do this.

Please read <https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md> and <https://github.com/mypaint/mypaint/wiki/Reporting-Bugs>.

You have been helpful, really, and I want to continue working with you, but I would really like you to make a habit of different reporting issues separately.

**Closed by achadwick** 2015-12-30 12:54 UTC
Labels: performance, windows

**Comment by achadwick** [comment] 2015-12-30 12:58
@bluecd 
> BTW of Innosetup: produced Mypaint 64 desktop icon gives me fatal python error so I cant run mypaint anyway.

Please report this as a separate issue. I will need to know the exact text of the fatal Python error message when you do this, and what you were doing, and what you typed, and a lot more information besides.

Please read <https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md> and <https://github.com/mypaint/mypaint/wiki/Reporting-Bugs> before reporting the new issue.

Then, to report the new issue: https://github.com/mypaint/mypaint/issues/new.

Please keep the topics separate.

**Comment by achadwick** [comment] 2015-12-30 13:00
@bluecd 
> Just playing w/another thing: have Innosetup installed, added to path yet mypaint.cmd is missing now, horrible to set manually  that parametered startup command.
> Should I simply give Inno up by now? 

Please report this as a separate issue. I don't really know what you're doing or trying here, so it makes most sense for you to tell me what you are doing in a separate issue thread. Thanks!

Please read <https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md> and <https://github.com/mypaint/mypaint/wiki/Reporting-Bugs> before reporting the new issue.

Then, to report the new issue: https://github.com/mypaint/mypaint/issues/new.

Please keep the topics separate.
