### ISSUE TITLE
Open Recent menu: lists non-openable junk

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#267] opened 2015-03-22 19:07 UTC
When you have used the file manager in Mypaint (File > open) recently to open or import the resources in MyPaint... these entries remain on the list, e.g., a palette color, a zip brush pack. The resources appear like a document, is possible to have in this list only image documents (.jpeg, .png or .ora)?

**Comment by achadwick** [comment] 2015-03-22 19:16
Confirmed in 1.1.1-alpha built on 20150305, git ba0649b, and thanks for the reminder to have a look at it. It even contains misspelled names and other junk:

![Example of the bad menu.](https://cloud.githubusercontent.com/assets/61299/6770920/30114f82-d0c7-11e4-9e32-577421ac687f.png)

Something to do with the recent-file manager we use (GtkRecentManager): we had to make a compromise at some point in the GTK3 migration IIRC, though I don't recall what. Perhaps we can fix this now that GTK3 has moved on a bit.

**Comment by achadwick** [comment] 2015-03-22 19:20
This also kills "Open Recent" (F3) if the most recent thing in there happens to be a .gpl palette file, for example. Although oddly it only does so on the next launch of MyPaint.

**Comment by jy2wong** [comment] 2015-03-23 01:59
For extra fun, `GtkRecentAction`s were deprecated in GTK 3.10.

**Comment by achadwick** [comment] 2015-03-23 02:07
In fairness, all GtkActions were. But we're stuck with them for this release :D
That can be OK though: GTK is quite good at keeping deprecated stuff in a working state for years: that ancient GtkHSV for example. And actions are/were pretty fundamental things.

Complete aside, but I do kinda like the replacement GAction (gi.repository.Gio.Action) style of working.

**Comment by achadwick** [comment] 2015-03-23 12:17
Fingers crossed, this should be good as a small introductory task.

**Comment by achadwick** [comment] 2015-04-20 20:49
**Triage note:** confirmed, and it's clear and obvious what the problem is at least. This shouldn't need any string changes, so assigning to the first block of work in the beta cycle.

**Closed** 2015-08-02 17:53 UTC
Labels: bitesize, bug, UX
