### ISSUE TITLE
Cursor size limit too low (Windows 10)

### ISSUE THREAD

**Issue by hungercp** [mypaint/mypaint#1192] opened 2022-09-14 13:19 UTC
#### Description of the problem

Brush cursor not growing after a small limit.
Once it reaches a certain size the cursor will no longer reflect the actual size of the brush, which would be fine if it was an obscurely large brush size however the limit was far too small. However this is only on Windows, I have used mypaint on linux and the cursor size limit was much higher and usable without any workarounds. 

#### Basic system details

MyPaint version: 2.0.1 w64
Operating system: Windows 10

#### Steps to reproduce

1. Start MyPaint on Windows 10
2. Increase brush size until it is visible that it does not grow after increasing just a few times from the default brush size

#### Workaround

Editing line 82 in mypaint-w64\mingw64\lib\mypaint\gui\cursor.py so that the max_cursor_size = 9999999999999999 (or some other large value)
This will allow the brush size to be reflected into the cursor size far beyond the default limit (which strangely seems to work fine as expected on linux)

**Comment by AesaraB** [comment] 2024-01-17 23:39
Duplicate of #1192

**Closed by AesaraB** 2024-01-17 23:39 UTC
Labels: solution.Duplicate, type.Enhancement, platform.Windows, cat.UX, cat.UI
