### ISSUE TITLE
click & drag opacity slider

### ISSUE THREAD

**Issue by Griatch** [mypaint/mypaint#299] opened 2015-04-21 13:05 UTC
MyPaint has for me lost the ability to click a slider and drag it to a value. This is most prevalent with the opacity slider: I have to click repeatedly left or right of the current position to gradually step it to the desired value. Not only is this slower and breaks work flow, it also gives a lot less fine-control. 

Tested in latest GIT version, on Linux Mint (KDE).

**Comment by achadwick** [comment] 2015-04-21 13:32
Specific MyPaint version and OS version please?

Does reverting to a recent MyPaint revision fix this? c0c088b7391ecb9c70c1d21ab4d81b3bd0b0884d specifically.

**Comment by achadwick** [comment] 2015-04-21 13:34
Cannot reproduce with the latest Debian Testing...

Is this for subwindows only?

What specific sequence of actions are you performing? Step by step please, from a fresh config...

**Comment by 0ion9** [comment] 2015-04-21 13:36
What version of GTK3 are you using? I'm using 3.15.9.r34.gfc838ce on Arch Linux x86_64  and cannot reproduce, either with subwindows or docks. Both the brush opacity slider and layer opacity slider move smoothly with a click+drag.

**Comment by Griatch** [comment] 2015-04-21 13:52
I will try it again when I get back home. It has been like this for a while; I almost assumed it was a design decision.

**Comment by achadwick** [comment] 2015-04-22 00:59
I've tested this out with a fresh Linux Mint 17.1 "Rebecca" KDE edition install in a VM (using `virtualbox-guest-x11` 4.3.18-dfsg-1~ubuntu1~trusty1 on the guest, and `virtualbox-4.3` 4.3.26-98988~Debian~wheezy on the host), and I cannot reproduce it.

@Griatch More questions, because obviously we don't have enough information to reproduce the issue yet.:

* The title refers to an "opacity slider". **Which opacity slider, and where?**
* **How are you doing the "click & drag"**? Touchpad one-finger-tap and drag? Touchpad hardware button and drag? Touchscreen? Real physical mouse? I'm a bit limited in what a VM can do here, but KDE's Touchpad panel is telling me to install the Synaptics driver, so that might be it.
  * Does ensuring proper, expected touchpad behaviour fix this for you?
* **Is this for subwindows only?**
* **What specific MyPaint version are you running?** Help→About string with the hex numbers please, or paste a git revision if you know what you're doing.
* **What version of GTK3 are you running?**
* **Are you using a different GTK3 theme to the Mint default one**? I notice it uses a custom, non-Adwaita theme.

Unmarking as "bug" - this one hasn't been reproduced yet, and clearly Linux Mint 17 can be made to behave itself with MyPaint with some configurations...

**Comment by Griatch** [comment] 2015-04-22 10:52
@achadwick 

- I'm running rev 0b3067f and purged my settings to make sure I started from something clean.
- The click and drag fails to work both with the mouse as with my Wacom Intuos4 pen tip. I click the slider and try to drag it ... it gets selected but it just doesn't move. I have to click elsewhere on the slider to shift it. 
- `dpkg -l libgtk*  gives me the following list pertaining to gtk3:

    ```
ii  libgtk-3-0:amd64                            3.10.8~8+qiana                             amd64        
ii  libgtk-3-bin                                3.10.8~8+qiana                             amd64       
ii  libgtk-3-common                             3.10.8~8+qiana                             all         
ii  libgtk-3-dev                                3.10.8~8+qiana                             amd64       
    ```
- I have not changed the Mint GTK3 Theme as far as I know. 
- I use KDE with the OpenGL 3.1 compositing type (not that turning this to XRender matters) and the Nvidia proprietary driver 331.113.
- Below is the location of the opacity slider I refer to - it's up to the right just above the layer list (I don't know what a "subwindow" is meant to be, as far as I can tell I can only open "docked" requesters in MyPaint these days, there is no way to open any other type of hovering window, is there?):
![mypaint_sliderbug](https://cloud.githubusercontent.com/assets/294267/7272497/a291d5a4-e8eb-11e4-8e7e-680c456e98ab.png)

**Comment by Griatch** [comment] 2015-04-22 11:29
Just to add, I see the same behavior for other sliders, such as those in the "Ellipses and Circles" dock (Size, Opaque etc).

**Comment by achadwick** [comment] 2015-04-22 11:53
Thanks for the detailed information! Looks like it's some event masking thing eating click+drag, but that doesn't explain why you see it and I don't. Anything especially unusual about your device setup, or pointer shortcuts within KDE? Don't suppose you're using a gesture manager all?

Does upgrading to Rebecca (Linux Mint 7.1 LTS) fix it?

If we can rule out it just being all sliders in gtk3, it's not a MyPaint issue. What about the ones within `gtk3-widget-factory` (package `gtk-3-examples` on Debian, maybe mint too)?

**Comment by Griatch** [comment] 2015-04-22 11:59
The `gtk3-widget-factory` demo works just fine with the same setup, so alas I fear MyPaint is not off the hook just yet. :)  

I'm not using a gesture manager no. And although I usually use my custom right-side shortcut setup I tested this with purged settings.

I can try to update to 17.1 to see what comes of it. Will get back to you on that.

**Comment by Griatch** [comment] 2015-04-22 12:26
Upgraded to Linux Mint 17.1 (Rebecca) and this bug still remains for me there. The GTK3 versions are the same in this version as for 17.0  though.

**Comment by Griatch** [comment] 2015-04-22 12:28
... Also, reverting to c0c088b does not resolve this.

**Comment by Griatch** [comment] 2015-04-22 13:02
Found the issue! 

It seems I *was* using a non-Mint-default GTK3 theme - namely the "oxygen-gtk" theme. How this happened I don't know, maybe it carried over from a previous upgrade. Switch the GTK3 theme to anything else really (including the Default one, which is why it worked for you) and the slider works correctly. 

So this is resolved, but it might maybe be worth to warn for this somewhere. The oxygen theme was probably an old GTK3 default on previous versions of Mint KDE.

**Comment by achadwick** [comment] 2015-04-22 15:01
Oh, *that* theme! Yeah, we've had issues with oxygen-gtk in the past. I'm going to check out what Mint 17.1 KDE has as its default before closing this though.

Thanks for chasing this one down! :cake:

**Comment by achadwick** [comment] 2015-04-23 00:30
Okay, one weirdness here.

![image](https://cloud.githubusercontent.com/assets/61299/7288241/852f1524-e956-11e4-976e-b067f6c005f7.png) ← Linux Mint 17.1 KDE

* Linux Mint 17.1 KDE *does* have oxygen-gtk as its default configuration's theme, for both GTK2 and GTK3 (tested: virtualbox 64-bit VM guest as above, on a host with Intel graphics hardware)
* Kubuntu 14.04 LTS *also* has oxygen-gtk as its default configuration's theme, for both GTK2 and GTK3 (tested: directly on real Intel hardware, 64-bit system)
* Both work for me, so I think you *should* be able to use this theme now.

I'm running MyPaint with `./mypaint -c /tmp/cfgtmpN` though to make a throwaway config. People bitten by this bug could try that, and if it changes your experience, please report! It shouldn't change the way MyPaint dances though...

Other things to try: does using a different nvidia graphics driver fix it? Or non-accelerated graphics, maybe?

What I can say is that it's not a design decision of ours, and it seems to be a problem with a specific theme in KDE, under non-Intel and non-VirtualBox graphics drivers. Workaround is to use a different theme, possibly even the (ugly as sin) GTK default. Mint-X works for me too.

Closing, since this seems to be a fault in some other software (not completely sure what, but...). Please reopen if you can demonstrate otherwise!

**Closed by achadwick** 2015-04-23 00:30 UTC
Labels: upstream, works-for-me
