### ISSUE TITLE
MyPaint automaticly starts drawing, holding the left mouse button makes it stop

### ISSUE THREAD

**Issue by DioBrando2** [mypaint/mypaint#617] opened 2016-03-03 16:32 UTC
Whenever my mouse is on the drawing space it automaticly starts drawing but when i hold the left mouse button it stops,seems like its reverse

I've  tried reseting all the settings,but it still hasn't been fixed.

I

**Comment by achadwick** [comment] 2016-03-03 16:45
Is this a temporary thing? Does releasing the left mouse button again start drawing?

How did you reset all your settings?

**Comment by achadwick** [comment] 2016-03-03 16:49
@DioBrando2 
There's not quite enough information in your original report to move this issue forward. Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs). We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us. Please can you tell us at least:

* What operating system you are using, and its version?
* What MyPaint version you are using, and whether it's a "w32" or a "w64" one if you're on Windows
* Your tablet make and model number (look on the bottom of the pad)
* Your tablet driver version, if Windows (look in Add or Remove Programs for Wacom devices)

**Comment by DioBrando2** [comment] 2016-03-03 16:56
Windows;Windows 7
1.20,its w32
Not using a tablet

I reset all of my settings by going trought every tab in the settings menu and clicking "revert"

This problem seems to be happening in evey version i download (most of the new ones)

And,yes if i dont hold the left mouse button it automaticly starts drawing.

**Comment by achadwick** [comment] 2016-03-03 17:02
@DioBrando2 thanks for the info! No, this should not be happening. But it doesn't look too much like a bug right now either. Anyway, here's some workarounds to try:

* Does the behaviour change if you switch to a different brush? Some brushes are designed to splash paint around without you having to press anything.
* https://github.com/mypaint/mypaint/wiki/FAQ-No-zero-pressure any use?
* Can you fix it with https://github.com/mypaint/mypaint/wiki/v1.2-Global-Pressure-Mapping-Pressure-workaround ?
* If all else fails, please try resetting your configuration completely: https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset

**Comment by achadwick** [comment] 2016-03-03 17:03
This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code.

@DioBrando2 
You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/), from Twitter ([@MyPaintApp](https://twitter.com/MyPaintApp), #mypaint), on IRC ([#mypaint on freenode](irc://freenode/mypaint)), or on the [MyPaint mailing list](https://mail.gna.org/listinfo/mypaint-discuss).

**Comment by achadwick** [comment] 2016-03-03 17:03
**TRIAGE NOTE:** looks like a user support request.
This is the wrong forum for direct user support, reporter has been redirected to better places to ask.
This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status.

**Comment by achadwick** [comment] 2016-03-03 17:09
Resetting fully by deleting MyPaint's settings should fix this. There may be a bug to find in how MyPaint got into this state though! :bug: :mag: 

We'll need some better steps for reproducing this if it's to be treated as a bug. In the meantime I hope one of the workarounds fixes it.

My bet/fear is that it's a hardware or driver issue (oh, Windows... :computer:)

**Comment by DioBrando2** [comment] 2016-03-03 17:51
![ee](https://cloud.githubusercontent.com/assets/17620318/13503641/d31d7a06-e170-11e5-8df2-9ea478bffc0d.png)
I have fixed it,i messed around with the pressure settings and this combination has fixed it

Do you have any idea what the original problem was?

**Comment by achadwick** [comment] 2016-03-03 18:11
@DioBrando2 Strange curve! :astonished:

Mice tend not to send pressure details, but maybe not all? There's so much different hardware out there!

_Help → Debug → Test Input Devices_ will tell you if your mouse is different.
Normally we support devices that don't send pressure by faking an Input Pressure for them: 0.5 while the button's held, zero after you release the button. The fakery happens before the pressure curve above is applied.

The only thing I can think of besides that is if your pressure curve was a `\` downward slope (not a `/` upwards slope or the shape above), you'd get some painting pressure from zero input pressure.

(We've probably already ruled out a sticky mouse button... glad it's fixed for now :smile: )

**Comment by achadwick** [comment] 2017-01-23 19:16
It's not clear that this was ever a bug or a feature request. Closing.

**Closed by achadwick** 2017-01-23 19:16 UTC
Labels: needs-info, user-support
