### ISSUE TITLE
Blank layer and Edit Layer in External app... (workflow doubt)

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#241] opened 2015-03-06 13:49 UTC
If you open in another app the blank layer, only created and not yet modified on mypaint, this layer on destination app, e.g. on gimp, appears with 1x1 pixels layer and this can cause some workflow problems.
Suggestion:
Is possible, in this case (blank layer), to have automatically a canvas equal the current frame size on MyPaint? Or disable this possibility... and only save layers that mypaint uses.

**Comment by achadwick** [comment] 2015-04-21 23:33
This issue seems to have been buried for a bit. It is a bit strange, considering that we do this for vector layers (with a fancy/dubious dotted border too!)

Confirmed here on master at 0b3067fcb29312135aa14d8e90076611cc2b3f01. To reproduce

1. Start MyPaint and EITHER
  * do nothing, OR
  * paint something, then create a new layer;
2. Open the layers panel if it isn't already open (press the "L" key, by default);
3. Create a new blank painting layer by clicking the "+" button in the layers panel;
4. Ensure the layer is highlighted;
5. Press the right button over the layer to display the context menu, then choose "Edit Layer in External App...";
6. Choose a simple editor that shows the size; "Gnome Paint Drawing Editor" will do;
7. Note that the external edit file is 1x1.

I've tentatively assigned this to the 1st beta phase for 1.2 since I doubt it will introduce any string changes.

**Comment by achadwick** [comment] 2015-04-21 23:57
One thing that is worth noting: it's *very* easy to create a saved image in MyPaint which is rather big for other apps to handle. For example, at the 6.25% zoom, that would create quite a big image for a 1080p screen:

```calc
; s = 2**4
; s*1920; s*1080;
	30720
	17280
```

Which saves as (estimated) 5 to 6MB of blank, lightly compressed PNG data that on expansion may slow down a system a lot, or even crash the other program out depending on how it represents the image internally.

This isn't an issue with vector layers, of course. Perhaps this is one place where it would be OK to expose the internal tile size and just get the user to resize an image which is at minimum 64x64 px. That ought to be more obvious and manageable than the current approach.

Using any user-defined frame size is another option of course, and it's more consistent, but I quite like the idea of opening just a fragment of a wider image in a separate app.

**Comment by americogobbo** [comment] 2015-04-22 00:45
I understand your preoccupation... the great feature of MyPaint is exactly this. But perhaps a small "tessera" 64x64 px is the ideal and sufficient.

**Closed** 2015-07-19 21:28 UTC
Labels: enhancement, UX
