### ISSUE TITLE
MyPaint 1.2.1 w64 crashing on scrap-related actions

### ISSUE THREAD

**Issue by eradikal** [mypaint/mypaint#793] opened 2017-04-04 21:10 UTC
#### Description of the problem
Installed a few of the latest releases (1.2.0 stable, all 1.2.1 betas, 1.2.1 stable for w64 from installer). Seems to constantly crash on various scrap-related actions (load scrap from backup, save scrap as specifically).
Tried clean uninstall and install, tried running the provided w64 debug console but when running it MyPaint doesn't even load. 

#### Basic system details

MyPaint version: 1.2.1 Stable W64
Operating system: Win7 Home Premium

#### Steps to reproduce
1. Start MyPaint
2. Choose scrap from backup to load and save
3. select file path to save.
4. System crashes, "python2w.exe stopped responding" prompt.

Or
1. Start Mypaint
2. Draw
3. Save Scrap As
4. Select file path to save
5. System crashes, "python2w.exe stopped responding" prompt.

#### Backtraces or error messages
```
Running gdb.exe...
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
c:\program files\mypaint-w64\mingw64\bin\../etc/gdbinit:5: Error in sourced comm
and file:
Error while executing Python code.
Reading symbols from python2.exe...(no debugging symbols found)...done.
Starting program: C:\program files\mypaint-w64\mingw64\bin\python2.exe mingw64/b
in/mypaint
[New Thread 4676.0x13f4]
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefi
x u'C:/Program Files/mypaint-w64/mingw64'
INFO: lib.i18n: Windows: LANG='he_IL'
INFO: lib.i18n: Windows: LANGUAGE='he_IL'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain fu
ncs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (c
types)
[New Thread 4676.0x11dc]
[New Thread 4676.0x15c4]
[New Thread 4676.0x17a8]
[New Thread 4676.0x11b8]
[New Thread 4676.0x17a0]
[New Thread 4676.0x1010]
warning: HEAP[python2.exe]:
warning: Heap block at 000000000D353AF0 modified at 000000000D353B01 past reques
ted size of 1

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00000000773f9e52 in ntdll!EtwpCreateEtwThread ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt full
#0  0x00000000773f9e52 in ntdll!EtwpCreateEtwThread ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00000000774097c1 in ntdll!RtlFindClearBits ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#2  0x00000000773d65f3 in ntdll!EtwEventSetInformation ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#3  0x00000000774142d9 in ntdll!RtlLogStackBackTrace ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#4  0x00000000773b797c in ntdll!TpAlpcRegisterCompletionList ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#5  0x000007feff4910c8 in msvcrt!free () from C:\Windows\system32\msvcrt.dll
No symbol table info available.
#6  0x000000006241e64b in ?? ()
   from C:\program files\mypaint-w64\mingw64\lib\python2.7\site-packages\gi\_gi.
pyd
No symbol table info available.
#7  0x000000006241cbd8 in ?? ()
   from C:\program files\mypaint-w64\mingw64\lib\python2.7\site-packages\gi\_gi.
pyd
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#8  0x000000006241e2ff in ?? ()
   from C:\program files\mypaint-w64\mingw64\lib\python2.7\site-packages\gi\_gi.
pyd
No symbol table info available.
#9  0x000000006ce4b701 in libpython2.7!PyObject_Call ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#10 0x000000006ceddd95 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#11 0x000000006cee0445 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#12 0x000000006cee0445 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#13 0x000000006cee0445 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#14 0x000000006cee243a in libpython2.7!PyEval_EvalCodeEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#15 0x000000006ce6f687 in libpython2.7!PyFrame_Fini ()
---Type <return> to continue, or q <return> to quit---
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#16 0x000000006ce4b701 in libpython2.7!PyObject_Call ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#17 0x000000006ce594ec in libpython2.7!PyCell_Set ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#18 0x000000006ce4b701 in libpython2.7!PyObject_Call ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#19 0x000000006cea0696 in libpython2.7!_PyObject_LookupSpecial ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#20 0x000000006ce9d1a1 in libpython2.7!PyType_IsSubtype ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#21 0x000000006ce4b701 in libpython2.7!PyObject_Call ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#22 0x000000006ceddd95 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#23 0x000000006cee243a in libpython2.7!PyEval_EvalCodeEx ()
---Type <return> to continue, or q <return> to quit---
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#24 0x000000006ce6f762 in libpython2.7!PyFrame_Fini ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#25 0x000000006ce4b701 in libpython2.7!PyObject_Call ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#26 0x000000006ce594ec in libpython2.7!PyCell_Set ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#27 0x000000006ce4b701 in libpython2.7!PyObject_Call ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#28 0x000000006cea0696 in libpython2.7!_PyObject_LookupSpecial ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#29 0x000000006ce9d1a1 in libpython2.7!PyType_IsSubtype ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#30 0x000000006ce4b701 in libpython2.7!PyObject_Call ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#31 0x000000006ceddd95 in libpython2.7!PyEval_EvalFrameEx ()
---Type <return> to continue, or q <return> to quit---
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#32 0x000000006cee243a in libpython2.7!PyEval_EvalCodeEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#33 0x000000006cee0284 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#34 0x000000006cee243a in libpython2.7!PyEval_EvalCodeEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#35 0x000000006cee0284 in libpython2.7!PyEval_EvalFrameEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#36 0x000000006cee243a in libpython2.7!PyEval_EvalCodeEx ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#37 0x000000006cee255f in libpython2.7!PyEval_EvalCode ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#38 0x000000006cefa512 in libpython2.7!PyGILState_Release ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#39 0x000000006cefb7c1 in libpython2.7!PyRun_FileExFlags ()
---Type <return> to continue, or q <return> to quit---
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#40 0x000000006cefcdfd in libpython2.7!PyRun_SimpleFileExFlags ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#41 0x000000006cf0d9c8 in libpython2.7!Py_Main ()
   from C:\program files\mypaint-w64\mingw64\bin\libpython2.7.dll
No symbol table info available.
#42 0x00000000004013f8 in ?? ()
No symbol table info available.
#43 0x000000000040151b in ?? ()
No symbol table info available.
#44 0x00000000772459cd in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\system32\kernel32.dll
No symbol table info available.
#45 0x000000007737a561 in ntdll!RtlUserThreadStart ()
   from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#46 0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
(gdb)
```

**Comment by jplloyd** [comment] 2020-07-11 15:05
I can only speculate that this may have been related to not handling corrupt backup data gracefully, but I cannot reproduce this with new builds on Windows 10. Closing this, since 1.2.1 won't receive any updates, and Windows 7 is out of support.

**Closed by jplloyd** 2020-07-11 15:05 UTC
Labels: windows
