### ISSUE TITLE
Near-immediate crash

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#526] opened 2015-12-08 04:08 UTC
Startup log:

```
$ mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
INFO: mypaint: There is an old-style configuration area in u'/home/kau/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOME and $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
INFO: lib.i18n: POSIX: LANG='en_AU.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py:1554: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  initialized, argv = Gtk.init_check(sys.argv)
zsh: segmentation fault (core dumped)  mypaint
```
Same results occur even if I nuke all configuration (~/.mypaint and ~/.config/mypaint), nuke /usr/share/mypaint and /usr/lib/mypaint, and rebuild ('sudo scons -c; sudo scons enable_gegl=yes prefix=/usr;sudo scons -c; sudo scons enable_gegl=yes prefix=/usr install'. 
I have also tried the mypaint-git package in AUR, that produces same result too (and doesn't use enable_gegl=yes flag, FWIW that probably means problem isn't gegl related). 

I have also tried running straight from source dir, that doesn't work either.

Plain `mypaint` package (1.1.0) starts okay, but of course is ancient and all brushes are literally unusable (cannot be selected), so it's not a real option. 

System information:
* Arch Linux x86_64
* GTK3 3.18.5-13.18.5-1
* Glib2 2.46.2-2
* gobject-introspection 1.46.0-1

**Comment by achadwick** [comment] 2015-12-08 13:32
Okay, please follow the steps in DEBUGGING.md. This needs the fullest sort of backtrace you can give. Logging output in non-debug mode is not enough.

Are you able to run any simple Python scripts that make use of GObject-Introspection? Try https://gist.github.com/achadwick/54e5b111e5ac908becf1 - it's not exactly minimal, but it tests a lot of PyGI stuff.

**Comment by dannielsoares** [comment] 2015-12-09 03:23
Maybe not really related, but I was having, somewhat randomly, crashes/segfaults *when I moved the canvas* (barely, just holding the button), even before the first stroke. Didn't matter if it was a new image or a loaded file. It was happening nearly every time, but not really always. It's possibly unrelated, as after "resetting" the ".mypaint" folder, it didn't happen again, so far -- but maybe it is just random luck for now. My main point is that perhaps "moving the canvas" could be the culprit, or a clue to it, I guess.

Maybe I'm going too far and being to random with ignorant "clues", but I didn't know until this month that some GTK3 themes could make applications such as Firefox and Icedove crash, according to some recent forum threads (such as https://bbs.archlinux.org/viewtopic.php?id=181476 ). Oxygen-GTK was supposedly the theme making it crash. That wouldn't be something I'd naturally check before, but was going to be the next thing if resetting the dot-folder didn't seem to work... but it looks like it did.

**Comment by 0ion9** [comment] 2015-12-09 03:49
@achadwick: Yes, axischart works, my pyGI still isn't broken, same as last time you asked ;)

Insofar as DEBUGGING.md. it doesn't appear to work:

```
gdb -ex r --args python ./mypaint -c /tmp/cfgtmp_throwaway_2
GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
Starting program: /usr/bin/python ./mypaint -c /tmp/cfgtmp_throwaway_2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Traceback (most recent call last):
  File "./mypaint", line 419, in <module>
    stderr_fp = os.fdopen(stderr_fd, 'ab', 0)
  File "/usr/lib/python3.5/os.py", line 1028, in fdopen
    return io.open(fd, *args, **kwargs)
OSError: [Errno 29] Illegal seek
[Inferior 1 (process 1790) exited with code 01]
```
My best guess initially is that gdb is doing something weird with stdout and mypaint doesn't understand it.

That said, there weren't any -debug / -dbg packages for gtk or python2.7. so I might have to build them manually and retry then.

**Comment by achadwick** [comment] 2015-12-09 10:18
@dannielsoares Seems pretty clearly unrelated to this one.

**Comment by achadwick** [comment] 2015-12-09 10:20
@0ion9 Okay, yes. Arch doesn't do convenient debug packages ☺
Can you confirm you're running the latest revision of of git, by SHAsum please?

I can't reproduce this crash at startup on Debian testing/unstable running

* Linux kernel 4.2.0-1-amd64
* gtk-3-0 3.18.5
* libglib2.0-0 2.46.2-1
* gir1.2-freedesktop 1.46.0-2
* gir1.2-glib-2.0 1.46.0-2
* libgirepository-1.0-1 1.46.0-2

This should be basically the same setup as yours, so perhaps this is Arch-specific.

It would be helpful to isolate this to a specific line in the MyPaint source code. Have you run the program with MYPAINT_DEBUG turned on yet? When you do that next, please also try `-t`:

    $ MYPAINT_DEBUG=1 mypaint -t -c /tmp/throwawaycfg$$

then when it crashes, please paste the lines between the last colourful line from MyPaint and the segfault notification from zsh inclusive. MyPaint will run really slowly with `-t` and print every line it executes, so be prepared form a short wait. There may be a lot of output even if you limit it, so use a gist if there's too much to fit on a screen.

**Comment by 0ion9** [comment] 2015-12-09 10:33
Ah, no, I'd only tried to run it in gdb.
[backtrace from your suggested cmdline -- 19000+ lines. haha, what.](https://gist.github.com/0ion9/8ed323be0ae70aab9e77/raw/aa4cafa5358cbc08390cf469e9a1214e6ee63816/hugebacktrace.txt)

**Comment by achadwick** [comment] 2015-12-09 10:58
Pretty weird. It seems to be trying to format a debug message bubbling up from 

```
workspace.py(2104):     screen, ptr_x, ptr_y, _modmask = display.get_pointer()
```

which I think is the last line real line of code in MyPaint that gets executed. Let's exclude the special colour formatter and the lines that duplicate stderr, just in case:

```sh
$ ./mypaint -c /tmp/junk-config-$$ 2>&1 | cat
```

I hope that redirection is good for zsh. Try it in bash if zsh complains. In fact, please can you try it in bash anyway, and I'll try zsh my end.

**Comment by achadwick** [comment] 2015-12-09 11:02
Okay, that `2>&1 | cat` incantation does work in zsh (5.1.1) on mine. Hopefully that can be excluded.

**Comment by 0ion9** [comment] 2015-12-09 11:25
Doesn't appear to produce anything useful:

```
INFO: mypaint: Installation layout: not installed, testing from within the source tree
INFO: mypaint: There is an old-style configuration area in u'/home/kau/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOME and $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
INFO: lib.i18n: POSIX: LANG='en_AU.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py:1554: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  initialized, argv = Gtk.init_check(sys.argv)
```
And modifying the commandline with MYPAINT_DEBUG=1 to include 2>&1 | cat, results in [this](https://gist.github.com/0ion9/b544010a00793ab480be), in which it wanders around for a bit in filehandling.py, ends up trying to start a thread? and crashes while trying to decrease a refcount?
Well, it's the same *kind* of crash as before (attribute access).. and also within the python stdlib like before.

I'm beginning to suspect something is seriously hokey with python2.7.

**Comment by achadwick** [comment] 2015-12-09 13:28
That threading stuff gets invoked by the standard logging module (I think). All it's trying to do is format up a warning from GI that a particular function is now deprecated:

```
WARNING: py.warnings: /home/kau/zba/xra/mypaint-gtk3-gk/gui/workspace.py:2104: DeprecationWarning: Gdk.Display.get_pointer is deprecated
  screen, ptr_x, ptr_y, _modmask = display.get_pointer()
```

@0ion9 Does the following interactive test behave similarly on your machine, or does it break on any of the warnings?

```
Python 2.7.10+ (default, Oct 10 2015, 09:11:24) 
[GCC 5.2.1 20151028] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging, warnings
>>> logging.basicConfig(level=logging.DEBUG)
>>> logger = logging.getLogger("testpy")
>>> logger.info("hello, world")
INFO:testpy:hello, world
>>> warnings.resetwarnings()
>>> logging.captureWarnings(True)
>>> def f():
...     logger.info("hello, f()")
...     return False
... 
>>> from gi.repository import GObject
>>> GObject.idle_add(f)
WARNING:py.warnings:__main__:1: PyGIDeprecationWarning: GObject.idle_add is deprecated; use GLib.idle_add instead

1L
>>> from gi.repository import Gtk
WARNING:py.warnings:__main__:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.

>>> GObject.idle_add(f)
8L
>>> GObject.idle_add(Gtk.main_quit)
9L
>>> Gtk.main()
INFO:testpy:hello, f()
INFO:testpy:hello, f()
>>> quit()
```

**Comment by 0ion9** [comment] 2015-12-09 13:54
@achadwick : similarly; not exactly the same.
Particularly, note the added message here:

```
>>> from gi.repository import Gtk
WARNING:py.warnings:/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py:1554: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  initialized, argv = Gtk.init_check(sys.argv)

WARNING:py.warnings:__main__:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
```

Also:

```
>>> GObject.idle_add(f)
7L
>>> GObject.idle_add(Gtk.main_quit)
8L
```
I believe this indicates that one less callback has been registered.

All other messages match exactly.

**Comment by achadwick** [comment] 2015-12-09 16:00
@0ion9 Are you able to patch with the diff in https://github.com/mypaint/mypaint/issues/513#issuecomment-163302927 and see if this moves the problem on somewhere else?

**Comment by achadwick** [comment] 2015-12-09 16:52
@dannielsoares may be right about this being related to #513. Same call, different places in the code maybe. I'll treat them together when I have a chance; the other thread has the beginnings of a strategy now.

Are affected people using Wayland or Xorg, just out of interest?

**Comment by 0ion9** [comment] 2015-12-09 21:03
@achadwick Applying the #513 patch allows Mypaint to start. However, as soon as I press a key or click, I get a similar crash in the threading module. Can paste log if wanted (but it really isn't that different from the last one)

I'm using Xorg too -- 1.18.0-3 , which I see is slightly newer than Mikshaw's version

**Comment by achadwick** [comment] 2015-12-11 00:08
Reproduced with master as of a1e8ac1a981efdf0faa7b9b557a1044ee3929b5d and GDK + GTK 3.18.5 under GNOME on Xorg. You have to use a secondary device like a tablet to trigger it - basically make it the last device used, so that X considers it the core pointer.

I don't know what's changed upstream, but for MyPaint's purposes we can replace the deprecated old-style calls with new ones referring to the "client pointer" device (a.k.a. the core pointer as determined by X or whatever) and everything should be fine.

Closing as a duplicate of #513.

**Closed by achadwick** 2015-12-11 00:08 UTC
Labels: bug, duplicate, upstream

**Comment by achadwick** [comment] 2015-12-11 02:32
Upstream report: https://bugzilla.gnome.org/show_bug.cgi?id=759323
