### ISSUE TITLE
Language setting in mypaint-w32-1.2.1-20170129a

### ISSUE THREAD

**Issue by winterfuyu** [mypaint/mypaint#868] opened 2017-10-19 23:25 UTC
I noticed when installing it did not give me an option to choose the language like it used to in the previous version. I have a Japanese locale but most of my installed apps are in English because either I could change it in the preferences or it gave me an option before installing. Is there a way to change the language at all in 1.2.1?

**Comment by achadwick** [comment] 2017-10-24 14:02
There is no way to change the language in 1.2.1.

Let's turn this user support request into something that can be worked on.

I don't think we have ever offered a choice of language. Earlier versions offered to not install translations, which would result in MyPaint falling back to the default (something resembling English).

"Styrene":https://github.com/achadwick/styrene (the repacker and bundle maker that MyPaint uses) is a bit too simplistic to offer modules right now. But I guess there's scope for it to manage the translation areas during (re)installation. Hmm.

**Comment by odysseywestra** [comment] 2017-10-24 17:15
Possible Duplicate of #772

**Comment by hansjacobwagner** [comment] 2018-01-28 10:21
My god - You should try the danish UI.
They are for some reason very hard to make, I never saw any that felt right.
And this for some part feels like done by google translate. You have to read the danish term, then search for meaning in English, because the danish doesn't give any direct sense.
Please give the option to download an English Ver.
As is - to distracting.

**Comment by jplloyd** [comment] 2019-10-13 15:40
Language settings are now available in master - there is a dropdown menu in the preferences under the "View" tab. 

[Windows build](https://ci.appveyor.com/project/achadwick/mypaint/build/job/62kj1tw7av0vw57c/artifacts)
[Linux appimage](https://github.com/mypaint/mypaint-appimage/releases/tag/continuous)

**Closed by jplloyd** 2019-10-13 15:40 UTC
Labels: enhancement, translation, windows
