### ISSUE TITLE
v2.0.1 AppImage does not start when local user-install of numpy is available

### ISSUE THREAD

**Issue by mryndzionek** [mypaint/mypaint#1093] opened 2020-07-09 15:25 UTC
#### Description of the problem

Running AppImage on Linux Mint 19.1 Tessa fails. Numpy is installed.

#### Basic system details

MyPaint version: [✍ 2.0.1]
Operating system: [✍ Linux Mint 19.1 Tessa]
Desktop environment: [✍ Xfce]

#### Steps to reproduce

1. Start MyPaint:
```
./MyPaint-v2.0.1.AppImage
```

#### Backtraces or error messages

```
DIR: /tmp/.mount_MyPainJH9aM8
No explicit user theme set
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/tmp/.mount_MyPainJH9aM8/usr'
INFO: mypaint: Using brushdir path relative to installation-prefix
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/tmp/.mount_MyPainJH9aM8/usr/bin/mypaint", line 55, in <module>
    datapath,iconspath,old_confpath,localepath=get_paths();logger.debug('datapath: %r',datapath);logger.debug('iconspath: %r',iconspath);logger.debug('old_confpath: %r',old_confpath);logger.debug('localepath: %r',localepath)
  File "/tmp/.mount_MyPainJH9aM8/usr/bin/mypaint", line 44, in get_paths
    else:from lib import fileutils as P;Q=P.expanduser_unicode(u'~');D=B(Q,'.mypaint/')
  File "/tmp/.mount_MyPainJH9aM8/usr/lib/mypaint/lib/fileutils.py", line 2, in <module>
    import os,os.path,sys,functools,logging,shutil,unicodedata,lib.helpers
  File "/tmp/.mount_MyPainJH9aM8/usr/lib/mypaint/lib/helpers.py", line 7, in <module>
    from .  import mypaintlib
  File "/tmp/.mount_MyPainJH9aM8/usr/lib/mypaint/lib/mypaintlib.py", line 7, in <module>
    _mypaintlib=swig_import_helper();del swig_import_helper
  File "/tmp/.mount_MyPainJH9aM8/usr/lib/mypaint/lib/mypaintlib.py", line 6, in swig_import_helper
    except ImportError:return A.import_module('_mypaintlib')
  File "/tmp/.mount_MyPainJH9aM8/usr/lib64/python2.7/importlib/__init__.py", line 19, in import_module
    __import__(A);return sys.modules[A]
ImportError: No module named _mypaintlib
```

**Comment by jplloyd** [comment] 2020-07-09 15:34
Hmm, is this a 32bit version of Mint? That's the only reason I can think of that would cause an error like this.

**Comment by mryndzionek** [comment] 2020-07-09 15:55
No, it's 64:
```
4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I know it's strange. Tried with different Numpy version installed via APT and pip - no luck.

**Comment by jplloyd** [comment] 2020-07-09 16:04
You don't need to install any numpy version for the appimage to work - it bundles both python and the libraries it needs. If it fails to run because of a system-installed numpy that would obviously be a problem.

I'll try it on a clean Mint 19 install to see if it fails out of the box.

**Comment by mryndzionek** [comment] 2020-07-09 16:58
Okay, I know that AppImage leaves some packages/libraries out, so I thought Numpy is one of them.

**Comment by jplloyd** [comment] 2020-07-09 17:41
Yes, some core libraries are excluded in the build process.

On a clean install of [19.1 Tesoo xfce](https://www.linuxmint.com/edition.php?id=265) in a vm, both the v2.0.1 appimage and the latest alpha appimage run without any issues. I can't reproduce your error after fully upgrading the system either, neither with nor without numpy (not that it _should_ make a difference).

To cover the unlikely case that the binary got corrupted during the download, check the sha256sum, which should be:
`626cf82d7dc60195e5de872b673b958dd01aca0a6f5f399c8691a1ca5e2adc26`

If that is not the issue, does the v2.0.0 appimage work?

**Comment by mryndzionek** [comment] 2020-07-09 19:30
The sum is correct. If run it as root it works! It seems that it has something to do with environment variables settings.

**Comment by jplloyd** [comment] 2020-07-09 19:57
You can extract the contents of the appimage by running it with `--appimage-extract`. The contents will end up in a directory named `squashfs-root`, where the file `AppRun` contains the setup which sets environment variables and starts the bundled MyPaint installation. Running `./AppRun` from that directory should work the same as running the appimage itself. If that doesn't work (when not running as root) it seems something is up with your linker configuration (best guess).

**Comment by mryndzionek** [comment] 2020-07-09 20:10
When running `./AppRun` the result is the same... Also, `MyPaint-v2.0.0-1.AppImage` works okay.

**Comment by jplloyd** [comment] 2020-07-09 20:55
Ok, then as a holdover, here is an appimage build of v2.0.1 using the setup for v2.0.0:
zipped appimage: https://0x0.st/itZR.zip (link should be valid for 100+ days)
md5 of zip: fb2cf5966f085f7f3518aebe8b284110
md5 of appimage: 4891d13f197746c064d5011f92443b75

The v2.0.1 appimage has been downloaded some ~1700 times, so either this is not a common issue, or no other affected person bothered to report it. It would be nice to figure exactly why it happens though, so we can roll back only the relevant changes, or fix the root cause.

**Comment by mryndzionek** [comment] 2020-07-09 21:08
This one fails with:
```
DIR: /tmp/.mount_MyPainTFQSoA
AILIBDIR=/tmp/tmp.xo9bJKxxWQ
awk: /tmp/tmp.xo9bJKxxWQ/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
deleting /tmp/tmp.xo9bJKxxWQ/libxcb-dri3.so*
awk: /tmp/tmp.xo9bJKxxWQ/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
System stdc++ library: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
System stdc++ library version: "3.4.25"
Bundled stdc++ library version: "3.4.19"
Newest stdc++ library version: "3.4.25"
Using system stdc++ library
awk: /tmp/tmp.xo9bJKxxWQ/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
atomiclib: /usr/lib/x86_64-linux-gnu/libatomic.so.1
Checking versions of library "libfontconfig"
awk: /tmp/tmp.xo9bJKxxWQ/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
  system library: "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1" (libfontconfig.so.1.10.1)
  system library version: 1.10.1
  ailib: "/tmp/.mount_MyPainTFQSoA/usr/lib/libfontconfig.so.1.11.1"
  bundled library: "/tmp/.mount_MyPainTFQSoA/usr/lib/libfontconfig.so.1.11.1" (libfontconfig.so.1.11.1)
  bundled library version: 1.11.1
  newest library version: "1.11.1"
Checking versions of library "libfreetype"
awk: /tmp/tmp.xo9bJKxxWQ/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
  system library: "/usr/lib/x86_64-linux-gnu/libfreetype.so.6.15.0" (libfreetype.so.6.15.0)
  system library version: 6.15.0
  ailib: "/tmp/.mount_MyPainTFQSoA/usr/lib/libfreetype.so.6.14.0"
  bundled library: "/tmp/.mount_MyPainTFQSoA/usr/lib/libfreetype.so.6.14.0" (libfreetype.so.6.14.0)
  bundled library version: 6.14.0
  newest library version: "6.15.0"
Removing bundled "libfreetype"
removed '/tmp/tmp.xo9bJKxxWQ/libfreetype.so.6'
removed '/tmp/tmp.xo9bJKxxWQ/libfreetype.so.6.14.0'
GTK_PATH=/tmp/.mount_MyPainTFQSoA/usr/lib/gtk-2.0
GTK_IM_MODULE_FILE=/tmp/.mount_MyPainTFQSoA/usr/lib/gtk-2.0:/tmp/.mount_MyPainTFQSoA/usr/lib/gtk-2.0
PANGO_LIBDIR=/tmp/.mount_MyPainTFQSoA/usr/lib
/tmp/.mount_MyPainTFQSoA/apprun-helper.sh: line 130: /tmp/.mount_MyPainTFQSoA/startup_scripts/*.sh: No such file or directory
No explicit user theme set

** (process:7119): WARNING **: 23:02:24.259: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: /usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: __GLXGL_CORE_FUNCTIONS
Traceback (most recent call last):
  File "/tmp/.mount_MyPainTFQSoA/gtk-theme-helper.py", line 6, in <module>
    from lib.glib import get_user_config_dir
  File "/tmp/.mount_MyPainTFQSoA/usr/lib/mypaint/lib/glib.py", line 5, in <module>
    from lib.gibindings import GLib
  File "/tmp/.mount_MyPainTFQSoA/usr/lib/mypaint/lib/gibindings.py", line 11, in <module>
    from gi.repository import Gdk
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/site-packages/gi/importer.py", line 41, in load_module
    B=load_overrides(F)
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 33, in load_overrides
    F=importlib.import_module(I)
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/importlib/__init__.py", line 19, in import_module
    __import__(A);return sys.modules[A]
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/site-packages/gi/overrides/Gdk.py", line 36, in <module>
    Color=override(Color)
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 61, in override
    B=C.get_g_type();assert B!=TYPE_NONE
AssertionError
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/tmp/.mount_MyPainTFQSoA/usr'
INFO: mypaint: Using brushdir path relative to installation-prefix

** (process:7120): WARNING **: 23:02:24.494: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: /usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: __GLXGL_CORE_FUNCTIONS
Traceback (most recent call last):
  File "/tmp/.mount_MyPainTFQSoA/usr/bin/mypaint", line 293, in <module>
    = get_paths()
  File "/tmp/.mount_MyPainTFQSoA/usr/bin/mypaint", line 241, in get_paths
    from lib import fileutils
  File "/tmp/.mount_MyPainTFQSoA/usr/lib/mypaint/lib/fileutils.py", line 2, in <module>
    import os,os.path,sys,functools,logging,shutil,unicodedata,lib.helpers
  File "/tmp/.mount_MyPainTFQSoA/usr/lib/mypaint/lib/helpers.py", line 5, in <module>
    from lib.gibindings import GdkPixbuf
  File "/tmp/.mount_MyPainTFQSoA/usr/lib/mypaint/lib/gibindings.py", line 11, in <module>
    from gi.repository import Gdk
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/site-packages/gi/importer.py", line 41, in load_module
    B=load_overrides(F)
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 33, in load_overrides
    F=importlib.import_module(I)
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/importlib/__init__.py", line 19, in import_module
    __import__(A);return sys.modules[A]
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/site-packages/gi/overrides/Gdk.py", line 36, in <module>
    Color=override(Color)
  File "/tmp/.mount_MyPainTFQSoA/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 61, in override
    B=C.get_g_type();assert B!=TYPE_NONE
AssertionError
```
I really would like to go to the bottom of this. Could you maybe help me with decoding my original Traceback? First it says that it cannot find numpy, then there is a trace showing that it fails somewhere while setting-up paths and then at the end it says that it cannot find _mypaintlib. I don't know what does things have in common, what is the thing that connects them.

**Comment by jplloyd** [comment] 2020-07-09 21:33
Fairly sure that the ImportError for `_mypaintlib` is caused by the failure to import numpy, and is not a separate issue. I get the same error on the Tesso vm for the previous build, this build does work (on my vm):

https://github.com/mypaint/mypaint/releases/download/v2.0.1/MyPaint-v2.0.1-alt.AppImage

I'll look into this again over the weekend.

**Comment by mryndzionek** [comment] 2020-07-09 21:45
Yeah, this one works. So what is different in this one?

**Comment by jplloyd** [comment] 2020-07-10 05:47
The first one was built on a known faulty commit (I forgot it was faulty): [7f4a209c486cba](https://github.com/mypaint/mypaint-appimage/commit/7f4a209c486cba59bb1fdf5350a3a93aead9b391).

As for the changes between the latest version and the known working version, there are 43 commits, of which maybe a dozen could be relevant. The fact that you can run the image as root suggests the problem does not come down to missing dependencies, but rather the wrong library/module being prioritized somewhere due to your setup. To be clear: that would not be a problem with your setup, but a bug in the appimage.

If it's not too much of a bother, could you create a new user on your system and see if the appimage (the original one) works when running as that user - to rule out user access as an issue?

**Comment by mryndzionek** [comment] 2020-07-10 06:20
> If it's not too much of a bother, could you create a new user on your system and see if the appimage (the original one) works when running as that user - to rule out user access as an issue?

Yes, it works.

**Comment by jplloyd** [comment] 2020-07-10 20:19
After installing a local python 2.7 version of numpy with `pip install numpy` on the same vm, I can reproduce the original error. Shouldn't be too hard to fix.

**Comment by jplloyd** [comment] 2020-07-11 07:36
Fixed in https://github.com/mypaint/mypaint-appimage/commit/bbea03cbab723f62acbf263479a1dd91e944d227

You can download the latest continuous release here to confirm: 
https://github.com/mypaint/mypaint-appimage/releases/tag/continuous

**Closed by jplloyd** 2020-07-11 07:36 UTC
Labels: bug, packaging

**Comment by mryndzionek** [comment] 2020-07-11 08:22
Thanks for resolving this so quickly!
