### ISSUE TITLE
brushes will not close out of main window 

### ISSUE THREAD

**Issue by Jeffro012** [mypaint/mypaint#667] opened 2016-04-28 22:59 UTC
The brushes I installed will not close out of the main window, there are several layers of them that re-open even after I restart. 

(side note, I totally love this program minus the bloopers and the crashes I've created some awesome works with it and hope this gets resolved, thank you to the creators)

**Comment by achadwick** [comment] 2016-04-29 09:32
Hi there - thanks for the report!

What does this mean? What do you see? Screenshots would be helpful. You must tell us the version you are running. You must tell us what operating system you are working with.

There's not quite enough information in your original report to move this issue forward, sadly. Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs). We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

**Comment by Jeffro012** [comment] 2016-04-29 21:55
Hi there,  Thank you for getting back with me.  Today, for some bizarre reason it won't open at all.  I'm running windows 10, a rebuild of windows 7 and 8.   (Since I cannot open it, I'll do my best to describe it), The brush windows once open will not close, they also pop out and become unmoveable (when I can finally select a brush), even when I use the small icon or click move box.   Prior to it shutting me out completely, it also would show several windows where I had attempted to open a brush pack.  It also goes into "Program Close" and shuts me down when I attempt to use features such as the "Circle Feature" it will almost always kick me out of the whole program.  When I can finally open it again, (I may have to uninstall it and reinstall it before I can get back into it) and IF it behaves like that again I will gladly screen shot it for you.  

Sorry this is all I have for the moment.   Jeff 

    On Friday, April 29, 2016 5:33 AM, Andrew Chadwick <notifications@github.com> wrote:
 

 Hi there - thanks for the report!What does this mean? What do you see? Screenshots would be helpful. You must tell us the version you are running. You must tell us what operating system you are working with.There's not quite enough information in your original report to move this issue forward, sadly. Please read the bug reporting guidelines. We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.—

**Comment by Jeffro012** [comment] 2016-04-29 21:58
Here is a link for your viewing pleasure to show you some of the work I've done with the program.  I truly love this program btw.  

thepossumfamily.wix.com/jeffro  
 Jeff 

    On Friday, April 29, 2016 5:33 AM, Andrew Chadwick <notifications@github.com> wrote:
 

 Hi there - thanks for the report!What does this mean? What do you see? Screenshots would be helpful. You must tell us the version you are running. You must tell us what operating system you are working with.There's not quite enough information in your original report to move this issue forward, sadly. Please read the bug reporting guidelines. We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.—

**Comment by achadwick** [comment] 2016-04-29 22:49
I still don't know what version of MyPaint you are running, and now there are multiple things going wrong, and it sounds like you have fresh installation issues happening. I'm sorry you are having so much trouble using MyPaint, but all I can do now is point you at the FAQ and the forums. This isn't something I can fix as a developer, at least not without some big splitting up and careful reporting of each individual sub-thread.

* https://github.com/mypaint/mypaint/wiki/FAQ (hint: try [deleting the config and starting again](https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset))

This issue tracker is not for direct user support. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. The main task for this tracker is to turn problems into stuff programmers can actually do something about.

If you think you really have identified a bug, please make sure it's easily reproducible, then walk me through what *I* have to do to see it for myself.

Don't be discouraged if we can't help here. Issue trackers don't get that many views, sadly. You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/).

**Comment by achadwick** [comment] 2016-04-29 22:53
Unfortunately I can't take this report any further because there are too many problems bundled into this single issue. This issue tracker only operates effectively when there's a single problem in each issue thread.

Please can you do what I suggested above, and if you really have found a bug, report each one separately in its own thread. Thanks.

**Comment by achadwick** [comment] 2016-04-29 22:53
**TRIAGE NOTE:** piggybacked issue report.
Closed: requested reporter to split out each sub-issue into a new topic.

**Closed by achadwick** 2016-04-29 22:53 UTC
Labels: needs-info, user-support

**Comment by achadwick** [comment] 2016-04-29 22:58
(BTW, the Community Forums are also a great place to share cool artwork you make - lots of users do just that! Sorry about the hyper-focus of this place - the forums are friendlier, and they have cake :cake:)

(Okay, probably no cake. But I hope we can help you get your problems fixed over there anyway :smile: )
