### ISSUE TITLE
[Feature Request] - Customisable Tool Options Panel

### ISSUE THREAD

**Issue by RyanHarvieStark** [mypaint/mypaint#964] opened 2019-02-07 02:04 UTC
In the brush editor you could have an option for each setting to allow it to appear as a slider in the tool options panel. This would improve Mypaint's usability. Each brush could have appropriate custom settings immediately accessible instead of having to open the brush editor. For example, a brush that is designed for smudging might benefit from smudge control being immediately accessible. A more textural brush might benefit from jitter being immediately accessible etc etc. The current tool option panel sliders would be fine as a default.

This is how Clip Paint Studio handles quick access to brush settings and it is very useful.

MyPaint version: MyPaint---20190204
Operating system: ArchLinux
Desktop environment: Xfce

**Comment by odysseywestra** [comment] 2019-12-11 17:47
@RyanHarvieStark Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get wider community feedback.

**Comment by odysseywestra** [comment] 2019-12-12 07:15
Duplicate of #269 Closing in favor of the older one.

**Closed by odysseywestra** 2019-12-12 07:15 UTC
Labels: enhancement
