### ISSUE TITLE
mypaint fails to detect tablet on fedora 22

### ISSUE THREAD

**Issue by GregS555** [mypaint/mypaint#388] opened 2015-07-31 20:46 UTC
I'm running mypaint 1.2.0-git  on Fedora 22 KDE spin.
My Wacom Intuos3 tablet is not detected by mypaint, i.e. I have no pressure support and it is not listed under settings->devices.
However, pressure support works in mypaint 1.1.0, krita and gimp.

**Comment by achadwick** [comment] 2015-07-31 21:48
Please can you paste the full version number from the about box? 1.2.0 has not been released, and that is not our version numbering scheme.

That configuration area shows all the devices known to GDK, so this sounds like an issue with GDK, not MyPaint. Just to rule out something lower-level though, can you paste the output of `xinput list`, and the relevant portions of `lsusb -v` if this is a USB device please? Treble backticks

    ```
    like this
    ```

will make it clearer to read.

(This issue tracker is, alas, not a user support forum for getting your tablet working, and MyPaint's tablet support is only ever going to be as good as your {kernel, X server, GDK} combination makes it (on the Linux platform). However if there's a bug to be resolved, I can point you in the direction of the right place to report it.)

**Comment by GregS555** [comment] 2015-07-31 23:16
The full version number is 1.2.0-beta.0.93+git.b8f0b62.dirty.
However, the problem has persisted for quite some time/git versions on my system.

Because the tablet works in Gimp and MyPaint 1.1.0, I attributed the bug to MyPaint 1.2.0-beta although I was not sure if they use different dependencies.
I'm sorry if this appears as an abuse of the issue tracker as a support forum.
It is not my intention to waste the time of any developer on issues that are restricted to my system.
If you could tell me the recommended GDK version, I will try to build it and report any potential regression upstream.


```xinput list``` returns:
```
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ HID 046a:0021                             id=9    [slave  pointer  (2)]
⎜   ↳ Wacom Intuos3 9x12 Pen stylus             id=10   [slave  pointer  (2)]
⎜   ↳ Wacom Intuos3 9x12 Pad pad                id=11   [slave  pointer  (2)]
⎜   ↳ Microsoft Microsoft 5-Button Mouse with IntelliEye(TM)    id=12   [slave  pointer  (2)]
⎜   ↳ Wacom Intuos3 9x12 Pen eraser             id=13   [slave  pointer  (2)]
⎜   ↳ Wacom Intuos3 9x12 Pen cursor             id=14   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Power Button                              id=7    [slave  keyboard (3)]
    ↳ HID 046a:0021                             id=8    [slave  keyboard (3)]
```

```lsusb -v``` says:
```
Bus 005 Device 002: ID 056a:00b2 Wacom Co., Ltd Intuos3 9x12
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x056a Wacom Co., Ltd
  idProduct          0x00b2 Intuos3 9x12
  bcdDevice            1.02
  iManufacturer           1 Tablet
  iProduct                2 PTZ-930
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              300mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     170
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval               4
Device Status:     0x0000
  (Bus Powered)
```

**Comment by achadwick** [comment] 2015-07-31 23:39
Thanks - and don't worry about it. Plain support requests can sometimes evolve to identify bugs in a useful way, so not a waste of time :grinning: 

The GTK version we recommend is anything after (GTK) 3.10, so that's unlikely to be an issue on Fedora 22. My Debian box's 3.16.5 is working fine, if that's a hint.

Can you confirm that you're seeing an axis that reflects pressure in the output of `Wacom Intuos3 9x12 Pen stylus` as well? No need to paste the output :)

That leaves GIR and Python integration. Can you give https://gist.github.com/achadwick/54e5b111e5ac908becf1 a spin too, and let me know whether or or not it plots out traces corresponding to your pressure? If it *does* then this is more probably MyPaint bug!

**Comment by GregS555** [comment] 2015-08-01 14:03
Do you mean the output of ```xinput test <device>``` ?
That gives me a pressure axis that responds to pen pressure.
The pressure axis in ```axischart.py``` remains a flat line.
The GTK version on my system is 3.16.6, Python is 2.7.10.
I'm afraid I don't know what GIR is and can't find a fedora package with that acronym?

**Comment by achadwick** [comment] 2015-08-01 14:44
Yes, sorry. Corrected: `xinput test "Wacom Intuos3 9x12 Pen stylus"` (as you figured out).

GIR = the XML glue format that exposes GObject Introspection bindings to languages like Python. <https://wiki.gnome.org/Projects/GObjectIntrospection>. Debian put all the glue in separate packages with a string like `gir1.2-` on the front, and I assumed Fedora would be doing the same. Guess not :open_mouth: 
Don't worry about it. If these weren't available, you wouldn't be able to run programs like axischart.py or MyPaint. The functions can sometimes be improperly tagged in this language, but that tends to throw exceptions for missing args or broken type conversions rather than just subtly eat data.

Python and GTK versions look fine. X11 is reporting the right sorts of devices. Basically your installation looks sound.

My £0.02 - it's a GDK regression between 2.x and 3.16. The events are not being filled in properly in the C code, so they're not coming through to Python - perhaps the tablet stylus is not being detected as a pen? axischart.py should emit lines like

```
INFO:Axischart:New device class='gtk.gdk.X11DeviceXI2' name='Wacom Intuos5 touch M Pen stylus' (src='pen')
INFO:Axischart:New device class='gtk.gdk.X11DeviceXI2' name='Wacom Intuos5 touch M Pen eraser' (src='eraser')
INFO:Axischart:New device class='gtk.gdk.X11DeviceXI2' name='Wacom Intuos5 touch M Finger' (src='touchpad')
INFO:Axischart:New device class='gtk.gdk.X11DeviceXI2' name='Wacom Intuos5 touch M Pad pad' (src='pen')
```

when it first sees events from a device it hasn't seen before. Does it even show that (guessing not, given MyPaint doesn't list them out)?

Your next port of call is the [GTK/GDK bugzilla](https://bugzilla.gnome.org/), I'm afraid. If you find or raise a bug there, please drop a link here so that people can find it. It's worth chasing the devs on IRC about it too: [#gtk+ on irc.gnome.org](irc://irc.gnome.org/%23gtk%2B). I can't help further because I don't own the hardware in question.

#29 and #178 here are examples of ones we've successfully chased upstream before. I'm going to close this one and leave it tagged as "upstream", but feel free to use this issue as a dumping ground for images if you need.

**Closed by achadwick** 2015-08-01 14:44 UTC
Labels: needs-info, upstream

**Comment by gwojcik** [comment] 2017-07-21 22:10
This problem is still present in current fedora 26.

It is caused by environment variable GDK_CORE_DEVICE_EVENTS. If it is set then core device manager is created instead of xi2 device manager. In source: [gdkdevicemanager-x11.c](https://git.gnome.org/browse/gtk+/tree/gdk/x11/gdkdevicemanager-x11.c#n37).

In Fedora GDK_CORE_DEVICE_EVENTS is enabled as workaround for scrolling and focus problems in gtk apps running in kde, details in redhat bugzilla [bug 1226465](https://bugzilla.redhat.com/show_bug.cgi?id=1226465#c20).
Variable is set in `/etc/xdg/plasma-workspace/env/gtk3_scrolling.sh`

To fix mypaint detection of tablets do: `unset GDK_CORE_DEVICE_EVENTS`
