### ISSUE TITLE
Help→About MyPaint: license tab: incorrectly escaped text in locale using Cyrillic on Windows

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#638] opened 2016-04-05 14:30 UTC
Help - About Mypaint - License
![1](https://cloud.githubusercontent.com/assets/13454470/14285414/d76933da-fb64-11e5-9e91-daaad2bf2140.jpg)

**Comment by achadwick** [comment] 2016-04-05 14:58
Hi there - thanks for the report!

Is this using the same computed locale as https://github.com/mypaint/mypaint/issues/636#issuecomment-205723126 ?

**Comment by achadwick** [comment] 2016-04-05 15:01
Affects 1.2.1 beta 0 64 - Windows 10 64.

Do you see the program version at all in that dialog? It may be on the first "tab", i.e. button.

**Comment by zb13y** [comment] 2016-04-05 15:08
1.2.1-beta.0+gitexport.3fd40c8

(Python 2.7.11, GTK 3.20.1, GdkPixbuf 2.34.0, Cairo 1.15.2, GLib 2.48.0)

**Comment by achadwick** [comment] 2016-04-05 15:09
Thanks!

It's not related to fonts. It's accidental XML escaping, so I retitled.

Escaping was added for the license strings in 7673c36be65a911d7fe77a125d0cb2211056de42, prior to 1.2.1-beta.0. So... my fault? Except that the Linux about dialog seems to require escaping.

Cannot reproduce in GNOME 3.18ish under Debian testing/unstable in 4f07003 using `LANGUAGE=ru_RU.CP1251`. But the about box has a very different look on that platform:

![about box image](https://cloud.githubusercontent.com/assets/61299/14286768/24b974f0-fb48-11e5-919d-a913f01d5989.png)

**Comment by zb13y** [comment] 2016-04-05 15:11
> Is this using the same computed locale as #636 (comment) ?
Yes.

**Comment by achadwick** [comment] 2016-04-05 15:46
Whoops, my mistake. Wrong tab, silly me :stuck_out_tongue_winking_eye:

The license text is incorrectly escaped on my system too:

![image](https://cloud.githubusercontent.com/assets/61299/14287503/cb8f6bf2-fb4a-11e5-91f5-c690c4bc1c26.png)

**Comment by achadwick** [comment] 2016-04-06 01:20
Looks OK in my testing. Fix is in on master (for 1.3.0), and will be present in 1.2.1 or its next beta.

**Closed by achadwick** 2016-04-06 01:20 UTC
Labels: bug, translation, windows
