### ISSUE TITLE
Sidebar panels (docked subwindows) don't remember their sizes after resizing the main window

### ISSUE THREAD

**Issue by Griatch** [mypaint/mypaint#298] opened 2015-04-21 12:49 UTC
1. Have a brush list (maybe other docks, haven't tested) open in a toolbar and extend it vertially as desired.
2. Minimize MyPaint, then maximize it back up again
3. The brush list is now shrunk back to its smallest possible vertical size. One has to re-size it manually. 

It feels more reasonable that dock proportions should be retained across minimization. 

Tested with latest MyPaint GIT version on Linux Mint (KDE).

**Comment by achadwick** [comment] 2015-04-21 13:28
Specific MyPaint version and OS version please?

Good suggestion though. Bugs me too.

**Comment by achadwick** [comment] 2015-04-21 13:29
Likely to not have string changes. Beta cycle, maybe.

**Comment by Griatch** [comment] 2015-04-21 13:54
Specific OS version is Linux Mint 17 with KDE desktop.

**Comment by achadwick** [comment] 2015-04-21 16:39
I think I may be misinterpreting this report and thinking of something else.

* When you say a "toolbar", do you mean a floating window, or a docked sidebar?
* When you say "minimize", what do you mean? Which button or menu item are you selecting?
* What specific version of MyPaint is this? Please look in the about box and report the string there.

I cannot reproduce this one with git master at 0b3067fcb29312135aa14d8e90076611cc2b3f01 (Tue Apr 21), in GNOME 3.14, trying "Minimize" on the main window from the menu (yay, GNOME doesn't have a minimize button)

![sshot](https://cloud.githubusercontent.com/assets/61299/7257381/2fb4d3f4-e84d-11e4-83f6-5fbad7958f12.png)

Also:

* Is this a very recent change? I need to know whether it works with the previous commit, c0c088b7391ecb9c70c1d21ab4d81b3bd0b0884d, then fails with 0b3067fcb29312135aa14d8e90076611cc2b3f01 because window management changed with that commit.

**Comment by achadwick** [comment] 2015-04-22 01:17
Cannot reproduce in Linux Mint KDE 17.1 LTS as described in the original report, under a virtualbox VM and with all the default Linux Mint KDE Edition stuff. Here's what I did:

1. Opened one brush list in the sidebar, and one in a floating window, a bit like the GNOME screenshot above.
2. Resized both brush list windows down a bit, to show all brushes
3. Clicked on the main window's minimize button:
    * ![kwin minimize button](https://cloud.githubusercontent.com/assets/61299/7265604/2140d42a-e894-11e4-8faa-74ad737b9561.png)
    * Application is minimized to the panel
4. Clicked on the button for the window in the panel
   * main window is restored
   * both brush lists have my chosen size still
5. Clicked on Maximize (next to kwin's Minimize button)
   * main window now fills the screen
   * both brush lists have my chosen size still

--------------------------------------

@Griatch , since I clearly don't have the information I need to reproduce this yet:

* **Do you perhaps mean something other than "minimize"?** "Minimize" to me means what the button in the picture does to the window.
* **Please provide exact steps to reproduce the issue**. Be as verbose as you possibly can be.

**Comment by Griatch** [comment] 2015-04-22 11:10
You are correct, "minimize" is not the right term, sorry about that. Just simply resizing is enough.

Here is the process:

1. Start size of window. Note the vertical height of the docked brush list. 
![mypaint_resize1](https://cloud.githubusercontent.com/assets/294267/7272966/6db58fa2-e8ef-11e4-887f-4f3529d3b429.png)
2. Resize the image (the reason I originally called this minimize is that I double-click the window main title which in my KDE setup causes the application to switch between filling the entire screen and a smaller, movable window. But it's not fully minimized, just shrunk. Manually resizing has the same effect though):
![mypaint_resize2](https://cloud.githubusercontent.com/assets/294267/7273037/1986abea-e8f0-11e4-8223-28904e2007f6.png)
3. Next resize the application back up again. For me the brush list is now smaller than it was, it shrunk as much as it could along with the resizing of the window and I have to manually resize it back up again to make use of the larger screen estate:
![mypaint_resize3](https://cloud.githubusercontent.com/assets/294267/7273071/5f7c454c-e8f0-11e4-9e51-a032b8fbcca6.png)

Quickly resizing the application for some reason (such as when briefly wanting to see some other image on the same screen) will thus require a manual adjustment of the brush list every time.

**Comment by achadwick** [comment] 2015-04-27 11:53
Just updating here. Thanks for the clear explanation - it is what I thought is was after all, and it's a pain when fullscreening/unfullscreening too.

**Comment by achadwick** [comment] 2015-08-27 21:55
Okay, I've had a look at the workspace code, and this is caused by the way we do the sidebar stacks: we use a nested structure of `GtkPaned`s. There's no real way around this, unfortunately: when you put the root paned of such a structure inside a `GtkScrolledWindow` and then resize the scrolledwindow's parent smaller, it forces the content to shrink before giving you the scrollbar.

(Okay, we might be able to do something to make adjusting a divider change the minimal size of the dockpanel tab-set above it, either with the new sizing system or with gtk_widget_set_size_request() like the old UI. But that's going to require a re-coding of the stacks. Maybe we should just go with GDL <https://github.com/GNOME/gdl> instead?)

**TRIAGE:** acknowledged, and it should be fixed. However to do so is going to need more work than we really have time for before the 1.2.0 release. Deferring.

**Closed** 2016-04-15 18:48 UTC
Labels: enhancement, ux
