### ISSUE TITLE
Error when saving file

### ISSUE THREAD

**Issue by crispysnore** [mypaint/mypaint#277] opened 2015-03-29 01:02 UTC
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 449, save_as_cb(self=<gui.filehandling.FileHandler object>, action=<gtk.Action object at 0x3f97f78 (GtkAction at 0x4a7870)>)
                # Do not change working file
                self.save_as_dialog(self.save_file, suggested_filename = current_filename, export=True)
            else:
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 509, save_as_dialog(self=<gui.filehandling.FileHandler object>, save_method_reference=<bound method FileHandler.wrapper of <gui.filehandling.FileHandler object>>, suggested_filename='', start_in_folder=None, export=True, **options={})
                            # Do not change working file
                            save_method_reference(filename, True, **options)
                        else:
  File "C:\Program Files\MyPaint\library.zip\gui\drawwindow.py", line 46, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'C:\\Users\\loc\\Desktop\\Drawing and concepts\\tonkii insect ripoff.ora', True), **kwargs={})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 292, save_file(self=<gui.filehandling.FileHandler object>, filename=u'C:\\Users\\loc\\Desktop\\Drawing and concepts\\tonkii insect ripoff.ora', export=True, **options={})
                thumbnail_pixbuf = self.doc.model.render_thumbnail()
            helpers.freedesktop_thumbnail(self.filename, thumbnail_pixbuf)
  File "C:\Program Files\MyPaint\library.zip\lib\helpers.py", line 152, freedesktop_thumbnail(filename=None, pixbuf=<gtk.gdk.Pixbuf object at 0x30325a0 (GdkPixbuf at 0x9105420)>)
        file_mtime = str(int(os.stat(filename).st_mtime))
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by achadwick** [comment] 2015-03-29 09:50
Duplicate of #125.

**Closed by achadwick** 2015-03-29 09:50 UTC
