### ISSUE TITLE
Mouse becomes unresponsive after switching windows (Windows)

### ISSUE THREAD

**Issue by fullmontis** [mypaint/mypaint#261] opened 2015-03-18 16:55 UTC
I am using build 1.1.1a for GTK 3.14.9 on Windows 7 64bit from http://opensourcepack.blogspot.it/search/label/mypaint.

To reproduce the bug, switch to another window using a tablet ( I have a Wacom Intuos). Then come back to the window by using the mouse. Now I can't access any menu with the mouse. It becomes unresponsive. 

If I move the cursor with the tablet, then the mouse becomes useable again and I can access the menus.

**Comment by tumagonx** [comment] 2015-03-18 17:23
I use UC-Logic and can't reproduce this. Anyone with Wacom could confirm this?

**Comment by achadwick** [comment] 2015-03-18 17:54
@fullmontis Please can you provide some more information for us?

1. Could you give us the exact model code off the back of the tablet, and its marketing name (like "Intuos 3", "Intuos 5") please?
2. What version of the Wacom driver is this? You are using the official Wacom drivers, right?
3. Please tell us the real version number of the MyPaint build you're using as well. It's in the usual Help→About dialog.
4. When you switched to a window, is it one of MyPaint's windows, or something belonging to the operating system (like the panel or the desktop), or another app's window (like Windows Explorer or your web browser)?
5. Does this happen every time, or just some of the time?
6. Is GIMP affected by this?

**Comment by fullmontis** [comment] 2015-03-18 21:19
1. Wacom Intuos Pen&Touch Small CTH-480
2. Driver version 6.3.6b5. Official, yes.
3. MyPaint Version 1.1.1-alpha.20150307+git.6b3a1e7
4. Another app, I tried with the desktop, or another mypaint window. Same problem.
5. Tried about 7 times, happened every time
6. No

**Comment by achadwick** [comment] 2015-03-23 10:54
Flagging as something I at least need to take a look at before the 1.2 release. Sorry for the lack of response so far.

**Comment by achadwick** [comment] 2015-04-20 22:26
Confirmed with driver version 6.3.11w3, Intuos 5 touch Medium PTH-650, Win7-64bit, MSYS2's MinGW32 environment, but there's not a great deal we can do about it. It appears to affect all GTK3 apps I've tried, including trivial stuff like:

```python
#!python2

from gi.repository import Gtk, Gio

class HeaderBarWindow(Gtk.Window):
    def __init__(self):
        Gtk.Window.__init__(self, title="Stack Demo")
        self.set_border_width(10)
        self.set_default_size(500, 400)
        hb = Gtk.HeaderBar()
        hb.set_show_close_button(True)
        hb.props.title = "HeaderBar example"
        self.set_titlebar(hb)
        button = Gtk.Button()
        icon = Gio.ThemedIcon(name="mail-send-receive-symbolic")
        image = Gtk.Image.new_from_gicon(icon, Gtk.IconSize.BUTTON)
        button.add(image)
        hb.pack_end(button)
        box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        Gtk.StyleContext.add_class(box.get_style_context(), "linked")
        button = Gtk.Button()
        button.add(Gtk.Arrow(Gtk.ArrowType.LEFT, Gtk.ShadowType.NONE))
        box.add(button)
        button = Gtk.Button()
        button.add(Gtk.Arrow(Gtk.ArrowType.RIGHT, Gtk.ShadowType.NONE))
        box.add(button)
        hb.pack_start(box)
        self.add(Gtk.TextView())

win = HeaderBarWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```

Symptoms are that once window focus is transferred back to the GTK3 program using the mouse, interaction with any widget using the mouse is impossible. It is not limited to just menus. In MyPaint that means you can't draw with the mouse after doing this. For the test app above, you can't reposition the text cursor using the mouse, or click the widgets in the header bar, and the mouse cursor has a fixed shape.

Linux seems OK. Only Windows seems to be affected.

Workaround is to use the Intuos's stylus to interact with the GTK3 programs' window briefly. Then you can pick up the mouse and interact with the window normally using it.

This is not a MyPaint issue: please report it upstream via the GNOME bugzilla: https://bugzilla.gnome.org/ - product gtk+, Component: Backend: Win32.

**Closed by achadwick** 2015-04-20 22:26 UTC
Labels: upstream, windows
