### ISSUE TITLE
Program crashes when trying to set canvas size

### ISSUE THREAD

**Issue by DaydreamBunnii** [mypaint/mypaint#1082] opened 2020-05-25 19:47 UTC
#### Description of the problem

When trying to set canvas size the program crashes.
Cannot set canvas size and popup doesn't go away unless you restart MyPaint.

#### Basic system details

MyPaint version: MyPaint version 2.0.0+gitexport.af5225a
Operating system: Ubuntu 20.04
Desktop environment: GNOME

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. Click on "edit frame" button on toolbar
3. Crash dialogue appears

#### Backtraces or error messages

```python
Mypaint version: 2.0.0+gitexport.af5225a
System information: Linux-5.4.0-29-generic-x86_64-with-glibc2.29
Using: Python 3.8.2, GTK 3.24.18, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.64.1
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/document.py", line 2198, mode_radioaction_changed_cb(self=<gui.document.Document object>, action=<Gtk.RadioAction object at 0x7fb16a2707c0 (GtkRadioAction at 0x7fb154003d50)>, current_action=<Gtk.RadioAction object at 0x7fb16a270980 (GtkRadioAction at 0x3493c80)>)
                    mode = mode_class()
                self.modes.context_push(mode)
  variables: {'self.modes.context_push': ('local', <bound method ModeStack.context_push of <ModeStack [FreehandMode, FrameEditMode]>>), 'mode': ('local', <gui.framewindow.FrameEditMode object at 0x7fb15b889400>)}
  File "/usr/lib/mypaint/gui/mode.py", line 1369, context_push(self=<ModeStack [FreehandMode, FrameEditMode]>, mode=<gui.framewindow.FrameEditMode object>)
            self._stack.append(mode)
            mode.enter(doc=self._doc)
            self.changed(old=old_mode, new=mode)
  variables: {'mode.enter': ('local', <bound method FrameEditMode.enter of <gui.framewindow.FrameEditMode object at 0x7fb15b889400>>), 'doc': (None, []), 'self._doc': ('local', <gui.document.Document object at 0x7fb16a2cc850>)}
  File "/usr/lib/mypaint/gui/framewindow.py", line 116, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
            """Enter the mode"""
            super(FrameEditMode, self).enter(doc, **kwds)
            # Assign cursors
  variables: {'super': ('builtin', <class 'super'>), 'FrameEditMode': ('global', <class 'gui.framewindow.FrameEditMode'>), 'self': ('local', <gui.framewindow.FrameEditMode object at 0x7fb15b889400>), 'enter': (None, []), 'doc': ('local', <gui.document.Document object at 0x7fb16a2cc850>), 'kwds': ('local', {})}
  File "/usr/lib/mypaint/gui/mode.py", line 442, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
            self.__reset_delta_totals()
            return super(ScrollableModeMixin, self).enter(doc, **kwds)
  variables: {'super': ('builtin', <class 'super'>), 'ScrollableModeMixin': ('global', <class 'gui.mode.ScrollableModeMixin'>), 'self': ('local', <gui.framewindow.FrameEditMode object at 0x7fb15b889400>), 'enter': (None, []), 'doc': ('local', <gui.document.Document object at 0x7fb16a2cc850>), 'kwds': ('local', {})}
  File "/usr/lib/mypaint/gui/mode.py", line 1108, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
                try:
                    self.inactive_cursor = self.doc.app.cursors. \
                            get_action_cursor(self.ACTION_NAME,
  variables: {'self.inactive_cursor': ('local', <gui.framewindow.FrameEditMode object at 0x7fb15b889400>), 'self.doc.app.cursors.get_action_cursor': ('local', <bound method CustomCursorMaker.get_action_cursor of <gui.cursor.CustomCursorMaker object at 0x7fb16304d820>>), 'self.ACTION_NAME': ('local', 'FrameEditMode'), 'gui.cursor.Name.ARROW': ('global', 'cursor_arrow')}
  File "/usr/lib/mypaint/gui/cursor.py", line 331, get_action_cursor(self=<gui.cursor.CustomCursorMaker object>, action_name='FrameEditMode', cursor_name='cursor_arrow')
                return Gdk.Cursor.new(Gdk.CursorType.ARROW)
            return self.get_icon_cursor(icon_name, cursor_name)
  variables: {'self.get_icon_cursor': ('local', <bound method CustomCursorMaker.get_icon_cursor of <gui.cursor.CustomCursorMaker object at 0x7fb16304d820>>), 'icon_name': ('local', 'mypaint-frame-symbolic'), 'cursor_name': ('local', 'cursor_arrow')}
  File "/usr/lib/mypaint/gui/cursor.py", line 351, get_icon_cursor(self=<gui.cursor.CustomCursorMaker object>, icon_name='mypaint-frame-symbolic', cursor_name='cursor_arrow')
                if "symbolic" in icon_name:
                    icon_pixbuf = gui.drawutils.load_symbolic_icon(
                        icon_name, 18,
  variables: {'icon_pixbuf': (None, []), 'gui.drawutils.load_symbolic_icon': ('global', <function load_symbolic_icon at 0x7fb16b00fee0>), 'icon_name': ('local', 'mypaint-frame-symbolic'), 'fg': (None, []), 'outline': (None, [])}
  File "/usr/lib/mypaint/gui/drawutils.py", line 300, load_symbolic_icon(icon_name='mypaint-frame-symbolic', size=16, fg=(1, 1, 1, 1), success=None, warning=None, error=None, outline=(0, 0, 0, 1))
        icon_pixbuf, was_symbolic = info.load_symbolic(
            fg=rgba_or_none(fg),
  variables: {'icon_pixbuf': (None, []), 'was_symbolic': (None, []), 'info.load_symbolic': ('local', gi.FunctionInfo(load_symbolic)), 'fg': ('local', (1, 1, 1, 1)), 'rgba_or_none': ('local', <function load_symbolic_icon.<locals>.rgba_or_none at 0x7fb15b8c3700>), 'success_color': (None, []), 'success': ('local', None), 'warning_color': (None, []), 'warning': ('local', None), 'error_color': (None, []), 'error': ('local', None)}
Error: rsvg-error-quark: XML parse error: error code=201 (3) in (null):26:121: Namespace prefix xlink for href on use is not defined
 (0)
```

**Comment by jplloyd** [comment] 2020-05-25 19:56
Hi, thanks for reporting!

This is a duplicate of #1064 and has been fixed in the master and the 2.0.1 bugfix release that will be released on friday unless there are any showstoppers.

A workaround for this issue was posted here: https://github.com/mypaint/mypaint/issues/1064#issuecomment-632988335

You could also use an appimage from the [2.0.1 prerelease](https://github.com/mypaint/mypaint/releases/tag/v2.0.1-rc.0).

**Closed by jplloyd** 2020-05-25 19:56 UTC
