### ISSUE TITLE
Broken auto-center of the drawing in fullscreen when loading

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#869] opened 2017-10-23 15:22 UTC
#### Description of the problem

Broken auto-center of the drawing in fullscreen.

#### Basic system details

MyPaint version: [1.2.1+gitexport.bcf5a28d (Stable) and last alpha 1.3.0 from AppVeyor]
Operating system: [Windows 10x64 1703 15063.674]

#### Steps to reproduce

1. Start MyPaint
2. Open fullscreen
3. Hide interface
4. Draw some lines near angles* (to know that picture have moved)
    Picture must be drawn in all space of the fullscreen canvas (4 lines near angles)
5. Save work
6. Load it
7. Picture center moved (mostly to left 10% of picture)

Also if it possible, it will be good to auto-center by frame.

**Comment by achadwick** [comment] 2017-10-24 11:49
Hi there. Thanks for the report! It's good to know about this one.

Faster steps to reproduce that can be done with `python setup.py demo`:

1. Up to step 5 as above.
2. Press F5 :smile: 

Looks fine to me, if you use a frame.  May be a pixel or two out.

If no frame is used, MyPaint saves an image with a top-left (x=0, y=0) based on the tiles used by all layers. So you get an apparent offset of up to 64 pixels, which is the tile size.

@zb13y
Does that adequately describe the problem you're seeing?  This may become more important if we increase the tile size: there are some performance benefits to doing that.

This may be a WONTFIX again, because I'm quite loath to make the screen edge determine the image size in the absence of a frame. But, convince me otherwise. IMO, making this work for save would create a disparity between saving PNG and saving OpenRaster, because PNG people won't expect to lose data. So we would only be using the trick for .ora.

**Comment by achadwick** [comment] 2017-10-24 11:54
Faster still (and to prove that it's not just saving, that's kind of a red herring :fish:)

1. `python setup.py demo`
2. Press <kbd>F11</kbd> to fullscreen MyPaint, and wait a second or two for the interface to hide.
3. Carefully draw near the edges.
4. Watch the top-left one, and press <kbd>F12</kbd> to re-centre the document.
5. Centre moves a bit, unless you're doubly lucky.

Should be no more than 64 pixels though. 10% (of a screen that could be abny width) sounds a bit too much (your screen is bigger than 640 px wide, right?)

**Comment by zb13y** [comment] 2017-10-24 12:34
Hm, i have different problem. Problem is with fullscreen center and window center.

1. Go to fullscreen with interface on, load work.
2. Hide interface
3. Drawing moved by 10% (it's not moved, just centered with interface)

Seems this can be closed, user can center work with f12.

**Comment by achadwick** [comment] 2017-10-24 14:06
I see - you expected a previous centering to still have an effect?

My goal has always been for the canvas to stay where it is on the -screen- when the interface hides and shows. It's irritating otherwise, if you bang on F12 a lot or get into the groove with the autohide feature.

/makes note to redo the workspace layout module with `GtkOverlay`, which didn't exist back when I wrote it...

**Closed by achadwick** 2017-10-24 14:06 UTC
Labels: works-for-me
