### ISSUE TITLE
Do Ugee tablets not work with Mypaint anymore

### ISSUE THREAD

**Issue by Carball-tunnel** [mypaint/mypaint#621] opened 2016-03-12 15:15 UTC
I'm currently using the Ugee M1000L and I'm having trouble using the MyPaint on it, it works fine with other software like Krita and the Old MyPaint 
![proof](https://cloud.githubusercontent.com/assets/17799814/13723719/d8fdb8be-e832-11e5-8462-83dcbf3d7c55.JPG)
I looked up other individual's similar problem and can't find a solution to the problem?

**Comment by achadwick** [comment] 2016-03-12 16:39
@Carball-tunnel 
Thank you for reporting this issue. we may not be able to help you without more information from a lot of people.

You can refer to this issue in those threads by writing `#621` in your comment texts. This glitch does look a bit familiar, but since I don't understand your problem yet, I can't say whether or not this is a duplicate.

(I can't answer your question because I don't have the hardware in question. Sorry. I just can't test it. We support Ugee tablets *only if* GDK supports it. MyPaint uses libgdk from the GTK/GNOME project for its tablet input gathering.)

There's not quite enough information in your original report to move this issue forward.
Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs).
We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code.
I won't close this report straight away though because sometimes we can help, often the feedback is useful anyway, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you quickly here, but don't be discouraged if we can't.
You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/), from Twitter ([@MyPaintApp](https://twitter.com/MyPaintApp), #mypaint), on IRC ([#mypaint on freenode](irc://freenode/mypaint)), or on the [MyPaint mailing list](https://mail.gna.org/listinfo/mypaint-discuss).

**Comment by achadwick** [comment] 2016-03-12 16:41
(Probably upstream, i.e. GDK. Don't forget to [search the GNOME bugzilla](https://bugzilla.gnome.org/buglist.cgi?quicksearch=ugee) too!)

**Comment by avengabaco** [comment] 2016-04-11 14:22
Also having this issue with Mypaint when I tried it with my Ugee 1910B.

The pointer is perfectly under the pen tip yet strokes are drawn four inches to the left. 
This also happens in 'Autodesk Sketch book' but not other software that I have tried if that helps.

![my paint](https://cloud.githubusercontent.com/assets/18399689/14430354/2733bef6-fff9-11e5-9209-c3c83fb315f6.jpg)

**Comment by achadwick** [comment] 2016-04-11 17:12
@Carball-tunnel
Please try the suggested workaround from @avengabaco. Any change?

**Comment by achadwick** [comment] 2016-04-11 17:12
**TRIAGE NOTE:** looks like a user support request. This is the wrong forum for direct user support, reporter has been redirected to better places to ask. This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status.

**Comment by achadwick** [comment] 2016-04-11 17:15
(... a user support request AND an upstream glitch-causing bug. The glitch should definitely be reported on the [upstream bug tracker](https://bugzilla.gnome.org/buglist.cgi?quicksearch=ugee) against component "gtk+".)

It would be useful to know whether this can be reproduced under Linux. For now I will treat is as a Windows-specific issue too.)

**Closed** 2016-05-07 14:18 UTC
Labels: glitch, needs-info, upstream, user-support, windows
