### ISSUE TITLE
Backup recovery prompt does not show up on startup if started by opening a file

### ISSUE THREAD

**Issue by nekohayo** [mypaint/mypaint#505] opened 2015-11-24 17:08 UTC
If Mypaint crashed/hung/etc. last time I used it, it will only offer me the recovery option if I start mypaint "standalone" instead of launching it by double-clicking the file I was working on (in the file manager). Probably not intentional?

**Comment by achadwick** [comment] 2015-11-24 17:22
This is actually working as intended - MyPaint tries to do what you told it.

* The recovery data is kept when MyPaint is started with a file.
* If you started with a file, you can still run “File → Recover File from an Automated Backup…” from the menu.
  * This is actually a bit more flexible than the startup-time recovery tool - if you have no backup data, MyPaint will offer you the ability to go and inspect the Cache folder where stuff is kept.

**Comment by achadwick** [comment] 2015-11-24 17:56
Closing, since it's mostly working like it should for the 1.2.0 release. We can revisit the design of the dialogs 

(Except for one straight-up bug, which I've reported as #508 ☺)

**Closed by achadwick** 2015-11-24 17:56 UTC
Labels: works-for-me

**Comment by nekohayo** [comment] 2015-11-24 18:10
Hmm I understand it works as intended from an engineering* hat on, but do your** users typically/majoritarily launch the app from the launcher, vs from the file browser? I don't see much harm in saying "Hey, you tried loading this file, but we actually have a backup that is newer. Do you want that instead?"… Unless people have actually complained and requested that to be a manual action from the File menu, that is.

*: speaking as someone who implemented such a system in Pitivi, and saw plenty of "wrong" systems (like OpenOffice/LibreOffice!) that offer backups that are older than the file's last modification time.

**: I realize I might be a bit unusual in terms of userbase representativity ;)

**Comment by achadwick** [comment] 2015-11-24 18:16
Yeah, `*` above is one of the _bad_ autorecovery styles I was trying to avoid when I made that dialog!

Autobackups in MyPaint at present don't have a file path associated with them, and we try to force the user to save the cache data somewhere sensible right away. But as I think you're saying, there's a workflow path where 1) the user clicks on a .ora file to edit, 2) mypaint opens, then Bad Things happen, 3) user tries to autorecover by redoing 1. and gets confused about why there's apparently no autosave data.

Right now (for the 1.2.0 release), I'm mostly just silly-pleased we can save big PNGs in little strips while the user's still working, and tat the result is mostly robust :smile: Totally happy to revisit the workflow after the release, especially the "Discard" button.
