### ISSUE TITLE
MyPaint crashes after opening/moving a brush group as a subwindow

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#198] opened 2015-02-11 12:57 UTC
Windows 8.1 64-bit, MyPaint 1.1 (Latest build from tumagonx's website)
opensourcepack.blogspot.com/2013/01/mypaint-and-pygi.html
Using a Monoprice 4x3" Tablet with latest drivers.

-Went to the Brush Submenu and opened a brush group (Set 4)
-Moved the Set 4 subwindow and then tried to resize it.
-The subwindow stopped responding and then crashed the program.

-Reopened MyPaint and opened a different brush group (Set 1)
-Dragged the Brush group from the side panel
-MyPaint Crashes

**Comment by tumagonx** [comment] 2015-02-11 13:12
If I understand correctly the second case maybe a dupe of https://github.com/mypaint/mypaint/issues/194 and the both may related

**Comment by achadwick** [comment] 2015-02-11 13:17
@AtsusaKaneytza is this 1.1.1-alpha (real version is visible in the About dialog)?

Seeing the output when this is run from the command line would confirm it, but this does appear to be a duplicate. Does it happen no matter what tab you drag out?

**Comment by tumagonx** [comment] 2015-02-11 13:30
I will upload the new debug version then, takes time cause it will be big upload.

but at the moment you can rename python\mypaint.exe to something else then rename python\python.exe to python\mypaint.exe to see console

**Comment by tumagonx** [comment] 2015-02-11 15:30
Try http://iweb.dl.sourceforge.net/project/tumagcc/mypaint-1.1.1a-debug_win32.7z
use run_inside_debugger or run_in_console

**Comment by AtsusaKaneytza** [comment] 2015-02-11 17:13
@achadwick yeah, it appears to be the case. Sorry about the duplicate report

**Comment by achadwick** [comment] 2015-02-11 18:58
(Closed as duplicate of #194)

**Closed** 2015-02-11 18:57 UTC
Labels: duplicate, windows
