### ISSUE TITLE
Error report when Save As, then Quit, then restart

### ISSUE THREAD

**Issue by bunk3m** [mypaint/mypaint#202] opened 2015-02-12 20:27 UTC
Hi again.
I'm running version 1.1.1.alpha.20141216+git.68f876fc
Today when I used MyPaint again, I started getting errors.  I haven't updated anything since I did a fresh install a few months back.  This is probably the first time I've used MyPaint since then.
It started when I opened a jpg and then tried to save it as another name.  This operation failed.  Then there was a problem when I tried to Quit.  And again when I restarted.  I've included each of the error report below.
I changed the direct file location to /Users/userid/Desktop to ~/Desktop

Here is the "Save As" error report:
```
Mypaint version: 1.1.1-alpha
System information: Darwin-13.4.0-x86_64-64bit
Traceback (most recent call last):
  File "/opt/local/share/mypaint/gui/filehandling.py", line 507, save_as_cb(self=<gui.filehandling.FileHandler object>, action=<Action object at 0x10ea73aa0 (GtkAction at 0x7ff0cb3165d0)>)
            else:
                self.save_as_dialog(self.save_file, suggested_filename=current_filename)
  variables: {'suggested_filename': (None, []), 'self.save_file': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x10ebc1150>>), 'self.save_as_dialog': ('local', <bound method FileHandler.save_as_dialog of <gui.filehandling.FileHandler object at 0x10ebc1150>>), 'current_filename': ('local', u'~/Desktop/201412 Server Migration/201412 Network Layout_01.jpg')}
  File "/opt/local/share/mypaint/gui/filehandling.py", line 565, save_as_dialog(self=<gui.filehandling.FileHandler object>, save_method_reference=<bound method FileHandler.save_file of <gui.filehandling.FileHandler object>>, suggested_filename=u'~/Desktop/201412 Server Migration/201412 Network Layout_01.jpg', start_in_folder=None, export=False, **options={'quality': 90})
                        else:
                            save_method_reference(filename, **options)
                        break
  variables: {'options': ('local', {'quality': 90}), 'save_method_reference': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x10ebc1150>>), 'filename': ('local', u'~/Desktop/201412 Server Migration/201502 Network Layout_01.jpg')}
  File "/opt/local/share/mypaint/gui/drawwindow.py", line 79, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'~/Desktop/201412 Server Migration/201502 Network Layout_01.jpg',), **kwargs={'quality': 90})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'self': ('local', <gui.filehandling.FileHandler object at 0x10ebc1150>), 'args': ('local', (u'~/Desktop/201412 Server Migration/201502 Network Layout_01.jpg',)), 'func': ('local', <function save_file at 0x10ecd8500>), 'kwargs': ('local', {'quality': 90})}
  File "/opt/local/share/mypaint/gui/filehandling.py", line 317, save_file(self=<gui.filehandling.FileHandler object>, filename=u'~/Desktop/201412 Server Migration/201502 Network Layout_01.jpg', export=False, **options={'quality': 90})
                export=export,
                **options
                )
  variables: {'options': ('local', {'quality': 90})}
  File "/opt/local/share/mypaint/gui/filehandling.py", line 370, save_doc_to_file(self=<gui.filehandling.FileHandler object>, filename=u'~/Desktop/201412 Server Migration/201502 Network Layout_01.jpg', doc=<gui.document.Document object>, export=False, **options={'quality': 90})
                    feedback_cb=self.gtk_main_tick,
                    **options
                )
  variables: {'options': ('local', {'quality': 90})}
  File "/opt/local/share/mypaint/lib/document.py", line 729, save(self=<Document nlayers=1 bbox=Rect(0, 0, 1344, 832) paintonly=False>, filename=u'~/Desktop/201412 Server Migration/201502 Network Layout_01.jpg', **kwargs={'feedback_cb': <function gtk_main_tick>, 'quality': 90})
            try:
                result = save(filename, **kwargs)
            except GObject.GError, e:
  variables: {'kwargs': ('local', {'feedback_cb': <function gtk_main_tick at 0x10ecd8320>, 'quality': 90}), 'save': ('local', <bound method Document.save_jpg of <Document nlayers=1 bbox=Rect(0, 0, 1344, 832) paintonly=False>>), 'result': ('local', None), 'filename': ('local', u'~/Desktop/201412 Server Migration/201502 Network Layout_01.jpg')}
  File "/opt/local/share/mypaint/lib/fileutils.py", line 113, _wrapped_save_method(self=<Document nlayers=1 bbox=Rect(0, 0, 1344, 832) paintonly=False>, filename=u'~/Desktop/201412 Server Migration/201502 Network Layout_01.jpg', *args=(), **kwds={'feedback_cb': <function gtk_main_tick>, 'quality': 90})
                logger.exception("Save method failed")
                os.remove(temp_path)
                raise ex
  variables: {'os.remove': ('global', <built-in function remove>), 'temp_path': ('local', u'~/Desktop/201412 Server Migration/.tmpsave.201502 Network Layout_01.jpg')}
OSError: [Errno 2] No such file or directory: '~/Desktop/201412 Server Migration/.tmpsave.201502 Network Layout_01.jpg'
```

Here is the error report for "Quit" after "Save As" error
```
Mypaint version: 1.1.1-alpha
System information: Darwin-13.4.0-x86_64-64bit
Traceback (most recent call last):
  File "/opt/local/share/mypaint/gui/drawwindow.py", line 654, quit_cb(self=<DrawWindow object at 0x10ea738c0 (MyPaintDrawWindow at 0x7ff0cbcd2230)>, *junk=(<Action object at 0x10fa6aa50 (GtkAction at 0x7ff0cb361c60)>,))
            self.app.doc.model.flush_updates()
            self.app.save_gui_config()  # FIXME: should do this periodically, not only on quit
  variables: {'self.app.save_gui_config': ('local', <bound method Application.save_gui_config of <gui.application.Application object at 0x10ea69e90>>)}
  File "/opt/local/share/mypaint/gui/application.py", line 551, save_gui_config(self=<gui.application.Application object>)
            self.preferences["workspace.layout"] = workspace.get_layout()
            self.save_settings()
  variables: {'self.save_settings': ('local', <bound method Application.save_settings of <gui.application.Application object at 0x10ea69e90>>)}
  File "/opt/local/share/mypaint/gui/application.py", line 368, save_settings(self=<gui.application.Application object>)
            """Saves the current settings to persistent storage."""
            self.brushmanager.save_brushes_for_devices()
            self.brushmanager.save_brush_history()
  variables: {'self.brushmanager.save_brushes_for_devices': ('local', <bound method BrushManager.save_brushes_for_devices of <gui.brushmanager.BrushManager object at 0x10ede5bd0>>)}
  File "/opt/local/share/mypaint/gui/brushmanager.py", line 747, save_brushes_for_devices(self=<gui.brushmanager.BrushManager object>)
            for device_name, devbrush in self.brush_by_device.iteritems():
                devbrush.save()
  variables: {'devbrush.save': ('local', <bound method ManagedBrush.save of <ManagedBrush u'devbrush_pen' p=None>>)}
  File "/opt/local/share/mypaint/gui/brushmanager.py", line 1034, save(self=<ManagedBrush u'devbrush_pen' p=None>)
            logger.debug("Saving brush preview to %r", preview_filename)
            gtk2compat.gdk.pixbuf.save(self.preview, preview_filename, 'png')
            # Save brush settings
  variables: {'preview_filename': ('local', u'~/.mypaint/brushes/devbrush_pen_prev.png'), 'self.preview': ('local', <Pixbuf object at 0x10face1e0 (GdkPixbuf at 0x7ff0ccf4f240)>), 'gtk2compat.gdk.pixbuf.save': ('global', <function save at 0x10dc61f50>)}
  File "/opt/local/share/mypaint/gui/gtk2compat.py", line 26, save(pixbuf=<Pixbuf object at 0x10face1e0 (GdkPixbuf at 0x7ff0ccf4f240)>, path=u'~/.mypaint/brushes/devbrush_pen_prev.png', type='png', **kwargs={})
        def save(pixbuf, path, type, **kwargs):
            return pixbuf.savev(path, type, kwargs.keys(), kwargs.values())
AttributeError: 'Pixbuf' object has no attribute 'savev'
```
Then I restarted fresh.  Quit X11 etc.  When I restarted I got this:
```
Mypaint version: 1.1.1-alpha
System information: Darwin-13.4.0-x86_64-64bit
Traceback (most recent call last):
  File "/opt/local/share/mypaint/gui/history.py", line 109, on_size_allocate(self=<ManagedBrushPreview object at 0x1095e4c80 (gui+history+ManagedBrushPreview at 0x7fd9626d9900)>, widget=<ManagedBrushPreview object at 0x1095e4c80 (gui+history+ManagedBrushPreview at 0x7fd9626d9900)>, alloc=<CairoRectangleInt>)
                self.image_size = alloc.width, alloc.height
                self._update()
  variables: {'self._update': ('local', <bound method ManagedBrushPreview._update of <ManagedBrushPreview object at 0x1095e4c80 (gui+history+ManagedBrushPreview at 0x7fd9626d9900)>>)}
  File "/opt/local/share/mypaint/gui/history.py", line 132, _update(self=<ManagedBrushPreview object at 0x1095e4c80 (gui+history+ManagedBrushPreview at 0x7fd9626d9900)>)
            s = min(w, h)
            scaled_pixbuf = self._get_scaled_pixbuf(s)
            self.set_from_pixbuf(scaled_pixbuf)
  variables: {'self._get_scaled_pixbuf': ('local', <bound method ManagedBrushPreview._get_scaled_pixbuf of <ManagedBrushPreview object at 0x1095e4c80 (gui+history+ManagedBrushPreview at 0x7fd9626d9900)>>), 's': ('local', 24), 'scaled_pixbuf': (None, [])}
  File "/opt/local/share/mypaint/gui/history.py", line 114, _get_scaled_pixbuf(self=<ManagedBrushPreview object at 0x1095e4c80 (gui+history+ManagedBrushPreview at 0x7fd9626d9900)>, size=24)
                theme = Gtk.IconTheme.get_default()
                return theme.load_icon(Gtk.STOCK_MISSING_IMAGE, size, 0)
            else:
  variables: {'Gtk.STOCK_MISSING_IMAGE': ('global', 'gtk-missing-image'), 'theme.load_icon': ('local', gi.FunctionInfo(load_icon)), 'size': ('local', 24)}
Error: gtk-icon-theme-error-quark: Icon 'gtk-missing-image' not present in theme (0)
```
At the moment MyPaint Alpha is still working and I'm happy to provide any other info as you need.

**Comment by bunk3m** [comment] 2015-02-12 20:36
Just wanted to check the file I updated and thought I've saved.  It didn't save any of my work today. :-(

**Comment by bunk3m** [comment] 2015-02-12 20:42
I can now update and say the "Save" isn't working either.
Error report:
----
Mypaint version: 1.1.1-alpha
System information: Darwin-13.4.0-x86_64-64bit
Traceback (most recent call last):
  File "/opt/local/share/mypaint/gui/filehandling.py", line 487, save_cb(self=<gui.filehandling.FileHandler object>, action=<Action object at 0x102740be0 (GtkAction at 0x7fbe88c63540)>)
            else:
                self.save_file(self.filename)
  variables: {'self.save_file': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x102742150>>), 'self.filename': ('local', u'~/Desktop/201412 Server Migration/201501 Network Layout_01.jpg')}
  File "/opt/local/share/mypaint/gui/drawwindow.py", line 79, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'~/Desktop/201412 Server Migration/201501 Network Layout_01.jpg',), **kwargs={})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'self': ('local', <gui.filehandling.FileHandler object at 0x102742150>), 'args': ('local', (u'~/Desktop/201412 Server Migration/201501 Network Layout_01.jpg',)), 'func': ('local', <function save_file at 0x1038ba500>), 'kwargs': ('local', {})}
  File "/opt/local/share/mypaint/gui/filehandling.py", line 317, save_file(self=<gui.filehandling.FileHandler object>, filename=u'~/Desktop/201412 Server Migration/201501 Network Layout_01.jpg', export=False, **options={})
                export=export,
                **options
                )
  variables: {'options': ('local', {})}
  File "/opt/local/share/mypaint/gui/filehandling.py", line 370, save_doc_to_file(self=<gui.filehandling.FileHandler object>, filename=u'~/Desktop/201412 Server Migration/201501 Network Layout_01.jpg', doc=<gui.document.Document object>, export=False, **options={})
                    feedback_cb=self.gtk_main_tick,
                    **options
                )
  variables: {'options': ('local', {})}
  File "/opt/local/share/mypaint/lib/document.py", line 729, save(self=<Document nlayers=1 bbox=Rect(-64, -64, 1408, 896) paintonly=False>, filename=u'~/Desktop/201412 Server Migration/201501 Network Layout_01.jpg', **kwargs={'feedback_cb': <function gtk_main_tick>})
            try:
                result = save(filename, **kwargs)
            except GObject.GError, e:
  variables: {'kwargs': ('local', {'feedback_cb': <function gtk_main_tick at 0x1038ba320>}), 'save': ('local', <bound method Document.save_jpg of <Document nlayers=1 bbox=Rect(-64, -64, 1408, 896) paintonly=False>>), 'result': ('local', None), 'filename': ('local', u'~/Desktop/201412 Server Migration/201501 Network Layout_01.jpg')}
  File "/opt/local/share/mypaint/lib/fileutils.py", line 113, _wrapped_save_method(self=<Document nlayers=1 bbox=Rect(-64, -64, 1408, 896) paintonly=False>, filename=u'~/Desktop/201412 Server Migration/201501 Network Layout_01.jpg', *args=(), **kwds={'feedback_cb': <function gtk_main_tick>})
                logger.exception("Save method failed")
                os.remove(temp_path)
                raise ex
  variables: {'os.remove': ('global', <built-in function remove>), 'temp_path': ('local', u'~/Desktop/201412 Server Migration/.tmpsave.201501 Network Layout_01.jpg')}
OSError: [Errno 2] No such file or directory: '~/Desktop/201412 Server Migration/.tmpsave.201501 Network Layout_01.jpg'
---

**Comment by bunk3m** [comment] 2015-02-12 20:46
I will uninstall and rebuild and install again.

**Comment by bunk3m** [comment] 2015-02-12 20:50
Cleaned build and rebuilt using MacPorts.  Still won't save.
Installed: MyPaint-devel @1.1.1.alpha.20141216+git.68f876fc_0

**Comment by achadwick** [comment] 2015-02-13 01:38
I can't read these tracebacks. Could you reformat between triple-backtick lines please, like

    ```
    [tracebacks here]
    ```

so that the indents are right? It really matters.

You can click on the exit button next to the X to make the edit:

![howto-edit](https://cloud.githubusercontent.com/assets/61299/6180680/81825cae-b320-11e4-9bbe-1ce172bf0661.png)

More info about github markup here: https://guides.github.com/features/mastering-markdown/#syntax

**Comment by bunk3m** [comment] 2015-02-13 17:49
Thks @achadwick.  This is the first project where I report anything with Github.  I'm not a programmer so don't know what I'm supposed to do and appreciate the guidance.  I hope this looks better and is usable now.  

If not, let me know and I'll fix it again.

**Comment by achadwick** [comment] 2015-02-13 18:12
Looks great - thank you for reporting it and especially for fixing up the tracebacks.

Is that a personal build from git, or one using the port?
Either way, the `savev()` exception is going to need 8439ef56b587d8c12d225e55fcc2e97562fcaeb7 or beyond at least (Jan 14, contains some refinements designed to cope with Windows's GdkPixbuf API oddities), and the code may need to be patched further for darwin.
If it comes back after 8439ef56b587d8c12d225e55fcc2e97562fcaeb7 is applied, and it _will_ if the GdkPixbuf workarounds aren't right for your system, please raise a separate issue about it. having too many issues reported in one issue becomes overwhelming for us poor maintainers!

I think the one about `Icon 'gtk-missing-image' not present in theme will be fixed by anything containing f14bea1d0dde89349920acb30236e6fa6b006d40, also dated Jan 14. Must have been a productive day.
You should tell the maintainer that the default icon theme, "hicolor" is a requirement of MyPaint. I don't know what the Macports port is called

(Those hex strings refer to commits in git, and should help the MacPorts maintainer find code that fixes these two issues)

That leaves the original exception, `OSError: [Errno 2] No such file or directory: '~/Desktop/201412 Server Migration/[...]`. I assume the directory actually exists.

**Comment by achadwick** [comment] 2015-02-13 18:20
Again on the 14th Jan: 77b5747ae10e2bc7223a59a57286bda3744b6f64 will probably get pulled in in any MacPorts alpha update. This may suppress the message and log it to the terminal, but I suspect the result would be that you'll end up with a lot of tempfiles cluttering the areas you save to. It needs a proper fix, and I suspect that the problem is being caused by a rogue tilde (`~`) that's somehow crept in there. Here's what happens on Linux:

```
$ touch ~/TESTFILE
$ python
>>> import os
>>> os.remove('~/TESTFILE')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 2] No such file or directory: '~/TESTFILE'
>>> os.remove('/home/andrewc/TESTFILE')
>>> 
```

so I'm not entirely surprised that `os.remove()` is refusing to expand that tilde on OSX. Something's not right here.

How did you open this file in MyPaint?

**Comment by achadwick** [comment] 2015-02-13 18:21
Anyway, first steps are to chase up the MacPorts port maintainer for MyPaint and get them to update it to a more recent MyPaint codebase. If that's how ports work. There have been significant porting improvements over the last couple of months while I've been tussling with the Windows nettle.

**Comment by bunk3m** [comment] 2015-02-13 19:05
Thx @achadwick .

To answer your questions as best I can.
``` Is that a personal build from git, or one using the port?```
I built using Macports.
``` so I'm not entirely surprised that `os.remove()` is refusing to expand that tilde on OSX. Something's not right here.
How did you open this file in MyPaint?```
I put the tilde in there myself.  I was removing the /Users/my_user_name as I didn't want to share my Mac user_name.  I apologize I thought I made that clear and hope I didn't send you down a rabbit hole.
Yes I was able to open the file in MyPaint.
```Anyway, first steps are to chase up the MacPorts port maintainer for MyPaint and get them to update it to a more recent MyPaint codebase. If that's how ports work. There have been significant porting improvements over the last couple of months while I've been tussling with the Windows nettle.```
I'll post this to Macports.  I'll put in the link so the maintainer can follow.

**Comment by bunk3m** [comment] 2015-02-13 19:15
Posted a comment suggesting that the maintainer on Macports have a look at this issue and use a newer build so we can test.  Thanks.

**Comment by achadwick** [comment] 2015-02-14 22:42
> I put the tilde in there myself. I was removing the /Users/my_user_name as I didn't want to share my Mac user_name. I apologize I thought I made that clear and hope I didn't send you down a rabbit hole.
> Yes I was able to open the file in MyPaint.

Not a problem. Thanks for stopping me digging.

> Posted a comment suggesting that the maintainer on Macports have a look at this issue and use a newer build so we can test. Thanks.

Thanks for that. Shall I close this issue for now, or would you be OK with making test builds and testing the bleeding edge? MyPaint can be run from within its build tree without affecting your current installation: see https://github.com/mypaint/mypaint/blob/master/README_OSX.md

**Comment by bunk3m** [comment] 2015-02-16 15:38
```Thanks for that. Shall I close this issue for now, or would you be OK with making test builds and testing the bleeding edge? MyPaint can be run from within its build tree without affecting your current installation: see https://github.com/mypaint/mypaint/blob/master/README_OSX.md```

I can try to build using the instructions in the link above.  I have some questions before I begin.  I don't code so I don't know where this should go so it doesn't screw up anything important.

I have this already installed using MacPorts. I presume all the dependencies have already been installed.  So do I have to install those dependencies again?

I checked and see that all are already installed except for py27-scipy.  I've just installed that.
Where do you suggest I put the code / stuff from github?  

Will this create an executable similar to the Macports build?  

If yes, where will the application end up?  

Will it be in the same place as the git hub download or in the /Applications/MacPorts/ folder?
Thanks again.

**Comment by achadwick** [comment] 2015-02-17 15:46
@bunk3m 
Follow the instructions in the document to install the required dependencies. You do not have to install the deps every time you run MyPaint or build it, but most of the dependencies must be available when MyPaint runs.

Just for testing, you can run MyPaint immediately after building it without having to install from a terminal:

    $ cd path/to/github-clone-or-download-of/mypaint
    $ scons
    $ ./mypaint -c /tmp/cfgtmp$$

(That `-c PATH` runs it with a fresh throwaway configuration every time. Omit that part if you trust the bleeding-edge code with your normal config and brushes!)

You can put your development stuff from github anywhere you like amongst your ordinary files.

I recommend using the `git` commands to download the code and pull in submodules rather than downloading tarballs.

You don't have to install what you build, but you can if you really want. I'm told that in OS X + MacPorts, the /opt tree is deemed to belong to MacPorts, and you should not install your own stuff there. Conventionally on a Linux box or other varieties of Unix, /usr/local is where you install stuff you compile yourself, and package mangers stay away from it. Maybe there, if you must? Check your $PATH. If /usr/Iocal/bin is listed, then /usr/local is a valid prefix for you.

I don't recommend installing from git at all if you're tracking MacPorts's MyPaint too to get serious work done: mere testing can be done without having to install the program, and double installations have been a bit problematic in the past.

But if you know what you're doing, see the Linux docs for how to install to different prefixes (and please try out the OS X docs and raise issues about them if they're wrong!). I very much *don't* know what I'm doing with OSX however, so I can't help you if it breaks.

Let me know how you want to proceed with this. I'm happy to walk you through getting up and testing from OSX: the more testers we have the better!

**Comment by bunk3m** [comment] 2015-02-21 21:28
@achadwick 
I'm slowly trying to figure out git and so will try to help.
I downloaded the GitHub gui from github and cloned mypaint a040b14
Then I tried your instructions but ran into a problem.
I put the clone into ```/Shared/Devo/MyPaint/git/mypaint``` I probably could have done this better but I'm learning as I go.
> $ cd /Shared/Devo/MyPaint/git/mypaint
> scon
> $ scons
scons: Reading SConscript files ...
building for 'python2.7' (use scons python_binary=xxx to change)
using 'python2.7-config' (use scons python_config=xxx to change)
Delete(["libmypaint-tests.so", "libmypaint-tests.so", "libmypaint.so", "libmypaintlib.so", "libmypaint.a", "libmypaint-tests.a", "lib/_mypaintlib.so"])
Enabling i18n for brushlib in full application build
scons: warning: Ignoring missing SConscript 'brushlib/SConscript'
File "/Users/Shared/Devo/MyPaint/git/mypaint/SConstruct", line 214, in <module>
Missing submodule "brushlib"
Please run "git submodule update --init" to create it. See the README
for more information.

No idea what this means.
Tried ```Sync``` from the gui and got

> The submodule at "brushlib" points to "../libmypaint.git", which does not exist.

And also tried from command line:

> $ git submodule update --init
fatal: repository '../libmypaint.git' does not exist
Clone of '../libmypaint.git' into submodule path 'brushlib' failed

You're going to have to lead me my the hand.  I have no idea what I'm doing.

**Comment by achadwick** [comment] 2015-02-21 22:15
When you run `git` on the command line it must be from within the clone folder. So do

```
$ cd /Shared/Devo/MyPaint/git/mypaint
$ ls -ld .git*
$ git submodule update --init
```

this should base the meaning of that `../` on the state in `/Shared/Devo/MyPaint/git/mypaint/.git`, assuming it's a normal clone. Note the leading `.` to the `.git` folder, which makes it hidden on traditional Unix. The `ls` line is just there because I don't know what the GitHub gui does.

(Submodules are a bit of an advanced topic, and maybe it's best to use the command line for this.)

**Comment by bunk3m** [comment] 2015-02-22 00:30
Thanks again.
It still doesn't work.

Here are the results of the commands above:
> $ pwd
/Users/Shared/Devo/MyPaint/git/mypaint

> ls -ld .git*
drwxr-xr-x+ 15 bunk3m  staff  510 21 Feb 16:40 .git
-rw-r--r--+  1 bunk3m  staff   18 21 Feb 16:10 .gitattributes
-rw-r--r--+  1 bunk3m  staff  348 21 Feb 16:10 .gitignore
-rw-r--r--+  1 bunk3m  staff   65 21 Feb 16:10 .gitmodules

> git submodule update --init
fatal: repository '../libmypaint.git' does not exist
Clone of '../libmypaint.git' into submodule path 'brushlib' failed

I'm OK using the command line.

**Comment by achadwick** [comment] 2015-02-24 23:37
@bunk3m 
Did you clone MyPaint exactly as described in https://github.com/mypaint/mypaint/blob/master/README_OSX.md, and are you running a recent enough git?

```
$ git --version
git version 2.1.4
```

is recent enough.

There doesn't seem to be any outstanding specific issue here as far as I can tell in amongst all this, and the issues tracker is not a user support forum, sorry. I can't hold your hand on this for too long. You can find all sort of good introductory information about using git here: http://www.git-scm.com/book (it's not by us).

Closing these issues. Please raise new issues, one per problem you encounter when trying to use our docs for OS X, and be clear about what the problem is with and why. Please read https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md if you go any further with this, specifically the section on reporting issues. Thanks!

Closing as request-for-help, because that's what this has turned into. But to recap for anyone else reading this:

> first steps are to chase up the MacPorts port maintainer for MyPaint and get them to update it to a more recent MyPaint codebase. If that's how ports work. There have been significant porting improvements over the last couple of months while I've been tussling with the Windows nettle.

And a more recent version than the OP's 1.1.1.alpha.20141216+git.68f876fc **might** fix this.

**Closed by achadwick** 2015-02-24 23:37 UTC
Labels: osx, request-for-help
