### ISSUE TITLE
Cursor hidden when using pen and tablet

### ISSUE THREAD

**Issue by Kashrlyyk** [mypaint/mypaint#421] opened 2015-08-28 15:17 UTC
If I use the mouse the cursor is visible. The option "Hide cursor while drawing" is unchecked. 

Windows 7 and myPaint 1.2.0-beta.1

**Comment by achadwick** [comment] 2015-08-28 15:22
Is this Windows in a virtual machine?

Please try the workaround in the FAQ first: https://github.com/mypaint/mypaint/wiki/FAQ-VM-cursor-visibility (it should help you out even if you aren't a VM user)

(I've never been able to reproduce this on real hardware - what tablet are you using, and what driver version please?)

**Comment by achadwick** [comment] 2015-08-31 15:31
@Kashrlyyk Did the workaround linked above work for you?

**Comment by Kashrlyyk** [comment] 2015-08-31 18:43
No, windows is not in a virtual machine. And even the shortest trail of the "Display pointer trails" option was too annoying to bear. So I don't know if it works.

**Comment by achadwick** [comment] 2016-01-27 11:23
@Kashrlyyk Hi there. Can you confirm whether or not this is happening with the 1.2.0 build?

**Comment by Kashrlyyk** [comment] 2016-02-06 17:06
Yes, it does. The mouse pointer has a cursor, the tablet pen doesn't.

**Comment by achadwick** [comment] 2016-02-06 19:39
I don't know what kind of tablet you are using or what the version number is. I'm sorry, I'm won't be of any help here. I don't know why this is happening, and I can't reproduce anything like it except in the VM case I mentioned. Maybe some tablet driver configuration option?

You might get a better answer by asking on the MyPaint [Community Forums](http://community.mypaint.org/) than by asking in this bug tracker. For one thing, the forums have more readers. You should certainly tell the forums people what tablet hardware and tablet driver software version you are using.

This problem would probably go away if we implemented good software cursors: #470.

If this turns out to be a fault in MyPaint'a actual code or documentation, we can fix that that here.

**Comment by achadwick** [comment] 2016-02-06 19:40
**TRIAGE NOTE:** looks like a user support request (or a user support request about aan upstream issue). This is the wrong forum for direct user support, reporter has been redirected to better places to ask. This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status.

**Comment by achadwick** [comment] 2016-03-04 12:33
No feedback that would allow us to treat this as a bug report or a feature request. Closing.

**Closed by achadwick** 2016-03-04 12:33 UTC
Labels: needs-info, user-support, windows, works-for-me
