### ISSUE TITLE
Switching to fullscreen makes the canvas dissappear, i3wm

### ISSUE THREAD

**Issue by hvinayan** [mypaint/mypaint#741] opened 2016-11-03 08:08 UTC
#### Description of the problem

Upon entering fullscreen, the canvas dissappears completely, leaving just the grey background. 
Happens everytime I move to fullscreen.
Happens even if MyPaint starts in full screen.
Have to restart the application in order for the canvas to reappear.

#### Basic system details

MyPaint version: 1.2.0+gitexport.f62444e
Operating system: Arch Linux 
Desktop environment: i3wm

#### Steps to reproduce

1. Start MyPaint on i3wm
2. Switch to full screen (either mod+f, or Full screen toggle in the application, or F11)

**Comment by achadwick** [comment] 2016-11-03 12:27
Duplicate of #735 maybe? Please can you test with the latest beta, and let me know if it's still happening.

**Comment by kdambrosio** [comment] 2016-12-15 03:33
Just happened upon this bug today, also using Arch linux with mypaint version 1.2.0-4. Let me know if I can provide any information to help fix it, or if I can test with a newer version.

**Comment by achadwick** [comment] 2016-12-15 08:37
Please test with git master, and confirm that the problem no longer happens. Thanks.

You can help by getting c225d1132a7da956a35a32534e91a42d22cdb8e1 into the Arch stable mypaint package too.

**Comment by achadwick** [comment] 2016-12-15 08:38
@kdambrosio What window manager are you using?

**Comment by hvinayan** [comment] 2016-12-15 17:40
Problem was fixed, Don't remember the exact when.
On 1.3.0 right now, and I can confirm that the bug is not present.

**Comment by achadwick** [comment] 2016-12-16 09:39
Thanks for the confirmation, and please consider telling your distro's packagers about c225d1132a7da956a35a32534e91a42d22cdb8e1.

**Closed by achadwick** 2016-12-16 09:39 UTC
Labels: duplicate, needs-info
