### ISSUE TITLE
Hiding UI without fullscreen mode ?

### ISSUE THREAD

**Issue by TheMiziko** [mypaint/mypaint#1027] opened 2019-08-18 07:14 UTC
I usually need to work with my references and manage multiple monitors, and it's very difficult to do it when in order to hide the UI I need to go to fullscreen mode.

Will it be possible to hide UI without going to fullscreen mode, or hide UI immediately after going to fullscreen mode and then be able to turn it ON with Tab button ?

**Comment by jplloyd** [comment] 2019-08-18 07:27
Closing as a duplicate of #136 

Personally I would like to have this feature too. It seems @achadwick reasoned that hiding all subwindows with a single keypress could be confusing for new users, which is probably true. One solution would be to add an option to hide subwindows regardless of whether one is in fullscreen mode or not, set to false by default.

I will look at this sometime next week.

**Closed by jplloyd** 2019-08-18 07:27 UTC

**Comment by jplloyd** [comment] 2019-08-24 18:06
If you're interested, I have added a comment related to this in the issue I previously linked to.
