### ISSUE TITLE
No Wacom ISD?

### ISSUE THREAD

**Issue by gerroon** [mypaint/mypaint#760] opened 2017-01-22 04:37 UTC
Version Windows (x32, x64) MyPaint v1.2.1 (2017-01-21)

Hi

I just downloaded the 32 and 64 bit versions. I have a Lenovo Yoga Win10 x64  device. This device has a stylus that I use on the screen to draw on. It is using Wacom drivers and the service is called Wacom ISD service under Windows. Anyway the pen works in every other app that I use (I believe Wintab stuff), like Krita, Sketchbook pro, Gimp etc. The latest builds of Mypaint (both the x32 and x64) does not show the device and the pen can't interact with the app naturally. It does not even work as a mouse inside  

I tend tot think that the previous version of Mypaint worked fine but that was really sometime ago and I remember thatit was hell of a hard job to deal with menus etc so I did not use it that much.

The device manager of Myp shows only the System Aggregated Pointer.

#### Steps to reproduce

1. Start MyPaint
2. Try to draw

**Comment by achadwick** [comment] 2017-01-22 05:19
@gerroon 

* Please try with GTK3-Demo too

  If you launch it from “Test MyPaint’s tablet support (GTK3-Demo)”, you will see a smaller window that can detect pressure and tilt. You can ignore its main window. Try drawing into the smaller window; you should see a blob that changes with the amount of pressure. At least, that happens when GDK is talking to wintab properly.

Trust me, GDK uses wintab.dll :nauseated_face:
None of those other apps use GTK3, so we've started shipping the demo tool.

One awkwardness with MyPaint: the tablet must be plugged in / connected wirelessly when MyPaint starts.

* What version of the Wacom drivers are you using?
* From where did you download them?

I'm afraid I don't know what an "ISD" is.

Please also compare with the most recent stable build of MyPaint, version 1.2.0.

**Comment by gerroon** [comment] 2017-01-22 05:23
@achadwick 

I will try youre suggestions.

Wacom calls it Wacom ISD in the Windows services, basically this is a device with wacom screen so you draw on the screen with pressure instead of separate device.

**Comment by achadwick** [comment] 2017-01-22 05:24
Please tell me your driver version and where you got it from. I also need to know if this is happening in the demo program.

Cannot reproduce with an Intuos5 and its drivers, version 6.3.20-3, downloaded from <http://www.wacom.com/en-us/support/product-support/drivers>.

Cannot reproduce with a HUION H610PRO and its drivers, V12.2.16, downloaded from their support site.

**Comment by gerroon** [comment] 2017-01-22 05:35
Ok tested the gtk demo and there is no blobs etc with the pen.

I can draw on the screen with my fingers, but the pen (which is used to draw on the screen) is non functional pretty much. 

You can see my device in action here

https://www.youtube.com/watch?v=d0PVjrzc-xk

**Comment by gerroon** [comment] 2017-01-22 05:36
The latest version of My paint works with my Wacom Intuous Pro 5 on Windows 7 desktop No problem there. 

I am using the drivers that came with the device.

**Comment by gerroon** [comment] 2017-01-22 05:46
Tiny progress, if I kill Tabtip.exe (which is a windowes ink service I believe), I can get Wacom driver show under Devices in Mypaint (x64 only) but that is pretty much it, no funcitonality with paint draw or pressure. Before it was not showing up. It is set to pen and any task but it does not do anything on the canvas and it has no click.

Like I said this pen works as is in Krita, Gimp and Sketchbook Pro , I just tested it again.

**Comment by gerroon** [comment] 2017-01-22 05:58
Btw this device does not use the standard wacom drivers, like I explained aboive wacom tablet drivers creates conflict.

**Comment by achadwick** [comment] 2017-01-22 06:01
@gerroon 
This fault with your Wacom ISD is either an installation problem, or a bug in GTK (and it sounds a lot more like the latter after your most recent tweaking). MyPaint 1.2.1's Windows build uses GTK version 3.22.7. Since your bug affects gtk3-demo as well, you need to report it at the GNOME bug tracker against the "gtk+" component and its Win32 backend. Only you can help things improve, since only you have the hardware.

MyPaint (or rather, GTK) does not use Windows Ink. It uses wintab. But tablet drivers usually provide both interfaces, so driver settings may make the wintab stuff happier.

Krita, GIMP, and Sketchbook Pro are not GTK3 apps. However GIMP is built on GTK2, so this counts as a regression since GTK2. Saying that would be a good way to get the GTK developers' attention.

* [Example search for existing “wintab” bugs](https://bugzilla.gnome.org/buglist.cgi?bug_status=__all__&content=wintab&no_redirect=1&order=bug_id%20DESC&product=gtk%2B&query_based_on=&query_format=specific)
* [Bug report form for gtk+ bugs](https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B) (needs a login)

You'll need to provide them with the information I asked for here, in detail. Definitely try to find the ISD tablet's driver version number before reporting it.

Closing, because this issue cannot be fixed here. Sorry :sob:

**Closed by achadwick** 2017-01-22 06:01 UTC

**Comment by gerroon** [comment] 2017-01-22 06:07
@achadwick 

thanks for your time and your suggestions and naturally we are grateful for your awesome work on this app.

This just sounds like my issue and the user is using pretty much the same tech as I do.



https://bugzilla.gnome.org/show_bug.cgi?id=776572

**Comment by achadwick** [comment] 2017-01-22 06:37
Oh, good news that Inkscape are on the GTK3 wagon. That will help a lot. Thanks for the info about the hardware varieties out there too!

It takes about an hour to rebuild GTK, it may be more productive to subscribe myself over there and yell at some usual suspects on IRC tomorrow. I'll mostly be focusing on avoiding regressions for hardware I do have☺ I'd suggest you add some comments on that bug too.

If you get yourself an [msys2 installation](https://msys2.github.io/) I can do a build with the patch and drop it here.

**Comment by achadwick** [comment] 2017-01-22 14:02
Sadly, I can't upload a patched libgtk3 DLL here for you to try. There's a maximum size of 10M in threads.

**Comment by gerroon** [comment] 2017-01-22 16:26
@achadwick 

I will try bugging them if I can test your build successfully. 


Maybe try this to upload the dll?

https://filebin.net/

**Comment by achadwick** [comment] 2017-01-22 17:29
@gerroon 
Good idea! While it lasts...

* https://filebin.net/4fe2fekhy53wa0me :open_file_folder:
  - These contain the patch in <https://bugzilla.gnome.org/show_bug.cgi?id=776572>.

With a little care, you might be able to manually slot the patched `.dll` files into an unpacked standalone copy of MyPaint and test them there in gtk3-demo and mypaint.

```
$ sha256sum gtk_debug_*
38ac88a44c0861d35746777be4692c4212eb07ccad42c9d26b90d38ebe879f57  gtk_debug_dlls_from_gtk3-git_3.22.7.30_gaff4268.zip
f8e389752ca71fcbd37ea330c04f866a549a2937fd4e382d19c647ed0a3eeab8  gtk_debug_packages_of_gtk3-git_3.22.7.30_gaff4268_for_current_msys2.zip
```

**Comment by gerroon** [comment] 2017-01-22 19:00
Hey @achadwick 


Thanks for the files. 

Some progress with the patched files! After restarting Mypaint couple times( not sure why, maybe it did not register the drivers iat the first time) I can see the wacom ISD in the devices along with an eraser (which my pen does not provide an eraser but no problem, maybe recognized as wrong pen?), I also can get the pen to draw and not only draw , I also have pressure with the Pen on the screen while drawing, but there is a big  but, there is a big shift between the pointer and where it draws, I do not know how many pixels but it is minimum couple hundreds pixels forward on Y and down on Y.

Also there are tiny squares around stroke path, guessing some debugging related?


Thanks againg for trying to handle this issue.

**Comment by achadwick** [comment] 2017-01-22 19:43
@gerroon 
Shouldn't be any tiny squares unless you turned on "Visualise Rendering" (those are blue). Are you using a HiDPI screen?

The offset is another upstream thing, but we are further along now. Are you using more than one monitor? That can be a cause of it. Have a search here too.

**Comment by gerroon** [comment] 2017-01-22 20:07
This is a Laptop, so only one monitor with Mypaint. 

I am using a 1440p so I guess that is a hiDPI screen.

**Comment by megaloegoman** [comment] 2017-01-22 23:35
Glad you find my patch useful and good to see other Windows users.

Alan, thanks for getting attention on bugzilla. But according to http://mypaint.org/blog/2016/11/20/wintab-fixes/,  you should've been aware of the bug in November? I didn't notice until December when I started building Inkscape with GTK3 instead of GTK2.

I also have noticed sometimes I need to restart Inkscape before pen devices show up. Apparently, you have to touch the screen with the pen to wake it up before starting any GTK app. Maybe this is a bug with the driver or maybe GTK's device enumeration isn't looking hard enough, or maybe there's a way to wake it up in software?

"there is a big shift between the pointer and where it draws"
I've experienced the same thing when I connected a 2nd monitor in extend desktop mode AND with a different resolution.

I also had problems with HiDPI. SetProcessDpiAwareness() fails with access denied, causing GTK to abort instead of continuing (can comment out the failed assertion or set GDK_WIN32_DISABLE_HIDPI=1).

**Comment by achadwick** [comment] 2017-01-23 10:32
@megaloegoman (by "Alan" do you mean me?)
Speaking for myself, I can only test with the hardware I own. This bug is specific to a piece of hardware I don't have access to.

**Comment by megaloegoman** [comment] 2017-01-23 11:37
Sorry, I meant Andrew, not Alan. 

From what I can tell, this bug should cause *all* Wintab devices to not be reported, when calling
gdk_seat_get_slaves(), so I don't know why you didn't see it earlier. If you called gdk_device_manager_list_devices() instead, which Inkscape used for GTK2, then you would see the tablets.

It seems GTK3 adds this concept of seats that wasn't in GTK2 and the seat registration wasn't performed. The 2nd problem is the master <--> slave association was wrong, based on what I see happen on GNU/Linux.

Cool that you fixed tilt sensitivity. I never noticed the problem because I haven't used my Intuos Pro for a few years. Tilt was an easy thing to give up in exchange for drawing on the screen.

**Comment by achadwick** [comment] 2017-01-23 12:41
MyPaint HiDPI bugs: #631 #686.

------------------------------------------------------

@megaloegoman 
Thanks for the info about GDK_WIN32_DISABLE_HIDPI=1.

MyPaint doesn't use the seats stuff. I don't understand it. Nor do we rely on gdk_device_manager_list_devices() during initialization - device settings have always been looked up dynamically.

The only thing that tries to enumerate devices is the per-device settings manager in Preferences, and there MyPaint uses a hybrid list of devices that have been observed during MyPaint operation combined with what list_devices() spits out. Yeah, I know. But enumeration was definitely broken at the time, and we worked around it.

This bug's resolution is still that it's *something* upstream which is fixed in (the 30 commits after 3.22.7 at gaff4268)+(your patch), because that's what I built and what @gerroon tested. I'm surprised that fixing enumeration fixes it, but thank you for looking into something that's been annoying me for some time.

The most productive way forward on the *probable* cause of this is to chase it at <https://bugzilla.gnome.org/show_bug.cgi?id=776572>. The patch there is currently at `accepted-commit_now`, so expect it to hit the next stable release. And thank you again! :smile:

**Comment by gerroon** [comment] 2017-01-23 23:20
@achadwick 

Disabling HIDPI resolves both the squares around the stroke and the pointer/stroke shift.

**Comment by achadwick** [comment] 2017-02-19 00:15
@gerroon 
FYI, I just merged a fix for MyPaint's home-grown HiDPI bugs. There are still some upstream bugs that break [all tablet input](https://bugzilla.gnome.org/show_bug.cgi?id=778508) and [menu usability](https://bugzilla.gnome.org/show_bug.cgi?id=778834) in HiDPI mode that still need their fixes merging. Fingers crossed for GTK 3.22.9 ☺

**Comment by gerroon** [comment] 2017-02-19 04:47
@achadwick 

Sounds great, when is the next release roughly?
