### ISSUE TITLE
Is there mypaint into Google Play or App Store?

### ISSUE THREAD

**Issue by gerardogc2378** [mypaint/mypaint#884] opened 2017-12-17 22:08 UTC
I like mypaint a lot but ...

Is there mypaint on Google Play or App Store? I want to have mypaint into Google Play or App Store, any roadmap for this question?

**Comment by achadwick** [comment] 2017-12-27 21:37
Hello, this is not a bug so I am closing it. Thank you for the question.

There is no plan for mobile platform support. MyPaint is an open source app for Windows and Linux users. We hope one day to support macOS better, but not through the App Store.

**Closed by achadwick** 2017-12-27 21:37 UTC
Labels: user-support, works-for-me
