### ISSUE TITLE
Using the static color palette will freeze the application

### ISSUE THREAD

**Issue by nekohayo** [mypaint/mypaint#506] opened 2015-11-24 17:17 UTC
Testing the 1.2 beta 3 (also affects beta 2 etc.), on Windows 7 64-bits (for the time being as I don't have a build for Fedora 23) with a Wacom Cintiq:

1. Start mypaint
2. Draw some quick lines with the penbrush
3. Click the color picker rectangle thingy at the bottom-left (not the eye-dropper)
4. Use the rigth arrow button to go to the palette, the one with a limited amount of colors represented as squares.
5. Click a light gray in there.
6. Try drawing on the canvas.

Result: application locked up (somehow not detected as unresponsive by the toolkit/OS, though), needs to be killed with the task manager. Happens 100% of the time for me with this procedure.

**Comment by nekohayo** [comment] 2015-11-24 17:31
Interesting little bit: the GTK mainloop and such is not frozen. If I click the window manager's "X" button, I see MyPaint prompts me for quitting with unsaved changes... but I can't actually click the buttons in that dialog!

So maybe it's some sort of pointer grab that never gets released?

**Comment by achadwick** [comment] 2015-11-24 17:54
I think so. Pointer grabs for those little popups seem really weird on Windows for some reason (sigh...). I'll see what I can do about it when I have a chance.

This looks like a duplicate of #321. Closing in favour of that one.

**Closed by achadwick** 2015-11-24 17:54 UTC
Labels: duplicate, windows
