### ISSUE TITLE
Show tool number values

### ISSUE THREAD

**Issue by DuendeInexistente** [mypaint/mypaint#1054] opened 2020-02-10 12:50 UTC
#### Description of the problem

![image](https://user-images.githubusercontent.com/20157727/74151239-7bd1d100-4bea-11ea-8dd2-0a85278809d8.png)
I would like it if the tool settings would display their numeric values. It would make remembering specific settings easier than a slider that scales to DPI.

#### Basic system details

MyPaint version: Beta appimage
Operating system: Ubuntu 17
Desktop environment: Xfce]

**Comment by jplloyd** [comment] 2020-02-10 12:54
Duplicate of #25

Hopefully we'll get this done, along with a lot of other user interface issues, in the next release (after 2.0.0).

**Closed by jplloyd** 2020-02-10 12:54 UTC
