### ISSUE TITLE
Separate layer adjusting/toggling suggestion 

### ISSUE THREAD

**Issue by flufflepaffles** [mypaint/mypaint#671] opened 2016-05-03 21:07 UTC
Hi, I love mypaint w64 and all of the brushes. It's easily one of the best programs i've ever used and loved so much. However, I would like to suggest something? I think it would be great if you could rotate and zoom a single layer, like maybe pressing the shift key while using the rotate and zoom. That way, you could adjust or toggle tricky areas like hands or something. Everything you do is greatly appreciated.

**Comment by odysseywestra** [comment] 2016-05-03 21:26
This has already been requested on our community forums.

https://community.mypaint.org/t/layer-transformation/241

**Comment by achadwick** [comment] 2016-05-04 09:21
It can't be done in a non-destructive way, but that's perhaps fine for getting sketches right.

The forums are currently down, but this is also a duplicate of #31 here.

**Closed** 2016-05-04 09:21 UTC
Labels: duplicate
