### ISSUE TITLE
Various problems after upgrade to latest version

### ISSUE THREAD

**Issue by DrawMeister123** [mypaint/mypaint#582] opened 2016-01-30 14:32 UTC
Hi, 

Please help. I am running Win7 Ultimate and just upgraded to the latest version of MyPaint (long time user and big fan) but it doesn't recognise the ORA files from my previous version (last stable release). It says these are incompatible, converter plugin PNG file not compatible. 

It also has an issue with the pen/tablet input. The pointer jitters and there is a long, long delay before any brush strokes appear on screen, and appear jumpy / zigzaggy / not smooth. 

If I have posted this in the wrong place - deep apologies. I really want the new version to work as it looks amazing. 

Thanks.

**Comment by achadwick** [comment] 2016-01-30 18:20
Hi there. Thank you for reporting.

The issue tracker is probably the right place for all these issues because each one sounds like a bug. However we want one issue per problem only. 

What I pretty much have to ask you do is split all your concerns out of this issue, and report them as separate issues. Please read <https://github.com/mypaint/mypaint/wiki/Reporting-Bugs> as well, if you haven't already. Thanks.

* That PNG compatibility issue looks alarming and especially like a bug.

* Regarding lags and jitters, please be sure to search the issue tracker before reporting and have a look at other similar-sounding bugs. I suspect this part of this issue is a duplicate of #390. The jitter sounds a bit like #177. However only you can confirm!

* Please make sure you are using the most recent tablet drivers before going any further. When you report the split-out issues from this one, we'll need to know details about your hardware, driver versions, software versions, the lot.

Closing because this is unlikely to be progressed usefully without splitting out each part and researching the sub-issues separately. Please go into a lot more detail, and please link your new reports back to this one with a `#582` code (write the issue number with a number sign in front of it). That way the thread won't get lost and threads link together neatly.

**Closed by achadwick** 2016-01-30 18:20 UTC
Labels: duplicate, needs-info, request-for-help

**Comment by DrawMeister123** [comment] 2016-01-30 20:54
With all due respect but 'HUH?' ... I am user of the software not a programmer and have no clue what you said about #582 something ...  

I'm going to read the other threads you linked to to see if they answer the questions.

**Comment by odysseywestra** [comment] 2016-01-30 21:15
Here's a guide that explains how [Github's Issue Tracker Works](
https://guides.github.com/features/issues/). Believe me it's a lot less
complicated than it looks.

On Sat, Jan 30, 2016, 12:54 PM DrawMeister123 <notifications@github.com>
wrote:

> With all due respect but 'HUH?' ... I am user of the software not a
> programmer and have no clue what you said about #582
> <https://github.com/mypaint/mypaint/issues/582> something ...
>
> I'm going to read the other threads you linked to to see if they answer
> the questions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mypaint/mypaint/issues/582#issuecomment-177299626>.
>
-- 

-- Albert Westra

**Comment by achadwick** [comment] 2016-01-31 00:18
@DrawMeister123 
Is there anything I can do to make reporting easier?

I hate being insistent about one problem for one issue report because it's stroppy and rude, but things get literally unmanageable if we let threads bumble around like a big katamari of troubles. So I hope you'll forgive me.

There may be nothing we can do about your tablet issues. Freaky glitches tend to be upstream problems in certain software components we rely on, but which we did not write. Same thing with the lag, but a different technical cause.

Check out #177 for pictures of one kind of jitter that we've seen. But I think you use different hardware, and perhaps your jitter looks different? When you report the jitter, a screenshot showing the problem would be really useful to see. Thanks!

The "incompatible, converter plugin PNG file not compatible" issue looks quite serious for our users, and I would love to see the exact error message or have some way of reproducing the problem myself. When you report this error in a new issue, having the full text of the error message would be really helpful for people trying to get it fixed. Thanks!

**Comment by DrawMeister123** [comment] 2016-01-31 04:13
OK the error message on the file open is:

gdk-pixbuf-error-quark: Fatal error reading PNG image file: Decompression error in IDAT (0)
