### ISSUE TITLE
Clicking fails in various ways for free-flow (width=0) palettes

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#250] opened 2015-03-09 13:48 UTC
I've noted an strange behavior when you try select the last entry on the palette... is very difficult describe this behavior and I've made a short video to show it:
https://www.youtube.com/watch?v=R613LO1z2OA
My box is Ubuntu Gnome 14.04 with MyPaint git master - last release.

**Comment by achadwick** [comment] 2015-03-09 13:53
Ooh, that's not supposed to happen.

Perhaps you have a duplicate colour somehow? The highlight is actually a closeness match - it has subtly different weights for exact and approximate matching. But if you've two exact matches, maybe it takes the first?
(I've tested making duplicates though, and it seems fine...)

Don't suppose you could pastebin/gist the palette .gpl file that shows the problem?

**Comment by achadwick** [comment] 2015-03-09 13:53
(Probably a bug, but I can't reproduce it myself so far)

**Comment by achadwick** [comment] 2015-03-09 13:57
Hmm, watching the full video it seems to be using a nearness metric: but to the current colour match and not the point that's clicked.

**Comment by americogobbo** [comment] 2015-03-09 14:11
The palette of video:
http://pastebin.com/zP3vvafF

**Comment by americogobbo** [comment] 2015-03-09 14:18
Well, if you place the cursor on the last entry of each line... is possible to select always the last entry until the last line... but if you select any entry on the middle of the palette... is not possible select the last entry on the bottom.

**Comment by achadwick** [comment] 2015-03-09 14:25
Reproduced - but only if the palette's "Columns" setting is 0 (meaning free-flow).

Possibly related: I can't click around in the palette editor to select things if the Columns value is 0, but I can if Columns is set to any higher value.

**Comment by achadwick** [comment] 2015-03-09 14:26
Quick workaround is to define a width for your palette.

**Comment by americogobbo** [comment] 2015-03-09 14:29
and double-click the color details show always the value=50%. Is curious... when the last entry color is selected on color details show another color: #7F7F7F in place of RGB(203 31 91). Another info interesting... is when I open the .gpl on gpick appears the this message:
File is currently in a non native format, possible loss of precision and/or metadata.

**Comment by achadwick** [comment] 2015-03-09 14:32
Reproduced with other palettes:

* First part of https://github.com/mypaint/mypaint/issues/250#issuecomment-77862497 only presents if there are duplicate colours.
* I'm not sure why the second part of that comment is happening.
* Also reproduced the one in https://github.com/mypaint/mypaint/issues/250#issuecomment-77863097 with a different palette (meaning it probably isn't related to the format or conversions). That mid-grey is sort of a fallback/default colour.

**Comment by achadwick** [comment] 2015-03-09 14:34
This is something that should be fixed up if #109 is to be implemented properly.

**Comment by americogobbo** [comment] 2015-03-09 14:56
Ok, last note... about around this issue, when I try select a palette in a different folder... always is loaded the first of filemanager list... I've a video to show it... that is very difficult to understand this behavior... if you choose a palette on bottom of the list is loaded... This palette is saved with mypaint after I added some colors on the last line.
https://www.youtube.com/watch?v=SO3dG80IPeA

**Comment by achadwick** [comment] 2015-03-09 15:14
@americogobbo Could you raise that last one as a separate issue please? I'm not sure I understand it from the video, but you seem to expect something with the name field?

**Closed** 2015-03-10 02:47 UTC
Labels: bug
