### ISSUE TITLE
No pressure-sensing in win8 (wacom intuos)

### ISSUE THREAD

**Issue by Kazekai** [mypaint/mypaint#592] opened 2016-02-06 06:27 UTC
I tried the program on win7 a few days ago and it actually worked for a nice change which I was thrilled about because it meant that maybe I could finally ditch that dinosaur SAI for something else but when I tried to run mypaint on a laptop that has win8 installed, the pressure-sensing wasn't working and it was definitely not the fault of my tablet.

The only issues I could find are from a year ago and pertain to all 64-bit versions of windows and not just win8 but since it was working in win7 64-bit all I can figure is that it's some new issue that didn't show up in a search.

**Comment by achadwick** [comment] 2016-02-06 19:03
Hi - have you tried asking on the [MyPaint community forum](<http://community.mypaint.org)?

This issue tracker isn't a good place for solving user problem reports unless we stand a chance of investigating and fixing the cause of the problem by changing MyPaint or its docs. One reason is that it doesn't get many eyeballs. The forums are better for that.

Anyway standard issue-tracker questions:

* What Intuos model is this please?
* Also, what driver number is it (best way to find out is to look in "Add or Remove Programs").
  * You might want to compare your win7 box with your win8 one here.
* Which *exact* MyPaint version is this? Please look in Help → About MyPaint, the long number with the hex string on the end can be cut-and-pasted.
* If you're trying the ~w32 version of MyPaint, does the ~w64 one work any better?
  * Or the other way around?

If this issue can be verified as a bug in MyPaint or a deficiency in our docs, I can take it forward. Otherwise, really, the forums are better than here.

**Comment by achadwick** [comment] 2016-02-06 19:28
**TRIAGE NOTE:** looks like a user support request. This is the wrong forum for direct user support,
reporter has been redirected to better places to ask. This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status.

**Comment by Kazekai** [comment] 2016-02-09 05:17
I finally fixed my desktop machine and it isn't working on here now either so I have no idea what the problem is.

Using an intuos CTL480
It doesn't tell me the driver number in "add or remove programs"
MyPaint x64 version 1.2.0+git.f62444e.dirty
Neither version works.

I wasn't sure if it was a user-specific issue. Also the forums require you to get a new account and doing that just to get help troubleshooting seemed like a waste.

**Comment by tumagonx** [comment] 2016-02-09 13:18
It's not a waste, actually with forum your chance having other users
with same tablet is bigger than here. Who knows they have the
workaround. Obviously many Wacom reportedly worked with mypaint (at
least recognized).

On 2/9/16, Kazekai <notifications@github.com> wrote:
> I finally fixed my desktop machine and it isn't working on here now either
> so I have no idea what the problem is.
>
> Using an intuos CTL480
> It doesn't tell me the driver number in "add or remove programs"
> MyPaint x64 version 1.2.0+git.f62444e.dirty
> Neither version works.
>
> I wasn't sure if it was a user-specific issue. Also the forums require you
> to get a new account and doing that just to get help troubleshooting seemed
> like a waste.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/592#issuecomment-181714622


-- 
!tuma

**Comment by achadwick** [comment] 2016-02-09 13:59
(You can log in to our forums with your Github account. @odysseywestra: don't suppose there's a forums category for tablet hardware debugging specifically? :smile: )

I'm used to Intuos models, which I think do report a version number in Add or Remove Programs. Maybe that doesn't happen for Pen & Touch drivers, or maybe you have to go digging. Anyway I've added what I think is a CTL-480S to my ever-growing Amazon wishlist for now. there's not much more I can do.

**Comment by achadwick** [comment] 2016-02-09 14:02
Maybe creating a new hardware compatibility matrix would be useful, but that's a bit OT.

**Comment by Kazekai** [comment] 2016-02-10 01:54
Thanks, that's good to know since I had another question to ask that isn't specifically an issue.

Testing the program on win8 again, the tablet's pressure sensing isn't working but neither are a lot of other things. The laptop uses win8 and not win8.1 though so I'm not sure if it's worth investigating until it gets updated. It isn't my laptop though so I can't do that myself. I have no idea if the strange behavior is related between the two OSes.

Sorry I can't find the information, I'm using the latest driver software for this tablet on amazon: http://www.amazon.com/gp/product/B00MJKE0AU?psc=1&redirect=true&ref_=oh_aui_detailpage_o03_s00 this is from my archived orders, I don't know how useful this information will be though.

**Comment by odysseywestra** [comment] 2016-02-10 05:24
@achadwick not yet but I could add that category. Though it might be better to have a tag system for that since there are multiple tablets models.

**Comment by Kapukw** [comment] 2016-02-16 13:37
I found interesting behavior:

When I just start MyPaint, pressure sensing is not working.
Then I launch Photoshop and check pressure (works fine).
After this check I launch MyPaint again and pressure works fine.

I check it on CTL-470 and CTL-471.

**Comment by achadwick** [comment] 2017-01-23 19:17
@Kapukw 
The Wintab interface we use can be sensitive to that. I don't quite understand why.

**Comment by achadwick** [comment] 2017-01-23 19:20
@Kazekai 
I'm closing this user support request because it didn't gather a concrete bug report or an actionable feature request.

However, you might want to check out [MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1), which was released recently. It contains several tablet fixes. If you test it out, please let us know if this problem is still happening - there's more we can do to help now.

**Closed by achadwick** 2017-01-23 19:20 UTC
Labels: needs-info, user-support, windows
