### ISSUE TITLE
Panels undock themselves when interacted with

### ISSUE THREAD

**Issue by Queatz** [mypaint/mypaint#698] opened 2016-06-02 02:25 UTC
#### Description of the problem

When I tap to select a brush, it undocks the brushes panel. Happens with most panels.

Video: https://youtu.be/D4GVNvqNXt4

#### Basic system details

MyPaint version: 1.2.0 stable
Operating system: Debian stretch
Desktop environment: GNOME 3.20.1

#### Steps to reproduce

1. Start MyPaint
2. Dock the brushes panel
3. Select a brush with a tablet (or drag a little with the mouse)

Expected:
The brushes panel stays locked

Actual:
The brushes panel undocks and you have to re dock it to the side panel.

**Comment by odysseywestra** [comment] 2016-06-02 05:48
What is the exact version of MyPaint you are using? You can find it under Help>About MyPaint.

**Comment by achadwick** [comment] 2016-06-02 09:06
Duplicate of #643.

**Closed by achadwick** 2016-06-02 09:06 UTC
Labels: duplicate
