### ISSUE TITLE
Suggestion: Paintable Mask?

### ISSUE THREAD

**Issue by ChengduLittleA** [mypaint/mypaint#1156] opened 2021-09-14 09:00 UTC
Hi! this is just a suggestion:

Would it be possible to implement a "mask painting" brush? Like selection in other programs, we paint a region and then use that region as mask, and clear the mask. So you could paint on the same layer as your existing one without creating a new layer because alpha lock is not always possible as you may want to mask a small region within painted area.

No need to use box or lasso, just a special mask that can be used to restrict painting region, maybe a special alpha lock layer that is always sampled.

Any ideas?

**Comment by Bouch76** [comment] 2022-08-12 06:33
It's a shame no-one has replied, I love using MyPaint and I agree with you whole heartedly. I understand that MyPaint is keeping it's workflow dedicated to Painting only functions, it doesn't strive to be Illustrator or Photoshop etc. 
When I paint "Real world" with Airbrush, Acrylics or Pencil, to create Masks I cut out pieces of cardboard or paper to produce clean edges or isolate an area of my canvas.  I think a Mask Brush feature is a legitimate inclusion for MyPaint.

**Comment by AesaraB** [comment] 2024-01-17 07:16
Duplicate of #31

**Closed by AesaraB** 2024-01-17 07:16 UTC
Labels: solution.Duplicate, type.Enhancement, cat.Tools, cat.Widget
