### ISSUE TITLE
Failed to start MyPaint after updating

### ISSUE THREAD

**Issue by w9** [mypaint/mypaint#780] opened 2017-02-07 19:53 UTC
#### Description of the problem

I have been using MyPaint for a while now (lovin' it!). After updating to the newest version, MyPaint refuses to start with the following error message:

    ERROR: gui.application: Missing icon 'mypaint-brush-symbolic': check that librsvg is installed, and update loaders.cache

#### Basic system details

MyPaint version: 1.2.1+gitexport.bcf5a28d
Operating system: ArchLinux
Desktop environment: Xfce

#### Steps to reproduce

1. Start MyPaint in Terminal
2. Get error

#### Backtraces or error messages

```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
INFO: lib.i18n: POSIX: LANG='en_US.utf8'
INFO: lib.i18n: POSIX: LANGUAGE=None
ERROR: gui.application: Missing icon 'mypaint-brush-symbolic': check that librsvg is installed, and update loaders.cache
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/application.py", line 126, in _init_icons
    pixbuf = icon_theme.load_icon(icon_name, 32, 0)
Error: gtk-icon-theme-error-quark: Icon 'mypaint-brush-symbolic' not present in theme Paper (0)
CRITICAL: gui.application: Required icon(s) missing
ERROR: gui.application: Icon search path: ['/home/████/.local/share/icons', '/home/████/.icons', '/home/████/.local/share/flatpak/exports/share/icons', '/var/lib/flatpak/exports/share/icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/share/icons', '/home/████/.local/share/flatpak/exports/share/pixmaps', '/var/lib/flatpak/exports/share/pixmaps', '/usr/local/share/pixmaps', '/usr/share/pixmaps', '/usr/share/pixmaps', '/usr/share/icons']
ERROR: gui.application: Mypaint can't run sensibly without its icons; please check your installation. See https://gna.org/bugs/?18460 for possible solutions.
```

**Comment by odysseywestra** [comment] 2017-02-07 20:08
It could be issues with updating your icon cache. Please read the readme about troubleshooting icon issues.

https://github.com/mypaint/mypaint/blob/master/README_LINUX.md

**Comment by achadwick** [comment] 2017-02-07 20:18
Oh hey. We've got a link to the old bug tracker in the code. Yuck. We ought to remove that and maybe replace it with a link here.

Also, this is practically FAQ material, so let's walk this one through for future reference!

Firstly, what @odysseywestra said above!

If these suggestions, and this is a packaged MyPaint build in AUR or wherever, please tell your MyPaint package maintainer that they need to run these commands in their `post_install` scriptlets. Please point them at [our comaintained PKGBUILD for Windows/MSYS2](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-mypaint-git) so they can see what we do (which is heavy overkill)

The second thing to try is SVG rendering in gdk-pixbuf, which is done with librsvg. MyPaint needs this to render symbolic icons and vector layers. It comes with a (sadly optional) loader plugin for [gdk-pixbuf](https://aur.archlinux.org/packages/gdk-pixbuf), so gdk-pixbuf needs to be told about new loaders as a result.

1. First of all, make sure you have librsvg installed. Try reinstalling it.

2. If that doesn't fix it, please run `gdk-pixbuf-query-loaders --update-cache` as root. This command is taken directly from `librsvg.install`, found on the [AUR librsvg-git page](https://aur.archlinux.org/packages/librsvg-git/).

Hope that fixes it for you!

**Comment by achadwick** [comment] 2017-02-07 20:21
docs for updating that link in the exception, and maybe updating the FAQ in the wiki. This issue can be closed when a commit pointing to somewhere more sensible is committed.

**Comment by odysseywestra** [comment] 2017-02-07 20:26
I can do that later on today.

**Comment by w9** [comment] 2017-02-07 22:40
Hi @odysseywestra and @achadwick, thanks for the response.

I have tried running

    sudo gtk-update-icon-cache /usr/share/icons/Paper
    sudo chmod a+r /usr/share/icons/Paper/icon-theme.cache

as well as

    sudo gdk-pixbuf-query-loaders --update-cache

However, the latter gave the following error message:

    g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

and the MyPaint still doesn't start.

**Comment by achadwick** [comment] 2017-02-07 22:51
@w9
I think that this is something we can't help you with: it looks like a problem with your installation. Sorry about that.

libpixbufloader-svg.so (part of rsvg) is trying to link up with [an opentype-related library called harfbuzz](https://aur.archlinux.org/packages/harfbuzz-git/) and failing to find a symbol it expects. Neither of these two libs is maintained by the MyPaint team. Please ensure that this is reported as a bug against the packages in question in the [downstream bug tracker for Arch Linux](https://bugs.archlinux.org/).

Sadly this is no longer good FAQ material. Oh well. :disappointed:

**Closed by achadwick** 2017-02-07 22:51 UTC
Labels: user-support, works-for-me

**Comment by achadwick** [comment] 2017-02-07 22:54
(Further to that, the failed linking appears to be caused by a package update that's beyond our control. A `pacman -Syu` *or* a package downgrade with pacman might fix it. Best of luck.)

**Comment by achadwick** [comment] 2017-02-07 23:41
One more FYI - MyPaint installs to the "hicolor" icon theme, not "Paper". It doesn't look like that's the cause of this one, though.

FAQ updated: <https://github.com/mypaint/mypaint/wiki/FAQ-Missing-icons>. I should tweak the README too.
