### ISSUE TITLE
Shortcuts don't work in non-latin keyboard layouts

### ISSUE THREAD

**Issue by ystr** [mypaint/mypaint#974] opened 2019-02-12 23:00 UTC
The title says it all, MyPaint reads localized text input instead of actual physical keys.

How to reproduce: switch to Cyrillic, try any key combination
Versions and systems: probably all of them (I tested 1.2.1 and 2.0.0 under Win32 and 1.2.0 under Debian 9 / GNOME).

The fix is to remove the event.group parameter from translate_keyboard_state in gui/keyboard.py.

**Comment by AesaraB** [comment] 2024-01-17 10:03
Duplicate of #642

**Closed by AesaraB** 2024-01-17 10:03 UTC
Labels: type.Bug, solution.Duplicate, platform.Windows, cat.Input.Keyboard, platform.Linux
