### ISSUE TITLE
Cannot select color.

### ISSUE THREAD

**Issue by GaryMatthews** [mypaint/mypaint#1200] opened 2023-05-31 04:37 UTC
cannot select color. 

i just installed this software on ubuntu 22.04.2 from the repo and strait away the first issue is opening the color pallet then attempting to select a color hides the pallet and keeps the interface locked out until i press the escape key. this behavior is no different to modal dialog blocking the parent window as all functionality including dragging, closing and all other events are disabled. there is no meaningful pattern to its behavior just that selecting the pallet from bottom left brings up the pallet editor and selecting a color within hides the dialog and keeps the app modal locked. using the escape key has no pattern to when it works or not so at least half the time i am using the kill command to to force the app to end. tabbing through apps to re-select mypaint sometimes works when just pressing the escape key seams to fail but most of the time requires forced kill to get rid of the mypaint window that is locked over all other windows.

steps to reproduce is sudo apt install mypaint. run mypaint and try to choose color.
steps to reproduce. remove package and try snap version... same thing it installs the same deb.

app image fails completely complains about fuse. i installed missing fuse and it now just coredumps. 

i am looking for a paint app that i can use the touch interface for drawing. i found it today and not willing to put in any further effort into it other then letting you know out of the box it fails on a new ubuntu 22.04 install and exhibited by both the apt and snap installed methods.

none of the binary releases work correctly on ubuntu 22.04 due to this issue. seams to work ok on 20.04 but not useful to me since that machine has no touch capability. (and the battery is dead so not portable)

**Comment by odysseywestra** [comment] 2023-05-31 06:29
Probably duplicate of #1161

Could you please check that issue out and close this one if you are having the same issues? That'll help keep this issue tracker a bit organized. Thanks.

**Closed** 2023-05-31 21:06 UTC
Labels: type.bug, solution.Duplicate, platform.Linux.Wayland, cat.UI
