### ISSUE TITLE
1.2.1 beta 0 64 - Windows 10 64 - Broken dockpanels (lots of problems)

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#639] opened 2016-04-05 14:48 UTC
When i'm trying to remove dockpanel from left or right column, icon of the dockpanel moves to left top corner.
![1](https://cloud.githubusercontent.com/assets/13454470/14285744/23f3f1a8-fb66-11e5-9aa0-4ad632ab3acb.jpg)

There are 2 closebuttons, and funny thing that i need to move pointer under that buttons to close dockpanel.
![2](https://cloud.githubusercontent.com/assets/13454470/14285745/23ff9508-fb66-11e5-94c3-d33967549e9e.jpg)

When i'm closing dockpanel, icon on toolbar shows that it not closed.
![3](https://cloud.githubusercontent.com/assets/13454470/14285746/2401d9a8-fb66-11e5-861e-e692b6ad4a73.jpg)

**Comment by achadwick** [comment] 2016-04-09 15:10
> There are 2 closebuttons

One is for the current tab, the other is for the entire window. There should only be a current tab one, but it's not a bug for Windows to choose to display one for the window too.

The rest of this looks like a big pile of upsteam bugs.

**Comment by achadwick** [comment] 2016-04-09 15:12
Hi there - thanks for reporting!

Unfortunately I can't take this report any further because there are too many problems bundled into this single issue. This issue tracker only operates effectively when there's a single problem in each issue thread. Please can you split out each of the following topics, and make a fresh issue report about each one?

* When i'm trying to remove dockpanel from left or right column, icon of the dockpanel moves to left top corner.
* Funny thing that i need to move pointer under that buttons to close dockpanel.
* When i'm closing dockpanel, icon on toolbar shows that it not closed.

Read the [issue reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs) before you split these topics out, and don't forget to search the tracker just in case someone has already reported the problem.

You can mention this original issue as `#639` in your split-out issue reports. However, because we cannot deal with piggybacked issue reports sensibly and in a timely fashion, I am closing this original report.

Thanks for the feedback, and I hope our (somewhat strange) policy isn't too scary. We only ask that topics get split up so that they can be dealt with and closed meaningfully.

**Comment by achadwick** [comment] 2016-04-09 15:12
**TRIAGE NOTE:** piggybacked issue report.
Closed: requested reporter to split out each sub-issue into a new topic.

**Closed by achadwick** 2016-04-09 15:12 UTC
