### ISSUE TITLE
Pythonw2 goes unresponsive 

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#376] opened 2015-07-25 11:21 UTC
I'm using the MyPaint 1.2 beta. I actually think it was linked here on GitHub, so I downloaded it. If not, it probably came from tumagonx's blog. I'm using Windows 8.1 64-bit, and a Yiynova MVP10U screen tablet.

I'm on mobile, so I'll update with my screenshots when I can access internet on my desktop. I was painting using the "bulk" brush from the classic brush set both times this happened.

the first time it happened, I had locked the alpha on the brush to change the color of a sketch. Suddenly stopped working in the middle of a stroke. I closed it, after 5 minutes of unresponsiveness (GIMP has made me very familiar with this problem... I know how it goes.)

2nd time: After I changed my sketch color, I was using the bulk brush again to do some flat color on a new layer. In the middle of my paint stroke (again) it stopped responding. This time I lost a lot of work. (I have autosave turned off because I was afraid an unresponsive error like this might corrupt my file. Again, GIMP horror stories have taught me such.)

**Comment by achadwick** [comment] 2015-07-25 11:38
Hi, thanks for reporting. If GIMP is affected too, it is unlikely that this is a MyPaint problem. Flagging as a user support issue, but expect it to be closed if this issue cannot be reproduced.

Did you check with taskmanager to see whether the process was consuming CPU?

I suggest turning autorecovery saving on if you have errors like this frequently in GIMP and MyPaint. MyPaint's autorecovery saves should be reasonably bombproof on a working system (writes happen in the correct order, so the layers tree is written after any new data files), somewhat less so when the power cuts out (because issues of filesystem consistency).

**Comment by achadwick** [comment] 2015-07-25 11:38
I will need to know the exact version of MyPaint which was affected. Please look in the program's about box and paste the entire string you see there.

**Comment by AtsusaKaneytza** [comment] 2015-07-25 12:17
MyPaint 1.2.0-beta.0+gitexport.adc9031

**Comment by AtsusaKaneytza** [comment] 2015-07-28 15:27
I checked the CPU while I was drawing, and the Memory usually ran at an average of 250-400 MB of memory, if that means anything. (That's a scary high number, and I'm not sure whether or not I should be concerned...)

**Comment by achadwick** [comment] 2015-07-28 15:35
MyPaint consumes lots of memory when it's working on a big image, and Python has quite silly memory management which doesn't help. It's not relevant to this issue, probably.

At the periods when mypaint appeared unresponsive, was it consuming CPU cycles (doing work) or was it completely dead? A good way to tell is to look on the "Processes" tab of Task Manager, and sort by the CPU column.

**Comment by AtsusaKaneytza** [comment] 2015-07-28 15:51
Well, I tried to reproduce the error I had before by drawing an absurdly large image (over 10K Pixels by 12K... Pixels) using the brush I did before. MyPaint ran over 1000MB of CPU. The program started acting fussy after I tried interacting with the window (not responding correctly to my tablet clicks) and when I minimized it, the window wouldn't restore correctly.
But it didn't go unresponsive, based on how MyPaint acted when I ended the task with task manager (it asked me if I wanted to save before I closed it, meaning it was still responsive)

**Comment by achadwick** [comment] 2015-07-31 22:42
What does "not responding correctly to tablet clicks" mean, exactly? Or "the window wouldn't restore correctly"?

Please could you let me know what the **CPU** usage is when this is happening? Sorry to belabour the point, but you are giving me memory counts (Mb). If those are well below the amount of memory on your computer, then it won't be a source of slowness unless you're running a ton of other stuff at the same time.

"CPU usage" is a measure of how much work the [Central Processor](https://en.wikipedia.org/wiki/Central_processing_unit) is doing, it's the one measured in percentages, (%). Lots of that happening while things are laggy might be indicative of something that can be investigated. What you say about save dialogs working seems to disprove that theory though.

I have no idea what's going on here or why it would *just lock up* like that, but I am trying to understand whether this is something that can actually be fixed.

--------------------------

**Triage note:** really need steps to reproduce this one, but it's probably nothing that can be fixed by changing MyPaint. GIMP is affected too, by the sounds of it. Stories about a program going weird are only going to get us so far, so close after a couple of weeks if nothing concrete emerges (sorry! Though the story may be useful to other people searching ☺)

**Comment by AtsusaKaneytza** [comment] 2015-07-31 23:53
-CPU Usage is usually higher than 80% when MyPaint begins slowing down immensely
-"not responding correctly to tablet clicks" meant that at the time, the window would act like its not active. Clicking on the maximize button wouldn't max the window. Hovering over tools wouldn't show tool tips. Clicking on tools wouldn't select the tools. Clicking on the canvas produced no strokes.

- "the window wouldn't restore correctly" meant that clicking on the window in the taskbar caused the window to only display a fraction of its size, even though the window was originally maximized. MyPaint's "restored" area would only take up 1/4th of the screen even though the rest of the window took up the whole screen. I didn't get a chance to screencap it at the time it happened, but it looked like it visually didn't finish rendering correctly (like what happened in the old days when Internet Explorer went unresponsive and if you dragged a window over it, it looked like a slinky)

sorry about the lack of info and screencaps

**Comment by achadwick** [comment] 2016-01-27 11:18
@AtsusaKaneytza Can you tell me whether this is still happening with v1.2.0? Thanks.

**Comment by AtsusaKaneytza** [comment] 2016-01-27 15:09
Nope, it hasn't been a problem anymore

**Comment by achadwick** [comment] 2016-01-27 15:22
Okay - thanks for the update ☺

**Closed by achadwick** 2016-01-27 15:22 UTC
Labels: performance, request-for-help
