### ISSUE TITLE
Windows: crash after opening brushes panel twice.

### ISSUE THREAD

**Issue by journey-of-code** [mypaint/mypaint#679] opened 2016-05-11 13:12 UTC
#### Description of the problem

Application crashes.
#### Basic system details

MyPaint version: 1.2.1-beta.1+gitexport.3198e3f
Operating system:  Windows 7, 64 bit
Desktop environment: Standard Windows
Intel Core i7-4712HQ, 16GB RAM.
Wacom Intuos 4, A4
#### Steps to reproduce
1. Open MyPaint.
2. Open favorites from menu icon.
   ![screenshot 040 mypaint](https://cloud.githubusercontent.com/assets/1939047/15181811/7583ba14-1789-11e6-87cd-d292441cffb9.png)
3. Opens in sidebar.
   ![screenshot 041 mypaint](https://cloud.githubusercontent.com/assets/1939047/15181856/baff0904-1789-11e6-80d8-f398a2a1e7db.png)
4. Break out favorites to floating window.
   ![screenshot 042 mypaint](https://cloud.githubusercontent.com/assets/1939047/15181886/d9c2bf52-1789-11e6-9b0b-62489a7343c5.png)
5. Close floating window.
6. Open favorites from menu icon.
   ![screenshot 040 mypaint](https://cloud.githubusercontent.com/assets/1939047/15181811/7583ba14-1789-11e6-87cd-d292441cffb9.png)
7. Observed crash.
   ![screenshot 043 python2w exe](https://cloud.githubusercontent.com/assets/1939047/15181909/04acd022-178a-11e6-935d-470ccd76f69e.png)
#### Additional notes

I'm experiencing a misplacement of the cursor on floating windows see my comment on [issue 569](https://github.com/mypaint/mypaint/issues/569).
Even when taking into account the misplacement of the cursor in the floating window, after step 5 I'm not able to put back the brush list to the sidebar.
Happens for all other brush lists as well.
I cannot prevent the break out in step 4 - as soon as I select a brush in the list, the brushes will break out into a floating window.

**Comment by achadwick** [comment] 2016-05-11 14:32
> as soon as I select a brush in the list, the brushes will break out into a floating window.

This will be fixed in the next beta, or the final release. It's #643.

**Comment by achadwick** [comment] 2016-05-11 14:36
Thanks for the main report! Nice and clear.

I thought I had seen this myself, but I was having difficulty working out the steps. As far as I can tell, it's Windows-specific, and may be tied to the specific GTK that beta's bundled with.

My time is a bit limited at the moment, but any backtraces from `gdb` would be very welcome.

**Comment by zb13y** [comment] 2016-05-11 15:10
Same as #640 ? If you close the dockpanel with lower closebutton you will not get crash?

**Comment by achadwick** [comment] 2016-05-11 15:12
You might have to be a bit careful about which X you click, that's true. There are sometimes offset issues.

**Comment by journey-of-code** [comment] 2016-05-11 15:21
Indeed it matters which button I press.
![screenshot 045 favorites](https://cloud.githubusercontent.com/assets/1939047/15186180/575175c8-179c-11e6-9942-47f745dfdc10.png)
Pressing close button `A` leads to the crash.
Pressing close button `B` does what it should.
Need anything else?

By the way - I think MyPaint 1.2 is a huge step forward and I love the new GUI.

**Comment by achadwick** [comment] 2016-05-11 15:33
@journey-of-code Sounds like your click is hitting the target, but can you confirm? There should be a little animation on both (? certainly the bottom) X buttons when you hover the pointer over them. The B one should get a box drawn around it, and its tooltip sould refer to closing the tab. Do you get that?

It's worth noting that the **A** close button isn't there in GNOME or (IIRC) Xfce under Linux, so That's How It Was Written. Perhaps more window construction flags could be thrown at it to cope with Windows better. The construction code is in [gui/workspace.py](https://github.com/mypaint/mypaint/blob/996a33e14b6bc20cd2ac6af8e1d821f01e1ce697/gui/workspace.py#L1834).

The proper solution is almost certainly to handle the close/destroy event and tidy up cleanly though. We can't guarantee that utility windows will have the same buttons on all platforms.

**Comment by journey-of-code** [comment] 2016-05-11 15:42
After I figured out the offset in the floating windows, I can click on the button I intend to.
Another indication is the icon animation when the (real) cursor hovers above the button.
I can confirm that this is there. There appears to be no animation for button `A`.
If the close button `A` is not present in GNOME/Xfce, I can see why it crashes.
Under Windows it seems to destroy the window so cleaning up after the event sounds like a good idea.

**Comment by achadwick** [comment] 2016-12-05 23:36
The offsets in popped-out utility windows are still present in Windows GTK 3.22.4 on MSYS2, and even exist for utility windows where the decorations are turned off (!).

Segfault still reproducible. Let's try to fix that, at least...

**Comment by achadwick** [comment] 2016-12-05 23:57
Okay, explicitly turning off the close button is a good first step. These little stack windows have other close "X"es, and using all of them should cause the window to be closed reliably.

These window decorations are provided by GTK itself on Windows, and are quite buggy. For example, resizing them is far harder than on GNOME-on-Xorg due to the offset, and when you do manage to grab a window edge, resizing makes the subwindow a truncated mess:

![truncated mess](https://cloud.githubusercontent.com/assets/61299/20907487/6b9cf180-bb46-11e6-8bb8-2efe38530ee0.png)

So perhaps snapping windows out should be disabled on Windows until upstream gets into a sensible state.

Having snapped-out subwindows means you have to position them, which is increasingly not supported by Xorg/Xwayland. I'm beginning to think that disabling this feature globally makes sense now :neutral_face:

**Closed** 2016-12-06 00:40 UTC
Labels: bug, crasher, windows

**Comment by achadwick** [comment] 2016-12-06 00:44
Sorry about dropping support for snapped-out windows on Win32 for 1.2.1, but given how shocking the user interface glitches are for this feature on that platform, we simply cannot release with it in this state.

If someone comes up with a bright idea for reinstating it, please propose it as a PR against master.
