### ISSUE TITLE
Can we please get a x64 build for Win?

### ISSUE THREAD

**Issue by gerroon** [mypaint/mypaint#748] opened 2016-12-04 21:38 UTC
Hi

Can we please get a x64 build for Windows? The last one is 9 months old and the most recent version was pulled out of releases due to signature issues.

I am using 64 bit version of wintab and I would like to try it with that version.

thanks

**Comment by achadwick** [comment] 2016-12-04 23:18
Duplicate of #578. Expect this to be fixed when 1.2.1 is released, no sooner.

**Closed by achadwick** 2016-12-04 23:18 UTC
Labels: duplicate

**Comment by achadwick** [comment] 2017-01-21 22:44
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now out, and contains a w64 installer and an experimental standalone bundle containing the same files.

**Comment by gerroon** [comment] 2017-01-22 02:24
yaayyyyy thanx man
