### ISSUE TITLE
HSL Saturation Modelling - Wet Brushes and around

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#256] opened 2015-03-12 18:44 UTC
I'm working on the wet brushes set. They are very interesting to use but I am not capable to resolve the relationship between with the grey values and HSL saturation instances... always the greys are changing the Hue... they appear redish... Perhaps is not possible to do it.
With other colors works fine my problem is only to modelling de grey tones.
In this model I'm using basically the Opacity  and Color HSL saturation.
Some suggestion?
http://pastebin.com/Y7wJjY84 (brush)

**Comment by iirelu** [comment] 2015-03-12 22:06
Screenshots of what it looks like?

**Comment by americogobbo** [comment] 2015-03-12 22:15
![weting-proofs-grey-problem](https://cloud.githubusercontent.com/assets/8180638/6629365/26a5e512-c8ec-11e4-9125-807037f7b3df.jpg)

**Comment by 0ion9** [comment] 2015-03-13 03:53
@americogobbo : 

"The problem is only with the greys... white works well."

That sounds like a bug. The problem should also occur with white and black. It's a problem that is inherent in the HSL model: A color with no saturation (ie. a pure grey) has no real hue, so an arbitrary hue value (usually 0, which is red) is used.

AFAICS the only way of avoiding this is to use a colorspace which does not have a single 'hue' term : For example YCbCr and Lab encode the information that creates the appearance of hue in two separate channels. I'm not sure how much value this would have (but I do agree that greyscales are currently problematic for any brush that wants to do hue alterations)

**Comment by americogobbo** [comment] 2015-03-13 12:40
Ok, I understood. Can I help to clarify this problem with some task?

**Comment by achadwick** [comment] 2015-03-13 12:43
I see it now. Affects "Change color satur. (HSV)" and "Change color satur. (HSL)".

This is a brush engine issue I guess. Closed in favour of mypaint/libmypaint#15.

**Closed by achadwick** 2015-03-13 12:43 UTC
