### ISSUE TITLE
Absolute Brush Size support

### ISSUE THREAD

**Issue by crydalch** [mypaint/mypaint#318] opened 2015-05-16 23:48 UTC
A feature from Mischief that I've found useful is constant brush sizes. When I zoom in/out of my Canvas, the brush size stays the same on screen, though (in the case of zooming out) that brush is now much larger relative to the canvas.

Does that make sense? Would it involve some pretty heavy changes internally?

Thanks!

**Comment by 0ion9** [comment] 2015-05-17 00:27
Duplicate of #289 , as far as I can see. Closing, please comment if there is some subtlety I'm missing.

**Closed by 0ion9** 2015-05-17 00:27 UTC

**Comment by crydalch** [comment] 2015-05-17 03:06
Ah not sure how I missed that! Thanks!
