### ISSUE TITLE
[KDE/kwin?] Only straight lines are drawn when not fullscreen

### ISSUE THREAD

**Issue by houz** [mypaint/mypaint#158] opened 2014-12-28 15:31 UTC
Since a while I can only draw straight lines unless going into fullscreen mode. I am not completely sure when this started but I know that I first mentioned it on IRC in April 2014. While everything is fine and dandy when running fullscreen, as soon as I have mypaint in a window freehand drawing behaves like this:
* press the mouse button on the canvas
* nothing happens
* move the mouse
* still nothing
* release the mouse
* a straight line from where I clicked to where I released is drawn

1.1.0 is working, this is only with git compiles. I am using Debian/Sid, KDE, an Intel GPU and the input pointer in my test was the Trackpoint (but IIRC the same happened with a Wacom tablet or a mouse).

**Comment by achadwick** [comment] 2015-01-01 20:35
Bisecting after and before the brushlib split is tricky! The main body of the bisection workflow becomes something like

```
$ scons
# ... test ...
$ scons  --clean ; rm -fr brushlib   # nuke that submodule
$ git bisect {bad|good}   # checks out something else
$ git submodule update --init --force   # grab the submodule at this mypaint revision
# ... and repeat...
```

Hope that helps... ☺

I've seen various interesting breakages in GNOME too, but only when fullscreen _is_ in operation (the idiotic thing comes to decide that a click on the window is a click on the backdrop...). Go figure.

Here we may want to try playing around with event masks, and checking that they're being set correctly after un-fullscreening. @houz: does your bug happen a) when mypaint is started initially in fullscreen, or b) only after leaving fullscreen mode?

**Comment by hetdegon** [comment] 2015-01-03 03:32
I have the same problem as well. Pressing F11 will cause normal behavior, but when it's windowed it'll just refuse to do anything but straight lines. I have been building from git for a long time, but due to work and other circumstances I've been neglecting it since summer, where it still worked properly. 

The straight lines in question aren't that thing where making a curve ends up looking like a low-poly object, but it just traces a line from the point where you start holding the draw button to the point where you release the button, even if you dragged the cursor all over the screen for a minute. There's no update at all until the button is released.

I am using Linux (64bit, Ubuntu 14.11), KDE4 with a Wacom Bamboo One tablet, which always worked fine with Mypaint. Note that drawing with mouse also causes this issue, so it doesn't seem related to tablet model.
Of course, my local clone is cleaned and submodule is automatically updated from my build script, so there's no chance of it being some past residue causing problems. I also tried removing my Mypaint configs but that didn't seem to affect anything.

I don't have many solutions other than going back to latest officially released package and hoping for the best. But since this bug was already reported I thought I'd chime in with my experience with it.
Let me know if you need any info that might help debug the issue.

**Comment by houz** [comment] 2015-01-03 12:48
When starting with `--fullscreen` it works (while in fullscreen mode).
I will try to bisect later.

**Comment by houz** [comment] 2015-01-03 15:57
Ok, done bisecting, the bad commit seems to be

```
commit d9994edcdb2f7153e0503f97d25ebfde1ad5063c
Author: Martin Renold <martinxyz@gmx.ch>
Date:   Mon Nov 11 20:05:56 2013 +0100

    eventhack: use new gtk+ API instead if available
    
    The latest git version of gtk+ has set_event_compression(), which is a
    much cleaner solution.
    
    https://bugzilla.gnome.org/show_bug.cgi?id=702392
```

**Comment by iirelu** [comment] 2015-01-03 18:12
Thanks for narrowing it down this far! Out of curiosity, what does Mypaint say when running on that specific commit?

**Comment by houz** [comment] 2015-01-03 21:35
```
$ git describe 
v1.1.0-420-gd9994ed
$ rm -rf ~/.mypaint/
$ ./mypaint 
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/flat_bar_l" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/inkster_l" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/extreme_round_l" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/ink_slow_s" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/ink-slowline_s" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/smudge_ink(0.7)_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/paint_radius_2_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/Smear_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/paint_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/paint_barrr_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/wet_paint_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/Dirty_Transparent_sk" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/classic_sk" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/airsmudgeultimate_sk" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/Sketcher2_sk" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/airsmudge_a" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/airbruch_press_a" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/Airbrush_a" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/classicroundblock_static_c" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/fill_c" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/flat_bar_l" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/inkster_l" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/extreme_round_l" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/ink_slow_s" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/ink-slowline_s" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/smudge_ink(0.7)_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/paint_radius_2_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/Smear_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/paint_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/paint_barrr_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/wet_paint_sm" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/Dirty_Transparent_sk" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/classic_sk" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/airsmudgeultimate_sk" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/Sketcher2_sk" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/airsmudge_a" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/airbruch_press_a" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/Airbrush_a" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/classicroundblock_static_c" not found',) (removed from group)
WARNING: gui.brushmanager: IOError(u'brush "kaerhon_v1/fill_c" not found',) (removed from group)
INFO: gui.brushmanager: Merging upstream brush changes into your collection.
WARNING: gui.workspace: Empty tab group in workspace, not added
WARNING: gui.workspace: Empty tab group in workspace, not added
INFO: lib.document: load_ora: u'/home/houz/.local/share/mypaint/scratchpads/autosave.ora'
INFO: lib.document: 0.018s load_ora total
INFO: gui.filehandling: Loaded scratchpad from u'/home/houz/.local/share/mypaint/scratchpads/autosave.ora'
INFO: gui.application: Looking for GTK devices with pressure
WARNING: gui.application: No pressure sensitive devices found.
INFO: gui.freehand: evhack: using set_event_compression(True) instead of evhack
```

**Comment by houz** [comment] 2015-01-03 21:38
Citing from the Gdk docs:
```
Some types of applications, e.g. paint programs, need to see all motion events and will benefit from turning off event compression.
```
I wonder why this works for anyone.

**Comment by 0ion9** [comment] 2015-01-03 22:45
.. Because pressure sensitive devices are detected in their system, and thus set_event_compression(False) is called instead?

**Comment by houz** [comment] 2015-01-03 23:42
Some more data points: When enabling debug logging I can see this:
Starting in window mode:
```
DEBUG: gui.freehand: Add motion event compression workaround: using set_event_compression(False) (<TiledDrawWidget object at 0x7fdb166896e0 (TiledDrawWidget at 0x2253880)>) (was True)
```
Pressing F11:
```
DEBUG: gui.freehand: Remove motion event compression workaround: restoring event_compression to True (<TiledDrawWidget object at 0x7fdb166896e0 (TiledDrawWidget at 0x2253880)>)
```
Moving the mouse:
```
DEBUG: gui.freehand: Add motion event compression workaround: using set_event_compression(False) (<TiledDrawWidget object at 0x7fdb166896e0 (TiledDrawWidget at 0x2253880)>) (was True)
```
This looks the same with a mouse and with a Wacom tablet. I have no idea if that is telling anything.

**Comment by achadwick** [comment] 2015-01-04 20:53
You mentioned fullscreen as a workaround. Is the bug still as described before and after f42f7437b74aecd9375cb5946a49eadb37ec1953 ?

If so, check out master again, and try windowed mode, but then pressing Escape when you encounter the bug. Does this fix things temporarily too?

(You'll only see DEBUG messages in modern MyPaint if `MYPAINT_DEBUG` is set in your environment when launching. Beware, it's noisy!)

**Comment by houz** [comment] 2015-01-05 00:55
When pressing Escape while drawing (i.e., click, move mouse, hit Escape, move more, release) then I can see correct strokes from the point where I pressed Escape. The part from the initial click to the Escape point is a straight line. This is with `v1.1.0-835-g6947ad9`.

**Comment by hetdegon** [comment] 2015-02-12 06:33
Just a little thing on this bug. I have built mypaint today to see if it was working again (unfortunately, it doesn't), and I noticed that this also happens in the color selector, dragging in general is not working unless pressing escape while holding down the button. Just in case that helps anything.

**Comment by achadwick** [comment] 2015-02-12 12:32
If you turn *both* of the event compression workarounds off:

```
# Which workarounds to allow for motion event compression
EVCOMPRESSION_WORKAROUND_ALLOW_DISABLE_VIA_API = True
EVCOMPRESSION_WORKAROUND_ALLOW_EVHACK_FILTER = True
```
-- they're near the top of `gui/freehand.py` as of 2c96580e3dffcdd2a68a551518c8c93fd5c1aefa

does this problem disappear?

You're likely to get very un-smooth lines, but GTK should at least give you the motion events between pen down and pen up.

But then it should do that anyway.

**Comment by achadwick** [comment] 2015-02-12 12:39
Also, try the old evhack filter alone. The code is still there, and we still need it while we support GTK 3.10 (now #16 is decided).

---------------------------

Problem may be KDE-specific based on the report alone. Anyone able to reproduce this in GNOME/Xfce/other?
@houz @hetdegon if you have an alternative DE installed, could you try the unmodified master in that too? Would be informative, thanks.

Maybe there are some oddball event mask requirements for the KDE window manager. But I'm guessing.

**Comment by hetdegon** [comment] 2015-02-12 21:46
I tested it as instructed on the other DE I had quickly available, Unity, and it does work there, so I guess this bug can be narrowed down to some KDE/Kwin quirk.

However, If I set 
>EVCOMPRESSION_WORKAROUND_ALLOW_DISABLE_VIA_API = False

it works again as expected! And the lines don't seem any worse than before. I'll take this as a temporary workaround until something can be figured out. If there's anything I can do to help debug the issue, please let me know.

**Comment by achadwick** [comment] 2015-04-22 02:40
FWIW, I can't reproduce this with a fresh Linux Mint 17.1 LTS, KDE Edition in a VM. That's admittedly not the same system as the OP at all though...

Bumping to the next alpha cycle to remind us to have a proper look at it. I've an old machine with Intel hardware I can dump sid onto, just a matter of getting round to it.

@houz In the meantime, can you let us know what theme you're using, and what version of GTK3? And whether it's still happening, of course.

**Comment by houz** [comment] 2015-04-22 13:58
I am using GTK3 3.14, and my GTK theme is the oxygen one. Actually that was a great hint, setting it to something else like clearlooks everything works.

**Comment by achadwick** [comment] 2015-04-22 15:06
Another good reason to avoid the oxygen-gtk theme, maybe? Just seen @Griatch 's comments in #299.

I want to confirm that the oxygen-gtk theme is off by default in highly KDE-centric environments like Mint 17.1 KDE and Ubuntu <whatever that old machine of mine is> with KDE bodged on as a second DE. But this sure looks like an upstream issue with a specific old (?) theme.

**Comment by achadwick** [comment] 2015-07-05 13:27
Okay, my mistake. oxygen-gtk is the default GTK theme in Mint 17.1. Still haven't been able to reproduce this one yet though.

I'm going to bounce this one on to the beta cycle, since I doubt there's very much we can do about the issue, and there's a workaround already.

**Comment by achadwick** [comment] 2015-10-11 22:49
@houz Can you confirm whether this is still happening with the latest Debian sid KDE? GTK is up around 3.18.1 now on that system :smile:

**Comment by houz** [comment] 2015-10-12 08:39
With the oxygen theme engine it still misbehaves, but since it works with all the other gtk engines this is most likely not a problem of mypaint. And it seems that gtk3-engines-oxygen isn't in Debian any longer.

**Comment by achadwick** [comment] 2015-10-12 09:22
Okay, that's two workarounds! It does sound as though the Oxygen GTK engine was breaking things and not anything (wrong) we're doing. Thanks for testing; closing as an upstream bug, solution is to fix or remove the obsolete/broken Oxygen GTK engine if anyone is bitten by this bug.

**Closed by achadwick** 2015-10-12 09:22 UTC
Labels: bug, upstream
