### ISSUE TITLE
No cursor when using Wacom Bamboo

### ISSUE THREAD

**Issue by notklaatu** [mypaint/mypaint#1166] opened 2021-12-04 01:57 UTC
#### Description of the problem

I can't see my brush when I paint with a Wacom tablet.  I can see what I've painted, I just can't see the cursor, so I rarely know exactly where I'm about to paint.

When I use my mouse or trackpad to draw in Mypaint, I can see the outlined shape of the brush.

For example, the round outline in this screenshot:

![Screenshot from 2021-12-04 14-45-30](https://user-images.githubusercontent.com/2211671/144692485-b647ae09-02b9-4c1c-bf1a-e3f558af8ac3.png)

I do not see this when using my Wacom tablet.

For comparison purposes, I *do* see my cursor when using my Wacom tablet when using Mypaint brushes in GIMP, and also when using Krita.

#### Basic system details

MyPaint version:  2.0.1
Operating system: CentOS Stream 8
Desktop environment: GNOME

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. Select any brush.
3. Using a mouse, paint on the canvas. 
4. Using a Wacom tablet, paint on the canvas (if you can manage to figure out where the canvas is without seeing your cursor).

#### Backtraces or error messages

I'm happy to paste in logs, but I don't know where they're located.

**Comment by AesaraB** [comment] 2024-01-17 13:06
Duplicate of #753

**Closed by AesaraB** 2024-01-17 13:06 UTC
Labels: type.Bug, solution.Duplicate, cat.Input.Pointer, platform.Linux, cat.UI
