### ISSUE TITLE
Dell active stylus not working (pressure=0) 

### ISSUE THREAD

**Issue by tihoulas** [mypaint/mypaint#734] opened 2016-09-11 11:34 UTC
Computer : HP Spectre x360 4158nf
Xinput report :
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ ELAN Touchscreen Pen                      id=10   [slave  pointer  (2)]
⎜   ↳ ELAN Touchscreen                          id=11   [slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=13   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
    ↳ Power Button                              id=8    [slave  keyboard (3)]
    ↳ HP Truevision Full HD                     id=9    [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=12   [slave  keyboard (3)]
    ↳ HP WMI hotkeys                            id=14   [slave  keyboard (3)]
    ↳ HP Wireless hotkeys                       id=15   [slave  keyboard (3)]

MyPaint version: 1.2.0+gitexport.f62444e
Operating system: ubuntu yakkety yak pre-release
Desktop environment: plasma 5.7

I am trying to use my computer as a drawing tablet. It uses an Elan Touchscreen Pen compatible with the Dell 750-AAHC pen.

The pen is recognized by evtest and mapped to event 14. While evtest gives out a pressure between 0 and 255, mypaint always reports a pressure value of 0. Hence no drawing appears.

Please find attached logs from evtest, xinput test and mypaint input debugs.

[logs.zip](https://github.com/mypaint/mypaint/files/465929/logs.zip)

**Comment by achadwick** [comment] 2016-09-11 11:53
What about **gtk3-demo** (use the *Event Axes* or *Touch and Drawing Tablets* demo)? Pressure should be registered as blobs of colour there.

![image](https://cloud.githubusercontent.com/assets/61299/18417086/9491ec50-781e-11e6-884a-eec501a34aaa.png)

It would be informative to know whether GTK3 generally can handle pressure from this device.

**Comment by achadwick** [comment] 2016-09-11 11:58
Somehow your events are not coming through to Xorg though, according to your xinput log (it should show an `a[2]` for pressure, I think).

I assume that your device does not work in GIMP either - please can you conform that too, @tihoulas ?

**Comment by achadwick** [comment] 2016-09-11 12:11
Xorg should have identified which driver it's using for the tablet. Look for lines like the following in your system logs or in Xorg's log if it still does that.

```
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (II) Using input driver 'evdev' for 'Genius EasyPen i405X'
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) Genius EasyPen i405X: always reports core events
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) evdev: Genius EasyPen i405X: Device: "/dev/input/event13"
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (--) evdev: Genius EasyPen i405X: Vendor 0x458 Product 0x5010
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (--) evdev: Genius EasyPen i405X: Found absolute axes
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (--) evdev: Genius EasyPen i405X: Found x and y absolute axes
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (--) evdev: Genius EasyPen i405X: Found absolute tablet.
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (II) evdev: Genius EasyPen i405X: Configuring as tablet
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) evdev: Genius EasyPen i405X: YAxisMapping: buttons 4 and 5
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) evdev: Genius EasyPen i405X: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/0003:0458:5010.0005/input/input21/event13"
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (II) XINPUT: Adding extended input device "Genius EasyPen i405X" (type: TABLET, id 15)
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (II) evdev: Genius EasyPen i405X: initialized for absolute axes.
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) Genius EasyPen i405X: (accel) keeping acceleration scheme 1
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) Genius EasyPen i405X: (accel) acceleration profile 0
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) Genius EasyPen i405X: (accel) acceleration factor: 2.000
Sep 11 13:00:54 spatula /usr/lib/gdm3/gdm-x-session[14214]: (**) Genius EasyPen i405X: (accel) acceleration threshold: 4
```

The one above, BTW, also doesn't do pressure. Pressure always comes through as zero on this tablet because evdev is Horrid and Broken™. Follow #732 while we try to come up with a system for dealing with *that* scenario.

**Comment by achadwick** [comment] 2016-09-11 12:16
It's the "Using input driver" line that's relevant, and sometimes anything about number of identified axes or device type.

Other drivers that do work (for me) (on Debian-testing GNOME right now): libinput for some Huion things

```
Sep 11 13:07:12 spatula /usr/lib/gdm3/gdm-x-session[14214]: (II) Using input driver 'libinput' for 'HUION PenTablet Pen'
```

```
Sep 11 13:14:38 spatula /usr/lib/gdm3/gdm-x-session[14214]: (II) Using input driver 'wacom' for 'Wacom Intuos5 touch M Pen'
```

**Comment by achadwick** [comment] 2016-09-11 12:21
Possible dup of #732 given the (apparent) absence of pressure at a low level.

@tihoulas to recap:
* Please confirm that no pressure is present in gtk3-demo (one of the two testers mentioned above)
* Please confirm that no pressure is present in GIMP
* Figure out what driver is forming the glue between your (working) kernel stuff and your (broken) graphical environment.

**Comment by achadwick** [comment] 2016-09-11 12:25
I think the Genius I tried is broken in the same way - `xinput test` does not present any `a[2]` values during operation, despite `xinput test-xi2` listing a pressure axis in its header. Kinda, what's an art program to do if a tablet says it does but can't? :confounded:

**Comment by tihoulas** [comment] 2016-09-11 13:47
So, it is not a mypaint bug. Mypaint is a wonderfull program, X11/xinput is still a mess.

I can confirm that:
 - I cannot draw anything with gimp, nor krita,
 - GTKDemo doesn't read any pressure at all.

Here is the Xorg log extract regarding the Elan pen :

[     5.497] (II) config/udev: Adding input device ELAN Touchscreen Pen (/dev/input/event9)
[     5.497] (**) ELAN Touchscreen Pen: Applying InputClass "evdev tablet catchall"
[     5.497] (II) Using input driver 'evdev' for 'ELAN Touchscreen Pen'
[     5.497] (**) ELAN Touchscreen Pen: always reports core events
[     5.497] (**) evdev: ELAN Touchscreen Pen: Device: "/dev/input/event9"
[     5.497] (--) evdev: ELAN Touchscreen Pen: Vendor 0x4f3 Product 0x2072
[     5.497] (--) evdev: ELAN Touchscreen Pen: Found 1 mouse buttons
[     5.497] (--) evdev: ELAN Touchscreen Pen: Found absolute axes
[     5.497] (--) evdev: ELAN Touchscreen Pen: Found x and y absolute axes
[     5.497] (--) evdev: ELAN Touchscreen Pen: Found absolute tablet.
[     5.497] (II) evdev: ELAN Touchscreen Pen: Configuring as tablet
[     5.497] (**) evdev: ELAN Touchscreen Pen: YAxisMapping: buttons 4 and 5
[     5.497] (**) evdev: ELAN Touchscreen Pen: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[     5.497] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/0003:04F3:2072.0007/input/input10/event9"
[     5.497] (II) XINPUT: Adding extended input device "ELAN Touchscreen Pen" (type: TABLET, id 10)
[     5.497] (II) evdev: ELAN Touchscreen Pen: initialized for absolute axes.
[     5.497] (**) ELAN Touchscreen Pen: (accel) keeping acceleration scheme 1
[     5.497] (**) ELAN Touchscreen Pen: (accel) acceleration profile 0
[     5.497] (**) ELAN Touchscreen Pen: (accel) acceleration factor: 2.000
[     5.497] (**) ELAN Touchscreen Pen: (accel) acceleration threshold: 4
[     5.498] (II) config/udev: Adding input device ELAN Touchscreen Pen (/dev/input/mouse1)
[     5.498] (II) No input driver specified, ignoring this device.
[     5.498] (II) This device may have been added with another device file.

**Comment by tihoulas** [comment] 2016-09-12 08:02
Some news on this. After gogoling a lot about evdev <-> xinput problems, I found a bug about Genius tablets pressure not working in xinput. This patch is supposed to solve this :

https://patchwork.freedesktop.org/patch/86593/

I wille try that as soon as possible and report back. If this works, everything should go back to normal in a few system updates.

**Comment by achadwick** [comment] 2016-09-12 09:27
Please use Github's "code fencing" feature for log output or code. Like this:

    ```
    log lines
    go here
    ```

If you don't, github sometimes tries to be too smart about references to other bugs, and will make an association when it shouldn't. The result's a bit more readable too.

More information here: <https://guides.github.com/features/mastering-markdown/#examples> (under "Code")

**Comment by achadwick** [comment] 2016-09-12 09:47
**Triage note:** affects only evdev devices, patch exists upstream, awaiting confirmation of fix.

Upstream: https://bugs.freedesktop.org/show_bug.cgi?id=95315 (maybe)
Upstream patch: https://patchwork.freedesktop.org/patch/86593/

Possibly fixed upstream in: xserver-xorg-input-evdev (Debian) xf86-input-evdev (Arch) version 2.10.3. Track changes here: <https://cgit.freedesktop.org/xorg/driver/xf86-input-evdev/log/>.

-------------

@tihoulas 
Well, evdev seems to be the source of a lot of worries. My hopes are fairly high for libinput, and the Wacom drivers have been pretty solid.

Could be a lot worse. The Windows equivalent is still a crawling horror-API from the 16 bit era presented by terrible proprietary hardware drivers.

**Comment by achadwick** [comment] 2016-09-12 09:55
Pretty certain to be a duplicate of #732. Closing in favour of that bug, which is covering potential workarounds we could do in the MyPaint code.

**Closed by achadwick** 2016-09-12 09:55 UTC
Labels: duplicate, upstream
