### ISSUE TITLE
XP-PEN 8060C Pen/Tablet: Jitter and lag, v1.2.0

### ISSUE THREAD

**Issue by DrawMeister123** [mypaint/mypaint#584] opened 2016-01-31 04:24 UTC
Screenshot of example of how the pen looks when it eventually appears

![screenshot of pen jitter](https://cloud.githubusercontent.com/assets/16974376/12700219/e417df60-c7e2-11e5-9762-1bced334be28.jpg)

Using Win 7 Ultimate with latest version of MYPAINT. Tablet is XP-PEN 8060C

The pointer also flickers constantly while using the pen, but does not with the mouse. Weirdly the pen works absolutely fine on the scratch pad. 

Zooming out to 100% does not change the behaviour. 

Split off from: 
#582

**Comment by odysseywestra** [comment] 2016-01-31 10:09
This looks like a duplicate of #390.

**Comment by achadwick** [comment] 2016-01-31 16:31
@odysseywestra 
Maybe a dup of #177 instead? Though the jags only go downwards in that one.

This doesn't seem lag-related.

**Comment by achadwick** [comment] 2016-01-31 16:31
@DrawMeister123 
Is your canvas view rotated at all in the picture above?

**Comment by DrawMeister123** [comment] 2016-02-01 04:21
Nope not rotated - opened at 25% zoom (to overcome the minuscule picture issue) - mouse, as I said, works fine, the pen not so much. There is a REALLLY long delay between the brush stroke and it appearing on the screen. Like you can go make a cup of tea long. And when it does it is all wonky as shown. 

Can I correct my statement that it is OK in the scratchpad - it is now not OK - in the scratch pad it has now decided to make random jagged lines downwards only.

**Comment by DrawMeister123** [comment] 2016-02-01 13:42
Just to say that I have reverted to 1.1 which works. Every heard the expression - if ain't broke don't fix it! This applies to windows in the extreme. Tried to see if there was an updated driver for my tablet. Thought I found one. Ended up with a black screen. Had to open in safe mode, uninstall the driver, reboot. Reinstall tablet driver that I know does work. Reboot. In the process decided old but working Mypaint better than no Mypaint.

**Comment by tumagonx** [comment] 2016-02-01 13:57
version 1.1? which exact mypaint is that?
If that's from me, it also use gtk 3.14 the same as mypaint 1.2. But
judging from your screenshot it most likely driver incompatibility
with gdk.

On 2/1/16, DrawMeister123 <notifications@github.com> wrote:
> Just to say that I have reverted to 1.1 which works. Every heard the
> expression - if ain't broke don't fix it! This applies to windows in the
> extreme. Tried to see if there was an updated driver for my tablet. Thought
> I found one. Ended up with a black screen. Had to open in safe mode,
> uninstall the driver, reboot. Reinstall tablet driver that I know does work.
> Reboot. In the process decided old but working Mypaint better than no
> Mypaint.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/584#issuecomment-177976654


-- 
!tuma

**Comment by DrawMeister123** [comment] 2016-02-02 05:19
mypaint-1.0.0-win32-installer.exe is the file name and I downloaded it in July last year.

**Comment by DrawMeister123** [comment] 2016-02-02 05:23
Well if it is driver incompatibility I have a problem. There is no updated driver for my tablet (last release 2009). The release "dated" 2013 on the website is in fact still the same 2009 version I have on disk. There may be some difference I can't see but my computer did NOT like the 'new' downloaded version hence the need to revert.

**Comment by achadwick** [comment] 2016-02-02 12:06
Retitled to help other users with this tablet model find this issue :smiley: 

MyPaint 1.0.0 far too old for us to support. Sorry the new one isn't working out for you either :disappointed: 

There have been way too many tablet regressions in GDK-land since GTK2, on Windows. All I can say is this it works OK with a Wacom tablet (but no tilt), and only a little glitchily with a Huion tablet (which doesn't have hardware tilt sensors). I'm using Win7 Pro on one test VM, and Ultimate on my real-hardware "slow machine" testbed. But I'm limited by the hardware I can actually test on.

(The situation's a little nicer under Linux, but there are weird glitches regressions even there. Tablet compatibility issues are the bane of developing for MyPaint. I can only hope that with GIMP joining us in GTK3-land, we'll get more eyes on these upstream bugs.)

**Comment by DrawMeister123** [comment] 2016-02-02 17:35
@achadwick it works absolutely fine with 1.0.0 which is why I reverted to it. It is 1.2 that does not work and which I have discarded because it does not work.

**Comment by tumagonx** [comment] 2016-02-02 18:10
Sorry earlier you did say version 1.1 which you actually refer to
version 1.0. Because here is no official mypaint 1.1 release for
Windows.

On 2/2/16, DrawMeister123 <notifications@github.com> wrote:
> Well if it is driver incompatibility I have a problem. There is no updated
> driver for my tablet (last release 2009). The release "dated" 2013 on the
> website is in fact still the same 2009 version I have on disk. There may be
> some difference I can't see but my computer did NOT like the 'new'
> downloaded version hence the need to revert.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/584#issuecomment-178382818


-- 
!tuma

**Comment by DrawMeister123** [comment] 2016-02-10 04:54
Seriously? I made a mistake with the flipping not-logical numbering of releases does it actually matter? The point is - unresolved problem with latest version. Gave up 'cos no help and no solutions. Useless to me if tablet doesn't work so reverted to earlier version which does work. Problem solved.

**Comment by odysseywestra** [comment] 2016-02-10 05:19
Actually it dose matter since there had been a lot of changes between those three versions.

I understand your frustration with this. It's sad that you had to use an older version to get your Tablet to draw on it. The one way you can help solve this bug is provide the information that we need to report this upstream since it's sounding like a GDK/GTK issue.

@achadwick what information dose he needs to provide?

**Comment by achadwick** [comment] 2016-02-10 11:57
### Closing as an upstream issue

This issue almost certainly relates to a bug in an upstream software component, namely GTK's Windows backend. It should be reported upstream at the GNOME bug tracker by somebody who owns this hardware and is willing to do a little digging on behalf of the GTK maintainers.

### How to report this problem upstream

> :point_right: **[The GNOME bug tracker](https://bugzilla.gnome.org/)**

I suggest you start with a search like ["XP-PEN"](https://bugzilla.gnome.org/buglist.cgi?bug_status=__open__&content=%22XP-PEN%22&list_id=96933&order=Importance&product=gtk%2B&query_format=specific). No results for that right now, but you can refine it.

There are a lot of projects at on GNOME's bug tracker. If you want to report a new bug, it's the `gtk+` product and the `Backend: Win32` component. Start here once you're logged in and it'll be easier: <https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B>.

Anyone reporting this bug and willing to see it through to the end needs to be able to help out the GTK developers. You will need to:

* Assure them you are running the latest tablet drivers for your model, and tell them what version that is.
* Tell them the model number of the tablet you used.
* Tell them the version of Windows you are using.
* Tell them the versions of any other software you tried, and how to reproduce the issue in them.
* Find what _exact_ version of `libgtk.dll` is being used.
* Try out GTK3 test code, such as <https://gist.github.com/achadwick/54e5b111e5ac908becf1>, in a development environment like [MSYS2](https://msys2.github.io/).
* Chase the developers on IRC <irc://irc.gimp.org/%23gtk+>. Real-time conversations really help.
* Be able and willing to debug any code you run. This may even require debugging builds of GTK itself.

It's quite a tall order, but by doing as much of that as you can you will help a lot of people.

**Closed by achadwick** 2016-02-10 11:57 UTC
Labels: request-for-help, upstream, windows

**Comment by DrawMeister123** [comment] 2016-02-10 13:01
So what you are basically saying is 'go away' because I'm not sure what part of I AM NOT A PROGRAMMER JUST A USER you missed. 

Please read what I said about the problem with Open Source in the other thread. THIS right here, is the problem. There is no help and no consideration for people who just want to use it. I don't actually give a toss what the problem is, what hoops someone who is a programmer needs to jump through to fix it. I, and every one else like me, just wants something that works. And if something does go wrong, someone somewhere who can help fix it. Not all this nonsense. 

I don't know what half of that means and guess what - I don't WANT to know. I'm not in the slightest bit interested in learning how to do any of that. At the risk of repeating myself. I just want software that works.

**Comment by tumagonx** [comment] 2016-02-10 13:32
@DrawMeister123. Indeed a working tablet support is crucial for
mypaint, me personally won't release mypaint if it not working but hey
it works for many wacom. So it's already useful app.

Understand the meaning of "upstream" here. It means issue lies on
software component that mypaint developer NOT responsible for. What
else do you expect? It's like blaming on iTunes (Apple) when the
problem is in Windows (Microsoft).

Unfortunately I doubt you will have luck (assuming you don't know how
to debug) with gnome bugtracker either unless umm.. they somehow have
your tablet or you donate a tablet for them.


On 2/10/16, DrawMeister123 <notifications@github.com> wrote:
> So what you are basically saying is 'go away' because I'm not sure what part
> of I AM NOT A PROGRAMMER JUST A USER you missed.
>
> Please read what I said about the problem with Open Source in the other
> thread. THIS right here, is the problem. There is no help and no
> consideration for people who just want to use it. I don't actually give a
> toss what the problem is, what hoops someone who is a programmer needs to
> jump through to fix it. I, and every one else like me, just wants something
> that works. And if something does go wrong, someone somewhere who can help
> fix it. Not all this nonsense.
>
> I don't know what half of that means and guess what - I don't WANT to know.
> I'm not in the slightest bit interested in learning how to do any of that.
> At the risk of repeating myself. I just want software that works.
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/584#issuecomment-182362345


-- 
!tuma

**Comment by DrawMeister123** [comment] 2016-02-10 13:52
Now see I have a simple kind of logic. 

Earlier version of Mypaint works perfectly with my system.

Mypaint 1.2 does NOT work. 

No other changes were done on my system between uninstalling version 1.whatever and installing 1.2 

THEREFORE PROBLEM IS MYPAINT not some other component that has not changed!

**Comment by achadwick** [comment] 2016-02-10 13:55
@DrawMeister123
My comment (https://github.com/mypaint/mypaint/issues/584#issuecomment-182333921) wasn't directed at you, and I should have made that clearer.

You've made it clear what your opinion of Open Source software is. I get it, and I pretty much agree. There's a lot more that can be done to build communities and foster user support. I'm glad that good people like @odysseywestra are doing awesome things like the [MyPaint Community Forum](http://community.mypaint.org/), and I wish there were more people getting involved at all levels.

Practically we can't help you _here_ on this one issue. I cannot take this problem further without the hardware, but from my experience I do not think it is a problem with MyPaint. We can't fix it here. This is not the right place to do that. All I can do is direct people - not necessarily yourself - to report it in the right way and see it though to the end with the people who can actually help. It takes a lot of heavy technical knowledge to get that job done, and I make no secret of it. But I'm aware there's a lot of really talented Windows people out there, more skilled in their domain than myself, who could take it forward.

Thank you again for reporting this problem to us.

**Comment by DrawMeister123** [comment] 2016-02-10 14:01
I'm sorry but I do not agree with your assessment that it is not Mypaint.

I used Mypaint 1.early in the morning. Then I had the bright idea to look for new brushes and found the  upgrade to 1.2. I downloaded 1.2. Uninstalled the earlier version. Installed 1.2 and boom couldn't use the tablet, couldn't open the files I had open not 2 hours previously. 

Got fed up looking for help. Uninstalled 1.2. Installed 1.earlier. BOOM everything works fine. Files open. Tablet works. All 100%

So you tell me, in that scenario how I'm supposed to believe the problem is not some difference somewhere in Mypaint between the earlier version and the new version?

**Comment by tumagonx** [comment] 2016-02-10 14:24
ahhh maybe we should rename mypaint 1.2 as mypaint 2.0. Therefor
people will think architecturally they are different (which is true).

Talk about logic:
@DrawMeister123 Strange that you don't ask about version 1.1? Cause
only me (tumagonx) know the answer. Guess what, mypaint 1.1 didn't
worked with *any* tablets. So you think 1.2 regressed? no it
progressed actually, Does it better than 1.0? no (lag issue) and we're
aware of it.

On 2/10/16, DrawMeister123 <notifications@github.com> wrote:
> I'm sorry but I do not agree with your assessment that it is not Mypaint.
>
> I used Mypaint 1.early in the morning. Then I had the bright idea to look
> for new brushes and found the  upgrade to 1.2. I downloaded 1.2. Uninstalled
> the earlier version. Installed 1.2 and boom couldn't use the tablet,
> couldn't open the files I had open not 2 hours previously.
>
> Got fed up looking for help. Uninstalled 1.2. Installed 1.earlier. BOOM
> everything works fine. Files open. Tablet works. All 100%
>
> So you tell me, in that scenario how I'm supposed to believe the problem is
> not some difference somewhere in Mypaint between the earlier version and the
> new version?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/584#issuecomment-182387674


-- 
!tuma

**Comment by achadwick** [comment] 2016-02-10 14:27
@DrawMeister123 https://github.com/mypaint/mypaint/issues/584#issuecomment-182387674
Well, I do know the innards of the software fairly well... but you have a point on the bundling and how it seems to end users.

The nice packaged component you're seeing is in reality many parts all bundled together. Users shouldn't have to care when it's working of course, much like a car. We get that too, and try to make it happen.

Internally though... different bundled GTK between the versions, so you get different behaviour. Not helped by an upgrade path forced on us requiring us to pick one or the other. I could go on. I won't. Here be technicalities.

Really, if 1.0 works for you then that's a great solution. I wish the shiny new motor could run on all roads out there too, but there's some scenarios that the funky old tractor will be better able to cope with. Not to disparage your tablet as a dirt track or anything, you understand.

(Anyway, I'll have to wrap this up soon if I'm resorting to terrible counter-productive analogies. At least both versions are free.)
