### ISSUE TITLE
New documents from templates

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#290] opened 2015-04-10 11:03 UTC
Split from issue #288 :

This issue proposes two changes:
- New menu item, 'New from template', which:
  - Offers the user a choice between template .ora files (stored in templates/ subdirectory inside the configuration directory). Should support subdirectories, so basic categorization is possible.
  - Loads the selected ORA file, clears the filename information, and marks the document dirty
- New preference item, "New document is created:"
  - Radiobutton selecting between 'Generic blank document' and 'From template:'
  - Button offering the same choice between templates found in templates/ subdirectory

The rationale is that for many types of work you do have to target specific output dimensions and other picture characteristics, this could be extremely helpful for these workflows. It would provide a way to setup in one step layers, frame size, and background.

I believe it would be a pretty simple and very helpful feature that is also pretty simple to implement, and I'm fully prepared to implement it in its entirety.

**Comment by 0ion9** [comment] 2015-04-10 11:12
Andrew Chadwick commented:

---
Of course, someone will have to make a library of blank .ora templates (or more usefully for source control: unpacked ORA-directories that get built). Could be big, better in a submodule maybe...
---

Personally, yes, I was basing my ideas on the expectation that there might be many templates. GIMP's approach to templates -- 'make it a submenu item' -- is IMO annoying to deal with when there are many templates.

**Comment by achadwick** [comment] 2015-04-10 11:16
Yeah. Submenus might also be a pain to deal with when migrating our action and menu structures to `GAction`s to keep up with GTK (we'll have to do that one day...). Better to make the design not need that!

I also like illustrated choices for these sorts of things, if there's going to be a big graphical variation between the templates. But your call; I'll assign this to you :D

**Comment by 0ion9** [comment] 2015-04-10 11:27
That's useful feedback, thanks -- I hadn't considered that when thinking about submenu vs file selector. I wasn't trying to suggest I had this all nailed down, I just proposed a solution that I thought would work for what I was trying to do. 

I don't really have many ideas for what templates people would like to see packaged with MyPaint, either. Other than standard (A4, white or mid-grey). So I welcome suggestions on that.

One other thought is perhaps some simple indication of the layer structure, in the form of '%d layers, %d groups'.

**Comment by achadwick** [comment] 2015-04-21 16:44
We probably can't accept any changes for this after the string freeze for 1.2.0-beta. I'm guessing there will be string changes for this :)

@0ion9 are you actively working on this? I can include it in the alpha cycle if it's ready. If not, we'll have to defer it until after the final 1.2.0 release.

**Comment by 0ion9** [comment] 2015-04-23 04:21
Not currently working on this. Planning to make some mockups soon. RL is pretty confusing currently, but that's no excuse.

**Comment by achadwick** [comment] 2015-06-07 00:34
Okay, deferred. We can revisit this later on.

**Comment by odysseywestra** [comment] 2019-12-27 22:52
@0ion9 Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get community feedback. If you can also set your post as a wiki that way we can edit the scope of the feature request that would be awesome as well. Don't forget to link back to here as well so I can keep track of it incase we need to reopen the issue. Thanks.

---
Probably a duplicate of #288

**Comment by AesaraB** [comment] 2024-01-17 22:38
I'd argue this feature is pointless with the presented use-case. If #288 were to be implemented, then how many clicks would you save with the inclusion of this feature, _really_?

Additionally, if the user has a use-case for custom .ora files that do more than set the frame size, then they could just copy a file and create that as a template.

Normally I would leave open feature requests that I personally don't have a use-case for. But I just can't see this as having a use-case for anyone, let alone a common one. Please do inform if I'm not seeing something.

**Closed by AesaraB** 2024-01-17 22:38 UTC
Labels: type.Enhancement, solution.Wontfix, cat.UX, cat.Data
