### ISSUE TITLE
Improvements for touch screens on tablets

### ISSUE THREAD

**Issue by alandbm** [mypaint/mypaint#599] opened 2016-02-12 04:31 UTC
- [ ] `pincht-to-zoom` + `rotate` → are much desired as **gestures!**  
  Ref.: [bug #22036: Would love to see a "Rotate Layer contents" function or someting similar](https://gna.org/bugs/?22036)
- [ ] _pen mode_ → when using a pen, to despise fingers and recognize only the pen input

---

Why exists that repository at gna.org?

**Comment by odysseywestra** [comment] 2016-02-12 05:01
Hi thanks for reporting. Sadly I'm closing this issue since it's is a duplicate of #427.

Also for feature request of the `pen mode` of MyPaint, please post it on our Community Forums over at http://community.mypaint.org . That way we can at least plan out how to go about this before we think about implementing this into MyPaint. Also it will help us keep our issue tracker focused on bugs reporting and fixing. 

For future bug reporting please refer to our [Reporting Bugs Wiki](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs).

Thanks and welcome to the community.

**Closed by odysseywestra** 2016-02-12 05:01 UTC

**Comment by odysseywestra** [comment] 2016-02-12 05:08
Also to answer your question about gna.org. That was the old issue tracker for MyPaint. Since we moved MyPaint code base from Gitorious to Github, we opted to use Github's issue instead of gna's. Plus we realized Github issue tracker is much more user friendly than the gna in my opinion.
