### ISSUE TITLE
Odd rendering artifact on SurfaceStudio device

### ISSUE THREAD

**Issue by mylojp** [mypaint/mypaint#798] opened 2017-04-29 16:29 UTC
```
MyPaint version: 1.2.1+gitexport.bcf5a28d
Operating system: Windows 10  Version 10.0.15063
Running on the new Microsoft Surface Studio 28 Inch all in one device.
Resolution: 45000x3000
Font size scale of 200%
```

1. Start MyPaint
2. Simply draw with any brush style and you will see the artifact

Notice the rectangles around the brush stroke
![image](https://cloud.githubusercontent.com/assets/2709213/25557017/6a65a8aa-2cbd-11e7-96fa-ed92021500e0.png)

to remove the artifacts I minimize and restore the application or switch to another app and back.

**Comment by achadwick** [comment] 2017-05-05 16:54
Hi, thanks for reporting.

This looks like a duplicate of #631 and #686, and has been fixed on master and on v1.2.x for the next release. The fact that you're using a HiDPI device confirms it to me (thanks for adding that info).

**Closed by achadwick** 2017-05-05 16:54 UTC
Labels: duplicate
