### ISSUE TITLE
Brush Strokes lag severely

### ISSUE THREAD

**Issue by moonshineTheleocat** [mypaint/mypaint#540] opened 2015-12-29 22:12 UTC
So... there is a nasty problem with Windows 10, where the brush strokes are lagging behind terribly. If you try drawing, it will take literally a few seconds before it finally responds.

This is beta 3

**Comment by achadwick** [comment] 2015-12-29 23:51
Closed as a duplicate of #390.

**Closed by achadwick** 2015-12-29 23:51 UTC
Labels: duplicate
