### ISSUE TITLE
At startup, in Russian locale: "UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 0: invalid continuation byte" [unsupported GTK/GLib version?]

### ISSUE THREAD

**Issue by sagax** [mypaint/mypaint#441] opened 2015-10-12 20:21 UTC
hi all!
i got [source](https://github.com/mypaint/mypaint/archive/v1.2.0-beta.1.tar.gz)
got [library](https://github.com/mypaint/libmypaint/archive/master.zip) and unzip to **brushlib** dir
next, run **scons**. all compiled.
next i try run **./mypaint** but got this error in terminal

``` bash
./mypaint 
INFO: mypaint: Installation layout: not installed, testing from within the source tree
INFO: lib.i18n: POSIX: LANG='ru_RU.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
Traceback (most recent call last):
  File "./mypaint", line 462, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/gui/main.py", line 94, in main
    from gui import application
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/gui/application.py", line 48, in <module>
    import lib.document
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/lib/document.py", line 39, in <module>
    import lib.tiledsurface as tiledsurface
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/lib/tiledsurface.py", line 26, in <module>
    import pixbufsurface
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/lib/pixbufsurface.py", line 35, in <module>
    u"Unable to construct a vital internal object. "
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/lib/gettext.py", line 82, in C_
    result = result.decode("utf-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 0: invalid continuation byte
```
---

my system configuration
```
uname -a
Linux 3.4.63-2.44-default #1 SMP Wed Oct 2 11:18:32 UTC 2013 (d91a619) i686 i686 i386 GNU/Linux

cat /etc/issue
Welcome to openSUSE 12.2 "Mantis" - Kernel

locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

python --version
Python 2.7.3

gtk-devel   1.2.10-1092.1

gtk2-devel   2.24.10-3.1.2

gtk3-devel   3.4.4-2.15.1

scons -v
SCons by Steven Knight et al.:
	script: v2.3.4, 2014/09/27 12:51:43, by garyo on lubuntu
	engine: v2.3.4, 2014/09/27 12:51:43, by garyo on lubuntu
	engine path: ['/usr/lib/python2.7/site-packages/SCons']

swig -version
SWIG Version 2.0.7
```
---

please help.

**Comment by achadwick** [comment] 2015-10-12 20:56
It's an unusual way of compiling: please try following the instructions at <https://github.com/mypaint/mypaint/blob/master/README_LINUX.md> if you want to build from source. It's easier to contribute code back if you do it that way! (well, after learning the intricacies of git :neutral_face:)
We do official source releases too, which I sign: <https://github.com/mypaint/mypaint/releases>

You need to upgrade your computer so that it has GTK 3.10.0 or above. GTK 3.4.4 is much too old, and is not supported for the upcoming release. Sorry about that.

I can't reproduce this issue with the current git master and LANG=ru_RU.utf8 and "Загрузки" in my working path like yours. This could be due to an old version of GLib on your system though.

Once you have a supported GTK (and its GLib dependency), try running with MYPAINT_DEBUG=1: you should get more information about how i18n is setting up and how locale is being inferred. You should see something like:

```
DEBUG: mypaint: datapath: u'.'
DEBUG: mypaint: iconspath: u'desktop/icons'
DEBUG: mypaint: old_confpath: u'/home/andrewc/.mypaint/'
DEBUG: mypaint: localepath: 'po'
DEBUG: mypaint: localepath_brushlib: 'brushlib/po'
INFO: lib.i18n: POSIX: LANG='ru'
INFO: lib.i18n: POSIX: LANGUAGE=None
DEBUG: mypaint: localepath: 'po'
DEBUG: mypaint: localepath_brushlib: 'brushlib/po'
DEBUG: mypaint: getdefaultlocale(): ('ru_RU', 'UTF-8')
DEBUG: mypaint: setlocale(LC_ALL, ''): 'ru_RU.utf8'
DEBUG: mypaint: getpreferredencoding(): 'UTF-8'
DEBUG: mypaint: getlocale(LC_COLLATE): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_CTYPE): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_MESSAGES): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_MONETARY): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_NUMERIC): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_TIME): ('ru_RU', 'UTF-8')
DEBUG: mypaint: C bindtextdomain('mypaint', 'po'): 'po'
DEBUG: mypaint: C bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('mypaint', 'po'): 'po'
DEBUG: mypaint: Python bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C bindtextdomain('libmypaint', 'brushlib/po'): 'brushlib/po'
DEBUG: mypaint: C bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('libmypaint', 'brushlib/po'): 'brushlib/po'
DEBUG: mypaint: Python bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C textdomain('mypaint'): 'mypaint'
DEBUG: mypaint: Python textdomain('mypaint'): 'mypaint'
DEBUG: gui.main: Adding GTK workarounds...
DEBUG: gui.main: GTK workarounds added.
DEBUG: lib.glib: Init g_get_user_config_dir(): u'/home/andrewc/.config'
DEBUG: lib.glib: Init g_get_user_data_dir(): u'/home/andrewc/.local/share'
DEBUG: lib.glib: Init g_get_user_cache_dir(): u'/home/andrewc/.cache'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_DESKTOP): u'/home/andrewc/Desktop'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_DOCUMENTS): u'/home/andrewc/Documents'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_DOWNLOAD): u'/home/andrewc/Downloads'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_MUSIC): u'/home/andrewc/Music'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_PICTURES): u'/home/andrewc/Pictures'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_PUBLIC_SHARE): u'/home/andrewc/Public'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_TEMPLATES): u'/home/andrewc/Templates'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_VIDEOS): u'/home/andrewc/Videos'
```

**Comment by achadwick** [comment] 2015-10-12 20:57
**Triage note**: unsupported GTK version :hushed:
Let's confirm that it's not a problem with a supported GTK+GLib first before closing it though.

**Comment by sagax** [comment] 2015-10-13 21:05
```
MYPAINT_DEBUG=1 ./mypaint 
INFO: mypaint: Debugging output enabled via MYPAINT_DEBUG
INFO: mypaint: Installation layout: not installed, testing from within the source tree
DEBUG: mypaint: datapath: u'.'
DEBUG: mypaint: iconspath: u'desktop/icons'
DEBUG: mypaint: old_confpath: None
DEBUG: mypaint: localepath: 'po'
DEBUG: mypaint: localepath_brushlib: 'brushlib/po'
INFO: lib.i18n: POSIX: LANG='ru_RU.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
DEBUG: mypaint: localepath: 'po'
DEBUG: mypaint: localepath_brushlib: 'brushlib/po'
DEBUG: mypaint: getdefaultlocale(): ('ru_RU', 'UTF-8')
DEBUG: mypaint: setlocale(LC_ALL, ''): 'ru_RU.UTF-8'
DEBUG: mypaint: getpreferredencoding(): 'UTF-8'
DEBUG: mypaint: getlocale(LC_COLLATE): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_CTYPE): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_MESSAGES): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_MONETARY): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_NUMERIC): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_TIME): ('ru_RU', 'UTF-8')
DEBUG: mypaint: C bindtextdomain('mypaint', 'po'): 'po'
DEBUG: mypaint: C bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('mypaint', 'po'): 'po'
DEBUG: mypaint: Python bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C bindtextdomain('libmypaint', 'brushlib/po'): 'brushlib/po'
DEBUG: mypaint: C bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('libmypaint', 'brushlib/po'): 'brushlib/po'
DEBUG: mypaint: Python bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C textdomain('mypaint'): 'mypaint'
DEBUG: mypaint: Python textdomain('mypaint'): 'mypaint'
DEBUG: gui.main: Adding GTK workarounds...
DEBUG: gui.main: GTK workarounds added.
DEBUG: lib.glib: Init g_get_user_config_dir(): u'/home/sagax_nb/.config'
DEBUG: lib.glib: Init g_get_user_data_dir(): u'/home/sagax_nb/.local/share'
DEBUG: lib.glib: Init g_get_user_cache_dir(): u'/home/sagax_nb/.cache'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_DESKTOP): u'/home/sagax_nb/\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0441\u0442\u043e\u043b'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_DOCUMENTS): u'/home/sagax_nb/\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_DOWNLOAD): u'/home/sagax_nb/\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0438'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_MUSIC): u'/home/sagax_nb/\u041c\u0443\u0437\u044b\u043a\u0430'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_PICTURES): u'/home/sagax_nb/\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_PUBLIC_SHARE): u'/home/sagax_nb/\u041e\u0431\u0449\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u044b\u0435'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_TEMPLATES): u'/home/sagax_nb/\u0428\u0430\u0431\u043b\u043e\u043d\u044b'
DEBUG: lib.glib: Init g_get_user_special_dir(G_USER_DIRECTORY_VIDEOS): u'/home/sagax_nb/\u0412\u0438\u0434\u0435\u043e'
DEBUG: lib.helpers: Using builtin python 2.6 json support
Traceback (most recent call last):
  File "./mypaint", line 462, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/gui/main.py", line 94, in main
    from gui import application
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/gui/application.py", line 48, in <module>
    import lib.document
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/lib/document.py", line 39, in <module>
    import lib.tiledsurface as tiledsurface
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/lib/tiledsurface.py", line 26, in <module>
    import pixbufsurface
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/lib/pixbufsurface.py", line 35, in <module>
    u"Unable to construct a vital internal object. "
  File "/home/sagax_nb/Загрузки/mypaint-1.2.0-beta.1/lib/gettext.py", line 82, in C_
    result = result.decode("utf-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbd in position 1: invalid start byte
```

i understood about version gtk and glib, thanks

**Closed** 2015-10-14 06:37 UTC
Labels: request-for-help, works-for-me

**Comment by achadwick** [comment] 2015-10-14 07:35
@sagax Is https://github.com/mypaint/mypaint/issues/441#issuecomment-147853890 from GTK >= 3.10 ?

**Comment by sagax** [comment] 2015-10-16 04:32
no, it's [comment](https://github.com/mypaint/mypaint/issues/441#issuecomment-147853890) for  GTK < 3.10
