### ISSUE TITLE
Brush Engine Enhancement: Bristle Strokes

### ISSUE THREAD

**Issue by Ico-dY** [mypaint/mypaint#431] opened 2015-10-02 21:29 UTC
As explained in Mypaint forum, a way to make bristle strokes would be very useful to have: http://forum.intilinux.com/mypaint-development-and-suggestions/bristle-strokes-in-mypaint/

It's practically impossible to mimic many styles/media without it. Is it really hard to make? ^^

**Comment by achadwick** [comment] 2015-10-02 22:25
Duplicate of mypaint/libmypaint#8, I think.

**Closed by achadwick** 2015-10-02 22:25 UTC
Labels: duplicate
