### ISSUE TITLE
[Feature Request] - Custom Input as "slider" and keys

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#848] opened 2017-08-02 15:50 UTC
Currently we can use keys/buttons to adjust size and opacity, and there are sliders for a few other settings.  I really think "Custom" could be much more interesting if it was a slider, and MUCH more useful if we could assign keys/buttons to increase/decrease the base value.  This would let you create brushes that have unique and adjustable properties and accessible in a way that doesn't require fancy hardware. 

![image](https://user-images.githubusercontent.com/6015639/28881391-d470f9ae-775c-11e7-9cc5-ebac14e985ec.png)

So you could map, say, "jitter" to the custom input and then be able to adjust your jitter on-the-fly just like you would adjust size.  Or assign multiple settings to custom and then you can adjust 5 things at once with one button.

**Comment by 0ion9** [comment] 2017-08-03 06:17
So "Custom" would be acting as a kind of proxy here, a means to abstract a group of brush variations down to a single 'how much effect do you want' slider?

If so, it seems like it would be much more generally useful, as you say.

My mind also brings up a connection with the idea of 'brush overlays' : persistent partial overrides of brushes. I'm having some difficulty finding the post about this, but viewzoom is a good example -- having an overlay that mapped viewzoom to radius would make all brushes scale to zoom level. So it's like a version of your idea that would separate the custom behaviour rather than baking it into the brush.

(I think ideally we should have both kinds. Just throwing my idea out there in case it helps develop this one)

**Comment by briend** [comment] 2017-08-03 14:58
>So "Custom" would be acting as a kind of proxy here, a means to abstract a group of brush variations down to a single 'how much effect do you want' slider?

I think that was the whole intent of the Custom setting and input, originally.  I'm merely suggesting we upgrade it to the same importance as brush radius and opacity by giving it a slider and key mapping :-)

I think you're recalling this thread:
https://community.mypaint.org/t/combined-brushes-and-brush-randomizer/538
I still think overlays(or combined brushes) would be cool but I'm worried that many brush settings are fine-tuned in relation to other settings, so they can't just be plucked out and applied to another brush with any expectation that it will have the same effect :-(

Sorta like my brush randomizer, I got that working, but it makes a LOT of broken brushes-- most settings have a very small range of useful values, but we generally allow a lot more.  I suppose I could tweak it to only create mapped points within the middle 20% of the allowed values. . .:-P

**Comment by briend** [comment] 2017-08-04 03:16
I have a related PR here: https://github.com/mypaint/libmypaint/pull/104
This lets you hook additional settings to the base brush size, so you can control how your brush looks when it's bigger vs smaller.  Basically just like custom but tied to brush size instead.  So, only useful for when you want different behavior for different sized brushes.  Whereas Custom input would let you just have a unique controller for anything you want.

**Comment by odysseywestra** [comment] 2019-12-12 07:17
@briend this is basically a duplicate of #269. I'm going to go ahead and close this issue in favor of that one.

**Closed by odysseywestra** 2019-12-12 07:17 UTC
Labels: enhancement
