### ISSUE TITLE
Cintiq 13HD not recognized under Devices in Windows 8.1

### ISSUE THREAD

**Issue by Blue-Ten** [mypaint/mypaint#401] opened 2015-08-07 19:00 UTC
MyPaint v1.2.0-beta.0

![cintiq13hd-mypaint-beta](https://cloud.githubusercontent.com/assets/13457569/9143443/6b3e974a-3cfb-11e5-81dd-4bc0a853d615.png)

Not getting any pressure sensitivity and I only see the System Aggregated Pointer in Devices. Driver version is 6.3.11-4

I've tested the pen with "Use Windows Ink" checked and unchecked in the Wacom options. Results are the same in MyPaint for both modes.

**Comment by achadwick** [comment] 2015-08-07 19:51
:point_right: *Firstly, please try v1.2.0-beta.1* - newer prerelease builds are available on the releases page here :star2: 

I see you've added "python2w" (a.k.a. this particular MyPaint build) to the list, which is a step I don't generally do with my tablet when testing on Windows. However that's not the source of this:

![image](https://cloud.githubusercontent.com/assets/61299/9144008/df2e3d22-3d41-11e5-9413-f629ef589566.png)

Pressure's working for me with an Intuos 5 and Wacom driver version 6.3.13w3.

MyPaint's hardware support is - alas! - only as good as its underlying libraries' hardware support. It doesn't deal with hardware itself, it delegates that task to [GDK](https://en.wikipedia.org/wiki/GDK), whose bug tracker is at <https://bugzilla.gnome.org/>. Try [searching for problems with your model of tablet there](https://bugzilla.gnome.org/buglist.cgi?quicksearch=Cintiq), and file a new bug with them if one isn't present for your tablet. If you're reporting there after trying again with beta.1, please pass on that mypaint v1.2.0-beta.1 has been built with libgdk-3-0.dll at version 3.16.6.

Good luck with the GDK developers. Please link the bug you find/raise here, so MyPaint users searching for support can find it. And feel free to use this issue report as a dumping ground for images!

:point_right: *Quick thing everyone can try:* Are you using MyPaint w32 or MyPaint w64? Some people get better results with the w32 build :confused: 

Please also make sure you have a wintab.dll or a wintab32.dll in C:\Windows from your driver, and let us know what versions those are. That's how GDK talks to the hardware. I have two installed:

* C:\Windows\System32\Wintab32.dll at version 1.0.5.8
* C:\Windows\SysWOW32\Wintab32.dll, also at version 1.0.5.8

![image](https://cloud.githubusercontent.com/assets/61299/9144212/6a3d7ef4-3d43-11e5-9c71-a83145b46605.png)

Pressure works for me with this particular combination (+ updated Windows 7 Professional N Service Pack 1). However tilt does not.

It's also a bit weird (for any GDK people reading this) that I see the devices reported properly in events (see that Input Test window above) but not in MyPaint's device list window (which [uses `gdk_device_manager_list_devices()` in this version](https://github.com/mypaint/mypaint/blob/v1.2.0-beta.1/gui/device.py#L233), and which works just fine in Linux). There's clearly something funky going on at a low level here.

**Comment by Blue-Ten** [comment] 2015-08-07 20:21
Was using the 64-bit version of that build. Just tried the 32-bit version of the latest build, but still no pressure for me. I also have version 1.0.5-8 of Wintab in both folders.

I guess I'll pass this on to GDK then :). Thanks for all the info!

**Comment by achadwick** [comment] 2015-08-07 20:42
GIMP will be using GDK too - though at what version I don't know. It's literally the "GIMP Drawing Kit", so I guess that's confirmed as upstream then. Perhaps with >1 version of GDK.

I'm going to have another look at our gui.device.Monitor code to try and figure out why it's not listing tablets on Windows. At the very least it could be made to do auto-discovery based on incoming events as a fallback.

For now though: closed as an upstream issue, and I hope it gets fixed. :+1: Thanks in advance for chasing this through, since you have access to the hardware, and please do link back any actual upstream bug reports when you pass on the info.

I hope our docs here are good enough to allow you to test anything that needs testing.

**Closed** 2015-08-07 20:42 UTC
Labels: upstream, windows, works-for-me

**Comment by achadwick** [comment] 2015-08-08 00:03
One weirdness I've noticed is that the device needs to be plugged in before MyPaint starts, otherwise GDK won't even report it with incoming events. Additionally:

* GdkDeviceManager: device-added and device-removed aren't emitted on Windows.
* GdkDevice: vendor-id and product-id (new in 3.16) are NULL on Windows.

for my VirtualBox setup, anyway.
