### ISSUE TITLE
Button mapping does not reflect actual actions

### ISSUE THREAD

**Issue by LeavOA** [mypaint/mypaint#921] opened 2018-04-09 13:44 UTC
#### Description of the problem

Preference say that button3 should be scroll and CTRL+button3 zoom, but in reality no matter how I change the settings, button3 remains zoom and CTRL+button3 is scroll (opposite)

Related note, I couldn't change any key combos with button3 and had to edit the settings.json manually to test.

#### Basic system details

MyPaint version: 1.2.1+gitexport.bcf5a28d
Operating system: Windows 10

#### Steps to reproduce
1. Start MyPaint
2. Open Preferences to see that:
       zoom combo is indeed ctrl+button3
       scroll combo is indeed button3
4. Draw something
5. ctrl+button3 on drawing, MyPaint scrolls.
6. button3 on drawing, MyPaint zooms

####Additional notes

Button3 works as expected in other programs, such as chrome.
button3 = scroll
ctrl+button3 = zoom

Thanks!

**Comment by jplloyd** [comment] 2019-06-25 21:00
Default bindings works as advertised, testing on same OS and MyPaint build. I cannot reproduce being unable to change the bindings either. I think this is a case of expecting MMB to be Button3 and RMB to be Button2  (which _is_ sometimes, but not always, the case). Closing this for now - reopen if my assumption is incorrect.

Side note: the use of Button2/Button3 in the default bindings _is_ switched around for the linux and windows versions of MyPaint, but this is due to the default button assignment for Wacom pens being different between the OS's.

**Closed by jplloyd** 2019-06-25 21:00 UTC
