### ISSUE TITLE
scons prefix=/somewhere installs stuff and shouldn't

### ISSUE THREAD

**Issue by ryandesign** [mypaint/mypaint#347] opened 2015-06-21 15:48 UTC
Attempting to *build* MyPaint by running `scons prefix=/somewhere` attempts to modify /somewhere. It should not be attempting to modify anything outside of the build directory until I ask for it to *install*, by running `scons prefix=/somewhere install`.

```
$ scons prefix=/somewhere
scons: Reading SConscript files ...
OSError: [Errno 13] Permission denied: '/somewhere':
  File "/Users/rschmidt/sw/mypaint/SConstruct", line 44:
    env = Environment(ENV=os.environ, options=opts, tools=tools)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-2.3.4/SCons/Environment.py", line 986:
    variables.Update(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-2.3.4/SCons/Variables/__init__.py", line 216:
    option.validator(option.key, env.subst('${%s}'%option.key), env)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-2.3.4/SCons/Variables/PathVariable.py", line 102:
    os.makedirs(val)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157:
    mkdir(name, mode)
```

I [reported this issue in 2013](https://gna.org/bugs/?20399) but it was closed as "works for me", though the problem remains with the latest development code today.

**Comment by achadwick** [comment] 2015-06-21 16:38
I'm not a Mac user, but under Linux you can't set the prefix to something that doesn't exist on / and then expect scons to create it for you when you run as an ordinary user. I get exactly the same error as you.

@ryandesign I'm not sure why you need to do this. Perhaps a brief explanation of what the macports scripts expect?

SCons actually appears to be working as designed. It isn't really a build-then-install system. It's a build-and-install system. See <https://bitbucket.org/scons/scons/wiki/FrequentlyAskedQuestions#markdown-header-how-do-i-install-files-the-install-method-doesnt-do-anything-in-general-how-do-i-build-anything-outside-my-current-directory> and the entry after it.

* If you do `scons prefix=/something/missing`, you are telling scons to create that prefix now, and everything it knows about in it.
* `scons` should be equivalent to `scons prefix=.`
* We declare the `install` target as an alias for `$prefix`.

Not sure what I can do here, but some general things:

* Does the `scons prefix=/opt/WHEREITGOESAFTERINSTALL --install-sandbox=/where/macports/likes/to/install` option work around this for you? `$prefix` will still have to exist first, and *will* be created (IMO this is bad design in SCons, but it doesn't break the Debian builds because their prefixes already exist).
* Can you get away with a `$prefix` somewhere inside your working tree?
* Can you get away with `/bin/true` as your build step in your scripting? Or if you need to run tests, perform a sequence like [build locally → run tests locally → clean locally] for your build?

**Comment by achadwick** [comment] 2015-06-21 16:42
Can't change the build system for 1.2 - no time for testing. We will need to switch to something else after that in order to support Python 3, however. Plain old distutils might be a better choice, but we'll need to properly separate out libmypaint.

Leaving unmilestoned, because this is an issue that needs to accumulate workarounds.

**Comment by ryandesign** [comment] 2015-06-21 18:49
In MacPorts, we definitely want to be able to build first, then install second, as a separate step. And everywhere else in MacPorts that we're using scons, we are successfully doing this. We're doing it successfully for MyPaint too, with some workarounds, but workarounds shouldn't be needed; build systems should work properly out of the box.

Perhaps we should just omit setting `prefix` at build time as you suggest. I don't remember why I thought I needed to set it at build time. We do so successfully in other ports using scons, so I assumed it would work for MyPaint also. On OS X it is normal to want to set the installation prefix at build time, because the absolute path to the installation prefix gets baked into any shared libraries that are built and anything that links with them. But MyPaint doesn't have shared libraries so that reason doesn't apply here. The SConstruct sets `default_prefix = '/usr/local/'`, and of course we don't want any references to /usr/local ending up in the built software, so perhaps I was trying to avoid that. Certainly, references to the build-time prefix (the default /usr/local/, or another value as specified on the command line) get written into libmypaint.pc. But they get rewritten at install time, so I guess that's ok.

If you don't wish to change the build system prior to 1.2, and you're already planning on replacing scons with something else after 1.2, then I guess we don't need to look into it further. I would welcome such a change, since scons is such a pain to deal with, from a packager's perspective, since there is no standardization between projects on how a packager is to supply basic settings.

**Comment by achadwick** [comment] 2015-06-21 21:30
I wonder if those other projects are doing something better than our hack to verb the "install" target/noun?

```python
# Convenience alias for installing to $prefix
env.Alias('install', '$prefix')
```
-- [SConstruct:204] (https://github.com/mypaint/mypaint/blob/591e7fb8d96d279ee713e4a62c474cbbdbb92906/SConstruct#L204)

I'd love to see some good example projects and see what they do.

-------------------------------------------------------

Another bit of code that looks dubious in our SConstruct is

```python
opts.Add(PathVariable('prefix', 'autotools-style installation prefix', default_prefix, 
validator=PathVariable.PathIsDirCreate))
```
-- [SConstruct:29] (https://github.com/mypaint/mypaint/blob/591e7fb8d96d279ee713e4a62c474cbbdbb92906/SConstruct#L29)

Perhaps that `validator` arg should be `PathVariable.PathIsDir` instead?

**Comment by achadwick** [comment] 2015-06-22 01:27
@ryandesign Please can you patch with

```diff
diff --git a/SConstruct b/SConstruct
index 04aa665..187476e 100644
--- a/SConstruct
+++ b/SConstruct
@@ -25,8 +25,15 @@ default_openmp = True
 if sys.platform == "darwin":
     default_openmp = False
 
+def isabs(key, dirname, env):
+    assert os.path.isabs(dirname), "%r must have absolute path syntax" % (key,)
+
 opts = Variables()
-opts.Add(PathVariable('prefix', 'autotools-style installation prefix', default_prefix, validator=PathVariable.PathIsDirCreate))
+opts.Add(
+    'prefix', 'autotools-style installation prefix',
+    default=default_prefix,
+    validator=isabs,
+)
 opts.Add(BoolVariable('debug', 'enable HEAVY_DEBUG and disable optimizations', False))
 opts.Add(BoolVariable('enable_profiling', 'enable debug symbols for profiling purposes', True))
 opts.Add(BoolVariable('enable_gegl', 'enable GEGL based code in build', False))
@@ -119,41 +126,37 @@ env.Execute(Delete([
     'lib/_mypaintlib.so',
     ]))
 
+
 set_dir_postaction = {}
 def install_perms(env, target, sources, perms=0644, dirperms=0755):
     """As a normal env.Install, but with Chmod postactions.
 
-    The `target` parameter must be a string which starts with ``$prefix``.
-    Unless this is a sandbox install, the permission bits `dirperms` will be
-    set on every directory back to ``$prefix``, but not including it. `perms`
-    will always be set on each installed file from `sources`.
+    The `target` parameter must be a string starting with ``$prefix``.
+    The permissions in `perms` will be assigned to each file which was
+    installed from `sources` in a post-install action.
+
+    The `dirperms` permissions will be assigned to each created
+    directory component which does not exist (at the time of calling
+    this function). Each set of permission bits is assigned in its own
+    postaction.
+
     """
     assert target.startswith('$prefix')
     install_targs = env.Install(target, sources)
-    sandboxed = False
-    final_prefix = os.path.normpath(env["prefix"])
 
-    # Set file permissions.
+    # Set file permissions, and defer directory permission setting
     for targ in install_targs:
         env.AddPostAction(targ, Chmod(targ, perms))
-        targ_path = os.path.normpath(targ.get_path())
-        if not targ_path.startswith(final_prefix):
-            sandboxed = True
-
-    if not sandboxed:
-        # Set permissions on superdirs, back to $prefix (but not including it)
-        # Not sure if this is necessary with the umask forcing. It might help
-        # fix some broken installs.
-        for file_targ in install_targs:
-            d = os.path.normpath(target)
-            d_prev = None
-            while d != d_prev and d != '$prefix':
-                d_prev = d
-                if not set_dir_postaction.has_key(d):
-                    env.AddPostAction(file_targ, Chmod(d, dirperms))
-                    set_dir_postaction[d] = True
-                d = os.path.dirname(d)
-
+        d = os.path.dirname(os.path.normpath(targ.get_abspath()))
+        d_prev = None
+        while d != d_prev and not os.path.exists(d):
+            if not d in set_dir_postaction:
+                env.AddPostAction(targ, Chmod(d, dirperms))
+                set_dir_postaction[d] = True
+            d_prev = d
+            d = os.path.dirname(d)
+
+    # Return like Install()
     return install_targs
 
 
```

This is an ugly quick patch that applies over ./brushlib/ and ./ together; I'll prepare more conventional branches for this too.

and let me know if this relaxes the checks enough for you to support something like:

    $ scons prefix=/opt/frodo --install-sandbox=`pwd`/__SANDBOX__

and whatever you're doing with MacPorts.

Note that `prefix` has to be an absolute path with this patch, but it doesn't have to exist.

**Comment by achadwick** [comment] 2015-06-22 13:33
@ryandesign
Can you test whether the patch above makes scons work as you'd expect please? Alternatively, instead of applying a patch to your tree, you can check the branches I'm intending to merge:

* https://github.com/achadwick/mypaint/tree/mypaint-issue347-sconsfixes
* https://github.com/achadwick/libmypaint/tree/mypaint-issue347-sconsfixes

Quick get:

```sh
git clone --branch mypaint-issue347-sconsfixes https://github.com/achadwick/mypaint.git
cd mypaint
git submodule update --init --force
```

I've tested against Win7 and Debian testing/stretch, and with our [debian packaging](https://github.com/mypaint/debian) too, and all seems to work acceptably.

Quick summary of what this allows:

```
$ cd /home/yourself/mypaint
$ scons prefix=/opt/wibble --install-sandbox=/tmp/SANDBOX  /tmp/SANDBOX
               ^^^^[1]^^^^                   ^^^^^[2]^^^^  ^^^^[3]^^^^^
```

1. Your `prefix` arg will have to be absolute syntactically - but it doesn't have to exist before running scons now, and nor will it be created unless you actually tell SCons to build it (hurrah!)
2. Your `--install-sandbox` must still be an absolute path. You don't have to store it under the current working directory any more, but it does have to be inside the target (3)...
3. This target is required for most sandboxes, with the exception of ones under your current working directory - the default target is ".". What you can't do is use the "install" alias for this command line, because "/opt/wibble" is not something that scons knows how to build (it *does* know how to build /tmp/SANDBOX/opt/wibble though, while pretending that it's /opt/wibble for the purposes of `.pc` generation etc.)

**Comment by achadwick** [comment] 2015-06-24 10:38
@ryandesign Have you been able to test whether the patch/branches above work for you yet? I think it will get you what you want with a suitable combination of prefix string and sandbox root. It shouldn't be dabbling around outside destroot with the proposed changes, as you documented it doing in https://gna.org/bugs/?20399#comment5

I haven't seen any problems with it in my testing, so I would like to merge this code this evening.

**Comment by achadwick** [comment] 2015-06-24 10:39
Not really an upstream bug (with SCons).

**Comment by achadwick** [comment] 2015-06-25 15:18
Merged. Please test this and reopen if it's still an issue.

**Closed** 2015-06-25 15:17 UTC
Labels: osx
