### ISSUE TITLE
Wacom pen AWOL

### ISSUE THREAD

**Issue by LasaVecu** [mypaint/mypaint#963] opened 2019-02-04 01:22 UTC
#### Description of the problem

Trying MyPaint v1.2.1 on a Wacom pen computer (MobileStudio) under Windows 10 (64). All works well using my finger but the  Wacom pens are useless. If I use the pen in the upper left quadrant of the screen I see the effect about 3'' below and 1'' to the right of where the pen is.

Also working with Krita, Affinity Designer and Inkscape on the same Wacom. All of these work fine.

With best regards,  tiha

**Comment by odysseywestra** [comment] 2019-02-04 01:45
Are you having the same issues with the latest version of GIMP 2.8. If so
this may be an issue with GTK/GDK and you will need to report a bug
upstream.

**Comment by jensdheise** [comment] 2019-03-24 12:19
Same problem here on a HP zBook (Wacom Pen) with MyPaint v1.2.1 as well as MyPaint v2.0.0-alpha.
No problem with Gimp, Inkscape etc. . So following the GTK/GDK idea may be the wrong track.

**Comment by briend** [comment] 2019-03-24 15:45
Try to find the gtk3-demo in the program folder.  There is a drawing tablet test in there towards the bottom of the list.  Please find that and see if it works.  If it doesn't work it is almost surely a gtk3 problem.  Those other apps that are working are most likely not using gtk3, but rather QT or gtk2, etc

**Comment by jensdheise** [comment] 2019-03-24 17:32
Okay, same effect running the tablet test. Pressure works, drawing a dot in the top-left corner of the test area translates by about 2cm from the top and 1,5cm from the left. The scaling is wrong too by ~factor 2.
So sad :-(
Thanks anyway

**Comment by jplloyd** [comment] 2020-06-03 19:34
Duplicate of #743, #763, #830 (possible others).

**Closed by jplloyd** 2020-06-03 19:34 UTC
