### ISSUE TITLE
Missing icons even after faq missing icons workarounds

### ISSUE THREAD

**Issue by zockolade** [mypaint/mypaint#1084] opened 2020-05-28 12:55 UTC
#### Basic system details

MyPaint version: 2.0.0+gitexport.af5225a
Operating system: ArchLinux
Desktop environment:Xfce

#### Steps to reproduce

I have done this:
https://github.com/mypaint/mypaint/wiki/FAQ-Missing-icons

I also used:
sudo gtk-update-icon-cache -tf /usr/share/icons/hicolor

But it still look like the icons I marked red are missing:
https://pasteall.org/media/2/a/2a91123dc9901058efeece9edb555a05.jpg

#### Backtraces or error messages

When I am starting mypaint via terminal window I only see one Warning:

(mypaint:27321): Gtk-WARNING **: 14:46:38.900: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

**Comment by jplloyd** [comment] 2020-05-28 15:12
The problems are that librsvg 2.48 is stricter than earlier versions, and the icons in the 2.0.0 release that use refs (clones, in inkscape terminology) will fail to render due to not having xlink namespace declarations.

Duplicate of #1064 (same cause)

This is fixed in master and will be part of the 2.0.1 bugfix release, to be released tomorrow. I expect the Arch version will be updated within a few days after that.

**Closed by jplloyd** 2020-05-28 15:12 UTC
