### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by douglasdelate** [mypaint/mypaint#574] opened 2016-01-22 22:37 UTC
Hi,

I created a new design and fill the area with a color, this error occurred.

``` python
Mypaint version: 1.2.0+git.f62444e.dirty
System information: Windows-7-6.1.7601-SP1
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\share\mypaint\gui\colors\paletteview.py", line 669, _motion_notify_cb(self=<_PaletteGridLayout object at 0x7e88b40 (gui+colors+paletteview+_PaletteGridLayout at 0x69eb6a0)>, widget=<_PaletteGridLayout object at 0x7e88b40 (gui+colors+paletteview+_PaletteGridLayout at 0x69eb6a0)>, event=<void>)
            x, y = event.x, event.y
            i = self.get_index_at_pos(x, y)
            # Set the tooltip.
  variables: {'self.get_index_at_pos': ('local', <bound method _PaletteGridLayout.get_index_at_pos of <_PaletteGridLayout object at 0x7e88b40 (gui+colors+paletteview+_PaletteGridLayout at 0x69eb6a0)>>), 'i': (None, []), 'x': ('local', 25.0), 'y': ('local', 100.0)}
  File "C:\Program Files\MyPaint\share\mypaint\gui\colors\paletteview.py", line 1141, get_index_at_pos(self=<_PaletteGridLayout object at 0x7e88b40 (gui+colors+paletteview+_PaletteGridLayout at 0x69eb6a0)>, x=25.0, y=100.0, nearest=False, insert=False)
            # Calculate a raw row and column
            r = int((y-dy) // s_ht)
            c = int((x-dx) // s_wd)
  variables: {'int': ('builtin', <type 'int'>), 'dy': ('local', 3), 'y': ('local', 100.0), 's_ht': ('local', 17), 'r': (None, [])}
ValueError: cannot convert float NaN to integer
```

![image](https://cloud.githubusercontent.com/assets/16844965/12524912/bc1ea54e-c147-11e5-9195-75c872c02625.png)

Thank you for this beautiful program.
Douglas (Rio de Janeiro / Brasil)

**Comment by alexandre-mbm** [comment] 2016-01-23 03:01
Hello, @douglasdelate! If you speak portuguese and you are programmer, [contact me](mailto:alexandre.mbm@gmail.com) please.

**Comment by achadwick** [comment] 2016-01-23 19:08
@alexandre-mbm 
Please do not ask for private replies on public issues without at least giving a reason, and only post here if you're advancing the issue discussion directly and publicly. Thanks.

**Comment by achadwick** [comment] 2016-01-23 19:10
@douglasdelate 
Thank you for reporting. That's strange. I wonder why the bug is showing up in palette code. I'll try to reproduce the problem here, but I may need more information before it can be fixed.

Do you have an empty palette panel by any chance?

**Comment by achadwick** [comment] 2016-01-23 19:14
Cannot reproduce in master at 5170ffc5c93bc604bf0da621d3d0bdf9784b703c with an empty palette, or with a palette consisting only of empty slots, or with a palette with more columns than slots, or with a palette with 0 columns (= fill width).

**Comment by douglasdelate** [comment] 2016-01-24 02:32
hi @achadwick 

I downloaded yesterday My Paint, did some tests , I saved art and open a new project, I selected palettes : " HCY Wheel" , "Color Palette " and " Crossed Bowl" .
Randomly selected a color in " HCY " and scattered the area with the tool " Flood Fill " . The original project has iregular texture , so I made several fills with this tool. Realized how many steps , it is difficult to reproduce.

I also could not reproduce the error yet, but I will study this piece of code and figure out what happened.

I never programmed in Python , but I downloaded the sources for study. 
 
Let's find this dirty bug!

Thanks a lot

**Comment by achadwick** [comment] 2016-01-24 22:48
Sorry, looks like I closed this one by accident.

**Comment by achadwick** [comment] 2016-01-27 17:04
@douglasdelate have you got any further with this? I can't reproduce this at all with the reported values:

```python
>>> r = int((100.0-3) // 17)
>>> r
5
```

I can tell from the traceback that this happens when the mouse pointer is moving over the Color Palette, but no amount of clicking around makes this exception happen.

**Comment by ucyo** [comment] 2016-12-15 10:00
This looks like a `numpy` error ...

To reproduce the error message:
```python
arr = np.arange(12, dtype=int)
arr[0] = np.nan
```

**Comment by achadwick** [comment] 2016-12-15 10:13
@ucyo There shouldn't be anything numpy-related in the palette view code.

If no-one else can reproduce this error **as originally reported**, then I suggest we close it.

**Closed** 2020-06-03 19:09 UTC
Labels: exception, needs-info, works-for-me
