### ISSUE TITLE
Rotate layer feature and bucket fill improvements

### ISSUE THREAD

**Issue by freelanceear** [mypaint/mypaint#443] opened 2015-10-18 01:18 UTC
Rotating layers would be a very useful feature for adjusting sketches pre-paint. Moving layers is implemented, as is rotating the canvas view, so it just seems logical to be able to rotate layers. As for the implementation, I think holding Ctrl while moving a layer to rotate would work nicely.

Bucket fill would be a useful tool if you could grow the fill by 1 or 2 pixels so it properly fills things. As it is, even with finely-tuned tolerance, I always end up with a 1-pixel line of empty space. My workflow is to create clean edges with the inking tool, fill the shapes with bucket fill, then paint in detail with lock alpha channel. Having to remove the 1-pixel line for each shape really slows me down. I'm not good with code, but the process would probably be:
-determine where to fill
-grow the determined region by 1 pixel (similar to how GIMP lets you grow selections)
-fill
For UI, a tick box in the bucket fill options panel would work.

**Comment by achadwick** [comment] 2015-10-18 09:56
Hi, thanks for reporting! It's better to split issues into individual points, one per issue - we use this place as a bug and enhancement request tracker, that's why :smile: 

The first request is a duplicate of #31.

The second request is a duplicate of #73.

I've moved your comments over - can you subscribe to those issues and maybe brainstorm a bit? Thanks.

**Closed by achadwick** 2015-10-18 09:56 UTC
Labels: duplicate, enhancement
