### ISSUE TITLE
can't open mypaint

### ISSUE THREAD

**Issue by lottadfandoms** [mypaint/mypaint#669] opened 2016-05-01 03:00 UTC
**I've downloaded and tried both 64 and 32 versions, from here: https://github.com/mypaint/mypaint/releases
**
And installed nicely, but can't get either to open. Even with "run as administer". Maybe I'm doing something wrong? I've never been good with downloads that much, along with computers. Mind helping me out..?

**Comment by achadwick** [comment] 2016-05-01 03:08
Hi there - thanks for the feedback!

IMPORTANT: please do not use "Run as Administrator" for ordinary software.

This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help. Often the feedback is useful too, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you straight away here, but don't be discouraged if we can't. Issue trackers don't get that many views, sadly. You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/).

**Comment by achadwick** [comment] 2016-05-01 03:10
I don't know if this is a bug I can fix.

Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs). We need a lot more information about your system, and more information about your (attempted?) MyPaint installation if this report is going to be useful to us.

Please say what you downloaded. Include the version from either the file, or the about box if you got it to run.

Please say what OS (Linux, Mac OS, Windows, ...) you are using, and what version.

**Comment by achadwick** [comment] 2016-05-01 03:11
**TRIAGE NOTE:** looks like a user support request. This is the wrong forum for direct user support, reporter has been redirected to a better place to ask. This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status.

**Comment by danpla** [comment] 2016-05-01 10:26
I had the same problem after installing the v1.2.1-beta.0 after v1.2.0. It seems like the (un)installer of v1.2.0 does not remove all files completely.

@lottadfandoms Try to re-install MyPaint (after uninstallng the existing version, remove the `mypaint` directory from the `Program Files`, if any).

**Comment by danpla** [comment] 2016-05-01 11:38
Steps to reproduce (tested with 32-bit versions on Windows 7):

1. Install, run, and then uninstall [v1.2.0](https://github.com/mypaint/mypaint/releases/tag/v1.2.0)
2. Install [v1.2.1-beta.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1-beta.1)
3. Try to run via `cmd`:

    ```
c:\Program Files (x86)\MyPaint>bin\python2.exe bin\mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'c:\\Program Files (x86)\\MyPaint'
INFO: lib.i18n: Windows: LANG='ru_RU'
INFO: lib.i18n: Windows: LANGUAGE='ru_RU'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
Traceback (most recent call last):
  File "bin\mypaint", line 464, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "c:\Program Files (x86)\MyPaint\share\mypaint/gui/main.py", line 95, in main
    from gui import application
  File "c:\Program Files (x86)\MyPaint\share\mypaint/gui/application.py", line 48, in <module>
    import lib.document
  File "c:\Program Files (x86)\MyPaint\share\mypaint/lib/document.py", line 35, in <module>
    import numpy
  File "C:\Program Files (x86)\MyPaint\numpy\__init__.py", line 137, in <module>
  File "C:\Program Files (x86)\MyPaint\numpy\add_newdocs.py", line 9, in <module>
  File "C:\Program Files (x86)\MyPaint\numpy\lib\__init__.py", line 4, in <module>
  File "C:\Program Files (x86)\MyPaint\numpy\lib\type_check.py", line 8, in <module>
  File "C:\Program Files (x86)\MyPaint\numpy\core\__init__.py", line 5, in <module>
ImportError: No module named multiarray
```
4. Try to run via the MSYS/MinGW shell -> all is OK

To fix:

1. Uninstall `v1.2.1-beta.1`
2. Remove `c:\Program Files (x86)\MyPaint` manually (traces of `v1.2.0`)
3. Install `v1.2.1-beta.1` again

**Comment by tumagonx** [comment] 2016-05-01 11:54
might related to #572


On 5/1/16, Daniel Plachotich <notifications@github.com> wrote:
> Steps to reproduce (tested with 32-bit versions on Windows 7):
>
> 1. Install, run, and then uninstall
> [v1.2.0](https://github.com/mypaint/mypaint/releases/tag/v1.2.0)
> 2. Install
> [v1.2.1-beta.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1-beta.1)
> 3. Try to run via `cmd`:
>
>     ```
> c:\Program Files (x86)\MyPaint>bin\python2.exe bin\mypaint
> INFO: mypaint: Installation layout: conventional POSIX-like structure with
> prefix u'c:\\Program Files (x86)\\MyPaint'
> INFO: lib.i18n: Windows: LANG='ru_RU'
> INFO: lib.i18n: Windows: LANGUAGE='ru_RU'
> WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
> INFO: mypaint: Trying platform-specific fallback hacks to find
> bindtextdomain funcs.
> INFO: mypaint: Windows: found working bindtextdomain funcs in
> 'libintl-8.dll' (ctypes)
> Traceback (most recent call last):
>   File "bin\mypaint", line 464, in <module>
>     main.main(datapath, iconspath, old_confpath, version=version)
>   File "c:\Program Files (x86)\MyPaint\share\mypaint/gui/main.py", line 95,
> in main
>     from gui import application
>   File "c:\Program Files (x86)\MyPaint\share\mypaint/gui/application.py",
> line 48, in <module>
>     import lib.document
>   File "c:\Program Files (x86)\MyPaint\share\mypaint/lib/document.py", line
> 35, in <module>
>     import numpy
>   File "C:\Program Files (x86)\MyPaint\numpy\__init__.py", line 137, in
> <module>
>   File "C:\Program Files (x86)\MyPaint\numpy\add_newdocs.py", line 9, in
> <module>
>   File "C:\Program Files (x86)\MyPaint\numpy\lib\__init__.py", line 4, in
> <module>
>   File "C:\Program Files (x86)\MyPaint\numpy\lib\type_check.py", line 8, in
> <module>
>   File "C:\Program Files (x86)\MyPaint\numpy\core\__init__.py", line 5, in
> <module>
> ImportError: No module named multiarray
> ```
> 4. Try to run via the MSYS/MinGW shell -> all is OK
>
> To fix:
>
> 1. Uninstall `v1.2.1-beta.1`
> 2. Remove `c:\Program Files (x86)\MyPaint` manually (traces of `v1.2.0`)
> 3. Install `v1.2.1-beta.1` again
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/669#issuecomment-216036277


-- 
!tuma

**Comment by tumagonx** [comment] 2016-05-01 11:57
since I don't bundle pyo/pyc / generate them at install, they are
excluded by inno

On 5/1/16, Bakhtiar Hasmanan <mr.tiar@gmail.com> wrote:
> might related to #572
>
>
> On 5/1/16, Daniel Plachotich <notifications@github.com> wrote:
>> Steps to reproduce (tested with 32-bit versions on Windows 7):
>>
>> 1. Install, run, and then uninstall
>> [v1.2.0](https://github.com/mypaint/mypaint/releases/tag/v1.2.0)
>> 2. Install
>> [v1.2.1-beta.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1-beta.1)
>> 3. Try to run via `cmd`:
>>
>>     ```
>> c:\Program Files (x86)\MyPaint>bin\python2.exe bin\mypaint
>> INFO: mypaint: Installation layout: conventional POSIX-like structure
>> with
>> prefix u'c:\\Program Files (x86)\\MyPaint'
>> INFO: lib.i18n: Windows: LANG='ru_RU'
>> INFO: lib.i18n: Windows: LANGUAGE='ru_RU'
>> WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
>> INFO: mypaint: Trying platform-specific fallback hacks to find
>> bindtextdomain funcs.
>> INFO: mypaint: Windows: found working bindtextdomain funcs in
>> 'libintl-8.dll' (ctypes)
>> Traceback (most recent call last):
>>   File "bin\mypaint", line 464, in <module>
>>     main.main(datapath, iconspath, old_confpath, version=version)
>>   File "c:\Program Files (x86)\MyPaint\share\mypaint/gui/main.py", line
>> 95,
>> in main
>>     from gui import application
>>   File "c:\Program Files (x86)\MyPaint\share\mypaint/gui/application.py",
>> line 48, in <module>
>>     import lib.document
>>   File "c:\Program Files (x86)\MyPaint\share\mypaint/lib/document.py",
>> line
>> 35, in <module>
>>     import numpy
>>   File "C:\Program Files (x86)\MyPaint\numpy\__init__.py", line 137, in
>> <module>
>>   File "C:\Program Files (x86)\MyPaint\numpy\add_newdocs.py", line 9, in
>> <module>
>>   File "C:\Program Files (x86)\MyPaint\numpy\lib\__init__.py", line 4, in
>> <module>
>>   File "C:\Program Files (x86)\MyPaint\numpy\lib\type_check.py", line 8,
>> in
>> <module>
>>   File "C:\Program Files (x86)\MyPaint\numpy\core\__init__.py", line 5,
>> in
>> <module>
>> ImportError: No module named multiarray
>> ```
>> 4. Try to run via the MSYS/MinGW shell -> all is OK
>>
>> To fix:
>>
>> 1. Uninstall `v1.2.1-beta.1`
>> 2. Remove `c:\Program Files (x86)\MyPaint` manually (traces of `v1.2.0`)
>> 3. Install `v1.2.1-beta.1` again
>>
>> ---
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/mypaint/mypaint/issues/669#issuecomment-216036277
>
>
> --
> !tuma
>


-- 
!tuma

**Comment by achadwick** [comment] 2016-05-01 17:30
@lottadfandoms
Can you confirm that @danpla's suggestion is a workaround for you?

@danpla @tumagonx
for what it's worth, I don't see any traces of lingering 1.2.0 in Program Files when I test in Win7. Both w32 and w64 versions of MyPaint.

Would it matter that I normally don't use an admin account to run MyPaint?

**Comment by AnTi-ArT** [comment] 2016-05-11 16:30
I can confirm this. Win10, 64, version 1.2.1-beta 1. Uninstall via Windows Settings did not remove everything, I got the same multiarray module missing error.

Uninstall + Manual folder delete did indeed fix it for me.
Thanks!

**Comment by achadwick** [comment] 2016-05-29 16:11
Closing because the original reporter has not updated with any information or confirmed the suggested workarounds. Other comments may be other things or they may not. We'll never know.

This issue tracker is not the right place for general rolling user support threads unless the request can be rapidly turned into a good bug report.

**Closed by achadwick** 2016-05-29 16:11 UTC
Labels: needs-info, user-support
