### ISSUE TITLE
MyPaint won't run. "GLib arguments" error

### ISSUE THREAD

**Issue by cyber-doug** [mypaint/mypaint#726] opened 2016-08-17 06:25 UTC
MyPaint tries to run but fails with the following output from the terminal:
![captura de tela de 2016-08-17 03-13-38](https://cloud.githubusercontent.com/assets/20234673/17726411/28f928e0-6429-11e6-9f86-150a72056f62.png)

#### Basic system details
MyPaint version: 1.2.0-3
Operating System: Solus 1.2.1 (recently changed to rolling release)
Desktop Environment: Budgie 10.2.6-91

I was able to run MyPaint before Solus changed to kernel 4.7 and pushed some other important updates. Not sure if it could be related to the distribution. Now it won't run. All I see is the mouse pointer playing a loading animation until it stops and nothing happens. It is always reproducible.

#### Backtraces or error messages

```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
INFO: lib.i18n: POSIX: LANG='pt_BR.utf8'
INFO: lib.i18n: POSIX: LANGUAGE=None
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 462, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/usr/share/mypaint/gui/main.py", line 92, in main
    lib.glib.init_user_dir_caches()
  File "/usr/share/mypaint/lib/glib.py", line 109, in init_user_dir_caches
    logger.debug("Init g_get_user_config_dir(): %r", get_user_config_dir())
  File "/usr/share/mypaint/lib/glib.py", line 71, in get_user_config_dir
    return filename_to_unicode(d_fs)
  File "/usr/share/mypaint/lib/glib.py", line 57, in filename_to_unicode
    ustring = GLib.filename_to_utf8(opsysstring, -1, 0, 0)
TypeError: GLib.filename_to_utf8() takes exactly 2 arguments (4 given)
```

**Comment by achadwick** [comment] 2016-08-17 11:49
Duplicate of #634.

**Closed by achadwick** 2016-08-17 11:49 UTC
Labels: duplicate
