### ISSUE TITLE
No ora preview (Old ora saves from MyPaint 1.0). Windows 64, 1.2 beta 0.73.

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#382] opened 2015-07-29 09:57 UTC
In new version i don't have error messages. All is working. But when i open files, i dont see preview for ora. I can see preview for png and jpeg (in beta 0 no preview for all files, now only ora). Old ora saves from MyPaint 1.0.

And i dont have association in windows with ora files for mypaint. MyPaint 1.0 had associations, 1.2 dont have. Now ora files associated with krita.

**Comment by achadwick** [comment] 2015-07-29 10:02
File associations would be nice to have, but let's handle that in a separate issue: #383

**Comment by achadwick** [comment] 2015-07-29 10:04
Just to confirm: @zb13y, is this in the dialog you see when you do File → Open or similar?

Please tell me what version of Windows you are using.

**Comment by zb13y** [comment] 2015-07-29 10:10
Yes, File-Open. Windows 7 x64.

**Comment by Teyphas** [comment] 2015-07-29 11:11
@zb13y Try this. Open file which has no preview, then simply re-save it and check it again. Works for me.

**Comment by zb13y** [comment] 2015-07-29 11:20
Hm... that works. Is it ora in 1.0 and 1.2 different? Ora 1.0 - 30 mb, ora 1.2 - 45 mb.

**Comment by achadwick** [comment] 2015-07-29 11:27
There's a `mergedimage.png` in the more recent format, which will bulk it up. It's a rendering of the entire document's content, requested by the Krita developers as an insurance against data loss in the case of us breaking the layer model :)

Nested layers or the new layer types don't introduce any data overhead.

**Comment by achadwick** [comment] 2015-07-29 11:42
On my system at least, MyPaint stores them in "%LOCALAPPDATA%\Microsoft\Windows\Temporary Internet Files\thumbnails". This location has probably changed since v1.0.x.

This issue can be reproduced by deleting all subfolders in that thumbnails area, and then starting MyPaint. Browse to wherever you keep your scraps, and click on some files when trying to open them.

The thumbnail for an OpenRaster file can be regenerated by opening it and then saving it. But you shouldn't have to do that.

Perhaps more seriously, when you have a mix of openraster files with thumbnails and ones without in the same folder, the preview state "sticks" to the last non-NULL cache entry encountered since the dialog was opened. This means that you may get the wrong preview for a file when opening it.

Possibly the open and save dialogs should attempt to (re-)thumbnail .ora files as they go, but only by looking at `Thumbnails/thumbnail.png` or (in extremis) `mergedimage.png`. There's a datestamp-based logic to the way FreeDesktop.org thumbs work, so we shouldn't have to do much work.

**Comment by achadwick** [comment] 2015-07-29 11:57
Worth doing for 1.2.0 if we have time: there's no especially good workaround, tempfiles like these can disappear at any time, and the bad update thing is actively misleading on all platforms.

**Comment by achadwick** [comment] 2015-07-29 11:57
Hopefully bitesized too.

**Closed** 2015-07-31 23:15 UTC
Labels: bitesize, bug, windows
