### ISSUE TITLE
[Wayland] Segfault when attempting to drag certain child windows

### ISSUE THREAD

**Issue by jigpu** [mypaint/mypaint#811] opened 2017-06-08 17:51 UTC
#### Description of the problem

If certain child windows are opened, MyPaint immediately crashes with a segfault if the user attempts to drag the window to another location. Other windows are unaffected. A partial list is included below:

*Works Fine:*
 * Preferences
 * Background Chooser

*Causes Segfault:*
 * Test Input Devices
 * Brush Settings Editor
 * Brush Icon Editor

#### Basic system details

MyPaint version: 1.3.0-alpha+git.be1fe883
Operating system: Arch Linux
Desktop environment: GNOME (Wayland session)
Packages: Python 2.7.13, GTK 3.22.15, GdkPixbuf 2.36.6, Cairo 1.14.8, GLib 2.52.1

#### Steps to reproduce

1. Start MyPaint
2. Open one of the windows listed above by selecting them from the "Window" menu.
3. Attempt to drag the window around
4. If the window is in the "Works Fine" list, no problem is encountered. If the window is in the "Cuases Segfault" list, the program crashes with a segfault.

#### Backtraces or error messages
The following backtrace was captured after attempting to drag the "Test Input Devices" window. No errors were logged by MyPaint prior to the segfault.

```
jgerecke@wacom-arch2 /home/jgerecke $ sudo coredumpctl gdb 31189
           PID: 31189 (python2.7)
           UID: 1000 (jgerecke)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Thu 2017-06-08 10:36:41 PDT (30s ago)
  Command Line: python2.7 /usr/bin/mypaint
    Executable: /usr/bin/python2.7
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (jgerecke)
       Boot ID: 0e9d647a0a29400c8036e7a75a820d9a
    Machine ID: e1d94bea39f3051220e6366b00000a96
      Hostname: wacom-arch2
       Storage: /var/lib/systemd/coredump/core.python2\x2e7.1000.0e9d647a0a29400c8036e7a75a820d9a.31189.1496943401000000000000.lz4
       Message: Process 31189 (python2.7) of user 1000 dumped core.
                
                Stack trace of thread 31189:
                #0  0x00007fee69b00319 wl_proxy_marshal (libwayland-client.so.0)
                #1  0x00007fee6baa5003 n/a (libgdk-3.so.0)
                #2  0x00007fee64610d91 n/a (libgtk-3.so.0)
                #3  0x00007fee6d8e01c8 ffi_call_unix64 (libffi.so.6)
                #4  0x00007fee6d8dfc2a ffi_call (libffi.so.6)
                #5  0x00007fee6de07c8a g_cclosure_marshal_generic_va (libgobject-2.0.so.0)
                #6  0x00007fee6de071a4 n/a (libgobject-2.0.so.0)
                #7  0x00007fee6de218cd g_signal_emit_valist (libgobject-2.0.so.0)
                #8  0x00007fee6de21fbf g_signal_emit (libgobject-2.0.so.0)
                #9  0x00007fee6de09d27 g_cclosure_marshal_VOID__BOXEDv (libgobject-2.0.so.0)
                #10 0x00007fee6de071a4 n/a (libgobject-2.0.so.0)
                #11 0x00007fee6de218cd g_signal_emit_valist (libgobject-2.0.so.0)
                #12 0x00007fee6de21fbf g_signal_emit (libgobject-2.0.so.0)
                #13 0x00007fee64463495 n/a (libgtk-3.so.0)
                #14 0x00007fee644661bd n/a (libgtk-3.so.0)
                #15 0x00007fee644335ae gtk_event_controller_handle_event (libgtk-3.so.0)
                #16 0x00007fee64610320 n/a (libgtk-3.so.0)
                #17 0x00007fee646103b2 n/a (libgtk-3.so.0)
                #18 0x00007fee644ac9f1 gtk_main_do_event (libgtk-3.so.0)
                #19 0x00007fee6ba41d65 n/a (libgdk-3.so.0)
                #20 0x00007fee6ba9d8f2 n/a (libgdk-3.so.0)
                #21 0x00007fee6db2d7b7 g_main_context_dispatch (libglib-2.0.so.0)
                #22 0x00007fee6db2da20 n/a (libglib-2.0.so.0)
                #23 0x00007fee6db2dd42 g_main_loop_run (libglib-2.0.so.0)
                #24 0x00007fee644abed5 gtk_main (libgtk-3.so.0)
                #25 0x00007fee6d8e01c8 ffi_call_unix64 (libffi.so.6)
                #26 0x00007fee6d8dfc2a ffi_call (libffi.so.6)
                #27 0x00007fee6e2a974c n/a (_gi.so)
                #28 0x00007fee6e2ab258 n/a (_gi.so)
                #29 0x00007fee72346682 PyObject_Call (libpython2.7.so.1.0)
                #30 0x00007fee723e4503 PyEval_EvalFrameEx (libpython2.7.so.1.0)
                #31 0x00007fee723e88dc PyEval_EvalCodeEx (libpython2.7.so.1.0)
                #32 0x00007fee723e4d02 PyEval_EvalFrameEx (libpython2.7.so.1.0)
                #33 0x00007fee723e88dc PyEval_EvalCodeEx (libpython2.7.so.1.0)
                #34 0x00007fee723e4d02 PyEval_EvalFrameEx (libpython2.7.so.1.0)
                #35 0x00007fee723e88dc PyEval_EvalCodeEx (libpython2.7.so.1.0)
                #36 0x00007fee723e89e8 PyEval_EvalCode (libpython2.7.so.1.0)
                #37 0x00007fee72402efe run_mod (libpython2.7.so.1.0)
                #38 0x00007fee724041c1 PyRun_FileExFlags (libpython2.7.so.1.0)
                #39 0x00007fee724054e4 PyRun_SimpleFileExFlags (libpython2.7.so.1.0)
                #40 0x00007fee72417ca0 Py_Main (libpython2.7.so.1.0)
                #41 0x00007fee71d5743a __libc_start_main (libc.so.6)
                #42 0x0000563072c5c7ea _start (python2.7)
                
                Stack trace of thread 31197:
                #0  0x00007fee71e1f3b9 syscall (libc.so.6)
                #1  0x00007fee6db7344a g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fee6db01f49 n/a (libglib-2.0.so.0)
                #3  0x00007fee6db0256c g_async_queue_timeout_pop (libglib-2.0.so.0)
                #4  0x00007fee6db55d5d n/a (libglib-2.0.so.0)
                #5  0x00007fee6db55295 n/a (libglib-2.0.so.0)
                #6  0x00007fee720e3297 start_thread (libpthread.so.0)
                #7  0x00007fee71e2425f __clone (libc.so.6)
                
                Stack trace of thread 31190:
                #0  0x00007fee71e1a2bd poll (libc.so.6)
                #1  0x00007fee6db2d9b6 n/a (libglib-2.0.so.0)
                #2  0x00007fee6db2dacc g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fee6650455d n/a (libdconfsettings.so)
                #4  0x00007fee6db55295 n/a (libglib-2.0.so.0)
                #5  0x00007fee720e3297 start_thread (libpthread.so.0)
                #6  0x00007fee71e2425f __clone (libc.so.6)
                
                Stack trace of thread 31191:
                #0  0x00007fee71e1a2bd poll (libc.so.6)
                #1  0x00007fee6db2d9b6 n/a (libglib-2.0.so.0)
                #2  0x00007fee6db2dacc g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fee6db2db11 n/a (libglib-2.0.so.0)
                #4  0x00007fee6db55295 n/a (libglib-2.0.so.0)
                #5  0x00007fee720e3297 start_thread (libpthread.so.0)
                #6  0x00007fee71e2425f __clone (libc.so.6)
                
                Stack trace of thread 31192:
                #0  0x00007fee71e1a2bd poll (libc.so.6)
                #1  0x00007fee6db2d9b6 n/a (libglib-2.0.so.0)
                #2  0x00007fee6db2dd42 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fee6d40cf86 n/a (libgio-2.0.so.0)
                #4  0x00007fee6db55295 n/a (libglib-2.0.so.0)
                #5  0x00007fee720e3297 start_thread (libpthread.so.0)
                #6  0x00007fee71e2425f __clone (libc.so.6)

GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python2.7...(no debugging symbols found)...done.
[New LWP 31189]
[New LWP 31197]
[New LWP 31190]
[New LWP 31191]
[New LWP 31192]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `python2.7 /usr/bin/mypaint'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fee69b00319 in wl_proxy_marshal () from /usr/lib/libwayland-client.so.0
[Current thread is 1 (Thread 0x7fee728d0440 (LWP 31189))]
(gdb) 
```

**Comment by achadwick** [comment] 2017-06-10 11:43
This is more than a little weird. Can you let me know the GNOME and Wayland versions?

I don't use Wayland because `gdk_window_set_event_compression(win, FALSE)` is broken as of  xwayland 1.19.2-1 + gnome-core 3.22. I'd appreciate a little digging into this: is the behaviour affected by particular window flags?

**Comment by achadwick** [comment] 2017-06-10 11:49
Please can you rebuild with debugging-enabled Python, GTK, and GLib, and get me a `bt full` from `gdb`?

This smells an awful lot like an upstream bug with Wayland, since it's not happening (or it hasn't been reported) with the Windows or X11 backends.

**Comment by achadwick** [comment] 2017-06-10 11:49
Oops, wrong button. Sorry!

**Comment by jigpu** [comment] 2017-06-13 17:21
I've attached the output of `bt full` for the same "Test Input Devices" reproduction for review:
 [mypaint_bug_811_bt_full.txt](https://github.com/mypaint/mypaint/files/1072276/mypaint_bug_811_bt_full.txt)

Poking around in the source a little, I see the following:

````
(gdb) frame 2
#2  gdk_wayland_window_begin_move_drag (window=<optimized out>, device=0xabe160 [GdkWaylandDevice], button=<optimized out>, root_x=<optimized out>, root_y=<optimized out>, timestamp=<optimized out>)
    at gdkwindow-wayland.c:3498
3498	  zxdg_toplevel_v6_move (impl->display_server.xdg_toplevel,
(gdb) list gdk_wayland_window_begin_move_drag
3477	                                    GdkDevice *device,
3478	                                    gint       button,
3479	                                    gint       root_x,
3480	                                    gint       root_y,
3481	                                    guint32    timestamp)
3482	{
3483	  GdkWindowImplWayland *impl;
3484	  GdkEventSequence *sequence;
3485	  uint32_t serial;
3486	
3487	  if (GDK_WINDOW_DESTROYED (window) ||
3488	      !WINDOW_IS_TOPLEVEL (window))
3489	    return;
3490	
3491	  impl = GDK_WINDOW_IMPL_WAYLAND (window->impl);
3492	
3493	  if (!impl->display_server.xdg_surface)
3494	    return;
3495	
3496	  serial = _gdk_wayland_seat_get_last_implicit_grab_serial (gdk_device_get_seat (device),
3497	                                                            &sequence);
3498	  zxdg_toplevel_v6_move (impl->display_server.xdg_toplevel,
3499	                         gdk_wayland_device_get_wl_seat (device),
3500	                         serial);
3501	  if (sequence)
3502	    gdk_wayland_device_unset_touch_grab (device, sequence);
3503	
3504	  /* This is needed since Wayland will absorb all the pointer events after the
3505	   * above function - FIXME: Is this always safe..?
3506	   */
3507	  gdk_seat_ungrab (gdk_device_get_seat (device));
3508	}
(gdb) p impl->display_server
$1 = {outputs = 0x2807480 = {0xaed0c0}, wl_surface = 0x27f1820, xdg_surface = 0x130bd60, xdg_toplevel = 0x0, xdg_popup = 0x209d850, gtk_surface = 0x0, wl_subsurface = 0x0, egl_window = 0x0, 
  dummy_egl_window = 0x0, xdg_exported = 0x0}
````

It appears that Wayland's [xdg-shell protocol](https://github.com/wayland-project/wayland-protocols/blob/master/unstable/xdg-shell/xdg-shell-unstable-v6.xml) only provides a "move" request for toplevel windows. The "Test Input Devices" window is apparently being mapped as a popup, however (the `window.SubWindow` parent class sets `Gdk.WindowTypeHint.UTILITY` which the GTK3 `./gdk/wayland/gdkwindow-wayland.c:should_map_popup()` function sometimes treats as a popup).

I agree that this sounds like an upstream bug: if it is only possible to move toplevel windows, the toolkit should verify at some point that it's working with a toplevel window before going off the rails.

**Comment by manuq** [comment] 2017-06-16 21:05
I can't reproduce the issue. Dragging the mentioned child windows works fine for me, both with mouse and stylus.  Fedora 25 running Wayland.

**Comment by jigpu** [comment] 2017-06-19 18:55
It seems that [GNOME Bug 781945](https://bugzilla.gnome.org/show_bug.cgi?id=781945) is the corresponding upstream bug. Applying the two patches from that bug on top of Arch's GTK3 package fixes this issue.

**Comment by achadwick** [comment] 2017-06-19 20:59
Thanks for the investigation, @jigpu!

Closing as upstream (and linked), but if MyPaint is indeed incorrectly configured (doubtful, since GDK_WINDOW_TYPE_HINT_UTILITY is a sensible hint for some transient toplevels and I've no reason to suspect otherwise), I'm happy to accept patches with a good case for removing the hint :smile:

**Closed by achadwick** 2017-06-19 20:59 UTC
Labels: crasher, needs-info, upstream
