### ISSUE TITLE
Odd look of toolbars in Ubuntu 16.04

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#684] opened 2016-05-19 20:41 UTC
The toolbar buttons in Layer and Scratchpad docks are not looking well. Buttons have spacings and irregular border:

![image](https://cloud.githubusercontent.com/assets/4038431/15408722/4982a406-1e1a-11e6-9c1f-63a6c568c8a0.png)

MyPaint version: 1.3.0-alpha+git.1fc6f4c
OS: Ubuntu 16.04 x64
libgtk-3.so.0.1800.9

This is how it appeared in Ubuntu 15.10:

![image](https://cloud.githubusercontent.com/assets/4038431/15408796/af80d124-1e1a-11e6-88ee-3eeac233130d.png)

**Comment by achadwick** [comment] 2016-05-19 22:48
The theme is not drawing inline-toolbar properly.

* Please show me the `+` and `-` in Preferences → Buttons.
* Please show me these buttons in the _gtk3-widget-factory_ demo (the ones marked as "B"; they're on Page 2):
  ![inlinebar](https://cloud.githubusercontent.com/assets/61299/15411973/e9572172-1e1b-11e6-8777-f1f9d2d732e7.png)

**Comment by achadwick** [comment] 2016-05-19 22:48
TRIAGE: upstream theming issue. Let's just establish that MyPaint is doing everything correctly here.

**Comment by loentar** [comment] 2016-05-20 08:38
Unfortunately my demo does not have such toolbar. But I found similar toolbar in another place, please see screenshot, here is the +- buttons from settings too:

![image](https://cloud.githubusercontent.com/assets/4038431/15421711/74b36bc0-1e7d-11e6-9ef0-ca4b8162248e.png)

Looks like only two right toolbar buttons in MyPaint displays correctly.. Could this be a bug in python GTK3 binding, how can I check it?

**Comment by achadwick** [comment] 2016-05-20 11:59
Very unlikely to be a binding issue.

We set those toolbars up in hopefully a fairly standard way, through a factory function [gui.widgets.inline_toolbar() at gui/widgets.py#L87](https://github.com/mypaint/mypaint/blob/ff04196abe80a769b9cecf0ef80d3072b767bb8c/gui/widgets.py#L87).
Try messing with that code! You could try removing the homogeneous or expand settings. :wrench: 

It's called from here: [gui/layerswindow.py#L190](https://github.com/mypaint/mypaint/blob/c07bf455e54e0c3516f52a1bb58882b244e05843/gui/layerswindow.py#L190) and here: [gui/scratchwindow.py#L46](https://github.com/mypaint/mypaint/blob/c07bf455e54e0c3516f52a1bb58882b244e05843/gui/scratchwindow.py#L46).

Speculation: we've had some problems with the packing before: #536. Maybe that little toolbar just has too many items. Does the problem go away if you make the sidebar wider?

**Comment by achadwick** [comment] 2016-05-20 11:59
What about the button mapping editor (Preferences → Buttons)? Does that appear OK? :eyes: 

The button mapping editor uses a similar mini-toolbar for its `+` and `-` buttons, but it doesn't use our factory function: see [gui/buttonmap.py#L304](https://github.com/mypaint/mypaint/blob/c07bf455e54e0c3516f52a1bb58882b244e05843/gui/buttonmap.py#L304).

If the button editor looks OK in MyPaint on 16.04 right now, that's a sign that the factory function needs fixing.

**Comment by loentar** [comment] 2016-05-20 12:25
Button mapping editor looks OK, It's visible from previously attached screenshot.
Also I noticed that two right buttons are always appear OK...

Making toolbar wider does not change anything.
![image](https://cloud.githubusercontent.com/assets/4038431/15427551/95bbf276-1e9e-11e6-9faf-ad3f2a7fc7ca.png)

I will try to play with the code you suggested, thanks .

**Comment by achadwick** [comment] 2016-05-20 13:09
>  two right buttons are always appear OK...

That's interesting; perhaps the theme only expects there to ever be two buttons.

The buttons look fine in Adwaita, but I'm happy to accept a patch to make them look OK with other themes.

**Comment by loentar** [comment] 2016-05-20 13:38
I use the same default Ubuntu theme (Ambiance) as in Ubuntu 14.04, 15.10 (which worked). Not sure if this theme bug, because gtk3-widget-factory show three toolbar buttons correctly.

**Comment by danpla** [comment] 2016-05-20 14:38
What if to play with these properties:
[gui/widgets.py#L103-L104](https://github.com/mypaint/mypaint/blob/ff04196abe80a769b9cecf0ef80d3072b767bb8c/gui/widgets.py#L103-L104)

**Comment by loentar** [comment] 2016-05-21 14:01
Thanks for suggestions.. I tried it all, but without any success.

Also this is reproducible for the very simple example on Python, so this is definitely not a MyPaint bug:

```Python
#! /usr/bin/python3
from gi.repository import Gtk
win = Gtk.Window()
toolbar = Gtk.Toolbar()
toolbar.set_property("icon_size",1)
context = toolbar.get_style_context()
context.add_class(Gtk.STYLE_CLASS_INLINE_TOOLBAR)
toolbar.set_show_arrow(False)

toolitem = Gtk.ToolButton()
toolitem.set_property("icon_name","list-add-symbolic")
toolitem2 = Gtk.ToolButton()
toolitem2.set_property("icon_name","list-add-symbolic")
toolitem3 = Gtk.ToolButton()
toolitem3.set_property("icon_name","list-add-symbolic")

toolbar.insert(toolitem, -1)
toolbar.insert(toolitem2, -1)
toolbar.insert(toolitem3, -1)
win.add(toolbar)
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```

I tried this example on Ubuntu 16.04 started from LiveCD the result is the same for 3 buttons:

![image](https://cloud.githubusercontent.com/assets/4038431/15448796/93ac2b0a-1f74-11e6-84f2-3caaba555f7b.png)

and OK for two buttons:
![image](https://cloud.githubusercontent.com/assets/4038431/15448798/ab2a9a78-1f74-11e6-94d7-70a6f834767a.png)


Also I noticed that keyboard toolbar in System settings has been splitted by 2 buttons:
![image](https://cloud.githubusercontent.com/assets/4038431/15448804/cf868a76-1f74-11e6-8ff1-cb208493ba12.png)


Previously it looked like this:

![image](https://cloud.githubusercontent.com/assets/4038431/15448823/4d72d1d8-1f75-11e6-9810-aebf3695ff30.png)

It makes me think..

**Comment by danpla** [comment] 2016-05-21 14:22
@loentar 
What if to add "linked" class:
```python
# ...
context.add_class(Gtk.STYLE_CLASS_INLINE_TOOLBAR)
context.add_class('linked')
# ...
```

**Comment by achadwick** [comment] 2016-05-21 20:28
Fired up a xenial VM to test @loentar's test code.

`Gtk.STYLE_CLASS_LINKED` on either the toolbar, or on any of the items doesn't seem to fix it. Neither in addition to any existing style classes, nor replacing them.

The _CSS Theming → Style Classes_ tester in `gtk3-demo` confirms that it's a general problem with GtkToolbars styled as "inline-toolbar". It also hints that "linked" GtkBoxes may offer a way forward:

![screenshot](https://cloud.githubusercontent.com/assets/61299/15450689/77535570-1f9a-11e6-8d46-45df0ecd4675.png)

**Comment by loentar** [comment] 2016-05-21 20:56
Yes, I saw this example.. It looks exactly as yours when installed from repo..

But if it's compiled from source (e.g. `apt source gtk-3-examples && ./configure && make`) It looks like this:

![image](https://cloud.githubusercontent.com/assets/4038431/15450800/78fd0ce4-1faf-11e6-96a7-b3fad00a49a9.png)

Don't have any idea why..

**Comment by achadwick** [comment] 2016-05-21 21:24
There's a *vertical* linked box in gtk3-widget-factory, page 3. It doesn't render properly with Xenial Ambance either, but it's fine with Debian testing's 3.20.4 Adwaita.

![scrreenshot](https://cloud.githubusercontent.com/assets/61299/15450855/afa005a2-1fa1-11e6-96b8-f964f0475668.png)
-- Xenial gtk3-widget-factory, Ambiance theme

**Comment by achadwick** [comment] 2016-05-21 21:24
@loentar That's Adwaita, I think - the GNOME and GTK3 default.

![screenshot](https://cloud.githubusercontent.com/assets/61299/15450888/927ae3e2-1fa2-11e6-8d44-ca9cf4aa2987.png)
-- GTK 3.20 and Adwaita theme, gtk3-demo

**Comment by achadwick** [comment] 2016-05-21 21:34
Reported upstream as a Question:
https://answers.launchpad.net/ubuntu/+source/light-themes/+question/294023
Let's let them confirm and make it a bug. Please comment on it there.

I'm pretty certain this regression is actually a bug in Ubuntu's `light-themes` package (Radiance and Ambience themes), so I'm closing this issue. We can reopen it or make a new issue if it turns out that MyPaint has been abusing GTK theming all along.

Patches welcome for simplifying the code and using Gtk(H)Box instead with "linked". Groups of those look more flexible tbh.

**Closed by achadwick** 2016-05-21 21:34 UTC
Labels: needs-info, upstream

**Comment by achadwick** [comment] 2016-06-06 13:26
No response for the question, so I reported it as a bug. I guess that's the default approach to take when reporting at Launchpad :unamused:

**Reported upstream: [Launchpad bug #1589494](https://bugs.launchpad.net/bugs/1589494)**

**Comment by danpla** [comment] 2016-06-06 13:58
Maybe it's something Gtk-related. Here are two screenshots from Xubunu 16.04:
Greybird theme:
![1s](https://cloud.githubusercontent.com/assets/10910745/15824292/2ee767c6-2c07-11e6-87b9-7f5ca555e51b.png)
Hight Contrast theme:
![2](https://cloud.githubusercontent.com/assets/10910745/15824303/3ca22018-2c07-11e6-9569-7138ed63ae37.png)
