### ISSUE TITLE
Brush settings editor window extends indefinitely

### ISSUE THREAD

**Issue by mccouto** [mypaint/mypaint#605] opened 2016-02-18 03:38 UTC
It is impossible to use the controls in the Brush Settings Editor. Using the slider in the settings bar the brush settings editor window extends indefinitely. This happens in Xubuntu 14.04.3  Mypaint 1.2.0 + gitexport.f62444e installed with PPA: achadwick / MyPaint-testing
Steps to reproduce the bug:
1- choose a brush.
2- open the Brush Settings Editor
3- try to move the tools configuration sliders. The Brush Settings Editor window will increase indefinitely.

See it here:
https://youtu.be/pp7B1PtE2Fo

**Comment by achadwick** [comment] 2016-02-18 11:20
Hi @mccouto, thanks for reporting!

I've tested with a recently updated Xubuntu 14.04 in a VM using a reasonably standard DE configuration. I cannot reproduce this bug with master as of 764e8eca6b9d10c1b3e6a2e9ae3dce014035401f, or with Trusty mypaint 1.2.0+gitexport.f62444e from <https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing>.

Please, a few questions:

* Obs: Your buttons look different to mine.
  - Q: **What theme** are you using?
  - Q: Does the problem go away if you use **Greybird** instead?
* Obs: I notice that one of the button labels is too long.
  - Q: **What language** are you using? I think it's Portuguese...
  - Speculation: perhaps this is screwing up the layout up in the top left.

**Comment by mccouto** [comment] 2016-02-18 17:15
Hello, @achadwick,
The problem occurs because of theme Wow Elementary-light.
I tested others themes and did not happen more.
Thank you and congratulations for the excellent software!

**Comment by achadwick** [comment] 2016-02-19 11:28
This does not happen in Adwaita in GNOME under a `pt_BR` locale when the “Edita Ícone do Pincel” button label overflows horizontally.

I downloaded some copies of WoW from [nale12 on deviantart](http://nale12.deviantart.com/art/WoW-164793330) and [gnome-look](http://gnome-look.org/content/show.php/WoW?content=125065), and had a look inside. **Neither archive's _WoW-Light-Elementary_ folder contains a _gtk-3.0_ subfolder**.

**MyPaint uses GTK3**, so I'm closing this issue as "works-for-me" - meaning that there is a workaround, and that this is a desktop environment config issue. Presumably it affects all old gtk-2.0 themes which do not have a gtk-3.0 port yet. **The solution is to use a newer theme** like Xubuntu's default (greybird), the default Xfce theme, or GNOME/GTK's default (Adwaita).

We can revisit this as a "bug" if it turns out that MyPaint is doing something broken with its widget layout, but for now it looks like a theme issue only.

**Closed by achadwick** 2016-02-19 11:28 UTC
Labels: request-for-help, works-for-me

**Comment by mccouto** [comment] 2016-02-20 01:27
Yes @chadwick. I agree with you.
It is unfortunate because this is a beautiful theme.

2016-02-19 9:29 GMT-02:00 Andrew Chadwick <notifications@github.com>:

> This does not happen in Adwaita in GNOME under a pt_BR locale when the
> “Edita Ícone do Pincel” button label overflows horizontally.
>
> I downloaded some copies of WoW from nale12 on deviantart
> <http://nale12.deviantart.com/art/WoW-164793330> and gnome-look
> <http://gnome-look.org/content/show.php/WoW?content=125065>, and had a
> look inside. *Neither archive's WoW-Light-Elementary folder contains a
> gtk-3.0 subfolder*.
>
> *MyPaint uses GTK3*, so I'm closing this issue as "works-for-me" -
> meaning that there is a workaround, and that this is a desktop environment
> config issue. Presumably it affects all old gtk-2.0 themes which do not
> have a gtk-3.0 port yet. *The solution is to use a newer theme* like
> Xubuntu's default (greybird), the default Xfce theme, or GNOME/GTK's
> default (Adwaita).
>
> We can revisit this as a "bug" if it turns out that MyPaint is doing
> something broken with its widget layout, but for now it looks like a theme
> issue only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mypaint/mypaint/issues/605#issuecomment-186178554>.
>



-- 
Mozart Couto
www.mozartcouto.com.br
http://blogdodesenhador.blogspot.com
<http://mozartcoutoimagens.blogspot.com>
