### ISSUE TITLE
Creating a vector layer crashes

### ISSUE THREAD

**Issue by ghost** [mypaint/mypaint#531] opened 2015-12-15 04:24 UTC
So far i think everything in MyPaint works but once i create a vector layer it immediately crashes saying that pythonexe isnt working. I was told it might be a windows 10 problem but other than that I don't know what to do. I'd appreciate any kind of help! Thanks!
![screenshot 3](https://cloud.githubusercontent.com/assets/16299606/11802034/0c89d962-a2a9-11e5-8665-2c542afcda87.png)

**Comment by achadwick** [comment] 2015-12-15 09:58
Hi - can you provide the following information please?

* The full MyPaint version - you can find it in Help → About MyPaint.
* Whether this is MyPaint w32 or MyPaint w64.
* Where you got this build from.
* What hardware you are running this on.
* Whether you have InkScape installed.
* The steps you took to get this point (it sounds silly to ask, since it looks like you invoked the command from the menu, but please confirm)
* What you have tried to work around the problem, if anything, and whether it worked (!)

￼It's useful for us to see if anything was reported on the console for bugs like these. Try launching "MyPaint w64 (console debug)" or "MyPaint w32 (console debug)", and capturing the last screen or so of console output for us to see. You can cut and paste it into a triple-backtick block in github like this 

    ```
    Console debug
    lines
    go
    here!
    ```

Thanks in advance for any information you can give!

**Comment by zb13y** [comment] 2015-12-16 07:36
Windows 10, w64 beta 3. I have InkScape.

```
DEBUG: lib.document: autosave_countdown: autosave will run in 5s
DEBUG: lib.document: autosave: updates detected, doc marked autosave-dirty
DEBUG: gui.stategroup: Entering State, calling layerblink_state_enter
INFO: lib.layer.data: Loading new blank working file from u'C:\\Users\\\u0410\u0437\u0430\u043c\u0430\u0442\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.4izajr\\revisions\\tmpys2vax.svg'
WARNING: py.warnings: C:\Program Files\MyPaint\share\mypaint/gui/externalapp.py:86: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  msg_label = Gtk.Label(msg_text)
```

**Comment by achadwick** [comment] 2015-12-16 10:28
Thanks, that's helpful. It has made the empty ".svg" file, but it may now be failing to list apps. Mypaint doesn't get as far as actually launching InkScape, and the code that's at fault/triggering an upstream issue is probably somewhere in `gui/externalapp.py`.

* Do you see a dialog with «MyPaint нужно редактировать файл типа “{type_name}” ({content_type}). Какое приложение нужно использовать?» or «Какое приложение должна использовать MyPaint для редактирования файлов типа “{type_name}” ({content_type})?» ?
* Is Inkscape associated with `.svg` in Windows? By default?
* Does behaviour change if you associate e.g. Wordpad with `.svg`?
* What previous versions of MyPaint and Windows did you use, when it was successful?

**Comment by tumagonx** [comment] 2015-12-16 18:48
Is this related to https://bugzilla.gnome.org/show_bug.cgi?id=758248 
I'm not sure because the case in mypaint was a bit different from gtk3-demo...

**Comment by zb13y** [comment] 2015-12-17 09:17
Works in 1.2.0-beta.1+gitexport.a7012b4. Beta 2 crashes as beta 3. Crashes without dialogues.

**Comment by tumagonx** [comment] 2015-12-17 09:44
@zb13y I think that confirm my upstream bugreport.

@achadwick If it can't be solved at mypaint, I recommend to go back to gtk 3.16.x which will also give users Windows XP compatibility.

**Comment by achadwick** [comment] 2015-12-18 14:53
@tumagonx yeah, confirmed under MSYS2. Clearly some upstream breakage.

We can use `os.startfile()` in Python on Windows until upstream get the problem fixed.

**Comment by tumagonx** [comment] 2015-12-18 17:49
Just want to pointing out that gtk 3.18.x has many issues, it seems lag issue (not #390 one) also upstream related. Sometime for a release (especially GTK) you probably want to be sure picking and evaluate the right version of GTK (as happened to other big GTK-based projects) because new regression almost always present for Windows with new stable releases.

If it doesn't hurt and still API sufficient why take risk with newest version?

**Comment by achadwick** [comment] 2015-12-18 17:59
@tumagonx 
Annoyingly that's not possible with MSYS2 if you also want to keep on developing and testing it (I have limited hardware+software). I know of no way (yet) to turn back the the clock so that you get a consistent snapshot of the packages which were available at an earlier point in time.

/cc @Alexpux
Do you have any smarter ideas than me about how this might be done? It might be sort of awesome. Backups of repo indexes on the server would be neat if repo.msys2.org were to keep backups of its .pkg.tar.xz files.

**Comment by odysseywestra** [comment] 2015-12-18 18:01
We may have to maintain our  own repository for msys2 though I wouldn't
like that idea.

On Fri, Dec 18, 2015, 9:59 AM Andrew Chadwick <notifications@github.com>
wrote:

> @tumagonx <https://github.com/tumagonx>
> Annoyingly that's not possible with MSYS2 if you also want to keep on
> developing and testing it (I have limited hardware+software). I know of no
> way (yet) to turn back the the clock so that you get a consistent snapshot
> of the packages which were available at an earlier point in time.
>
> /cc @Alexpux <https://github.com/Alexpux>
> Do you have any smarter ideas than me about how this might be done? It
> might be sort of awesome. Backups of repo indexes on the server would be
> neat if repo.msys2.org were to keep backups of its .pkg.tar.xz files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mypaint/mypaint/issues/531#issuecomment-165857246>.
>
-- 

-- Albert Westra

**Comment by achadwick** [comment] 2015-12-18 18:10
(Which is to say that repo.msys2.org keeps a few months' worth of old versioned .pkg.tar.xz files, but only one .db and/or .files and a few .old versions of them. It might be possible with what we have right now to back up one's *local* .db files and thus roll one's own time machine.)

I wonder whether there's an approved mechanism for doing that, or if the main repo could be made to publish its own history one day.

For now though, I'm going to patch in a workaround in MyPaint for this issue.

**Comment by achadwick** [comment] 2016-01-07 15:37
With a little bit more investigation and reinstating the failing code branch, this segfault is happening in our call to `g_app_info_should_show()` in [`gui/externalapp.py:98`](https://github.com/mypaint/mypaint/blob/abdaf83e81cfa5dcc59a0f8c5671ca0e7153d7ce/gui/externalapp.py#L98). It is also reproducible on the command line.

```
$ python2 -i
Python 2.7.10 (default, Jul  8 2015, 15:14:56)
[GCC 5.1.0] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gio
>>> apps = Gio.AppInfo.get_all_for_type(".txt")  # surprise, not a mime type
>>> apps
[<__main__.GWin32AppInfo object at 0x2817b94 (GWin32AppInfo at 0x251a8a0)>, <__main__.GWin32AppInfo object at 0x2817bbc (GWin32AppInfo at 0x251a8c0)>]
>>> apps[0].should_show()
/mingw32/bin/python2: line 6:  3892 Segmentation fault      "$( dirname ${BASH_SOURCE[0]} )/python2.exe" "$@"
```

This upstream issue is **not a GTK+** issue. It's a GLib issue instead, which is somewhat more worrying. My affected versions and platforms:

* mingw-w64-i686-glib2 2.46.2-3
* mingw-w64-x86_64-glib2 2.46.2-3

Both packages are from from current MSYS2.

**Comment by tumagonx** [comment] 2016-01-07 15:53
@achadwick Yes it was probably glib 2.45.2 as I reported in https://bugzilla.gnome.org/show_bug.cgi?id=758248#

Despite the triggers probably different between #531, #551 and upstream 758248 but still ending up at g_app_info chunk which get major rework at that version.

**Comment by achadwick** [comment] 2016-01-29 02:03
Testing with the higher-level Gtk.AppChooserDialog to see if that offers a less crashy alternative:

* Code: https://gist.github.com/achadwick/98244f445e3b64ba040a
* Win7+MSYS2 current: `mingw-w64-x86_64-gtk3` 3.18.6-1 and `mingw-w64-x86_64-glib2` 2.46.2-3: no apps in list, when clicking "View All Aplications", only "Address Book" is shown, code segfaults immediately after a positive choice of this app, whatever it was.
* Win7+MSYS2 current: `mingw-w64-i686-gtk3` 3.18.6-1 and `mingw-w64-i686-glib2` 2.46.2-3: no apps in list even after clicking "View All Aplications". No segfaults, because I cannot make a choice.
* Linux+Debian testing/unstable: `libgtk-3-0:amd64` 3.18.6-1 and `libglib2.0-0:amd64` 2.46.2-3: appropriate apps appear in list, making a positive choice returns a valid GtkAppInfo from the chooser widget.

So this is no alternative on Windows yet for stable current GTK3/GLib/Gio. It's a bit more stable than fumbling with AppInfo ourselves, however.

**Comment by achadwick** [comment] 2016-01-29 02:50
Practically speaking, users want both the ability to just use a chosen default app for external edits (#98) or specify their own scripts and things (#477).

Time for a rewrite that takes into account all these bugs and preferences: see <https://github.com/mypaint/mypaint/issues/477#issuecomment-176536138>.

**Comment by zb13y** [comment] 2017-01-22 17:36
I don't have crash in 1.2.1+gitexport.bcf5a28d (Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1).

**Comment by achadwick** [comment] 2017-01-22 17:56
MyPaint uses the more stable `os.startfile()` on Windows, but we acknowledge that this is a workaround. However it's a pretty good workaround for now, and there is nothing more we can do for this by altering MyPaint's code. I'm moving this to closed, because it is being dealt with elsewhere.

To recap, The crash is still happening with the Python+Gio that v1.2.1 is shipping with.

![image](https://cloud.githubusercontent.com/assets/61299/22184501/bdf63e56-e0ca-11e6-9aad-e69e3117c98f.png)

# Reported upstream

This is an upstream bug in the GLib component. It has an open bug report in the GNOME bug tracker.

:bug: https://bugzilla.gnome.org/show_bug.cgi?id=758248

Please comment there, and help the Windows Gio developers out by making debugging builds of GLib and reproducing this crash with backtraces for them. We have some instructions in our wiki that may help you: <https://github.com/mypaint/mypaint/wiki/Debugging-crashes-on-Windows>

**Closed by achadwick** 2017-01-22 17:56 UTC
Labels: bug, crasher, upstream, windows
