### ISSUE TITLE
[Feature Request] Inking tool: Allow old Strokes to be Edited?

### ISSUE THREAD

**Issue by blurymind** [mypaint/mypaint#610] opened 2016-02-21 10:56 UTC
The ink tool would be much more useful if we could keep the strokes editable on a specialized layer. The way paint tool sai and clip paint studio do.

---

[**EDIT:** just using the original post for notes and status -- AC]
### Community Forums topic

Discussion that isn't deeply technical can go here: http://community.mypaint.org/t/212
### What needs to be done
- [x] Decide whether this would really need to be a specialized layer. **Yes, we do: https://github.com/mypaint/mypaint/issues/610#issuecomment-187184412**
- [ ] Gather user interface requirements via the forums etc.
- [ ] Make some low-level changes to the way strokemaps work (probably)
- [ ] Add some buttons to the inking tool
- [ ] Add tricky stroke bubbling/revisiting code

**Comment by odysseywestra** [comment] 2016-02-22 01:44
This would be a better topic for our [community forums](http://community.mypaint.org) under feature requests since it needs discussion on how to pull this off. It's a good idea just needs to be hashed out a bit more.

For now a work around would be to use the Vector layer and use inkscape(or another SVG editor) to be able to manipulate more than one vector line.

**Comment by achadwick** [comment] 2016-02-22 12:35
@blurymind 
I don't know how those programs work, but this is an interesting idea. I think my main problem with it for now is that ink strokes take a long time to render.

I assume the goal would be to use MyPaint brushes for rendering the ink strokes, just like the 1.2.x inking tool?

@odysseywestra 
The UX side of it should probably get a lot of eyes and some forum input. There are some technical notes about the current implementation I want to dump out here though.

As it happens I'm lightly refactoring the layers implementation right now to get the crappy feature tests we use for things like fillability and paintability right (and overthinking #603 if I'm honest - I should just fix that the easy way first sigh). Anyway that's just where my head is at right now.

**Comment by achadwick** [comment] 2016-02-22 12:54
## Technical notes :computer: 

Dumping info about the current implementation and how it might need to change for anyone willing to pick this up... look away now if you're allergic to programming or weird technical people (I count myself in that :eyeglasses: :neckbeard:)

### Performance :racehorse:

The core of the problem is that strokes overlap  in interesting ways, meaning that older ones influence how later ones look. If you want them to be editable, you'll have to :rewind: rewind an imaginary stack of applied strokes, :wrench: apply the change the user wants, then :fast_forward: replay the stack after it.

Strokes _could_ bubble to the top when re-edited (UX: "unlocked for edit?" :unlock:) to save on redraw time when the stroke is being edited. This would change the appearance if there were subsequent translucent strokes. It wouldn't affect the appearance too much for anime/manga/draughting/comics inking if we did that: lots of black strokes which don't affect each other very much.

Actually, the stack isn't that imaginary. We have the existing strokemap, kinda like flaky layers of dried paint with knowledge of the brush that was used baked in. The problem is akin to peeling back the layers and either changing an existing one or whipping it out and putting it on top. Except that you have to wet the ones in between where the one you want to fiddle with touched the canvas, and redo them in sequence.

Really major open question/stumbling block:

> :mortar_board: Given the sequence of points through which a stroke passes and its brush settings,
> :question: can we determine the maximum extent of pixels it touches?

We've looked at this a couple of times already: for the automated brush previews, and before that for the strokemap calculations. MyPaint is tile-based, so the answer to the "what need to be redrawn" question is usually answered with knowledge of what tiles were just changed. Tile granularity is fine for our purposes here. We can exclude re-rendering of historic strokes

### Strokemap

* [lib.strokemap.StrokeShape](https://github.com/mypaint/mypaint/blob/764e8eca6b9d10c1b3e6a2e9ae3dce014035401f/lib/strokemap.py#L30)
* [lib.stroke.Stroke](https://github.com/mypaint/mypaint/blob/764e8eca6b9d10c1b3e6a2e9ae3dce014035401f/lib/stroke.py#L13)
* [lib.layer.data.PaintingLayer.add_stroke_shape()](https://github.com/mypaint/mypaint/blob/764e8eca6b9d10c1b3e6a2e9ae3dce014035401f/lib/layer/data.py#L1396)

We currently store a strokemap on painting layers, and this kind of specialized layer would be a riff on that. The existing strokemap has the stack nature already, and it's tile-based so we can do extents! However it's stored as a pile of _purely visual_ between a before and after snapshot. :disappointed: And worse, it doesn't permanently store the input points that went into the stroke :scream: 

Do we want our new layer type to be compatible with the Pick Stroke command? Probably. We use the strokemap for some awesome things already. However it will need extending, and its serialized format will need to change to store input data too :chart_with_upwards_trend: 

(If the format for the strokemap has to change, see also #611)

### Automated brush previews

* [gui.drawutils.render_brush_preview_pixbuf()](https://github.com/mypaint/mypaint/blob/764e8eca6b9d10c1b3e6a2e9ae3dce014035401f/gui/drawutils.py#L129)

I'm mostly linking to this as an example of how fiddly calculating stroke extents can be given how dynamic MyPaint brushes are. However note that with knowledge of the low-level tiled surface and its tilemap, you can determine and store a complete picture of what tiles really got changed when a stroke was rendered.

Can (does?) the snapshot diffing we already use for generating stroke shapes already take account of this?

(A good question here is: even if this set of tiles is bigger than the set of tiles from a pure diff of changes, is it the same as the set of tiles which might change *in all circumstances* with the re-application of this brushstroke? :thought_balloon: tiles tiles tiles :checkered_flag:)

**Comment by achadwick** [comment] 2016-02-22 13:00
Retitled. If we bake in more information to the strokemap, we might not have to create a new layer type for this.

(Note: "flaky layers of paint (or ink)" != the layers that you see in the Layers dockpanel. They're tiny things already baked in to standard MyPaint painting layers, albeit in a slightly unhelpful/incomplete way.)

**Comment by achadwick** [comment] 2016-02-22 13:38
## Forums thread

I've added a topic in the MyPaint Community Forum for discussing this: http://community.mypaint.org/t/212

**Comment by achadwick** [comment] 2016-02-22 13:50
Thinking about this some more, I think our existing layers don't have enough guarantees that you'll be able to edit them correctly in all cases. What if some of the layer's pixels come from an external app edit? What happens when layer data is transformed in any way (e.g. our existing trimming, or fancy new stuff from #31)?

If you open a .ORA file in some other program, then it may either discard our strokemap or preserve it. It won't know how to edit it though. The end result would be changes that can't be recreated by MyPaint's brush engine.

**We will probably need a specialized type of inking layer** for old strokes to be editable. One which cannot be edited externally, or which decays to a normal painting layer if you try.

**Comment by achadwick** [comment] 2016-02-22 13:58
And... ouch. :fearful: We actually need to redraw every stroke which has ever intersected a tile touched by a stroke being edited, or find and use a bitmap snapshot in the undo stack for its preceding state (optimization). Our .ORA files do not store snapshots for space reasons :smile: 

And every stroke which is redrawn needs to be examined for dependencies too, and *those* strokes need to be redrawn. Recursively :repeat:  Suddenly this is looking like a complete layer redraw every time if you do any stroke overlapping at all!

For our specialized layer type, we could guarantee that its pixels are "pristine", meaning that they could be redrawn form all saved stroke info if necessary.

**Comment by achadwick** [comment] 2016-03-01 00:06
Some good news on this: our strokemaps do indeed store empty tiles. This answers the stroke-extent question nicely, although the dependency/overlap determination and how a redraw happens is still going to be hard.

And some bad news: our existing strokemap format doesn't save the initial brush _state_ even though it gets captured. Maybe it shouldn't: the brush engine might get finicky if you try and replay a really old stroke with old/outdated states.

**Comment by blurymind** [comment] 2017-12-18 16:18
That sounds like good news to me. You are getting closer to making this possible! :+1: 
Thank you for trying to come up with the most elegant way to implement it

**Comment by odysseywestra** [comment] 2019-12-27 22:59
@blurymind I'm going to go ahead an close this one since you already have a thread created over on the community forums. We'll reopen this issue when we are ready to bring this over.

**Closed by odysseywestra** 2019-12-27 22:59 UTC
Labels: enhancement, needs-info
