### ISSUE TITLE
Color Changer bug ?

### ISSUE THREAD

**Issue by Toybulldog** [mypaint/mypaint#213] opened 2015-02-23 18:58 UTC
Hello my English is not good enough to get the bug to explain . 
Therefore, a link to the Video .

https://vimeo.com/120391545

Color Changer bug ?

Color does not match . 
Whether with a bucket or brush.
The error happens irregularly.

Mypaint 1.1.1-alpha.20150222+git.cd841a9
Ubuntu 14.04.LTS
4,4 GiB
AMD Athlon(tm) 64 X2 Dual Core Processor 4400+ × 2 
Gallium 0.4 on AMD RV610

**Comment by iirelu** [comment] 2015-02-23 19:50
That is definitely a bug! Thank you for reporting it.

I can not reproduce it myself, sadly, so it will be hard to fix.

**Comment by 0ion9** [comment] 2015-02-24 03:41
I'm running Arch Linux x86_64, latest MyPaint git, GTK3.13.8, with evdev driver, and so far cannot reproduce.

**Comment by Toybulldog** [comment] 2015-02-24 07:24
I try to explain the bug :
I tried it on elementary os, with an older mypaint git version , and the same error.
The error I 've only been using this color changer .
![color changer2](https://cloud.githubusercontent.com/assets/11164330/6344819/6555d4e8-bbfe-11e4-90fc-324c3e437ded.jpg)

If I had the error, and I close mypaint.
Then I open mypaint again and the color history is wrong. The color history shows me black to gray
If I then click on black is a fault .
![if i then click on black is](https://cloud.githubusercontent.com/assets/11164330/6344772/ad56bb46-bbfd-11e4-938f-ded03a5fccb6.jpg)
Sometimes it takes a while until the problem is .
Sometimes 1 minute or more. If the error is there, he always comes back into shorter intervals
I change the color with the color changer, like this: Blue to purple, red to yellow and then to blue and back to green then purple.....
![if i then click on black is terminal](https://cloud.githubusercontent.com/assets/11164330/6344788/e9b8c03e-bbfd-11e4-94e6-16446c08bea7.jpg)
![terminal if wrong color](https://cloud.githubusercontent.com/assets/11164330/6344795/07707ad6-bbfe-11e4-8e22-696beec8f5ec.jpg)

**Comment by 0ion9** [comment] 2015-02-24 08:27
Your final image there is helpful, it shows that Mypaint is choosing invalid hue, and as a result, when it asks to change the color, no change is actually applied.

I'm ill right now, so not inclined to get really involved in debugging this, But a quick glance at the mypaint source code reveals that the pick_color() method (at line 90 of gui/colorselectionwindow.py) is probably responsible for requesting that the color be changed.

Tracing back further, we would go to mypaintlib/colorchanger_wash.hpp, the method pick_color_at(), and finally, to the method get_hsv().
If you look at get_hsv(), you can see that it takes the brush hue and adds  `pre->h/360.0` to it.  
As far as I can see, this is simply incorrect for many, many cases.
I suggest adding a line after the `h = brush_h + pre->h/360;` line in mypaintlib/colorchanger_wash.hpp, as follows:
`h = CLAMP(h, 0.0, 1.0);`

If this works, then your problem is temporarily solved and we'll have some idea where to try to fix it.

That's about all my brain can take right now, hope it helps :)

**Comment by achadwick** [comment] 2015-04-22 02:20
Maybe it's time to retire those old colour selectors? Of course, we'll need a replacement for the C and V keys.

I have code in a personal branch which works by popping up the sidebar colour selectors in something like the quick brush chooser you get on the "B" key (but with colour selectors not brush groups). I've actually been holding off on it because the old popups are kinda unmaintainable and don't follow the same API as the rest of the selectors at all. Not to mention the fixed size. However if they're buggy I don't need to worry about that and just drop them...? :smiling_imp:

Assigning this to myself as a reminder to get that code sorted out. Watch this space.

**Comment by iirelu** [comment] 2015-04-22 18:29
I know loads of people who love the C and V colour selectors so getting rid of them isn't a good idea. The code probably just needs a cleanup.

**Comment by achadwick** [comment] 2015-04-30 18:39
Okay, I'll be sure to retain them in some form. To help debug this one, I've added some wrappers to allow them to be docked into the sidebar like any other colour adjubrster - so now they can be put somewhere they don't disappear when clicked.

(I like the idea of C and B cycling through colour choosers and brush groups in their respective popups, much as C and V do now for their current things... Hm.)

**Comment by achadwick** [comment] 2015-05-03 20:40
Just pushed a branch I've been working on for a while that makes C/V/B all consistent, without dropping any functionality from them. It's only relevant to this issue in that C and V now need to be pushed a few more times to get to (and remember) the colour selector showing this bug.

**Comment by martinxyz** [comment] 2015-07-02 14:34
@0ion9 was right, the problem is hue-out-of-range. It's fixed now. Steps to reproduce:

1. use a normal color selector like "HSV cube" to select a saturated red with a positive hue (very slightly towards yellow)
2. use the "V" color changer and pick a strong violet (this decreases the hue below zero)
3. paint a stroke (result: violet) and use the bulk fill tool (result: yellow) and observe the "HSV cube" hue slider (it points to red)

The "change hue clockwise" command does not result in this bug.

**Closed** 2015-07-02 14:34 UTC
Labels: bug

**Comment by martinxyz** [comment] 2015-07-02 14:47
On a related note, IMO there is a usability regression since 1.1.0 for both the "R" color picker and the "V" color changer. Both require you now to click, while before it was a single key hit (or hold-hover-release). I'm not sure how many users were actually able to discover this feature, but at the time when I was still doing digital painting I was a heavy user of this. I haven't actually paint-tested to see if I'm okay the new behaviour, so I won't fill a new issue now, just saying, in case it's possible to bring it back.

**Comment by achadwick** [comment] 2015-07-02 22:39
Thanks, @martinxyz 
0762c4fa7f2ab8f92a046142a40d31ec89cd9db6 seems to have regressed brushlib quite a bit. I assume that's accidental?

**Comment by martinxyz** [comment] 2015-07-03 06:24
@achadwick uups, looks like I'm still figuring out git submodules. Thanks for the cleanup.
