### ISSUE TITLE
Wrong viewport offset in scratchpad after undocking

### ISSUE THREAD

**Issue by danpla** [mypaint/mypaint#647] opened 2016-04-08 17:05 UTC
After undocking the scratchpad, the viewport is shifted up left.

Steps to reproduce:

1. Open scratchpad at default zoom level and draw something: 
![2016-04-08-193943_1600x900_scrot](https://cloud.githubusercontent.com/assets/10910745/14391334/031bb7c6-fdc4-11e5-890e-7b9fea79e01c.png)

2. Undock the scratchpad. Image goes somewhere:
![2016-04-08-193954_1600x900_scrot](https://cloud.githubusercontent.com/assets/10910745/14391363/3898a5b2-fdc4-11e5-9fe4-71dbcac4a597.png)

3. Zoom out:
![2016-04-08-194011_1600x900_scrot](https://cloud.githubusercontent.com/assets/10910745/14391504/fa5b849e-fdc4-11e5-926b-e4407f3e7845.png)

Xubuntu, MyPaint 1.2.1 from the testing PPA

It may be related to #597.

**Comment by odysseywestra** [comment] 2016-04-08 17:32
Yeah that's related. Better off closing that one and put you experience on that one.

**Comment by achadwick** [comment] 2016-04-15 19:30
Hi, I'm testing #651 right now, and I don't think this is a duplicate of #597.

This issue comes into effect when you drag out a scratchpad window, and it's to do with some incorrectly applied compensation for the sidebars/toolbars showing and hiding (the scratchpad doesn't need it).

#597 takes effect at startup only.

The proof: #651 fixes this issue quite nicely (thanks @danpla!), but not #597.

**Comment by achadwick** [comment] 2016-04-15 19:37
Moved up to 1.2.1 since a fix looks imminent in #651.

**Closed** 2016-04-15 22:54 UTC
Labels: glitch
