### ISSUE TITLE
freehand tool drawing only straight lines on centos 7 kde.

### ISSUE THREAD

**Issue by cg-cnu** [mypaint/mypaint#707] opened 2016-06-19 07:09 UTC
#### Description of the problem

**Freehand** tool drawing only straight lines. [video](https://youtu.be/MKuFpFbpwag)
Happening irrespective of the brush selected. 
Same issue for eraser also. 
All the other drawing tools working as expected.

#### Basic system details

MyPaint version: [v1.2.1-beta.1 ](https://github.com/mypaint/mypaint/releases/tag/v1.2.1-beta.1)
Operating system: CentOS Linux release 7.2.1511 (Core)
Desktop environment: KDE - 4.14.8

#### Steps to reproduce

1. Start MyPaint
2. pick any brush 
3. select **freehand** tool.
4. It draws only straight lines. Won't draw free hand.

#### Backtraces or error messages

No error messages or backtraces found.

As for installation on centos 7, I downloaded the v1.2.1-beta.1 release and installed the dependencies and ran scons. Launched ./mypaint.
I suspect its specific to centos-KDE. Let me know if any additional info needed.

**Comment by cg-cnu** [comment] 2016-06-19 08:45
After testing around for a while, found that **freehand** is working fine in **Full screen mode**.

* Launch mypaint
* Freehand won't work as expected.
* Enter full screen mode and freehand works fine.
* Exit full screen mode and it stops working.

[video](https://youtu.be/ImicmXr18Jc)

In some cases, It continues to work even after exiting the full screen.

**Comment by achadwick** [comment] 2016-06-19 15:13
Duplicate of #158 , #665?

**Comment by achadwick** [comment] 2016-06-19 15:15
I shouldn't have closed that, sorry.

@cg-cnu Please confirm that changing the theme to something other than the (horribly buggy, seemingly) Oxygen theme makes this problem go away?

**Comment by cg-cnu** [comment] 2016-06-19 17:18
Yes, you are right! Oxygen seems to be very buggy, shifting from oxygen fixed the issue. Thanks for the help!

**Comment by achadwick** [comment] 2016-06-20 09:39
Okay, workaround is to not use Oxygen :seedling::sunny: 

There are some workarounds in #709 for anyone searching.

**Closed by achadwick** 2016-06-20 09:39 UTC
Labels: duplicate
