### ISSUE TITLE
Clicking on color in docked palette tab undocks the palette tab

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#643] opened 2016-04-07 00:39 UTC
Steps to reproduce:
1. Enable the 'palette' dockable
2. Dock it on the right
3. Make sure it has a palette visible, with a reasonable (32+) number of colors present
4. Click on a color panel.

Result: The color is selected (correct) but the tab is also undocked/moved into its own window (incorrect). If I re-dock it, the same thing will happen on subsequent occasions (nearly every click will 

Mypaint Version
==============
git 43c2a45: "About box: report GLib version too, on Windows"

Platform details:
==============

* Arch Linux x86_64
* gtk+3 3.20.2
* python 2.7.11 (or 3.5.1, but I don't believe MyPaint uses Py3 yet)
* Qtile WM r2425 (git commit 0c17528; python3 version.)
* Tablet = Monoprice 12", using evdev driver.

**Comment by achadwick** [comment] 2016-04-07 09:26
This should definitely not be happening. I can't reproduce in GNOME using `libgtk-3-0` 3.18.9 on Debian testing/unstable however, and I don't think anyone has reported anything like it.

First question: can you drag the colour swatches at all?

![palette-drag](https://cloud.githubusercontent.com/assets/61299/14346473/4e923a56-fcaa-11e5-8174-1c07ca60d6d7.png)

* Does switching temporarily to a different WM change things?
* Does switching temporarily to GTK 3.18 change things (I know this can be done in MSYS2 at least, and you might be able to do it in-session)

**Comment by 0ion9** [comment] 2016-04-08 01:17
> Can you drag the colour swatches at all
No, neither when docked or undocked. All drags register as tab drag (that is, the 'palette' icon appears under the cursor during the drag, rather than a color panel).
I think a similar behaviour may be occurring in Firefox, but that does not trigger on drags inside a tab, only on the tab itself.

> Switching to a different WM
Haven't tried yet, will edit in result

> Switching to gtk 3.18
Should be able to do this easily, will edit in result.

**Comment by 0ion9** [comment] 2016-04-09 04:26
OK, 3.19.8 is when the bug(?) was introduced. I'm still not 100% sure that MyPaint isn't involved  in the fault here, as I've had difficulty finding an GTK3 program that uses tabs similarly.

**Comment by achadwick** [comment] 2016-04-09 11:44
Oh goody. More GtkNotebook regressions maybe. I wonder if they're related to the workspace regressions (#639, #640) we're seeing for the Windows cut, which bundled GTK 3.20.1.

**Comment by briend** [comment] 2016-04-18 05:02
Doh, I just updated my debian sid-- libgtk-3-0:amd64 3.20.3-1
I have the same problem now.  To add a bit-- this happens to any dockable color picker as well as dockable brushes, using mouse or wacom tablet.  Work-around-- use popup pickers keyboard shortcuts-- these dialogs are unaffected.
Tested mypaint 1.2.0+gitexport.f62444e and 1.3.0-alpha+git.ac2688c
It might be important to note that there is NO problem with layers or the tool option sliders or other dockable dialogs.  Also important-- this only happens when you "drag" the pointer while clicking.  It just happens that using the mouse it is possible to click without movement, but using a stylus is basically impossible to click without moving the cursor.

**Comment by achadwick** [comment] 2016-04-18 16:32
@briend 
is it reproducible with https://gist.github.com/achadwick/1b3505beb47d65fedfd6 ?

**Comment by briend** [comment] 2016-04-19 01:48
No, I couldn't find any problems with that demo.  I also need to revise my earlier statement regarding the other tool windows-- it definitely happens there as well.  While the sliders themselves on the tool options don't exhibit the issue, if you click just above the sliders it will grab and move the window most of the time.  I made a video to show this-- a video is worth a thousand pictures:
https://www.youtube.com/watch?v=0Ohp1jcam_4

**Comment by briend** [comment] 2016-04-20 04:55
I reverted to these packages and the issue disappeared:
apt install  libgtk-3-0=3.18.8-1 libgtk-3-common=3.18.8-1 adwaita-icon-theme=3.18.0-2 libgtk-3-bin=3.18.8-1 gir1.2-gtk-3.0=3.18.8-1
snapshot.debian.org is great.  Used http://snapshot.debian.org/archive/debian/20160301T103342Z/

**Comment by tr37ion** [comment] 2016-04-29 09:42
I have the same issues with all dockers. Whenever I select something inside a docker and the mouse moves while the mouse button/pen tip is down the docker undocks.

Arch Linux (KDE Plasma)

**Comment by achadwick** [comment] 2016-04-29 09:45
@tr37ion GTK version please?

**Comment by tr37ion** [comment] 2016-04-29 09:48
libgtk-3.so.0 -> libgtk-3.so.0.2000.3

**Comment by achadwick** [comment] 2016-04-29 09:53
@tr37ion 
You can find out what it is with pacman on an Arch system:

    $ pacman -Qi gtk3

Assuming I have the package name right, and assuming that Arch is anything like MSYS2.

**Comment by tr37ion** [comment] 2016-04-29 09:57
Version         : 3.20.3-3
Btw. I'm on IRC.

**Comment by achadwick** [comment] 2016-04-29 11:22
Reproduced on Windows MSYS2 using GTK 3.21.1. Win7 in a VM, with no Aero effects.

MyPaint's colour selectors do not initiate their own drags. They let the toolkit do that with its default handler, and invoke `gtk_drag_source_set()` to turn on handling *during the button press handler itself*. This code is frankly a bit cluttered and nasty, and it can almost be expected to break.

If the button press handler in our `gui.colors.adjbases` returns True instead of False after doing this DnD setup/teardown (in order to suppress the default handler), the problem goes away. But then you can't drag colours around.

We should probably be initializing the drag ourself in the button press handler.

(The drag sensitivity is way too high as well. It's not respecting "`gtk-dnd-drag-threshold`", and starting drags at 1 pixel of movement. Of course, it's the wrong drag, so let's fix that first).

**Comment by achadwick** [comment] 2016-04-29 17:51
Okay, both the sensitivity thing and the accidental drag-out of the tab should be fixed now, for the palette window at least. Let me know if it crops up for any other dockpanels.

**Comment by defaultxr** [comment] 2016-04-30 02:44
Using the current git (1.3.0-alpha+git.5b86415 on Arch Linux; gtk3 3.20.3-3), this also affects the brush selection dockable for me when clicking a brush. It's better than in the 1.2.0 stable but too easy IMO to accidentally drag and undock, especially when using a drawing tablet. Personally I think it shouldn't be possible at all to move that dock by clicking on a brush; not sure if it's intentional behavior.

**Comment by achadwick** [comment] 2016-04-30 12:55
Reopened for the brush issue too. I suspect it has the same cause.

**Comment by achadwick** [comment] 2016-04-30 19:13
Fixed properly now, on both active branches. The earlier fix was preventing the palette panel's menu from firing :sob:

**Closed by achadwick** 2016-04-30 19:13 UTC
Labels: bug, glitch, upstream

**Comment by tr37ion** [comment] 2016-05-02 14:03
Nice, looks like it is fixed now :) Thanks.
