### ISSUE TITLE
Mypaint crashes while after build

### ISSUE THREAD

**Issue by nbg7** [mypaint/mypaint#593] opened 2016-02-08 03:41 UTC
Hi i have built mypaint through source code in my MAC OSX10.11
While running the mypaint paint file i get the following error

CRITICAL: mypaint: Installation layout: unknown!
Traceback (most recent call last):
  File "/Users/Nisarg/Documents/mypaint/mypaint/mypaint", line 444, in <module>
    = get_paths()
  File "/Users/Nisarg/Documents/mypaint/mypaint/mypaint", line 200, in get_paths
    raise RuntimeError("Unknown install type; could not determine paths")
RuntimeError: Unknown install type; could not determine paths
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

This is the .\mypaint output:

./mypaint
INFO: mypaint: Installation layout: not installed, testing from within the source tree
Traceback (most recent call last):
  File "./mypaint", line 452, in <module>
    init_gettext(localepath, localepath_brushlib)
  File "./mypaint", line 250, in init_gettext
    lib.i18n.set_i18n_envvars()
  File "/Users/Nisarg/Documents/mypaint/mypaint/lib/i18n.py", line 103, in set_i18n_envvars
    from AppKit import NSLocale
ImportError: No module named AppKit

**Comment by achadwick** [comment] 2016-02-08 09:34
Duplicate of #579.

**Closed by achadwick** 2016-02-08 09:34 UTC
Labels: duplicate, osx
