### ISSUE TITLE
Mypaint doesn't work with not latin path

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#588] opened 2016-02-02 08:11 UTC
If Mypaint installed with cyrillic path, program will not open. Windows 10 x64.

Maybe related with this [topic](http://community.mypaint.org/t/downloaded-version-1-2-on-windows-yet-not-opening-when-download-was-finished/162). Message from win xp user, that can't open program.

**Comment by achadwick** [comment] 2016-02-02 11:50
What exact version of MyPaint is this, and how can we reproduce the problem here?

Do you get any error messages? Please paste them here.

When you run MyPaint in console debug mode, is anything different? Do you get more information? Please paste any messages you see so I can look at them.

When you say "installed with cyrillic path", do you mean that you chose a path other than [C:\Program Files](https://en.wikipedia.org/wiki/Program_Files) to install to and that this was Cyrillic? Or do you mean that your user profile has Cyrillic characters in it?

If it's the second one, I thought we'd fixed this for v1.2.0.

**Comment by zb13y** [comment] 2016-02-02 13:52
Other than program files. For example C:\рвлорв\MyPaint. Program doesn't open, in task manager program shows for 1 second and disappears. Stabel 1.2.0, but beta have same problem. Windows 10 x64.

**Comment by achadwick** [comment] 2016-02-02 14:52
@zb13y 
Please run **MyPaint w64 (console debug)** from the Start menu, and tell me what that writes. You can paste in the middle of 2 triple-backtick markers like this, or use a [gist](https://gist.github.com/).

    ```
    log
    output goes
    here
    ```

**Comment by tumagonx** [comment] 2016-02-02 18:37
![cjkpath](https://cloud.githubusercontent.com/assets/4075264/12759931/6b1c75ea-ca16-11e5-88a1-5b539c4e2609.png)

Reproduced in win8.1

This should be fixed long time ago, @zb13y  I wonder if mypaint 1.0 also have issue too.

**Comment by tumagonx** [comment] 2016-02-02 19:02
oh the ctypes workaround not working, hmm the workaround was there for mypaint opening Unicode ora and having its setting stored in Unicode %USERPROFILE% but the case never verified when mypaint itself in Unicode path.

**Comment by tumagonx** [comment] 2016-02-02 19:26
I think this is not possible a least for python 2.x on WIndows.

**Comment by achadwick** [comment] 2016-02-02 19:26
For args handling, it may be work seeing if GLib/Gio has the smarts to deal with it...

> g_file_new_for_commandline_arg ()
> 
> GFile * g_file_new_for_commandline_arg (const char *arg);
> Creates a GFile with the given argument from the command line. The value of arg can be either a URI, an absolute path or a relative path resolved relative to the current working directory. This operation never fails, but the returned object might not support any I/O operation if arg points to a malformed path.
> 
> Note that on Windows, this function expects its argument to be in UTF-8 -- not the system code page. This means that you should not use this function with string from argv as it is passed to main(). g_win32_get_command_line() will return a UTF-8 version of the commandline. GApplication also uses UTF-8 but g_application_command_line_create_file_for_arg() may be more useful for you there. It is also always possible to use this function with GOptionContext arguments of type G_OPTION_ARG_FILENAME.

We'll still need some Windows-y special cases though. Hm.

**Comment by tumagonx** [comment] 2016-02-02 20:36
@achadwick yes, that should be the new replacement for args handling.

On 2/3/16, Andrew Chadwick <notifications@github.com> wrote:
> For args handling, it may be work seeing if GLib/Gio has the smarts to deal
> with it...
>
>> g_file_new_for_commandline_arg ()
>>
>> GFile * g_file_new_for_commandline_arg (const char *arg);
>> Creates a GFile with the given argument from the command line. The value
>> of arg can be either a URI, an absolute path or a relative path resolved
>> relative to the current working directory. This operation never fails, but
>> the returned object might not support any I/O operation if arg points to a
>> malformed path.
>>
>> Note that on Windows, this function expects its argument to be in UTF-8 --
>> not the system code page. This means that you should not use this function
>> with string from argv as it is passed to main().
>> g_win32_get_command_line() will return a UTF-8 version of the commandline.
>> GApplication also uses UTF-8 but
>> g_application_command_line_create_file_for_arg() may be more useful for
>> you there. It is also always possible to use this function with
>> GOptionContext arguments of type G_OPTION_ARG_FILENAME.
>
> We'll still need some Windows-y special cases though. Hm.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/588#issuecomment-178773474


-- 
!tuma

**Comment by zb13y** [comment] 2017-01-24 16:19
Is it duplicate of this https://github.com/mypaint/mypaint/issues/627? If so, then it can be closed.

**Comment by achadwick** [comment] 2017-01-24 16:28
@zb13y Yes, I think so. Closed as a duplicate of #627.

**Closed by achadwick** 2017-01-24 16:28 UTC
Labels: solution.Wontfix, platform.Windows, solution.Upstream, cat.Input.Keyboard, info.NeedInfo
