### ISSUE TITLE
build windows 1.2 - python26.dll is loaded

### ISSUE THREAD

**Issue by marcgardent** [mypaint/mypaint#572] opened 2016-01-20 20:44 UTC
the bin release under windows 7 (64bit or not) crashs directly:
Fatal Python error: Interpreter not initialized (version mismatch?)

MyPaint use python 2.7! but python26.dll is loaded?!!

**Comment by tumagonx** [comment] 2016-01-20 21:48
@Market, several questions:

- Do you have python 2.6 installed? or do you have other application
(in background) that use python 2.6 (if you can tell)?
- How is your PATH environment looks like? (open cmd console and type
echo %PATH%)
- Do you start mypaint from start menu or other ways?

On 1/21/16, Market Garden <notifications@github.com> wrote:
> the bin release under windows 7 (64bit or not) crashs directly:
> Fatal Python error: Interpreter not initialized (version mismatch?)
>
> MyPaint use python 27! but python26dll is loaded?!!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/572


-- 
!tuma

**Comment by MarketGarden** [comment] 2016-01-21 18:40
there are MyPaint 1.0.0! :) used Python26.dll !

Uninstall program didn't erased generated files - pyc.
I erase all of them and resinstall MyPaint 1.2.0.

It's work.

thx.
And triple thx, no lag!!!!

**Comment by tumagonx** [comment] 2016-01-21 18:59
Ahh, the leftover cache from 1.2.0 might do bad things in the future
too. This need to be noted in addition to "uninstall previous
version".

On 1/22/16, Market Garden <notifications@github.com> wrote:
> there are MyPaint 1.0.0! :) used Python26.dll !
>
> Uninstall program didn't erased generated files - pyc.
> I erase all of them and resinstall MyPaint 1.2.0.
>
> It's work.
>
> thx.
> And triple thx, no lag!!!!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/572#issuecomment-173669173


-- 
!tuma

**Comment by achadwick** [comment] 2016-05-01 17:01
How should we approach fixing this for users?

* Update the release notes for 1.2.1 to say "uninstall all previous versions first AND delete their file trees"?
* Update the .iss installer for MyPaint to purge its target folder (or move it out of the way) before installation?

**Comment by achadwick** [comment] 2016-05-01 17:19
@tumagonx 
I can't reproduce any leftover files from a 1.2.0 install under `C:\Program Files` or `C:\Program Files (x86)`. The uninstaller correctly removes them. What is "leftover cache from 1.2.0"? Stuff in the profile like prefs or autosave backups?

Q: If there are any lingering .pyc or .dll files from older installs than 1.2.0, won't the installer just fail when it sees that its target folder already exists?

![folder exists](https://cloud.githubusercontent.com/assets/61299/14943130/b53f2b8e-0fc8-11e6-9209-4d7a79ca9395.png)

A: Well, it asks at least. Clicking "Yes" makes it write into it. And when you uninstall MyPaint, it leaves the folder there because it didn't write it :neutral_face: 

Can we say anything more in the docs than "please be really careful to fully remove old versions"?

**Comment by tumagonx** [comment] 2016-05-02 22:05
Sorry for the late reply, you're right by default it won't write
pyo/pyc there (redirected instead to user's appdata directory) but if
(even just once) user tried to run mypaint 1.2.0 as admin it will do.
That's why some may not encounter this issue.

I prefer purging programfiles\mypaint before install.


On 5/2/16, Andrew Chadwick <notifications@github.com> wrote:
> @tumagonx
> I can't reproduce any leftover files from a 1.2.0 install under `C:\Program
> Files` or `C:\Program Files (x86)`. The uninstaller correctly removes them.
> What is "leftover cache from 1.2.0"? Stuff in the profile like prefs or
> autosave backups?
>
> Q: If there are any lingering .pyc or .dll files from older installs than
> 1.2.0, won't the installer just fail when it sees that its target folder
> already exists?
>
> ![folder
> exists](https://cloud.githubusercontent.com/assets/61299/14943130/b53f2b8e-0fc8-11e6-9209-4d7a79ca9395.png)
>
> A: Well, it asks at least. Clicking "Yes" makes it write into it. And when
> you uninstall MyPaint, it leaves the folder there because it didn't write it
> :neutral_face:
>
> Can we say anything more in the docs than "please be really careful to fully
> remove old versions"?
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/572#issuecomment-216056909


-- 
!tuma

**Comment by achadwick** [comment] 2017-01-21 22:40
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now out. Can you confirm whether or not this bug is still happening with it please? Our Windows build of 1.2.1 uses a different runtime environment to the 1.2.0 build, and a different installer.

It is still a good idea to remove pre-existing MyPaint installations in the same place :wink:  But I want to know what happens if there's a Python 2.7 install somewhere else. These MSYS2 builds should use a sensible $PATH order and thus be nicely self-contained, but given that they seek out and use your `msvcrt.dll` they must already look outside their bottles for some things.

**Comment by jplloyd** [comment] 2019-12-23 14:35
I think we can close this since the Windows build is using Python 3 now. In general, I hope we won't have these kind of dependency issues with everything shipped in the bundled MSYS2 installation.

**Closed by jplloyd** 2019-12-23 14:35 UTC
Labels: bug, crasher, windows
