### ISSUE TITLE
PNG export artefact

### ISSUE THREAD

**Issue by kaerhon** [mypaint/mypaint#287] opened 2015-04-09 16:17 UTC
There's an issue about PNG export, that makes ugly artefacts. Number of layers is unimportant (1 or 10 is the same). Jpg export is fine. 
It's a git build from the 7 april 2015, number 1.1.1-alpha.20150408+git.15dbe18, 
on lubuntu 14.04 64 bits

There are the pics. 

![truc](https://cloud.githubusercontent.com/assets/8515092/7071266/f22ccc14-dea9-11e4-9e2b-8de025f7f40a.png)
![truc2](https://cloud.githubusercontent.com/assets/8515092/7071265/f229674a-dea9-11e4-990b-97c068e39239.png)

**Comment by achadwick** [comment] 2015-04-09 21:55
Does this only happen with export? Which export?

**Comment by achadwick** [comment] 2015-04-09 22:00
Okay, reproduced with 98fbab2d52da86ec73584d4baa30b4892cc6bb6f.
This only happens when the frame is turned on.

**Workaround:** turn the frame off when exporting as PNG for now!

**Comment by achadwick** [comment] 2015-04-09 22:00
(Working on a proper fix, of course)

**Comment by achadwick** [comment] 2015-04-09 22:13
Bisecting, a16f34f5faab08867d8a412b0c056b10520ece74 appears to be the first bad commit. That wasn't expected. Some other thread must be stomping all over that RAM despite the precautions. (What's different about save and export?)

**Comment by achadwick** [comment] 2015-04-09 22:19
Minimal test case: (it's a .ora, rename it)

![x.ora](https://cloud.githubusercontent.com/assets/61299/7078175/ab2dc4e8-df0e-11e4-8da1-f3e682c5acd6.png)

Steps to reproduce with 98fbab2:

1. Load x.ora
2. Immediately press Ctrl+Shift+E to export.
3. Export as x.png

Error is reproducible seemingly 100% of the time. Corruptions visible every tile strip (currently 64 px).

**Comment by achadwick** [comment] 2015-04-09 22:28
Actually, it also seems to screw up saving .ora files from time to time too! The x.ora above shows the glitch. Here's a clean .ora for testing:

![y.ora](https://cloud.githubusercontent.com/assets/61299/7078327/0afeb084-df10-11e4-93f0-498a1c8d4a6b.png)

**Comment by achadwick** [comment] 2015-04-09 22:33
Reverting the bad commit appears to fix this for the y.ora upload above. Please pull, rebuild, and test, and yell at me if it's not fixed by the current HEAD.

**Comment by achadwick** [comment] 2015-04-09 22:34
Sorry, accidentally closed. Reopening, because this needs testing.

**Comment by kaerhon** [comment] 2015-04-10 00:57
y.ora has lines while exporting and saving with frame enabled. exports and saves clean without frame enabled.

i tried to build again, and it works as expected! thanks!

**Comment by achadwick** [comment] 2015-04-10 08:39
Looking at the causes of this again, it could well be the strip buffer's (`state->rowdata`) width calculation and the `memcpy()` populating it at [lib/fastpng.cpp:245](https://github.com/mypaint/mypaint/blob/a16f34f5faab08867d8a412b0c056b10520ece74/lib/fastpng.cpp#L245) that were at fault here.

Anyway, that commit was just a bit of strictly unnecessary futureproofing. If we revisit threaded autosaving, it can be resurrected from the timeline.

**Comment by achadwick** [comment] 2015-04-10 08:40
Thanks for reporting, and for testing out the fix BTW!

**Closed by achadwick** 2015-04-10 08:40 UTC
Labels: bug
