### ISSUE TITLE
Tablet clicks and strokes register incorrectly on 64-bit MyPaint

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#133] opened 2014-11-12 22:51 UTC
Using MyPaint 1.1.0 64-bit on Windows 8.1 64-bit
Monoprice 4x3" Graphics Tablet that uses UC-Logic drivers which are up to date.

I don't even know how to describe this? The pen clicks in MyPaint's 64-bit counterpart act extremely weird. The only way I can describe it is that it's a similar issue to what happens when you try to draw with a tablet in GIMP 2.8. (Which supposedly is some sort or problem with GNOME support on Windows and Mac or something like that but this is a MyPaint forum so moving on...) Except with MyPaint, the strokes are extremely disjointed and scattered and jittery.
The 64-bit version reacts fine to clicks and strokes to a mouse, as it should. Its trying to use the tablet which is where the problem lies.

![image](https://cloud.githubusercontent.com/assets/8382492/5020173/0107d946-6a8c-11e4-8289-10d89f104891.png)
This is what the strokes look like zoomed out. The canvas is at its default rotation. I was trying to draw a horizontal line.

How to reproduce: Open MyPaint 64-bit and try to draw with a tablet pen. Good Luck.

**Comment by achadwick** [comment] 2015-01-27 10:38
is this a duplicate of #177 by any chance? There's not much to go on with the image above, but the positional jitter looks a little similar.

(I've managed to tool myself up to be able to chase Windows input bugs now. Which is nice.)

**Comment by tumagonx** [comment] 2015-01-27 11:30
@AtsusaKaneytza: I never get any 64bit mypaint works with my UC-logic tab. Which driver version is yours?

**Comment by achadwick** [comment] 2015-03-05 12:37
@AtsusaKaneytza: Please correct me if I'm wrong, but closing as a duplicate (→ #177).

**Closed by achadwick** 2015-03-05 12:37 UTC
Labels: duplicate, windows
