### ISSUE TITLE
Crash upon startup..

### ISSUE THREAD

**Issue by bluecd** [mypaint/mypaint#656] opened 2016-04-19 13:57 UTC
INFO: mypaint: Debugging output enabled via MYPAINT_DEBUG
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefi
x u'C:\msys64\tmp\mypaint-builds\ac2688c\x86_64\mypaint-w64-1.3.0-alpha\m
ingw64'
DEBUG: mypaint: datapath: u'C:\msys64\tmp\mypaint-builds\ac2688c\x86_64\my
paint-w64-1.3.0-alpha\mingw64\share\mypaint'
DEBUG: mypaint: iconspath: u'C:\msys64\tmp\mypaint-builds\ac2688c\x86_64\m
ypaint-w64-1.3.0-alpha\mingw64\share\icons'
DEBUG: mypaint: old_confpath: None
DEBUG: mypaint: localepath: u'C:\msys64\tmp\mypaint-builds\ac2688c\x86_64\
mypaint-w64-1.3.0-alpha\mingw64\share\locale'
DEBUG: mypaint: localepath_brushlib: u'C:\msys64\tmp\mypaint-builds\ac2688c\
\x86_64\mypaint-w64-1.3.0-alpha\mingw64\share\locale'
INFO: lib.i18n: Windows: LANG='pl_PL'
INFO: lib.i18n: Windows: LANGUAGE='pl_PL'
DEBUG: lib.i18n: Sanitized the priority list in LANGUAGE to 'pl_PL'
DEBUG: mypaint: localepath: u'C:\msys64\tmp\mypaint-builds\ac2688c\x86_64\
mypaint-w64-1.3.0-alpha\mingw64\share\locale'
DEBUG: mypaint: localepath_brushlib: u'C:\msys64\tmp\mypaint-builds\ac2688c\
\x86_64\mypaint-w64-1.3.0-alpha\mingw64\share\locale'
DEBUG: mypaint: getdefaultlocale(): ('pl_PL', 'cp1250')
DEBUG: mypaint: setlocale(LC_ALL, ''): 'Polish_Poland.1250'
DEBUG: mypaint: getpreferredencoding(): 'cp1250'
DEBUG: mypaint: getlocale(LC_COLLATE): ('Polish_Poland', '1250')
DEBUG: mypaint: getlocale(LC_CTYPE): ('Polish_Poland', '1250')
DEBUG: mypaint: getlocale(LC_MONETARY): ('Polish_Poland', '1250')
DEBUG: mypaint: getlocale(LC_NUMERIC): ('Polish_Poland', '1250')
DEBUG: mypaint: getlocale(LC_TIME): ('Polish_Poland', '1250')
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain fu
ncs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (c
types)
DEBUG: mypaint: C bindtextdomain('mypaint', u'C:\msys64\tmp\mypaint-builds\a
c2688c\x86_64\mypaint-w64-1.3.0-alpha\mingw64\share\locale'): 'C:\msys64\
tmp\mypaint-builds\ac2688c\x86_64\mypaint-w64-1.3.0-alpha\mingw64\share\l
ocale'
DEBUG: mypaint: C bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('mypaint', u'C:\msys64\tmp\mypaint-buil
ds\ac2688c\x86_64\mypaint-w64-1.3.0-alpha\mingw64\share\locale'): u'C:\ms
ys64\tmp\mypaint-builds\ac2688c\x86_64\mypaint-w64-1.3.0-alpha\mingw64\sh
are\locale'
DEBUG: mypaint: Python bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C bindtextdomain('libmypaint', u'C:\msys64\tmp\mypaint-builds
\ac2688c\x86_64\mypaint-w64-1.3.0-alpha\mingw64\share\locale'): 'C:\msys6
4\tmp\mypaint-builds\ac2688c\x86_64\mypaint-w64-1.3.0-alpha\mingw64\share
\locale'
DEBUG: mypaint: C bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('libmypaint', u'C:\msys64\tmp\mypaint-b
uilds\ac2688c\x86_64\mypaint-w64-1.3.0-alpha\mingw64\share\locale'): u'C:\
\msys64\tmp\mypaint-builds\ac2688c\x86_64\mypaint-w64-1.3.0-alpha\mingw64\
\share\locale'
DEBUG: mypaint: Python bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C textdomain('mypaint'): 'mypaint'
DEBUG: mypaint: Python textdomain('mypaint'): 'mypaint'

(python2.exe:9096): Gdk-CRITICAL **: gdk_display_get_device_manager: assertion '
GDK_IS_DISPLAY (display)' failed

**Comment by achadwick** [comment] 2016-04-19 14:10
Hi there - thanks for the report!

There's not information in your original report to move this issue forward, sadly. Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs). We need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

**Comment by achadwick** [comment] 2016-04-19 15:30
Can you paste the output of `gdb -ex r --argc python2 ./mypaint` as well, please? It may be that this is a known issue involving the GTK libs.

**Comment by bluecd** [comment] 2016-04-19 19:12
1. Good you've amended 'args' ));

bluecd@computer  /c/Program Files/MyPaint
$ gdb -ex r -args python2 ./mypaint
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from python2...(no debugging symbols found)...done.
Starting program: /usr/bin/python2 ./mypaint
[New Thread 7116.0x2064]
[New Thread 7116.0x2568]
[New Thread 7116.0x2860]
[New Thread 7116.0x2cbc]
[New Thread 7116.0x213c]
  File "./mypaint", line 1
SyntaxError: Non-ASCII character '\x90' in file ./mypaint on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
[Thread 7116.0x213c exited with code 1]
[Thread 7116.0x2860 exited with code 1]
[Thread 7116.0x2cbc exited with code 1]
[Inferior 1 (process 7116) exited with code 01]
(gdb)

**Comment by achadwick** [comment] 2016-04-21 17:43
Sorry, I should have asked you to do a `bt` at the `(gdb)` prompt as well :neutral_face: 

The backtrace will help me decide whether this is a known issue. I suspect it's one of the existing GTK bugs, but let's see.

(BTW, when pasting, please can you put your backtraces or whatever between pairs of 3 backticks? Like this:

    ```
    $ gdb [...]
    [blah blah blah]
    (gdb)
    ```

Thanks! Doing that makes them much more readable in github. :eyeglasses:

**Comment by achadwick** [comment] 2016-04-21 17:44
More information on using the `gdb` debugger: https://github.com/mypaint/mypaint/blob/master/DEBUGGING.md

**Comment by achadwick** [comment] 2016-04-28 10:56
@bluecd 
Please provide a backtrace.

**TRIAGE NOTE**: I'm sort of assuming this is a duplicate of #636 right now. If it clears up after the next beta release or 1.2.1 itself, that'll be proof enough that it's the wintab init thing.

I don't rule out upstream breaking display initialization in other creative ways though :neutral_face:

**Comment by bluecd** [comment] 2016-04-28 12:58
Just some amendment to the note:
1. I did not have that crash when built w/Msys64 w/out install option - live mypaint.cmd command.
2. ALready had similar problems (although with Blender) and Huion wintab dll's.
 
regards,
bluecd
 
W dniu 2016-04-28 12:57:00 użytkownik Andrew Chadwick <notifications@github.com> napisał:
@bluecd
Please provide a backtrace.
TRIAGE NOTE: I'm sort of assuming this is a duplicate of #636 right now. If it clears up after the next beta release or 1.2.1 itself, that'll be proof enough that it's the wintab init thing.
I don't rule out upstream breaking display initialization in other creative ways though

**Comment by keemdy** [comment] 2017-01-11 07:00
MyPaint v1.2.1-beta.1 (2016-04-30)

wacom bamboo on computer my paint wont launch
wacom bamboo not on computer mypaint work partialy (Pressure not working eraser not working)

MyPaint w64 (console debug)

```
INFO: mypaint: Debugging output enabled via MYPAINT_DEBUG
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'C:\\Program Files\\MyPaint'
DEBUG: mypaint: datapath: u'C:\\Program Files\\MyPaint\\share\\mypaint'
DEBUG: mypaint: iconspath: u'C:\\Program Files\\MyPaint\\share\\icons'
DEBUG: mypaint: old_confpath: None
DEBUG: mypaint: localepath: u'C:\\Program Files\\MyPaint\\share\\locale'
DEBUG: mypaint: localepath_brushlib: u'C:\\Program Files\\MyPaint\\share\\locale'
INFO: lib.i18n: Windows: LANG='fr_FR'
INFO: lib.i18n: Windows: LANGUAGE='fr_FR'
DEBUG: lib.i18n: Sanitized the priority list in LANGUAGE to 'fr_FR'
DEBUG: mypaint: localepath: u'C:\\Program Files\\MyPaint\\share\\locale'
DEBUG: mypaint: localepath_brushlib: u'C:\\Program Files\\MyPaint\\share\\locale'
DEBUG: mypaint: getdefaultlocale(): ('fr_FR', 'cp1252')
DEBUG: mypaint: setlocale(LC_ALL, ''): 'French_France.1252'
DEBUG: mypaint: getpreferredencoding(): 'cp1252'
DEBUG: mypaint: getlocale(LC_COLLATE): ('fr_FR', 'cp1252')
DEBUG: mypaint: getlocale(LC_CTYPE): ('fr_FR', 'cp1252')
DEBUG: mypaint: getlocale(LC_MONETARY): ('fr_FR', 'cp1252')
DEBUG: mypaint: getlocale(LC_NUMERIC): ('fr_FR', 'cp1252')
DEBUG: mypaint: getlocale(LC_TIME): ('fr_FR', 'cp1252')
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
DEBUG: mypaint: C bindtextdomain('mypaint', u'C:\\Program Files\\MyPaint\\share\\locale'): 'C:\\Program Files\\MyPaint\\share\\locale'
DEBUG: mypaint: C bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('mypaint', u'C:\\Program Files\\MyPaint\\share\\locale'): u'C:\\Program Files\\MyPaint\\share\\locale'
DEBUG: mypaint: Python bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C bindtextdomain('libmypaint', u'C:\\Program Files\\MyPaint\\share\\locale'): 'C:\\Program Files\\MyPaint\\share\\locale'
DEBUG: mypaint: C bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('libmypaint', u'C:\\Program Files\\MyPaint\\share\\locale'): u'C:\\Program Files\\MyPaint\\share\\locale'
DEBUG: mypaint: Python bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C textdomain('mypaint'): 'mypaint'
DEBUG: mypaint: Python textdomain('mypaint'): 'mypaint'

(python2.exe:5772): Gdk-CRITICAL **: _gdk_win32_display_create_window_impl: assertion 'display == gdk_display_get_default ()' failed
```



result python2.exe stop working
im on window 10 64bit
bamboo fun cth-661

**Comment by achadwick** [comment] 2017-01-23 17:48
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has been released, and contains a fix for this bug. Several, actually...

Please can you try it out and see if this bug is still happening? If it is, it's probably best to create a new issue about it now. Debugging procedures are changing.

**Closed by achadwick** 2017-01-23 17:48 UTC
Labels: bug, crasher, duplicate, upstream, windows

**Comment by keemdy** [comment] 2017-01-24 08:52
MyPaint v1.2.1 (2017-01-21)
Hello,
It works but I have a small problem with Kaspersky an somes times python2.exe stop working
Thank you for your help

**Comment by achadwick** [comment] 2017-01-24 10:11
@keemdy 
Please report any "python2w.exe has stopped working" errors separately if you want me to chase them.
