### ISSUE TITLE
Preview Dockpanel causes too much lag while drawing.

### ISSUE THREAD

**Issue by MarbleStarry** [mypaint/mypaint#379] opened 2015-07-27 12:57 UTC
Yesterday I installed MyPaint 1.2.0-beta.0.17 on Ubuntu 15.04 via using achadwick/mypaint-testing PPA on Launchpad. I was so excited when I saw new UI and I found out there was a preview dock with viewfinder. But anytime I open it, it causes extreme lag to brush while drawing. After few tests I found out that, when I draw something little on canvas, preview dock immadately notices it and focuses to it and causes lag, then I draw something outside of the preview dock's focusing area and the brush works without lag until preview dock notices it and focuses into it, and then (yes, you guessed it) it starts to lag again. But when dock is closed, lag goes away and it runs well.

I think this happens because preview dock updates the preview in real-time with canvas. I think making preview dock update the view after stroke is finished would solve this issue. What I mean is:

Brush stroke begins>Preview dock waits for it>Brush stroke finishes>Preview dock updates the view.
instead of
Brush stroke begins>Preview dock updates the view in real-time>Brush stroke finishes>Preview dock finishes updating.
would be a lot better for performance.

Maybe putting a setting under the View tab to enable or disable real-time updating? Is it possible?

**Comment by achadwick** [comment] 2015-07-27 13:16
Yeah, the updates from the canvas surfaces in memory will be sent to both views. Like a little chain of rectangles following the brushstroke...

Is this the behaviour you get when drawing something on a new blank canvas, where the preview has to expand (and zoom) to show it?  Try setting a biggish frame (the preview is frame-aware, and IIRC doesn't zoom as much when there's a frame), and then draw only inside the frame. Is the degree of lag caused by having the preview dock-panel open acceptable in this case?

(There will always be some extra work caused by having the preview open... it's just more zoomy when there's no frame.)

(A workaround for folks with really slow computers is to close the preview panel, then zoom in, and use View → Fit to View a lot (bounce on the F10 key!). Works as a toggle between overview-mode and whatever you're working on right now.)

**Comment by achadwick** [comment] 2015-07-27 13:18
Related work: #313

**Comment by achadwick** [comment] 2015-08-06 10:25
@MarbleStarry Any further information here? Please respond.

**Comment by achadwick** [comment] 2015-08-19 11:52
@MarbleStarry Please respond. Same goes for anyone reading this. I can't gauge how serious or widespread this issue is without more details about peoples' systems.

**Comment by achadwick** [comment] 2015-08-19 11:54
**Triage note**: this has gone a little stale, but is probably worth keeping if we can. We really need some details about machine CPU speeds and graphics drivers/architectures on affected machines. Give it a month to gather replies before closing? It'll still be searchable and reopenable.

**Comment by MarbleStarry** [comment] 2015-08-19 12:26
I'm really sorry for not being able to respond for a long time! :disappointed: I will try to respond as soon as possible from now on.

Well, the PC I use is pretty bad when it comes to specs.
CPU: AMD E-350 Dual-Core 1.6Ghz
GPU: AMD Radeon HD 6310 (384MB, shared with system memory)
But MyPaint 1.1.0 was performing really well and 1.2.0 does have some performance issues here n' there but it's acceptable.

To answer your questions:
Q: Is this the behaviour you get when drawing something on a new blank canvas, where the preview has to expand (and zoom) to show it?
A: Yes! Exactly! :smile:

Q:  Try setting a biggish frame (the preview is frame-aware, and IIRC doesn't zoom as much when there's a frame), and then draw only inside the frame. Is the degree of lag caused by having the preview dock-panel open acceptable in this case?

A: Nope. It doesn't reduce the lag.

Btw, exact same lag also occurs when I use symmetry tool. <s>Also same thing when using big or complex brushes.</s> (Can something like frame-skipping be implemented? Instead of processing every frame going to be displayed when making a brush stroke? Or rendering the stroke in low quality and then render it in high quality after stroke finishes?)

**Comment by MarbleStarry** [comment] 2015-08-19 12:29
(I'm currently unable to test any further suggestions right now as I'm on Windows 10. I will install Ubuntu as dual boot soon.)

**Comment by achadwick** [comment] 2015-08-19 12:48
Thanks for the response - good feedback there :+1: 

Deferring draw events somehow was something I considered for the Windows-specific #390, but in that case it might not help (that one seems to be about the raw performance of the brushstroke rendering engine for a specific build).

To clarify, the brushstroke is rendered once to somewhere in memory, and then displayed by each view  connected to it. So if having more views open on the same thing slows it down, it's clear where the issue lies... :cry: 

Other things to look at: you can zoom out much further with the preview than you can with the main view (1:128 vs. 1:16), but I'm not sure we're doing the right things with mipmap levels to make this work as efficiently as possible.

We should also make sure that the preview window is stable, i.e. not redrawing its entire area each time. Each bit of drawing deep within a fixed frame should only update the area around the drawn brushstroke in the preview window.

(Personally I wouldn't mind being lazy about displaying stuff in the preview window: even a second of lad won't matter too much in something so small. Realtimeness expectations will be lower for it too :grinning: )

**Comment by MarbleStarry** [comment] 2015-08-21 18:29
Uhh... Weird stuff going on... I switched to Xubuntu 14.04.2 LTS 64bit and... somehow the lag issue got fixed. I just installed 1.2.0 from testing PPA (1.2.0-beta.1+gitexport.a7012b4) and it worked :laughing: :confused:  .

I guess it's because Xubuntu is a lot more lightweight than Ubuntu (Unity) so more room got left for Mypaint. Only way I could get same amount of lag was opening preview dock and symmetry tool simultaneously. But when only using preview dock or symmetry tool, there is (almost) no lag. It's like, you turned on smoothing just slightly and that is really acceptable. I also think the lag maybe was being caused by Ubuntu itself as it wasn't LTS release and suppossed to be less stable. 

But first one seems a lot more appropriate because other software (GIMP, Drawpile, etc.) and games (Minecraft, etc.) also performs a lot better.

**Comment by achadwick** [comment] 2015-08-21 20:46
Hmm. Perhaps there's some difference between the two DEs' compositors that matters. If you turn on Xfce's window manager compositing (if it isn't already), does that change it? I think the setting is in WM Tweaks in Xfce.

**Comment by MarbleStarry** [comment] 2015-08-21 21:10
I found the window compositing setting in "Window Manager (Fine-tune)" (I translated it from Turkish, I have no idea what it's exactly called in English version). It doesn't change anything. Performance is pretty much same both when window compositing turned on or off.

**Comment by Rolliboy** [comment] 2015-09-10 19:56
Hi all!
This is a link to a video that shows the slowness of any the stroke I made.
It also shows version 1.0.0 of mypaint that works very well.
seems that using a mouse there are less lag than using an Intuos 4

Another info is that closign any panel takes a second to succeed..

Hope you find this informations useful, ask anything I really appreciate this app and I'll try to give my little support!

VIDEO SAMPLE:
https://drive.google.com/file/d/0Bz0onNCzAi1AbmFIMUpKQnFjbHM/view?usp=sharing

MYPAINT:
1.2.0-beta.1+gitexport.a7012b4 

OS:
Windows 10 Pro 64 bit (10.0, build 10240)

HARDWARE:
Intel(R) Core(TM) i7 CPU 930 @ 2.80GHz (8 CPUs)
12GB RAM

GRAPHIC CARD:
AMD Radeon HD 5800 Series
Driver: aticfx64.dll v15.200.1062.1004
DirectX v11.2

**Comment by achadwick** [comment] 2015-10-09 00:15
@MarbleStarry I've made redrawing happen much less responsively in the preview panel than in the main area. Are you able to re-test the master branch and verify a fix?

**Comment by achadwick** [comment] 2015-10-21 23:34
@MarbleStarry I am assuming this is fixed in v1.2.0-beta.1.168 (available from the PPA and on the releases page), but please re-open this issue if you are running that version and there is still unacceptable lag when the preview window is open. Thanks!

**Closed by achadwick** 2015-10-21 23:34 UTC
Labels: performance
