### ISSUE TITLE
1.2.1 beta 64 - Windows 10 64 - Dockpanels (excess close button crash mypaint)

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#640] opened 2016-04-05 14:55 UTC
Windows 10 x64
1.2.1-beta.0+gitexport.3fd40c8
(Python 2.7.11, GTK 3.20.1, GdkPixbuf 2.34.0, Cairo 1.15.2, GLib 2.48.0)
1. Toggle dockpanel (i tried scratchpad)
2. Remove dockpanel from left or right column
3. Close dockpanel with excess close button
4. On the toolbar dockpanel shown working, even it already closed
5. Click again on that dockpanel on toolbar. Switches to closed dockpanel
6. Click again to open dockpanel - Crash

```
DEBUG: gui.workspace: Adding 'MyPaintScratchpadTool' []
DEBUG: gui.workspace: Showing <scratchwindow.ScratchpadTool object at 0x0000000012625230 (MyPaintScratchpadTool at 0x000000001542ef60)>, which is currently hidden
DEBUG: gui.workspace: Showing <workspace.ToolStack object at 0x000000000f391820 (MyPaintToolStack at 0x0000000004027ad0)> (ancestor of freshly shown tool <scratchwindow.ScratchpadTool object at 0x0000000012625230 (MyPaintScratchpadTool at 0x000000001542ef60)>)
```

**Comment by zb13y** [comment] 2016-04-14 11:49
Ok, this crash happens only when i close dockpanel with excess button.

<img src='https://cloud.githubusercontent.com/assets/13454470/14285745/23ff9508-fb66-11e5-94c3-d33967549e9e.jpg'></img>

**Comment by zb13y** [comment] 2016-05-05 11:02
1.2.1-beta.1+gitexport.3198e3f
(Python 2.7.11, GTK 3.20.3, GdkPixbuf 2.34.0, Cairo 1.15.2, GLib 2.48.0)

![1](https://cloud.githubusercontent.com/assets/13454470/15041861/b301ec9a-12d8-11e6-9877-1b59f55e9f57.jpg)![2](https://cloud.githubusercontent.com/assets/13454470/15041862/b3037dbc-12d8-11e6-8f0a-3436c417e03b.jpg)

Left screenshot - 1.2.1., right - 1.2.0.

What if mypaint redo closebuttons in dockable panels? When panel undocked it will have closebutton in window and when panel docked it will have own closebutton (like now). I think only dockable panels don't have closebuttons in windows, other windows have closebuttons. So MyPaint will look more unificated.

**Comment by achadwick** [comment] 2016-12-05 23:25
Confirmed duplicate of #679.

**Closed by achadwick** 2016-12-05 23:25 UTC
