### ISSUE TITLE
threw exception changing brush using stylus, similar to #875

### ISSUE THREAD

**Issue by kelvinwop** [mypaint/mypaint#900] opened 2018-02-22 23:28 UTC
#### Description of the problem

Error when trying to fix crazy strokes

#### Basic system details

MyPaint version: 
1.2.1+gitexport.bcf5a28d

(Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1)

Operating system: win 8.1

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. Use stylus first button after the jagged lines of error #879 and #177 appear
3. Haven't been able to reproduce, will keep thread updated if I can

#### Backtraces or error messages

```
Mypaint version: 1.2.1+gitexport.bcf5a28d
System information: Windows-8.1-6.3.9600-SP0
Using: Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1
Traceback (most recent call last):
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/document.py", line 1547, context_cb(self=<gui.document.Document object>, action=<Gtk.Action object at 0x000000000d400690 (GtkAction at 0x000000000e098190)>)
                # restore brush
                bm.select_brush(context)
                if self.app.preferences['misc.context_restores_color']:
  variables: {'bm.select_brush': ('local', <bound method BrushManager.select_brush of <gui.brushmanager.BrushManager object at 0x000000000d41a910>>), 'context': ('local', <ManagedBrush u'context02' p=None>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 687, select_brush(self=<gui.brushmanager.BrushManager object>, brush=<ManagedBrush u'context02' p=deevad/pen>)
            brushinfo = brush.brushinfo
            if not self.is_in_brushlist(brush):
  variables: {'brush.brushinfo': ('local', <lib.brush.BrushInfo object at 0x000000000e590990>), 'brushinfo': (None, [])}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 969, get_brushinfo(self=<ManagedBrush u'context02' p=deevad/pen>)
        def get_brushinfo(self):
            self._ensure_settings_loaded()
            return self._brushinfo
  variables: {'self._ensure_settings_loaded': ('local', <bound method ManagedBrush._ensure_settings_loaded of <ManagedBrush u'context02' p=deevad/pen>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 1211, _ensure_settings_loaded(self=<ManagedBrush u'context02' p=deevad/pen>)
                logger.debug("Loading %r...", self)
                self.load()
                assert self._settings_loaded
  variables: {'self.load': ('local', <bound method ManagedBrush.load of <ManagedBrush u'context02' p=deevad/pen>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 1153, load(self=<ManagedBrush u'context02' p=deevad/pen>)
            self._load_preview()
            self._load_settings()
  variables: {'self._load_settings': ('local', <bound method ManagedBrush._load_settings of <ManagedBrush u'context02' p=deevad/pen>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 1175, _load_settings(self=<ManagedBrush u'context02' p=deevad/pen>)
            try:
                self._brushinfo.load_from_string(brushinfo_str)
            except BrushInfo.ParseError, e:
  variables: {'self._brushinfo.load_from_string': ('local', <bound method BrushInfo.load_from_string of <lib.brush.BrushInfo object at 0x000000000e590990>>), 'brushinfo_str': ('local', '{\n    "comment": "MyPaint brush file", \n    "description": "A pen to draw and sketch", \n    "group": "", \n    "notes": "A brush preset part of the Brushkit v0.6 \\n created in october 2012 by David Revoy ( aka Deevad ) \\n source: http://www.davidrevoy.com/article142/ressource-mypaint-brushes \\n license: CC-Zero/Public-Domain", \n    "parent_brush_name": "deevad/pen", \n    "settings": {\n        "anti_aliasing": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_h": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_hsl_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_hsv_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_l": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_v": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_h": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_v": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "colorize": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "custom_input": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "custom_input_slowness": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "dabs_per_actual_radius": {\n            "base_value": 5.24, \n            "inputs": {}\n        }, \n        "dabs_per_basic_radius": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "dabs_per_second": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "direction_filter": {\n            "base_value": 2.0, \n            "inputs": {}\n        }, \n        "elliptical_dab_angle": {\n            "base_value": 178.09, \n            "inputs": {}\n        }, \n        "elliptical_dab_ratio": {\n            "base_value": 1.0, \n            "inputs": {}\n        }, \n        "eraser": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "hardness": {\n            "base_value": 1.0, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        0.12\n                    ], \n                    [\n                        1.0, \n                        -0.18\n                    ]\n                ]\n            }\n        }, \n        "lock_alpha": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_2": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_2_asc": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_adj": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_asc": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_random": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_speed": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_speed_slowness": {\n            "base_value": 1.0, \n            "inputs": {}\n        }, \n        "offset_multiplier": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_x": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_y": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "opaque": {\n            "base_value": 0.29159999999935204, \n            "inputs": {}\n        }, \n        "opaque_linearize": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "opaque_multiply": {\n            "base_value": 0.0, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        0.0\n                    ], \n                    [\n                        0.302469, \n                        0.104167\n                    ], \n                    [\n                        0.546296, \n                        0.333333\n                    ], \n                    [\n                        0.688272, \n                        0.729167\n                    ], \n                    [\n                        0.814815, \n                        0.927083\n                    ], \n                    [\n                        1.0, \n                        1.0\n                    ]\n                ]\n            }\n        }, \n        "pressure_gain_log": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "radius_by_random": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "radius_logarithmic": {\n            "base_value": 1.02, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        -0.5\n                    ], \n                    [\n                        0.326923, \n                        -0.320312\n                    ], \n                    [\n                        0.717949, \n                        0.046875\n                    ], \n                    [\n                        1.0, \n                        0.75\n                    ]\n                ]\n            }\n        }, \n        "restore_color": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "slow_tracking": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "slow_tracking_per_dab": {\n            "base_value": 1.52, \n            "inputs": {}\n        }, \n        "smudge": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "smudge_length": {\n            "base_value": 0.5, \n            "inputs": {}\n        }, \n        "smudge_radius_log": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "snap_to_pixel": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "speed1_gamma": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "speed1_slowness": {\n            "base_value": 0.04, \n            "inputs": {}\n        }, \n        "speed2_gamma": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "speed2_slowness": {\n            "base_value": 0.8, \n            "inputs": {}\n        }, \n        "stroke_duration_logarithmic": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "stroke_holdtime": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "stroke_threshold": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "tracking_noise": {\n            "base_value": 0.0, \n            "inputs": {}\n        }\n    }, \n    "version": 3\n}')}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/lib/brush.py", line 181, load_from_string(self=<lib.brush.BrushInfo object>, settings_str='{\n    "comment": "MyPaint brush file", \n    "des..."inputs": {}\n        }\n    }, \n    "version": 3\n}')
                # new json-based brush format
                self.from_json(settings_str)
            elif settings_str.startswith('#'):
  variables: {'self.from_json': ('local', <bound method BrushInfo.from_json of <lib.brush.BrushInfo object at 0x000000000e590990>>), 'settings_str': ('local', '{\n    "comment": "MyPaint brush file", \n    "description": "A pen to draw and sketch", \n    "group": "", \n    "notes": "A brush preset part of the Brushkit v0.6 \\n created in october 2012 by David Revoy ( aka Deevad ) \\n source: http://www.davidrevoy.com/article142/ressource-mypaint-brushes \\n license: CC-Zero/Public-Domain", \n    "parent_brush_name": "deevad/pen", \n    "settings": {\n        "anti_aliasing": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_h": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_hsl_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_hsv_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_l": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_v": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_h": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_v": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "colorize": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "custom_input": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "custom_input_slowness": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "dabs_per_actual_radius": {\n            "base_value": 5.24, \n            "inputs": {}\n        }, \n        "dabs_per_basic_radius": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "dabs_per_second": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "direction_filter": {\n            "base_value": 2.0, \n            "inputs": {}\n        }, \n        "elliptical_dab_angle": {\n            "base_value": 178.09, \n            "inputs": {}\n        }, \n        "elliptical_dab_ratio": {\n            "base_value": 1.0, \n            "inputs": {}\n        }, \n        "eraser": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "hardness": {\n            "base_value": 1.0, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        0.12\n                    ], \n                    [\n                        1.0, \n                        -0.18\n                    ]\n                ]\n            }\n        }, \n        "lock_alpha": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_2": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_2_asc": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_adj": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_asc": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_random": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_speed": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_speed_slowness": {\n            "base_value": 1.0, \n            "inputs": {}\n        }, \n        "offset_multiplier": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_x": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_y": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "opaque": {\n            "base_value": 0.29159999999935204, \n            "inputs": {}\n        }, \n        "opaque_linearize": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "opaque_multiply": {\n            "base_value": 0.0, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        0.0\n                    ], \n                    [\n                        0.302469, \n                        0.104167\n                    ], \n                    [\n                        0.546296, \n                        0.333333\n                    ], \n                    [\n                        0.688272, \n                        0.729167\n                    ], \n                    [\n                        0.814815, \n                        0.927083\n                    ], \n                    [\n                        1.0, \n                        1.0\n                    ]\n                ]\n            }\n        }, \n        "pressure_gain_log": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "radius_by_random": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "radius_logarithmic": {\n            "base_value": 1.02, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        -0.5\n                    ], \n                    [\n                        0.326923, \n                        -0.320312\n                    ], \n                    [\n                        0.717949, \n                        0.046875\n                    ], \n                    [\n                        1.0, \n                        0.75\n                    ]\n                ]\n            }\n        }, \n        "restore_color": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "slow_tracking": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "slow_tracking_per_dab": {\n            "base_value": 1.52, \n            "inputs": {}\n        }, \n        "smudge": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "smudge_length": {\n            "base_value": 0.5, \n            "inputs": {}\n        }, \n        "smudge_radius_log": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "snap_to_pixel": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "speed1_gamma": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "speed1_slowness": {\n            "base_value": 0.04, \n            "inputs": {}\n        }, \n        "speed2_gamma": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "speed2_slowness": {\n            "base_value": 0.8, \n            "inputs": {}\n        }, \n        "stroke_duration_logarithmic": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "stroke_holdtime": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "stroke_threshold": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "tracking_noise": {\n            "base_value": 0.0, \n            "inputs": {}\n        }\n    }, \n    "version": 3\n}')}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/lib/brush.py", line 165, from_json(self=<lib.brush.BrushInfo object>, json_string='{\n    "comment": "MyPaint brush file", \n    "des..."inputs": {}\n        }\n    }, \n    "version": 3\n}')
                if k not in self.settings:
                    print 'ignoring unknown brush setting %r' % k
                    continue
  variables: {'k': ('local', u'offset_angle_2')}
IOError: [Errno 9] Bad file descriptor
```

**Comment by NyanSquare** [comment] 2019-10-08 22:45
When MyPaint started, with my Wacom Intuos connected, I drew using the mouse, and then the error came out.

**Comment by jplloyd** [comment] 2019-10-09 08:39
This is caused by having used a newer version of MyPaint with brush settings that are not supported by 1.2.1. These kind of errors will no longer occur in newer versions, since context managers are now used for all (well, with one exception) file ops.

Just switching around to different brushes in 1.2.1 until the offending brushes have been pushed out of the history should solve this.

**Comment by jplloyd** [comment] 2019-12-27 23:23
Since the improved handling of files won't be backported to any 1.2.x release, we might as well close this.

**Closed by jplloyd** 2019-12-27 23:23 UTC
