### ISSUE TITLE
python2w.exe: can't set up different buttons in the Wacom tablet control panel

### ISSUE THREAD

**Issue by DarkDragon83** [mypaint/mypaint#561] opened 2016-01-11 20:36 UTC
Hey, 
me again :)
ok after you could helped me with my "floating windows problem", i have another one. 
My Paints working now and i want to set up my Wacom.
First Problem: 
In my wacom Settings, i cant add MyPaint as a Programm. 
As you can see on the pictures i tried to add MyPaint in my Wacom Settings, but it didnt work (as it does with gimp as you can see). Have i done sth wrong? So i cant adjust my Tablet functions for My Paint. 
![picture01](https://cloud.githubusercontent.com/assets/16556812/12245873/89a066c4-b8ab-11e5-997b-66c33fa93ae9.jpg)
![picture02](https://cloud.githubusercontent.com/assets/16556812/12245836/4b16cb96-b8ab-11e5-96b3-8b7a14f99fed.jpg)
![picture03](https://cloud.githubusercontent.com/assets/16556812/12245837/4d223416-b8ab-11e5-8dde-7b533af44452.jpg)
![picture04](https://cloud.githubusercontent.com/assets/16556812/12245839/4efd8d8a-b8ab-11e5-9afe-f1219d80b011.jpg)

My Second Problem is, i have a huge delay on every brush with my wacom (with the mouse too, but its not so much and just if i draw a lot very fast). 
If i do fast many strokes with or without stopping, the Program needs SECONDS (really, very long), to catch up with me. Cant draw precise this way, its really annoying.
I have tried several brush settings, but it dosnt seemed to chance anything at all.

**Comment by tumagonx** [comment] 2016-01-11 20:59
Looks like this related to #390 and seems relevant with what @AnomalousG said regarding app name? could it be this is the culprit?

**Comment by tumagonx** [comment] 2016-01-11 21:01
@DarkDragon83 if you rename pythonw.exe to mypaint.exe and re-add  what happened?

**Comment by tumagonx** [comment] 2016-01-11 21:07
If that works you could start mypaint by drag mypaint (without extention) and drop into mypaint.exe

**Comment by tumagonx** [comment] 2016-01-11 21:21
Another possibility is because python2w.exe don't have file description resource in the executable and the driver failed to "identify" it.

**Comment by achadwick** [comment] 2016-01-12 00:02
@tumagonx Another reason to go with your build for 1.2.0 ☺

Regarding exe names, I've been playing with `cx_Freeze` recently, and the results are pretty promising: <https://github.com/achadwick/hello-cxfreeze-gtk>. The result of that Noddy build has the right exe name in Task Manager, anyway.

@DarkDragon83 
The lag issue is almost certainly #390 again. Please comment there about lag on Windows, and note that @tumagonx 's build is (I sincerely hope) free of lag because of a different choice of GTK.

**Comment by achadwick** [comment] 2016-01-12 00:10
Certainly I'd like to investigate `cx_Freeze` as a fix for this in my builds. It seems pretty robust given what it does :neutral_face:

After #535 is fixed, we may be able to move to a true distutils/setuptools Python bundling, but I've not yet played with getting that test snippet above working with `python setup.py install`.

**Comment by DarkDragon83** [comment] 2016-01-12 12:19
Hey,
so rename it into mypaint.exe dosnt work either

**Comment by achadwick** [comment] 2017-02-03 02:10
(I am not dealing with the lag bug in this issue.)

**Comment by achadwick** [comment] 2017-02-03 02:18
Reproduced in v1.2.1. This is user support, not a bug.

It is possible to set up user-defined button action in the Wacom Tablet Properties program, but you must associate them with the python2w executable that's part of MyPaint. The procedure is:

1. Plug in your tablet.
2. Start _Wacom Tablet Properties_
3. Start _MyPaint_
4. In _Wacom Tablet Properties_, click on the `+` button highlighted above.
5. In the dialog ("Add Application for Custom Settings") that pops up:
  * Choose `python2w`
  * Check that the path is right (it must mention `Program Files[something]\mypaint-w64` (or `-32`))
  * Click the `OK` button to close the dialog.
6. Highlight the icon for the program.
7. Set your settings.

Steps 1-3 must be followed in order.

Hope that's OK. Closing...

**Closed by achadwick** 2017-02-03 02:18 UTC
Labels: user-support, windows
