### ISSUE TITLE
Clicking on the Layer Visibility button in the Layers Subwindow toggles the Layer Lock

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#234] opened 2015-03-04 03:51 UTC
Windows 8.1, MyPaint 1.1.1-alpha.20150211+git.72d08ef

I don't know what the proximity is for clicking on the "Layer Lock" option, but when I toggle a layer's visibility by clicking on it in the layer's subwindow, sometimes the layer lock option will also respond, which is slightly inconvenient.

**Comment by achadwick** [comment] 2015-03-04 10:12
Are you double-clicking by any chance? I've noticed that double-clicking the eye also toggles the lock as of e5ba4c6bea3f955ee4af07ba45b5a85708088383.

**Comment by mikshaw** [comment] 2015-03-04 22:45
on a possibly related note, i've seen a couple of times recently when layer visibility is accidentally toggled for reasons i haven't figured out, and i can't recreate. The first time was when adding a new layer, via hotkey, so there was no clicking involved,  and the layer that was already there became hidden. The other time was (i think) when selecting a layer...the previously selected layer became hidden. I'm not sure what happened, and in the second case i'm not sure when it happened...it wasn't anything more than a "hmmm" moment, but this thread sounds like it might be related.

debian testing, 64-bit

**Comment by achadwick** [comment] 2015-03-05 13:04
@AtsusaKaneytza do you double-click the icons, or is this this something else?

**Comment by achadwick** [comment] 2015-03-05 13:04
@mikshaw sounds like a different issue (this one looks to be limited to just the layers tree, but I haven't dug deeper). If you can reliably reproduce any part of it with a clean config, let us know the detailed steps.

**Comment by achadwick** [comment] 2015-03-05 20:32
@AtsusaKaneytza a fix should be along in the next Windows alpha. I'm assuming that the behaviour you were seeing was related to double-clicking, since that's all I was able to reproduce in my testing.

**Comment by AtsusaKaneytza** [comment] 2015-03-11 20:32
When I do it, its not a double click, its a single click.

**Comment by achadwick** [comment] 2015-04-22 01:41
@AtsusaKaneytza Can you either confirm that this bug is fixed with the latest Windows alpha, or provide full, detailed steps telling me how to reproduce the issue for myself if it's still happening? Many thanks.

**Comment by achadwick** [comment] 2015-04-22 01:43
**Triage note:** I think this is fixed; just seeking confirmation from the reporter. If this fix isn't confirmed in the next 14 days, let's close this issue.

**Comment by achadwick** [comment] 2015-06-04 15:27
No updates from reporter, time elapsed.

**Closed by achadwick** 2015-06-04 15:27 UTC
Labels: bug, needs-info, windows, works-for-me
