### ISSUE TITLE
Inking tool: Difficult to continue lines

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#227] opened 2015-02-27 05:25 UTC
Because the end point of a line is usually covered by a node, it's difficult to directly continue from one end of a line you have just plotted. Instead, you must begin drawing from the far endpoint of the next line, ending up at the endpoint you wanted to hit.

This is not altogether bad. But it is a bit of a problem with the interface and we'll need to work out a way to fix it at some point.

My only immediate idea is to place a second, smaller handle inside the first one: clicking on that should begin a new line from that point, ignoring the outer handle. The side effect of this, of course, would be that endpoint handles become slightly harder to move. They could be made bigger to compensate for this, perhaps.

**Comment by achadwick** [comment] 2015-02-27 10:29
(This refers to the newly added gui/inktool.py at eb76974969448486487feb08110981034f55fb11)

Just how common a use case is this for artists? I'm not sure how much this is needed. Is it frequent enough to not have to click on the accept (:check:) button when you want to continue a line?

A possibility I've considered is making the accept button appear near the end of the line that was drawn, about 30-70 screen pixels to the South of it. Or to its North if fingers being in the way on a Cintiq are an issue. However that might obscure some of the control points

------------------

(Aside: intuitively you might want to extend the current line instead (appending or prepending more handles to it), but those handles contain absolute time information for the sake of brushes with speed. Basically it can't be done without reversing the direction of time for the prepend case and lying about when it started for both cases, and I'm not really comfortable with that right now!)

**Comment by achadwick** [comment] 2015-05-01 17:31
@0ion9 Can you tell me how much of a needed feature this is please?

**Comment by 0ion9** [comment] 2015-05-02 01:22
Not as important as being able to reduce the number of points used, IME.
It's basically just the same difference, experentially, as the difference between using Line tool to draw a series of lines that happen to be connected, and using Connected Lines to draw them precisely connected.

**Comment by odysseywestra** [comment] 2019-12-12 06:53
Closing issue since this not a bug, but not really a feature request. Feel free to reopen this if you wish to continue this at a later time.

**Closed by odysseywestra** 2019-12-12 06:53 UTC
Labels: enhancement
