### ISSUE TITLE
Background always displays when I turn on Layer Solo, even with Show Background unchecked

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#233] opened 2015-03-04 03:07 UTC
Windows 8.1, MyPaint 1.1.1-alpha.20150211+git.72d08ef

Something I noticed when I was working on a commission:
I wanted to isolate the visibility of the layer to see if I made a mistake while inking (I accidentally picked another color and thought I drew a stroke in the new color)

The background was white when I did it though, so I couldn't tell, so i turned off the "show background" option under my layers.
Even after I did that though, when I toggled "Layer Solo", the background still showed up. I changed the background color, and the BG still showed up when I used "Layer Solo."

So I guess what I'm asking is: Shouldn't the "Layer Solo" option also exclude the file's background? Especially since when you switch between layers, the program will briefly show what the layer's contents look like without the background

Here's some screenshots of what I'm talking about, btw:
All layers visible:
![image](https://cloud.githubusercontent.com/assets/8382492/6477377/d9cd83d0-c1e8-11e4-881e-6bbb7cc2af5d.png)

Layer Solo toggled:
![image](https://cloud.githubusercontent.com/assets/8382492/6477384/ea672afc-c1e8-11e4-927c-5b7bc3bb8f04.png)

Even with "Show Background" unchecked, the background still displays with "Layer Solo"
![image](https://cloud.githubusercontent.com/assets/8382492/6477416/40dae5c2-c1e9-11e4-9746-f0ef36cb058c.png)

**Comment by 0ion9** [comment] 2015-03-04 03:38
IIRC this used to be the behaviour, but it was recently changed to be more useful -- the transparency checkers are often pretty unhelpful.

That second case, when Show Background is unchecked, seems like a legitimate bug though.

**Comment by achadwick** [comment] 2015-04-20 20:43
Confirmed. Taking this and #107 together, I think we should have two behaviours:

1. When "Show Background" is ON: the layer is shown by itself, directly over the background, with only its own layer mode in effect.
2. When "Show Background" is OFF: the layer is shown by itself, directly over the builtin checkerboard background, with its layer mode forced to "Normal", and at 100% opacity. This is what the layer blink effect does right now.

I don't think there are any other requirements to be met here, but it's been a while since I reviewed this issue. Please confirm that the description above is the way you want it to work.

Moving to the 1st beta cycle because this probably doesn't need any string modifications, but reassigning my way - it may get done in the alpha cycle if I have time.

**Closed** 2015-07-21 00:23 UTC
Labels: bug
