### ISSUE TITLE
Error with FrameEdit tool

### ISSUE THREAD

**Issue by khrakhm** [mypaint/mypaint#1097] opened 2020-07-30 12:35 UTC
#### Description of the problem
Error with FrameEdit tool. It doesn`t work

#### Basic system details

MyPaint version: 2.0.0+gitexport.af5225a. (Python 3.8.2, GTK 3.24.20, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.64.2)
Operating system: Ubuntu 20.04
Desktop environment: Ubuntu Desktop

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. Pick the FrameEdit Tool
3. Error window becames

#### Backtraces or error messages

```python
Mypaint version: 2.0.0+gitexport.af5225a
System information: Linux-5.4.0-42-generic-x86_64-with-glibc2.29
Using: Python 3.8.2, GTK 3.24.20, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.64.2
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/document.py", line 649, motion_notify_cb(self=<gui.document.Document object>, tdw=<tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>, event=<Gdk.EventMotion object at 0x7feaaf024360 (void at 0x410e210)>)
            # Normal event dispatch
            CanvasController.motion_notify_cb(self, tdw, event)
            return False  # XXX don't consume motions to allow workspace autohide
  variables: {'CanvasController.motion_notify_cb': ('global', <function CanvasController.motion_notify_cb at 0x7feaaf174c10>), 'self': ('local', <gui.document.Document object at 0x7feaacdd6520>), 'tdw': ('local', <tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>), 'event': ('local', <Gdk.EventMotion object at 0x7feaaf024360 (void at 0x410e210)>)}
  File "/usr/lib/mypaint/gui/document.py", line 120, motion_notify_cb(self=<gui.document.Document object>, tdw=<tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>, event=<Gdk.EventMotion object at 0x7feaaf024360 (void at 0x410e210)>)
            mode = self.modes.top
            result = mode.motion_notify_cb(tdw, event)
            self._update_last_event_info(tdw, event)
  variables: {'result': (None, []), 'mode.motion_notify_cb': ('local', <bound method FrameEditMode.motion_notify_cb of <gui.framewindow.FrameEditMode object at 0x7feaac041250>>), 'tdw': ('local', <tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>), 'event': ('local', <Gdk.EventMotion object at 0x7feaaf024360 (void at 0x410e210)>)}
  File "/usr/lib/mypaint/gui/framewindow.py", line 360, motion_notify_cb(self=<gui.framewindow.FrameEditMode object>, tdw=<tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>, event=<Gdk.EventMotion object at 0x7feaaf024360 (void at 0x410e210)>)
            if not self.in_drag:
                self._update_zone_and_cursors(tdw, event.x, event.y)
            return super(FrameEditMode, self).motion_notify_cb(tdw, event)
  variables: {'self._update_zone_and_cursors': ('local', <bound method FrameEditMode._update_zone_and_cursors of <gui.framewindow.FrameEditMode object at 0x7feaac041250>>), 'tdw': ('local', <tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>), 'event.x': ('local', 217.856201171875), 'event.y': ('local', 326.7908630371094)}
  File "/usr/lib/mypaint/gui/framewindow.py", line 329, _update_zone_and_cursors(self=<gui.framewindow.FrameEditMode object>, tdw=<tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>, x=217.856201171875, y=326.7908630371094)
            self._zone = zone
            self._update_cursors(tdw)
            tdw.queue_draw()
  variables: {'self._update_cursors': ('local', <bound method FrameEditMode._update_cursors of <gui.framewindow.FrameEditMode object at 0x7feaac041250>>), 'tdw': ('local', <tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>)}
  File "/usr/lib/mypaint/gui/framewindow.py", line 303, _update_cursors(self=<gui.framewindow.FrameEditMode object>, tdw=<tileddrawwidget.TiledDrawWidget object at 0x7feaacdc4340 (TiledDrawWidget at 0x2919130)>)
            cursors = [
                (1, self.cursor_move_w_e),     # right side
                (3, self.cursor_move_nw_se),   # bottom right corner
AttributeError: 'FrameEditMode' object has no attribute 'cursor_move_w_e'
```

**Comment by jplloyd** [comment] 2020-07-30 13:02
Thanks for the report. This is a duplicate of #1064 (among others) and has been fixed in the [2.0.1 release](https://github.com/mypaint/mypaint/releases/v2.0.1).

**Closed by jplloyd** 2020-07-30 13:02 UTC
