### ISSUE TITLE
Offset between cursor and drawing in dual screen mode

### ISSUE THREAD

**Issue by sebastien-bratieres** [mypaint/mypaint#410] opened 2015-08-17 10:00 UTC
I use Win 8 on a Surface Pro 8, and draw with a Wacom Intuos Pen&Touch Medium CTH-680 (not with the tablet pen). 
When using only tablet screen, drawing is as expected.
When I connect my second screen, the drawing no longer appears under the cursor. An offset appears both when I draw on the main (tablet) screen, and on the secondary monitor; however the offset is in a different direction on either screen. The offset is not present when drawing with the mouse.
Is any workaround known?

(Maybe this issue is not due to MyPaint... when I tried screen capturing this using an animated gif screen capture program, the pen/mouse pointer offset was different from what it is on the screen, and also the mouse showed an offset -- ok, ignore this extra info if it's confusing.)

**Comment by achadwick** [comment] 2015-08-17 10:23
Please tell me what version of MyPaint you are running: the long version string from **Help → About MyPaint** is the most informative one.

You don't draw with the tablet pen on your graphics tablet? I'm confused. Does this mean you draw on the CTH-680, but only use touch input on it?

Quick test - does this happen for you in GIMP also? And which version of GIMP?

I wonder if the "map to screen" tablet setting is actually mapping to the entire dual display? Please be sure to assign your tablet to a specific monitor in the dial screen case and try again.

(This sounds very like a user support request, which we try to discourage people submitting on the issue tracker (it's an awful place to do that: you only get developer eyes here). The issue tracker is for feature requests and bug reports, so if what you're reporting turns out not to be a parcel of work that can be done to improve MyPaint, I'll close this issue and refer you to somewhere else. Don't be discouraged if that happens.)

**Comment by achadwick** [comment] 2015-08-17 10:25
**Triage note**: needs mypaint version. This is almost certainly a GDK issue, and not something that can be handled here. Let's investigate for a bit first though.

**Comment by sebastien-bratieres** [comment] 2015-08-17 10:58
MyPaint version 1.2.0-beta.1+gitexport.a7012b4.
I use the pen on the CTH-680 (it has pen and touch, but I use only the
pen). The driver is up to date.
I don't use the Surface Pro's pen (it has a capacitive screen and a pen,
but I don't use that one, I use the Wacom graphic tablet's). The issue
arises only with the Wacom pen, not with the Surface Pro Pen, not with the
mouse.

The Wacom's Map to screen setting is set to map to whichever single display
I use. It is not mapping to both displays.

The issue does not appear in Gimp 2.8.14.

Happy to provide further information/do tests.

2015-08-17 11:23 GMT+01:00 Andrew Chadwick <notifications@github.com>:

**Comment by achadwick** [comment] 2015-08-17 15:45
@sebastien-bratieres Some illustrations of the offset might help. Can you share a drawing or screenshot showing your layout, and an approximation of the offsets' directions?

This sounds a lot like #243, in which case it's been affecting multiple versions of GDK for a long time (but why is it working in GIMP if that's the case?)

**Comment by achadwick** [comment] 2015-08-17 15:52
Possible upstream bugs (please search through their duplicates too, and comment upstream...) 

* https://bugzilla.gnome.org/show_bug.cgi?id=154657
* https://bugzilla.gnome.org/show_bug.cgi?id=167945

This is very much looking like an upstream issue at this point.

**Comment by sebastien-bratieres** [comment] 2015-08-18 11:22
Here's a video illustrating the issue: http://youtu.be/PH2rXKW7Fs4 . As I
wrote in the original report, my screen capturing tool shows the cursor in
yet another position than the actual position, and than the drawing
position.
This does sound like #243 for sure.
It does not, however, sound like the two upstream issues you mention, where
the issue is not a constant offset, but rather a mapping issue (dual screen
map vs single screen map discrepancy between tablet and program). Maybe
that explains why GIMP is not affected.


2015-08-17 16:52 GMT+01:00 Andrew Chadwick <notifications@github.com>:

**Comment by achadwick** [comment] 2015-08-18 12:05
@sebastien-bratieres "This video is private. Sorry about that."

Programs don't really maintain their own device "window" vs. "relative" vs. "display" vs. "monitor" mapping settings. At least, they don't in the X11 world.

**Comment by sebastien-bratieres** [comment] 2015-08-18 12:44
Apologies; the video is now accessible.

Programs...: you're referring to my point about the two upstream bug
reports? I don't know about the underlying software architecture, so I
can't comment on this; the symptoms description I read there did not seem
to correspond to mine, that's all I can say, for what it's worth...

2015-08-18 13:05 GMT+01:00 Andrew Chadwick <notifications@github.com>:

**Comment by achadwick** [comment] 2015-08-18 13:47
Beautifully explained in the video. Thank you for making it!

I noticed that your monitors were laid out

                       +-------------------+
    +-----------------+|                   |
    |                 ||                   |
    |     USB-mon     ||    Surface Pro    |
    |     USB mon     ||    main screen    |
    |                 ||                   |
    +-----------------+|                   |
                       +-------------------+

roughly side by side in your Windows monitor settings (I'm exaggerating the relative sizes somewhat!)

* https://youtu.be/PH2rXKW7Fs4?t=30s - on the USB monitor, strokes appear **above** and **to the right of** the cursor.
* https://youtu.be/PH2rXKW7Fs4?t=1m43s - in your settings, the monitors are arranged as above. Notably the surface pro's main screen is taller in pixels than your USB monitor, and roughly vertically centered relative to it.
* https://youtu.be/PH2rXKW7Fs4?t=2m15s - on the Surface Pro's main screen, stokes appear **to the left** of the cursor, but at the same height.

which is telling me that your cursor is somehow reflecting where the input is going on a virtual screen consisting of the bounding box of both physical screens:

    ##########################################
    #                   +-------------------+#
    #+-----------------+|                   |#   #=virtual display
    #|                 ||                   |#   C=cursor
    #|     S           ||             S  C  |#   S=registered stroke
    #|  C              ||                   |#
    #|                 ||                   |#
    #+-----------------+|                   |#
    #                   +-------------------+#
    ##########################################

Quick things to try, if you have time:

1. Does the horizontal offset get smaller in the middle of this "envelope"?
2. If you align the tops of the screens to each other in the setttings, does the vertical offset on the vertically smaller screen ever go away entirely ?
3. If you swap the monitors' physically and virtually, so that your Surface Pro is on the left, does the horizontal offset reverse too (on both monitors)?

**Comment by sebastien-bratieres** [comment] 2015-08-18 15:37
Your Windows monitor setting assumptions are correct.

1: no, that's where it is largest. The horizontal offset disappears at the
left (outer) edge of the envelope.
2: yes, the vertical offset disappears at the very top of the screen
3: yes
In addition, when screens are set as initially, offset is large at the
right, and disappears at the left (ie the outer edge of the envelope)
Not sure if this helps: Help/ Debug/ Test input devices tells me that
despite my 2ry screen being 1920*1080, the x values vary between 0 and
1280, y btw 0 and 720 (tested in full screen mode so I could go right to
the edge of the screen with the drawing). My primary screen has resolution
2160*1440 (says Windows).

2015-08-18 14:47 GMT+01:00 Andrew Chadwick <notifications@github.com>:

**Comment by achadwick** [comment] 2015-08-18 17:39
Okay, I made a thing for testing screen layouts, to make sure that Windows GDK knows the layout of the screens on the system. It does, so it's not that :grinning: 

![winmultiscreen](https://cloud.githubusercontent.com/assets/61299/9337615/48ca2e78-45d8-11e5-9fa3-1541ba87018a.png)

Program for this is at <https://gist.github.com/achadwick/c826870d80034c881d07>.

**Comment by achadwick** [comment] 2015-08-18 18:01
That's as far as I can test it on the VM setup above though. After assigning my Intuos5 to the VM's USB system, my cursor follows the brushstrokes no matter what virtual monitor I'm using. There are a few wrinkles to my setup because it's not real hardware:

* I do not get a cursor when I do this, so I have to fudge it by using pointer trails dialled all the way down to its lowest setting. It's a real tablet though, as far as the VM is concerned, and GDK/MyPaint receives pressure from it.
  ![Example Preferences dialog showing the setting in question](https://github.com/mypaint/mypaint/wiki/FAQ-win7-vm-pointer-trails.png)
  See the FAQ at <https://github.com/mypaint/mypaint/wiki/FAQ#how-can-i-make-a-cursor-icon-visible-when-using-a-tablet-in-a-vm>

* Perhaps my cursor only appears in the right position because it's really a pointer trail copy... I'll see if I can test out some real hardware too.

* I can't create any mapping other than "Full" in the _Wacom Tablet Properties_ (6.3.13w3) program. Attempting "Monitor 1" or "Monitor 2" results in a wrong-looking "Portion..." setup.

**Comment by achadwick** [comment] 2015-08-18 20:39
I can't reproduce this on real hardware with mypaint 0.2.0-beta.1 and Wacom drivers 6.3.13w3. What version of wintab32.dll are you using, and who made it? Mine's "Wacom Technology. Corp.", and it's version 1.0.5-8.

**Comment by sebastien-bratieres** [comment] 2015-08-18 21:36
wintab32.dll: same as mine. Wacom driver: where to look up the version?
(FYI I isntalled it 4 days ago). Any further info/ test I can do?

2015-08-18 21:39 GMT+01:00 Andrew Chadwick <notifications@github.com>:

**Comment by achadwick** [comment] 2015-08-18 23:46
Should be on the About button in the Wacom Tablet Properties program, 1m43s in your video :)

**Comment by sebastien-bratieres** [comment] 2015-08-19 07:21
6.3.13w3 like you.

**Comment by achadwick** [comment] 2015-08-23 18:46
From @AtsusaKaneytza on #243:

> UPDATE:
> Apparently, when I set my tablet monitor to "Extend" MyPaint will paint with no offset! That's really weird o_o
-- <https://github.com/mypaint/mypaint/issues/243#issuecomment-133896754>

I'm away from hardware I can test this on right now - can anyone confirm whether this is a good workaround in all circumstances?

**Comment by sebastien-bratieres** [comment] 2015-10-07 12:27
This is no workaround for me; my setting is already "Extend these displays", cf screenshot.
![image](https://cloud.githubusercontent.com/assets/4493404/10337383/857318dc-6cff-11e5-8210-b885219e6b78.png)

**Comment by sebastien-bratieres** [comment] 2015-11-24 11:40
1.2.0-beta.3+gitexport.0428646 fixed this issue for me. I no longer experience offsets in the same setup as described in my initial test case.

**Comment by achadwick** [comment] 2015-11-24 18:00
Interesting, since I did nothing ☺
That build uses GTK (and thus GDK) 3.18.3, so perhaps the fix was introduced there?

@sebastien-bratieres Can you confirm your current tablet driver version number too? The problem and the solution may also relate to how the two libs dovetail.

**Closed by achadwick** 2015-11-24 18:00 UTC
Labels: needs-info, request-for-help, upstream, windows

**Comment by sebastien-bratieres** [comment] 2015-11-30 10:03
My driver version is still 6.3.13w3.

**Comment by Trokenheim** [comment] 2017-01-12 21:36
Hi Sebastien and Achadwick!

I have the same problem and I've had it for ages on Windows. Last week I switched to a brand new computer and hoped that the problem might have gone, but it is exactly the same unfortunately. So it seems that the bug is still around and it drives me crazy :)

My way of solving it is to work in Ubuntu instead, where the exact same setup is used. But it works perfectly, so I would say it is a Windows problem.

I use a Wacom Companion Hybrid (latest drivers) as a second monitor. If only use the Wacom Companion Hybrid as monitor (laptop screen switched off), then it works fine.

The system is Windows 10 and Mypaint 1.2.1.

**Comment by achadwick** [comment] 2017-01-21 23:31
Worth noting that MyPaint 1.2.1 was only released today. @Trokenheim please can you test again in Windows, and if it's still happening get some feedback to us through another ticket?

Worth noting that we bundle a tablet tester (really GTK3-Demo's event_axes tester!) now, so you can get a second opinion. That's software that's unrelated to MyPaint in fundamental ways, so it will help identify when the real culprit is GTK/GDK.

**Comment by Trokenheim** [comment] 2017-01-23 11:34
Hi @achadwick 

Another ticket, does that I'll make a new issue? Sorry, but I'm a GitHub-noob.

**Comment by achadwick** [comment] 2017-01-23 13:59
@Trokenheim Yes, sorry. That's what I meant to write.

You can refer back to this issue as `#410` when you make the report. That will link things up nicely.

**Comment by AtsusaKaneytza** [comment] 2017-01-24 20:22
Tested out MyPaint 1.2.1 (32-bit) as asked
Tablet: Yiynova MVP10U Screen Tablet
OS: Windows 10 64-bit

In dual screen mode, there is still offset between the cursor position and the strokes made on the canvas. Single-screen mode works normally, as usual.
I tried out the Test Tablet Support Module, and it appears that the "Event Axes" window doesn't respond to my tablet pen, but responds fine to my mouse. So what does it mean?

**Comment by achadwick** [comment] 2017-01-25 02:35
@AtsusaKaneytza Make the blobs-and-crosshairs window bigger to be sure, or unplug your second monitor. The offset thing may be killing its usefulness.

Can't remember if I've asked, but do affected people use the same scale factor on both monitors? It might be upstream's <https://bugzilla.gnome.org/show_bug.cgi?id=776883> here.

**Comment by AtsusaKaneytza** [comment] 2017-01-26 02:52
My second monitor IS my tablet.
The screen tablet's resolution is 1024x600 pixels, whereas my laptop screen resolution is 1920x1080p.

**Comment by Trokenheim** [comment] 2017-01-26 21:06
Try to have the same zoom value on both screens. It helped me, the offset is gone. But I have to add that both screens have the same resolution also.
[https://github.com/mypaint/mypaint/issues/763](url)

**Comment by achadwick** [comment] 2017-01-27 11:34
@Trokenheim 
We could do with some instructions for that. Is it the DPI value, or am I looking in the wrong place?

BTW, your links aren't working. Just write #763 and github will link it automatically.

**Comment by Trokenheim** [comment] 2017-01-27 13:15
@achadwick I do not now the proper english term for it, since I have a swedish version of Windows. I talk about the screen settings where I can change the value for zoom/scale. It changes the size of text and icons.

### My setup
Screen 1 = Laptop
Screen 2 = Wacom Companion Hybrid

Screen resolution:
Both screens have the same screen resolution of 1920 x 1080. I haven't changed that at all.

![bild](https://cloud.githubusercontent.com/assets/25089495/22372013/dd70f806-e49a-11e6-8847-4363e2dbbb0e.png)

### Tests
1. Screen 1 100% - screen 2 100% = NO OFFSET
2. **Screen 1 100% - screen 2 125% = OFFSET**
3. **Screen 1 100% - screen 2 150% = OFFSET**
4. **Screen 1 100% - screen 2 175% = OFFSET**
5. Screen 1 125% - screen 2 100% = NO OFFSET
6. Screen 1 125% - screen 2 125% = NO OFFSET
7. **Screen 1 125% - screen 2 150% = OFFSET**
8. **Screen 1 125% - screen 2 175% = OFFSET**
9. Screen 1 150% - screen 2 100% = NO OFFSET
10. Screen 1 150% - screen 2 125% = NO OFFSET
11. Screen 1 150% - screen 2 150% = NO OFFSET
12. **Screen 1 150% - screen 2 175% = OFFSET**
13. Screen 1 175% - screen 2 175% = NO OFFSET

My conclustion of the testresults above  is that **the offset appears when screen 2 has a larger scale** than screen 1.

### Screenshot
Here is an screenshot of how it looks in effect. I've drawn a starting point and you can clearly see how the offset differs in relation to the amount of screen scaling.

![bild](https://cloud.githubusercontent.com/assets/25089495/22371756/3494f6b6-e499-11e6-9f45-845e1e44e3e1.png)

**Comment by Trokenheim** [comment] 2017-01-29 17:29
@hiuller Glad to help! ☺👍

**Comment by emandtf** [comment] 2017-07-21 09:02
Yes setting a 100% scale solves the problem but on a 4K screen (3800x2100) all interface (buttons, descriptions, etc...) are too very small to be clicked.
A few pixels button is hard to click, so this solutions is not always a good option.
