### ISSUE TITLE
Offsets with multiple displays. Yiynova tablet MVP20U+RH (UC LOGIC drivers) + MyPaint x32.

### ISSUE THREAD

**Issue by stkopp** [mypaint/mypaint#704] opened 2016-06-08 22:10 UTC
So, me again.
In last topic I pointed to [multiple issues with UC Logic drivers](https://github.com/mypaint/mypaint/issues/493). All of them, except one, is easily fixed with installing x32 bit version of mypaint. But, one issue still in place (although we can fix it with really non popular method).

I am talking about offset painting. I am using 2 displays (my tablet is MVP20U+RH) and if I want to draw in mypaint I need to turn off one display, or share displays (duplicate displays). It is not really convenient. I love Mypaint, but I can not always turn one display off.

I thought if I make virtual machine with linux for second display it kind of fix this issue for me, but I have found that linux do not support any other tablet than Wacom (and drivers from wizardpen or diamend wont work either), so this is not an issue either...alas :(

Maybe it is possible to fix issue with offset painting somehow?
Issue number[ #410](https://github.com/mypaint/mypaint/issues/410) is not helpful. Also I am using mypaint-w32-1.2.0-beta.4 (beta of mypaint 1.2.1 have some UI problems, sometimes I can not grab UI elements)

**Comment by achadwick** [comment] 2016-06-08 23:49
Really, the UI glitches are normally GTK3 issues. This is the wrong place to report them, but trying to describe the problem in enough detail to report upstream has always been like trying to catch jelly in a net.

Somebody with one of these setups is going to have to do some testing with MSYS2 and gtk3-demo. Otherwise we can't possibly know what component is at fault. Would you be up for that?

I suspect this is a duplicate of #614.

**Comment by stkopp** [comment] 2016-06-09 00:35
I would love to help, but I dont know how.
What should I do?

**Comment by achadwick** [comment] 2016-06-09 09:27
Still a bit swamped with other work, but you can help in a major way by looking at #614 and telling me whether the symptoms look similar. Don't worry too much about your tablet model when you're comparing. Perhaps you could confer with @Norashinshi and decide?

If you can't go much deeper, then this report is just user support. We don't have a fix for the underlying problem yet, and this is not the right forum for user support, sorry.

It would be useful to know if this problem presents on more than one tablet model. That might help with the sleuthing :feet::mag:

**Comment by stkopp** [comment] 2016-06-10 04:51
well, I guess I have similar problem.
Also GIMP dont responce correctly (as mypaint, I guess, It is messing with buttons in 64 bit verson...i cant install 32 bit, because gimp not allow us to install it, so, I can not test 32 bit version)

I wonder why krita dont have such problems? Do they use alternative technology?

So, if you telling me that this is wrong place to put my issue, where should I put it? Do I have to write somewhere here: https://bugzilla.gnome.org/show_bug.cgi?id=613501
?

**Comment by achadwick** [comment] 2017-01-22 06:14
@stkopp 
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has now been released. Please can you confirm whether or not this bug is still happening in that version?

**Comment by stkopp** [comment] 2017-01-22 10:07
Alas :( Problem is still here
![image](https://cloud.githubusercontent.com/assets/11293909/22181751/7e754ffa-e0a3-11e6-90e6-c315de8396d0.png)

I tryed to use all different versions from 64 bit to 32 and standalone

**Comment by stkopp** [comment] 2017-01-22 10:27
For everyone who will visit this page with similar problem - there is some "solution". You can download Lazy Nezumi which have free function of "correcting" some tablet problems such as mine. 

Well it is not the panacea, sometimes colours can not be grabbed and fast stroke leave big colour splatters...but it is actually kind of fixing the offset.
![animation](https://cloud.githubusercontent.com/assets/11293909/22181848/4ce3098e-e0a6-11e6-8524-6a4df5105866.gif)

**Comment by achadwick** [comment] 2017-01-24 11:01
@stkopp 
The offset thing looks like it might be <https://bugzilla.gnome.org/show_bug.cgi?id=776883>. Are you using the same scaling on both monitors?

**Comment by stkopp** [comment] 2017-01-24 17:27
Im not win10 user. Also my monitors have absolutely same resolution and monitor scaling is same on both monitors
![image](https://cloud.githubusercontent.com/assets/11293909/22258630/639f6aa4-e273-11e6-8d1f-d81c8e02b391.png)

**Comment by stkopp** [comment] 2017-02-23 09:55
Just get beta drivers from yiynova and offset in mypaint is gone! But...well...another problem:
![strokes](https://cloud.githubusercontent.com/assets/11293909/23253460/ad19b3ec-f9c5-11e6-81fe-a9d66026006b.gif)

I tried latest 32 and 64 bits releases all of them have same issues. I will try to run earlier builds and see if they work.

Photoshop and other software don't have this problem, so beta drivers is working correctly with other software.

**Comment by odysseywestra** [comment] 2017-02-23 10:33
@stkopp I'm having the same issue, however I'm using a wacom embeded tablet(HP TX2500) so I think this is a separate issue. I've meant to post a new issue about this, but forgot to get around to it. If you post a new issue I'll be sure to add my info as well.

**Comment by stkopp** [comment] 2017-02-23 11:35
@odysseywestra Hm, interesting, I will make a new post about it if @achadwick is ok with that :)

So, if wacom have this problems, we are on half way to solve them. I believe wacom users have more support in open source community.

**Comment by achadwick** [comment] 2017-02-23 13:36
Okay, it's probably safe to say that the Yiynova *offsets* are an upstream bug in the closed-source drivers, I guess :man_shrugging:

We have offset-fixes in the pipeline for GTK, but that looks like a separate issue, to do with monitor scaling and HiDPI.

@stkopp 
Lines between pen-ups and pen-downs. Ouch. I wonder what input we're receiving there. :thinking: 
Normally pressure input between strokes is like:

    ...1112266699977772211100000000000000000000000016688999...
    ......................A........................B..........

The brush engine will make a straight line between A and B if it receives no zero-pressure events between the two points. We artificially supply zero-pressure tail-in and lead-out events for button presses in some circumstances.

Definitely a separate issue, happy to help diagnose it and chase it with the right people.

**Comment by achadwick** [comment] 2017-02-23 13:37
Anyway, closing because the offsets have vanished on a driver upgrade, with all other things being kept the same.

**Closed by achadwick** 2017-02-23 13:37 UTC
Labels: needs-info, upstream, user-support, windows
