### ISSUE TITLE
Brushes in the `B` selector don't have description in the tooltip

### ISSUE THREAD

**Issue by bluss** [mypaint/mypaint#702] opened 2016-06-07 20:35 UTC
#### Description of the problem

Brushes in the **B** selector don't have description in the tooltip, but brushes in the docked selector do. It would be great to show the description in the tooltip for the **B** selector.

**Comment by achadwick** [comment] 2016-06-07 22:35
(Please can you fill in the other data requested in [the template](https://github.com/mypaint/mypaint/blob/master/ISSUE_TEMPLATE.md) if I don't cover it below? Thanks.)

Reproduced in git master as of 8acacb3dd0d972371d8b0a97176e5a42d011b25f. To clarify this one, the name of the brush is present, but the description is not.

![issue702-popup](https://cloud.githubusercontent.com/assets/61299/15876935/819fad5a-2d08-11e6-9454-dba80779f820.png)
![issue702-docked](https://cloud.githubusercontent.com/assets/61299/15876936/819fc93e-2d08-11e6-8686-7c5b9d210f75.png)

**Comment by achadwick** [comment] 2016-06-07 23:06
### Good new starter task

This is a little addition which makes a nice difference for users, and the solution is already coded. It would be easy for one of us to do the job, but I'd like to give a first-timer the opportunity to learn, if possible.

### What needs to be done

- Get yourself a Github account.
  - Check out the [hello-world tutorial](https://guides.github.com/activities/hello-world/) they suggest. It's good stuff.
  - Read up on the [branching model](https://guides.github.com/introduction/flow/) too.
- _Claim this proposal._ Leave a comment below saying that you want to work on this.
  - One of us will assign it to you
- Nowadays, you need to install [libmypaint](https://github.com/mypaint/libmypaint)'s development headers separately before MyPaint will build. To make things simpler, our [MyPaint-testing PPA](https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing) has a `libmypaint-dev` package available if you're on Ubuntu. Other [packages of libmypaint](https://github.com/mypaint/libmypaint/wiki/Packaging) are available.
- _Fork_ the [main MyPaint repository](https://github.com/mypaint/mypaint) into _your personal area_ on Github. This is a copy that you work on, with full control over.
- _Clone_ your forked MyPaint repository to your computer
  - `git clone git@github.com:YOURNAME/mypaint.git`
- _Branch_ your clone, just for this job
  - `git checkout -b issue702-add-descriptions-to-popup-brush-sel`
- Edit `gui/quickchoice.py`, and fix up the construction of the PixbufList which the QuickBrushChooser uses.
  - PixbufList is an old module, and uses some fairly odd conventions for setup :fish: :nose:
    - Nevertheless, that's what we're dealing with here :speak_no_evil: 
  - The construction in `quickchoice.py` needs an extra function. Take a look at the way `gui/brushselectionwindow.py` does it (hint: it's a supercall over in that module).
    - If you are adding a fancier `namefunc`, you must also get `idfunc` to return the simple identifier for the pixbuf list region.
    - It's probably better to use module-global functions like `_managedbrush_namefunc()` than local lambda definitions.
    - See if `quickchoice.py` actually just use the same functions as `brushselectionwindow.py`? Hint: the leading underscore should be removed, because that denotes a function or method that shouldn't be called from outside ts module or class.
- Test MyPaint can still run from within your clone.
- _Add_ your changes (use `git add gui/quickchoice.py` for this, and don't forget to add any changes to other files.)
- _Commit_ what you added with `git commit`. [Here's how to write the commit message](https://github.com/mypaint/mypaint/wiki/Contributing-Patches#commit-messages).
- _Push_ your branch back to your area in Github
  - This publishes your changes so we can see them.
- Send a _Pull Request_ to us, from your branch to our `master` branch
  - You can refer to this issue in the PR's description or its comments as `mypaint/mypaint#702`.
  - That's it! We may ask you to revisit the branch and revise it, but if it's a clean set of changes we won't need to and you'll be done as soon as we merge your code.
  - Celebrate! You just made your first pull request :tada: 

You can ask us to help at any stage. We all remember having to learn this stuff too. Saying "I don't know" or "I don't understand" is a _positive_ thing here! :bouquet: 

There are some really detailed video guides to this process on <http://makeapullrequest.com/>, and MyPaint has a growing text-based [Contributing guide](https://github.com/mypaint/mypaint/wiki/Contributing) in English on its wiki.

**Comment by bluss** [comment] 2016-06-08 13:47
Thanks for the pointers.

**Comment by achadwick** [comment] 2016-06-08 13:57
**Clamed** by @bluss. PR already in the pipeline: see mypaint/mypaint#703 :smiley:

**Closed** 2016-06-26 18:43 UTC
Labels: bitesize, enhancement, ux
