### ISSUE TITLE
Painting tools: no square and rectangles tool?

### ISSUE THREAD

**Issue by duritia** [mypaint/mypaint#1187] opened 2022-08-06 13:48 UTC
#### Description of the problem

There is a tool for making circles and ellipses, but no tool to make perfect squares and rectangles. This is something basic that I expected to find.

#### Basic system details

MyPaint version: 2.0.1+gitexport.478280f
Operating system: Debian 11
Desktop environment: Mate Desktop

#### Steps to reproduce

1. Start MyPaint
2. Observe that in the painting tools part of the toolbar, there are tools for drawing lines, curves, connected lines or curves, circles and ellipses, but no square and rectangles:

![image](https://user-images.githubusercontent.com/69221194/183251672-8ae424fb-3d39-4147-b8e9-cf03e1cd5094.png)

**Comment by AesaraB** [comment] 2024-01-17 06:49
Duplicate of #31

**Closed by AesaraB** 2024-01-17 06:49 UTC
Labels: solution.Duplicate, type.Enhancement, cat.Tools
