### ISSUE TITLE
Error while switching recent colors quickly

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#168] opened 2015-01-10 07:06 UTC
When switching recent colors quickly (like double click) "A programming error has been detected." message box is displayed.

```
Mypaint version: 1.1.1-alpha
System information: Linux-3.13.0-41-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/document.py", line 543, button_press_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7f69ab57a690 (TiledDrawWidget at 0x2f706b0)>, event=<void>)
                    return self._dispatch_named_action(None, tdw, event,
                                                       action_name)
            # User-configurable forbidding of particular devices
  variables: {'action_name': ('local', u'ColorHistoryPopup')}
  File "/usr/local/share/mypaint/gui/document.py", line 683, _dispatch_named_action(self=<gui.document.Document object>, win=None, tdw=<TiledDrawWidget object at 0x7f69ab57a690 (TiledDrawWidget at 0x2f706b0)>, event=<void>, action_name=u'ColorHistoryPopup')
                    # Pointer: popup states handle these themselves sanely.
                    handler.activate(event)
                    return True
  variables: {'handler.activate': ('local', <bound method State.activate of <gui.stategroup.State object at 0x7f69a141dc50>>), 'event': ('local', <void at 0x45768a0>)}
  File "/usr/local/share/mypaint/gui/stategroup.py", line 150, activate(self=<gui.stategroup.State object>, action_or_event=<void>)
                    # currently, we only support mouse buttons being pressed here
                    assert e.type == gdk.BUTTON_PRESS
                    # let's just note down what mous button that was
  variables: {'gdk.BUTTON_PRESS': ('global', 4), 'e.type': ('local', <enum GDK_2BUTTON_PRESS of type GdkEventType>)}
AssertionError: 
```

screenshot: https://drive.google.com/file/d/0BwvdX1pBENi1SmF0RkE2MHhXSWM/view

**Comment by 0ion9** [comment] 2015-01-10 07:28
Yeah, this happens for me too (latest git, Arch Linux x86_64, evdev-supported tablet)

**Comment by loentar** [comment] 2015-01-10 07:39
Also I see unexpected behavoir while switching recent colors:

When I select one color (first), draw, then select other color (second) from history, draw shortly - just an stroke, and then try to select previous (first) color, but recent I get another (third color) from history!

screencast: https://drive.google.com/file/d/0BwvdX1pBENi1Zm1URGd5aGpyNFU/view

**Comment by achadwick** [comment] 2015-01-10 16:19
@loentar The first issue may be a duplicate of #86. Do you have the history popup bound to a pointer button?

The [second thing](https://github.com/mypaint/mypaint/issues/168#issuecomment-69447408) should probably be reported in its own issue. Please keep issues separate unless you have evidence that they are related. Also, if you report it elsewhere, please search first because I think we had some complaints about the colour history feature recently.

Regarding the first issue: please give me *exact* instructions about how to reproduce this starting from a fresh configuration, i.e. running as `./mypaint -c /tmp/testcfg$$` in a new Terminal window. Include anything you have to do to get your buttons set up in the way needed to reproduce this bug.

**Comment by iirelu** [comment] 2015-01-10 16:22
The functionality of the recent colours popup is, frankly, a [complete and utter mess](https://github.com/mypaint/mypaint/issues/93). I very much want to rewrite it eventually.

**Comment by achadwick** [comment] 2015-01-10 16:25
Oh yes. #93 would be the issue.

@loentar I think this is a double-duplicate. Can you confirm?

**Comment by loentar** [comment] 2015-01-10 18:26
Yes, possibly you're right. I searched it but not found.

**Closed** 2015-01-10 20:28 UTC
Labels: duplicate
