### ISSUE TITLE
MyPaint not Detecting Mac OSX App File Assosiations outside of MacPorts 

### ISSUE THREAD

**Issue by cyborgcassowary** [mypaint/mypaint#598] opened 2016-02-12 02:05 UTC
This is my favorite feature with MyPaint 1.2. However, no external applications are loading when I try to edit the vector layer from an external app. Currently running MyPaint from Yosemite OS. 
![screen shot 2016-02-11 at 9 03 54 pm](https://cloud.githubusercontent.com/assets/1065658/12996997/25f5d9cc-d103-11e5-9a36-f9ab7e0a7437.png)

**Comment by odysseywestra** [comment] 2016-02-12 02:27
What applications do you have installed that can handle SVG files?

**Comment by cyborgcassowary** [comment] 2016-02-12 02:28
Sublime Text and Inkscape.

**Comment by odysseywestra** [comment] 2016-02-12 05:54
And I'm guessing you installed it from the installer provided by Inkscape website?  If that is the case It look like MyPaint having trouble detecting Mac OSX's app's file associations.  Could you install inkscape via MacPorts and see if the problem still persists?

Also which version specific version you are using? You can find out by going to Help -> About MyPaint.

**Comment by odysseywestra** [comment] 2016-02-12 05:59
Also are you able to use `Edit with External Application` when you right-click on a standard layer? Just want to make sure if it is affected as well since they both use the similar code except for opening `PNG` images instead of `SVG` images.

**Comment by cyborgcassowary** [comment] 2016-02-12 06:56
Version 1.2.0+gitexport.f62444e. Installing Inkscape via Macports made MyPaint recognize Inkscape. However, when I create a vector and save it, it doesn't update in MyPaint. Edit with External Application with a standard layer doesn't work at the moment. Would installing Gimp via Macports solve this problem?
![screen shot 2016-02-12 at 1 54 18 am](https://cloud.githubusercontent.com/assets/1065658/13000718/b840357a-d12b-11e5-8a57-60be9191126f.png)

**Comment by cyborgcassowary** [comment] 2016-02-12 07:01
Okay, I figured it out. In order to update the vector layer in MyPaint, I have to right click vector layer and click "Update Layer with External Edits"
![screen shot 2016-02-12 at 1 59 05 am](https://cloud.githubusercontent.com/assets/1065658/13000753/69bb4d30-d12c-11e5-9d8c-f2d0e7171c5f.png)

**Comment by odysseywestra** [comment] 2016-02-12 07:02
Okay cool I was just going to ask you that. However I am going to keep this issue open and rename it since MyPaint isn't detecting Mac OSX app file association preferences. So congrats you found a bug!

**Comment by achadwick** [comment] 2016-02-12 10:36
(All together now: “works fine in _♪myyy~~_ testing environment!”)

Okay, file monitoring is broken on Yosemite, but I expected we'd encounter something like that. "Update layer with External Edits" is the workaround ☺

Being unable to get the list of associations happens on Windows too. Sometimes with crashes (#531). On Linux, users would like more flexibility, so my current plan for these commands is something like <https://github.com/mypaint/mypaint/issues/477#issuecomment-176536138>. That should hopefully build in more flexibility for you guys too.

**Comment by achadwick** [comment] 2016-02-12 10:41
It's GLib's Gio component that's at fault here in both cases, and that sometimes logs when code hasn't been written for a particular backend IIRC. I'm adding the upstream tag because I don't think we're doing anything wrong here in MyPaint, but there's more we can do. See the notes in the linked comment above. Somebody Mac-smart could even add an OS file associations tab if we do it right.

@cyborgcassowary 
Please could you run your Yosemite build again, and tell us any interesting terminal/log messages from Gio when you try to open your first layer in an external app? You may need to turn on debugging messages by running MyPaint as

    $ MYPAINT_DEBUG=1 mypaint -c /tmp/throwaway-cfg-1

There will be a lot of clutter in your terminal from MyPaint itself, but it should be easy to distinguish messages from other sources. Ours are (hopefully) colour coded ☺

**Comment by cyborgcassowary** [comment] 2016-02-13 04:15
@achadwick 
Here's what I receive when trying to edit the first layer in another MyPaint window.
[externalapp_debug_1_mypaint.txt](https://github.com/mypaint/mypaint/files/128974/externalapp_debug_1_mypaint.txt)

I also have the terminal / log messages when I make edits in Inkscape. 
[externalapp_debug_2_mypaint_inkscape.txt](https://github.com/mypaint/mypaint/files/128975/externalapp_debug_2_mypaint_inkscape.txt)

I hope this helps.

**Comment by achadwick** [comment] 2017-01-23 17:58
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has been released. Please can you try it out and see if this bug is still happening? Please report your GLib version when you do.

IMO the GLib issue is really an upstream bug should be reported via the GNOME bugzilla against the glib component if it's still happening.

There is more we can do within the MyPaint codebase, but let's consider that in #477 instead of here - it's a feature request, not a bug. Closing.

**Closed by achadwick** 2017-01-23 17:58 UTC
Labels: needs-info, osx, upstream
