### ISSUE TITLE
Graceful fallback and alternative controllers for lacking inputs (tilt, etc)

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#861] opened 2017-09-13 21:12 UTC
Currently we have a fallback for devices that are missing pressure input; a mouse click will register 50% "pressure" as far as I recall.  I think we need to extend this idea quite a bit if we ever want to ship more complicated brushes that anyone can use in "functional" way.   By "functional" I mean the most useful state that someone could use without dynamic control.  Ideally it will at least make some kind of mark on the canvas :-)

*  Allow per-brush "fallback" setting for any potential lacking input.  For instance, the fallback "pressure" for one brush might be 100%.  For another brush, it might be 25%.  Likewise, fall-back "tilt", ascension, (someday, barrel-rotation) might all have various values on a per-brush case in order to have a "functional brush" in all scenarios.

* Implement some alternative keyboard controllers (possibly sliders too, but IMO keyboard inputs are more useful) for these inputs.  This would allow you to deviate from the fallback easily.  For instance, if the fallback "ascension" (which requires tilt) was designed for right-handed person, you could switch it to a left-handed angle pretty quickly.  Or, if a fall-back "tilt" was 45 degrees, you could adjust it to 90 degrees on-the-fly. 

With some practice I think even a user with just a mouse and keyboard could create some pretty dynamic effects in their artwork.  This could exponentially expand the audience for MyPaint.

One challenge is detecting whether or not a device is lacking an input to begin with.  My regular Wacom stylus reports a constant barrel rotation of "900" despite it lacking that feature.  Worst-case, maybe we could store a preference for each stylus with checkboxes for whether each input is ignored or not.

**Comment by sjcalamia** [comment] 2017-12-01 13:25
This feels like the right place to leave this comment... If not, I can create a new issue.

Regarding alternative input devices and types, my Surface Pro 4 uses a wintab driver, which happens to have a nice Python wrapper 
http://cgkit.sourceforge.net/doc2/wintab.html

This might change the way that input is polled in the application, however, but I would say is a necessary improvement as even Wacom is moving away from their driver technology and moving towards wintab type devices.
http://www.wacomeng.com/windows/docs/wintabbackground.htm

I have a Linux Subsystem for Windows installed on my machine, however the Linux subsystem does not allow graphical output. I'm experimenting with the code to see if I can compile natively without MSYS2. Because of this and wintab, this may warrant a fork. I'm still unsure.

**Comment by achadwick** [comment] 2018-01-02 10:29
@sjcalamia 
This is not a good place to discuss that.

Wintab's a horrid old 16-bit API that just happens to be an industry standard, and the thing that libgtk uses. MyPaint is built on top of GTK, so we are already receiving Wintab events if that is your goal.

Wacom have historically had pretty reliable and fast WINTAB DLLs with event delivery in the ~200Hz range. Other manufacturers' implementations very wildly, and it's still a finicky API that GTK has had a lot of regressions against in the past.

Note that you can only have one Wintab DLL on your system at once. It's a terrible interface, by modern standards.

The newer Windows APIs that look promising are the *Windows Tablet PC API*, and *Windows Ink*. The former will have more support, and if possible, GTK should be made to support it, not MyPaint. If you have the time, you could work on it with the GTK devs: they're quite friendly, I've met one or two, and they tend to hang out on IRC a lot. IRC is often the best way to nag them about getting patches into the development master 👉 https://www.gtk.org/development.php

**Closed** 2019-07-14 03:22 UTC
Labels: enhancement
