### ISSUE TITLE
When merging visible layers MyPaint crashes.

### ISSUE THREAD

**Issue by Ico-dY** [mypaint/mypaint#230] opened 2015-03-03 12:50 UTC
When merging visible layers MyPaint crashes.

Create two layers and draw something.
On the layers, right click -> merge visible.

```
Mypaint version: 1.1.1-alpha.20150303+git.5872b1a
System information: Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/document.py", line 1158, merge_visible_layers_cb(self=<gui.document.Document object>, action=<Action object at 0x7f4fe64a15a0 (GtkAction at 0x34f9790)>)
            """Merge Visible: merge all visible layers into new one"""
            self.model.merge_visible_layers()
            self.layerblink_state.activate(action)
  variables: {'self.model.merge_visible_layers': ('local', <bound method Document.merge_visible_layers of <Document nlayers=3 bbox=Rect(-960, -64, 5312, 3584) paintonly=False>>)}
  File "/usr/local/share/mypaint/lib/document.py", line 626, merge_visible_layers(self=<Document nlayers=3 bbox=Rect(-960, -64, 5312, 3584) paintonly=False>)
        def merge_visible_layers(self):
            self.do(command.MergeVisibleLayers(self))
  variables: {'self.do': ('local', <bound method Document.do of <Document nlayers=3 bbox=Rect(-960, -64, 5312, 3584) paintonly=False>>), 'self': ('local', <Document nlayers=3 bbox=Rect(-960, -64, 5312, 3584) paintonly=False>), 'command.MergeVisibleLayers': ('global', <class 'lib.command.MergeVisibleLayers'>)}
  File "/usr/local/share/mypaint/lib/document.py", line 512, do(self=<Document nlayers=3 bbox=Rect(-960, -64, 5312, 3584) paintonly=False>, cmd=<Merge Visible Layers>)
            self.sync_pending_changes()
            self.command_stack.do(cmd)
  variables: {'cmd': ('local', <Merge Visible Layers>), 'self.command_stack.do': ('local', <bound method CommandStack.do of <CommandStack undo_len=11 redo_len=0>>)}
  File "/usr/local/share/mypaint/lib/command.py", line 65, do(self=<CommandStack undo_len=11 redo_len=0>, command=<Merge Visible Layers>)
            self._discard_redo()
            command.redo()
            self.undo_stack.append(command)
  variables: {'command.redo': ('local', <bound method MergeVisibleLayers.redo of <Merge Visible Layers>>)}
  File "/usr/local/share/mypaint/lib/command.py", line 602, redo(self=<Merge Visible Layers>)
                    self._paths_merged.append(path)
                merged = rootstack.layer_new_merge_visible()
                self._merged_layer = merged
  variables: {'rootstack.layer_new_merge_visible': ('local', <bound method RootLayerStack.layer_new_merge_visible of <RootLayerStack len=3>>), 'merged': ('local', None)}
  File "/usr/local/share/mypaint/lib/layer/group.py", line 2181, layer_new_merge_visible(self=<RootLayerStack len=3>)
                tiles.update(layer.get_tile_coords())
                if isinstance(layer, PaintingLayer) and not layer.locked:
                    strokes[:0] = layer.strokes
  variables: {'layer.locked': ('local', False), 'layer': ('local', <PaintingLayer u'Layer 2'>), 'isinstance': ('builtin', <built-in function isinstance>), 'PaintingLayer': (None, [])}
NameError: global name 'PaintingLayer' is not defined
```

**Comment by Ico-dY** [comment] 2015-03-03 12:56
The same thing happens with "merge down":

Mypaint version: 1.1.1-alpha.20150303+git.5872b1a
System information: Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/document.py", line 1153, merge_layer_down_cb(self=<gui.document.Document object>, action=<Action object at 0x7f2829dc6230 (GtkAction at 0x1990f00)>)
            """Merge Down: merge current layer with the one below it"""
            if self.model.merge_current_layer_down():
                self.layerblink_state.activate(action)
  variables: {'self.model.merge_current_layer_down': ('local', <bound method Document.merge_current_layer_down of <Document nlayers=2 bbox=Rect(192, 960, 3264, 1728) paintonly=False>>)}
  File "/usr/local/share/mypaint/lib/document.py", line 622, merge_current_layer_down(self=<Document nlayers=2 bbox=Rect(192, 960, 3264, 1728) paintonly=False>)
                return False
            self.do(command.MergeLayerDown(self))
            return True
  variables: {'self.do': ('local', <bound method Document.do of <Document nlayers=2 bbox=Rect(192, 960, 3264, 1728) paintonly=False>>), 'command.MergeLayerDown': ('global', <class 'lib.command.MergeLayerDown'>), 'self': ('local', <Document nlayers=2 bbox=Rect(192, 960, 3264, 1728) paintonly=False>)}
  File "/usr/local/share/mypaint/lib/document.py", line 512, do(self=<Document nlayers=2 bbox=Rect(192, 960, 3264, 1728) paintonly=False>, cmd=<Merge Down>)
            self.sync_pending_changes()
            self.command_stack.do(cmd)
  variables: {'cmd': ('local', <Merge Down>), 'self.command_stack.do': ('local', <bound method CommandStack.do of <CommandStack undo_len=2 redo_len=0>>)}
  File "/usr/local/share/mypaint/lib/command.py", line 65, do(self=<CommandStack undo_len=2 redo_len=0>, command=<Merge Down>)
            self._discard_redo()
            command.redo()
            self.undo_stack.append(command)
  variables: {'command.redo': ('local', <bound method MergeLayerDown.redo of <Merge Down>>)}
  File "/usr/local/share/mypaint/lib/command.py", line 633, redo(self=<Merge Down>)
            if merged is None:
                merged = rootstack.layer_new_merge_down(self._upper_path)
                assert merged is not None
  variables: {'rootstack.layer_new_merge_down': ('local', <bound method RootLayerStack.layer_new_merge_down of <RootLayerStack len=2>>), 'self._upper_path': ('local', (0,)), 'merged': ('local', None)}
  File "/usr/local/share/mypaint/lib/layer/group.py", line 2131, layer_new_merge_down(self=<RootLayerStack len=2>, path=(0,))
                assert p is not None
                layer = self.layer_new_normalized(p)
                merge_layers.append(layer)
  variables: {'p': ('local', (1,)), 'layer': (None, []), 'self.layer_new_normalized': ('local', <bound method RootLayerStack.layer_new_normalized of <RootLayerStack len=2>>)}
  File "/usr/local/share/mypaint/lib/layer/group.py", line 2041, layer_new_normalized(self=<RootLayerStack len=2>, path=(1,))
                # Optimizations for the tiled-surface types
                if isinstance(srclayer, PaintingLayer):
                    return deepcopy(srclayer)  # include strokes
  variables: {'srclayer': ('local', <PaintingLayer u'Layer'>), 'isinstance': ('builtin', <built-in function isinstance>), 'PaintingLayer': (None, [])}
NameError: global name 'PaintingLayer' is not defined

**Comment by achadwick** [comment] 2015-03-03 13:02
On it!

(Thanks for the testing, it's awesome! For now though, could you be sure to enclose your traces in 3-backtick fences for github?

    ```
    backtrace goes here
    ```

it makes them much easier to read!)

**Comment by Ico-dY** [comment] 2015-03-03 13:05
Done! ^^

**Comment by Ico-dY** [comment] 2015-03-03 13:13
MyPaint crashes with the "normalize layer mode" too:

...
Mypaint version: 1.1.1-alpha.20150303+git.5872b1a
System information: Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/document.py", line 975, normalize_layer_mode_cb(self=<gui.document.Document object>, action=<Action object at 0x7f712dc310a0 (GtkAction at 0x1dbf930)>)
            """``NormalizeLayerMode`` GtkAction callback"""
            self.model.normalize_layer_mode()
  variables: {'self.model.normalize_layer_mode': ('local', <bound method Document.normalize_layer_mode of <Document nlayers=1 bbox=Rect(0, 64, 4800, 3264) paintonly=False>>)}
  File "/usr/local/share/mypaint/lib/document.py", line 610, normalize_layer_mode(self=<Document nlayers=1 bbox=Rect(0, 64, 4800, 3264) paintonly=False>)
            layers = self.layer_stack
            self.do(command.NormalizeLayerMode(self, layers.current))
  variables: {'self.do': ('local', <bound method Document.do of <Document nlayers=1 bbox=Rect(0, 64, 4800, 3264) paintonly=False>>), 'command.NormalizeLayerMode': ('global', <class 'lib.command.NormalizeLayerMode'>), 'self': ('local', <Document nlayers=1 bbox=Rect(0, 64, 4800, 3264) paintonly=False>), 'layers.current': ('local', <PaintingLayer u'Layer'>)}
  File "/usr/local/share/mypaint/lib/document.py", line 512, do(self=<Document nlayers=1 bbox=Rect(0, 64, 4800, 3264) paintonly=False>, cmd=<Normalize Layer Mode>)
            self.sync_pending_changes()
            self.command_stack.do(cmd)
  variables: {'cmd': ('local', <Normalize Layer Mode>), 'self.command_stack.do': ('local', <bound method CommandStack.do of <CommandStack undo_len=21 redo_len=0>>)}
  File "/usr/local/share/mypaint/lib/command.py", line 65, do(self=<CommandStack undo_len=21 redo_len=0>, command=<Normalize Layer Mode>)
            self._discard_redo()
            command.redo()
            self.undo_stack.append(command)
  variables: {'command.redo': ('local', <bound method NormalizeLayerMode.redo of <Normalize Layer Mode>>)}
  File "/usr/local/share/mypaint/lib/command.py", line 683, redo(self=<Normalize Layer Mode>)
            self._old_layer = parent[idx]
            normalized = layers.layer_new_normalized(self._path)
            parent[idx] = normalized
  variables: {'self._path': ('local', (0,)), 'normalized': (None, []), 'layers.layer_new_normalized': ('local', <bound method RootLayerStack.layer_new_normalized of <RootLayerStack len=1>>)}
  File "/usr/local/share/mypaint/lib/layer/group.py", line 2054, layer_new_normalized(self=<RootLayerStack len=1>, path=(0,))
            # Begin building output, and enumerate set of tiles to render
            dstlayer = PaintingLayer()
            dstlayer.name = srclayer.name
  variables: {'dstlayer': (None, []), 'PaintingLayer': (None, [])}
NameError: global name 'PaintingLayer' is not defined
...

**Comment by achadwick** [comment] 2015-03-03 13:14
Thanks for the reformatting! We should put them in the dialog's backtraces I guess: we put version info there courtesy of @odysseywestra to make pasted dumps more informative; might as well have them formatted properly.

**Comment by achadwick** [comment] 2015-03-03 13:40
Should be fixed in 02c6648b8602941ada08ecb338fdbb1a725fedba. Can you retest via the UI please, and let me know if there are any similar messages when you play with the layers panel?

**Comment by Ico-dY** [comment] 2015-03-03 13:58
Retested. It's all right now but could I ask a question?
When clicking on "merge visible" MyPaint makes a new layer from the content of source layers without deleting them. Is it the normal behavior? Usually other software delete the source layers after merging.

**Comment by americogobbo** [comment] 2015-03-03 14:08
Perhaps is useful to adopt the gimp voice: New from visible.


J. Americo Gobbo [Illustrator and Painter]
Website <http://americogobbo.com.br> | Blog
<http://americogobbo.blogspot.com> | Flickr <http://flickr.com/rabisco> |
Pinterest <http://www.pinterest.com/americogobbo/> | Twitter
<http://twitter.com/rabisco> | Facebook
<http://www.facebook.com/americogobbo>

**Comment by Ico-dY** [comment] 2015-03-03 14:16
Both are very useful for painters workflow: "new from visible", whitout source layers deleting, and "merge visible layers", with source layers deleting.

**Comment by achadwick** [comment] 2015-03-03 14:22
@Ico-dY yeah, that's the current behaviour in MyPaint. Looks like having a "Merge and Delete Visible" command was suggested in the code:
https://github.com/mypaint/mypaint/blob/02c6648b8602941ada08ecb338fdbb1a725fedba/lib/command.py#L580
but I guess it never got implemented.

@americogobbo, @Ico-dY Could you guys perhaps get together and write up what you need here as a new issue? It's beyond the scope of this one, and will get lost if the discussion happens in this thread. Thanks!

**Comment by achadwick** [comment] 2015-03-03 14:23
All done here. Apologies for the regression; I've taken steps to make sure it won't happen again :D

**Closed by achadwick** 2015-03-03 14:23 UTC
Labels: bug
