### ISSUE TITLE
MyPaint 1.2.1 crashes as soon as I use my tablet

### ISSUE THREAD

**Issue by darkhog** [mypaint/mypaint#946] opened 2018-09-22 17:58 UTC
#### Description of the problem

MyPaint crashes as soon as I use my tablet (Huion Inspiroy H950). Can draw fine with mouse. It doesn't happen with other drawing programs such as Krita.

#### Basic system details

MyPaint version: 1.2.1 (newest release)
Operating system: Win10 build 1803
Desktop environment: n/a

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. Try using the tablet
3. The window's kaput.

#### Backtraces or error messages
```
Running gdb.exe...
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
c:\program files\mypaint-w64\mingw64\bin\../etc/gdbinit:5: Error in sourced command file:
Error while executing Python code.
Reading symbols from python2.exe...(no debugging symbols found)...done.
Starting program: C:\program files\mypaint-w64\mingw64\bin\python2.exe mingw64/bin/mypaint
[New Thread 4480.0x2354]
[New Thread 4480.0x2a60]
[New Thread 4480.0x2b88]
[New Thread 4480.0x11c]
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'C:/Program Files/mypaint-w64/mingw64'
INFO: lib.i18n: Windows: LANG='pl_PL'
INFO: lib.i18n: Windows: LANGUAGE='pl_PL'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
[New Thread 4480.0x518]
[New Thread 4480.0x1fec]
[New Thread 4480.0x2970]
[New Thread 4480.0x2958]
[New Thread 4480.0x1520]
WARNING: gui.workspace: win32: floating windows are not supported (bug #679), not enabling subwindow creation by snapping out.
WARNING: gui.workspace: win32: floating windows are not supported (bug #679), not enabling subwindow creation by snapping out.
INFO: gui.device: New device 'System Aggregated Pointer' (GDK_SOURCE_MOUSE, axes:2, class=GdkDeviceWin32, vendor=None, product=None)
INFO: gui.document: Initialized background from u'C:/Program Files/mypaint-w64/mingw64/share/mypaint/backgrounds/10_soft_yellow.png'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendModeMenu'

(python2.exe:4480): Gtk-[1;33mWARNING[0m **: Theme parsing error: <data>:5:50: The style property GtkMenuBar:internal-padding is deprecated and shouldn't be used anymore. It will be removed in a future version
C:/program files/mypaint-w64/mingw64/lib/python2.7/site-packages/pygtkcompat/pygtkcompat.py:180: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  rect = Gdk.Rectangle(0, 0, 0, 0)
WARNING: gui.accelmap: Not listing '<Actions>/DocumentActions/RotateLeft' (no tooltip, fix before release!)
WARNING: gui.accelmap: Not listing '<Actions>/DocumentActions/RotateRight' (no tooltip, fix before release!)
INFO: gui.device: New device 'HUION Tablet Pressure Stylus' (GDK_SOURCE_PEN, axes:5, class=GdkDeviceWintab, vendor=None, product=None)

(python2.exe:4480): Gdk-[1;35mCRITICAL[0m **: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000070ee1e34 in ?? () from C:\program files\mypaint-w64\mingw64\bin\libgdk-3-0.dll
(gdb)
```

**Comment by hungryowlet** [comment] 2018-11-04 21:52
I've got the same problem. Used MyPaint 1.0 until now without problems - but after upgrading to 1.2.1 it immediately crashes as soon as my pen touches the surface. I use a Huion 1060P, Win 10 Home 64 Bit.

**Comment by briend** [comment] 2018-11-04 22:15
I would start with an alpha build:
https://ci.appveyor.com/project/achadwick/mypaint/history
Just find the first one that is "green" indicating the build was a success.

**Comment by hungryowlet** [comment] 2018-11-05 07:38
...where are the download links? All I can see are logs.

**Comment by briend** [comment] 2018-11-05 13:16
It's a bit buried.  You need to click on an environment, 64 bit probably.
 Then artifacts tab, then the installer:

https://ci.appveyor.com/api/buildjobs/6xnsrxo6ngrlidc4/artifacts/out%2Fbundles%2Fmypaint-git-w64-1.3.0-alpha-master.413-installer.exe

**Comment by hungryowlet** [comment] 2018-11-05 16:38
Thank you! Trying it and hoping for the best.

**Comment by hungryowlet** [comment] 2018-11-05 16:47
Tried it and the exact same thing happens. Poke canvas with tablet pen, program immediately shuts down. When I try again I can't use the tablet at all once MyPaint is open, mouse is fine, though. 1.0 still works without problems.

**Comment by obnblbn** [comment] 2018-12-10 19:57
I have the exact same problem with a pen tablet Huion H430P. As soon as the pen touches the tablet, MyPaint crashed immediately. This is true for version 1.2.1 and the newest alpha build version 1.3.0. Version 1.0.0 works fine with pen pressure and without any crash. The problem can be reproduced under Windows 8.1 (32-bit) and Window 10 (64-bit).

**Comment by briend** [comment] 2018-12-11 16:58
Please verify you are using a new alpha build.  When you do Help-->About it should look like this, showing GDK 3.24.1:
![image](https://user-images.githubusercontent.com/6015639/49816394-fb37ec00-fd2a-11e8-9d35-65520022eb62.png)
download here:
https://ci.appveyor.com/project/achadwick/mypaint

The particular bug you're having seems like it might be fixing in GDK 3.21.1

**Comment by darkhog** [comment] 2018-12-11 17:37
Doesn't work for me and mypaint-debug.exe returns the following:

`Running python2.exe...
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'E:/profile/Darkhog/mojeprogramy/mypain/mingw64'
CRITICAL: mypaint: Default brush collection not found!
CRITICAL: mypaint: It should have been here: u'C:/msys64/mingw64/share/mypaint-data/2.0/brushes'
python2.exe exited with status 1.`

**Comment by briend** [comment] 2018-12-11 18:44
@darkhog that's a new issue because I rolled out the new brush dependency too soon.  I'm hoping to fix that soon very soon.  In the meantime can you look for lib\config.py and edit it, change C: to E: and try again?

**Comment by obnblbn** [comment] 2018-12-12 17:17
I downloaded and installed version 2.0.0 alpha w64 and it did not start. Running mypaint-debug.exe showed the same error that darkhog reported. I found the file config.py here:
C:\Program Files\mypaint-git-w64\mingw64\lib\mypaint\lib\config.py

I was able to start mypaint 2.0.0-alpha after changing the line from
mypaint_brushdir = u'E:/msys64/mingw64/share/mypaint-data/2.0/brushes'
to
mypaint_brushdir = u'C:/Program Files/mypaint-git-w64/mingw64/share/mypaint-data/2.0/brushes'

Unfortunately version 2,0.0-alpha did not fix the problem. As soon as the pen touches the Huion H430P, the mypaint windows disappears (program crash). Under devices I don't see the tablet, only the mouse.

Mypaint version 1.0.0 works perfectly with the tablet, all others (tried 1.2.1, 1.3.0 and 2.0.0) don't.

**Comment by briend** [comment] 2018-12-12 17:42
Can you try the gtk3-demo-event-axes.exe  in the mypaint folder?  That should be a good test if it is a GTK bug

**Comment by darkhog** [comment] 2018-12-12 18:00
Seems to be the case.

```
(gtk3-demo.exe:11240): Gdk-CRITICAL **: 18:58:18.390: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
--: line 1: 19692 Segmentation fault      "$@"
gtk3-demo exited with status 139.
Press return to close this window.
```

Again, after I've touched the area. Perhaps you can roll back to the version used by 1.0 as it seems to ot suffer from this issue?

**Comment by obnblbn** [comment] 2018-12-12 18:44
Same with me:
Touching the tablet with the pen crashes both, gtk3-demo-event-axes.exe and gtk-widget-factory.exe.

**Comment by obnblbn** [comment] 2018-12-12 18:49
I can also confirm, that I cannot move the mouse cursor with the pen, as long as these programs are running.
Additionally, the programs crash only occurs if the mouse cursor is somewhere over the program window. Otherwise the program windows stay open.

**Comment by briend** [comment] 2018-12-13 04:37
Please try updating the drivers:
https://www.huiontablet.com/support/
and go into the driver settings and experiment turning on or off the Windows Ink setting and the WinTab setting.  

We can't go back to older GTK versions, unfortunately.  I'm thinking this is a bug in the newer GTK versions.  Please try to download GTK as shown here:
https://www.gtk.org/download/windows.php
you can just do step 1 and 2, and then launch the MSYS2 terminal and run gtk3-demo and choose the Table and Drawing demo and click Run.  If it crashes your next step is probably to submit a bug report to GTK.

**Comment by obnblbn** [comment] 2018-12-13 20:36
I already have the latest driver installed. In the driver settings I tried all possible pen setting combinations.

I downloaded the latest GTK version (steps 1+2), started gtk3-demo, selected "Touch and Drawing Tablets" and clicked Run. I placed the mouse cursor somewhere over the program window. As soon as the pen touches the Huion H430P tablet, the program is crashing.

So you are right, it seems to be a bug in the newer GTK versions. I will report the bug to GTK.

Thanks a lot!

**Comment by briend** [comment] 2018-12-13 20:48
No problem!  Thanks for reporting that, and try to include as much logging
detail as possible!  I think GIMP is migrating to gtk3.0 so hopefully that
puts some pressure on getting these things resolved

**Comment by obnblbn** [comment] 2018-12-13 21:36
GIMP 2.10.8 works fine with the Huion tablet. Don't know which GTK version it's using.

**Comment by darkhog** [comment] 2018-12-14 00:05
I have the newest drivers. The issue persists.

**Comment by obnblbn** [comment] 2018-12-14 18:13
I opened an issue and reported the bug to GTK:
https://gitlab.gnome.org/GNOME/gtk/issues/1522

**Comment by alidan** [comment] 2019-02-04 08:12
Used most recent alpha for windows, issue still there with my huion tablet
Really want this program as its fits a few of my needs/wants.

**Comment by obnblbn** [comment] 2019-05-17 18:26
Good news! This problem disappeared with the newest driver version (Driver_14.7.139.536) for the Huion tablet H430P and the MyPaint version v2.0.0-alpha.11. 
According to the MyPaint release notes, "it seems the related GTK issues have been resolved." :-)

**Comment by jplloyd** [comment] 2019-06-21 12:50
@darkhog @hungryowlet @alidan 
Can you confirm that upgrading the drivers fixes the crash for your tablet models as well?

And thanks to @obnblbn for digging into this!

**Comment by hungryowlet** [comment] 2019-06-21 15:47
@jplloyd It did, thank you! I'm so happy I can finally use it to draw, and I'm completely blown away by how good it is. A big thank you to everyone who's working on it!

**Comment by jplloyd** [comment] 2019-06-21 21:40
Nice, I also noticed in the community forum that the first tablet mentioned here has been reported to work now. Closing this.

**Closed by jplloyd** 2019-06-21 21:40 UTC
