### ISSUE TITLE
Scrolling functionality regression in 189e195

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#328] opened 2015-05-28 18:08 UTC
[Commit in question](https://github.com/mypaint/mypaint/commit/189e1952cf30038adcd38a95562c531e5a83c0e3).

I understand the approach this commit attempted to take, but it did so poorly. It may improve the situation where smooth scrolling is possible but completely ruins things when all that's available is a regular scrollwheel.

Immediately obvious problems:
* Scrolling now scrolls in relative intervals instead of snapping to exact 100%, 150%, 200%, etc zoom levels. This hurts a lot for pixel art, where exact zoom scales are very much required.
* Unable to zoom in and out using the scrollwheel whilst the tablet pen is active.
* The commit suggests that shift+scrolling should bring back the old behaviour, but this is not the case. It's very buggy, and requires you to zoom twice in the same direction before it properly registers any scrolling.
* If you zoom in or out too far, you can't return to exact 1:1 scale. Another big problem, as any rescaling will "smear" artwork (very obvious for pixel art).
* Panning performance is *extremely* diminished whenever zoomed out at a non-regular scale, which with the old zooming wasn't a problem as it snapped to 50%, 25%, etc, but with this is *always* a problem.

Proposed solution: Only use smooth scrolling if a device capable of smoothly scrolling is detected, otherwise default to using the previously-standard scrolling.

(Sorry for reporting this so late after its commit, I haven't used Mypaint in a while)

**Comment by achadwick** [comment] 2015-05-29 01:04
Thanks so much for testing this!

> pixel art, where exact zoom scales are very much required.

Good use case reminder, thanks. Not the _primary_ use case, but we shouldn't forget it.

> * Unable to zoom in and out using the scrollwheel whilst the tablet pen is active.

Could you elaborate? What kind(s) of device(s) are you using simultaneously here? Which scroll wheel(s)?

> * The commit suggests that shift+scrolling should bring back the old behaviour, but this is not the case. It's very buggy, and requires you to zoom twice in the same direction before it properly registers any scrolling.

Hm. Not with my testing. However that might be geared fairly heavily towards touchpads given what's driving this.

I don't get the "need to scroll twice" thing with any device I've tested with.

> * Panning performance is extremely diminished whenever zoomed out at a non-regular scale, which with the old zooming wasn't a problem as it snapped to 50%, 25%, etc, but with this is always a problem.

IMX 50% panning always sucks (really anything between 100% and 25%, which is weird since some of that should be using the 50% mipmap) and picks up again at 25%. It doesn't matter much how you get there, either smooth or discrete.

I think this one should be looked as a separate performance issue, because it needs understanding in its own terms.

> Proposed solution: Only use smooth scrolling if a device capable of smoothly scrolling is detected, otherwise default to using the previously-standard scrolling.

This is surprisingly hard to do right: multiple devices, GdkDevice objects don't exactly tell you what their smooth scrolling capabilities are, and the events you get actually depend on the event mask you set on the receiving widget. IIRC, GDK or X synthesizes non-smooth events as needed if a device only sends smooth ones, but I need to test that.

I'm thinking a global prefs toggle may be better. Does removing SMOOTH_SCROLL_MASK in [tileddrawwidget.py#L100](https://github.com/mypaint/mypaint/blob/189e1952cf30038adcd38a95562c531e5a83c0e3/gui/tileddrawwidget.py#L100) just help your device(s) scrolling straight off, and give you back the behaviour you want? If so, we can just add a knob for that.

**Comment by achadwick** [comment] 2015-06-07 00:26
I think the panning performance issue will have been resolved by #329's fix.

@iirelu: I'll assume that just turning off the mask will restore expected behaviour, since that made scrolling stepwise in the old way for my touchpad here. Putting together a patch now. If it doesn't make scrolling acceptable, please report a separate new issue for each thing you see as a regression.

**Closed** 2015-06-07 00:30 UTC
Labels: bug

**Comment by iirelu** [comment] 2015-06-07 00:34
Sorry, I was going to try and implement something to help with this a while ago but I never got around to it.

**Comment by achadwick** [comment] 2015-06-07 00:40
NP. I just wanted to address this enough to turn it into a real beta task if it gets reopened (since a turn-it-off knob needs new strings, and I basically forgot that oops. They're in now.)

I figure turning off the smooth scrolling bit in the event mask should suffice to get behaviour back to something like one-before- 189e1952cf30038adcd38a95562c531e5a83c0e3, so I just went ahead.
