### ISSUE TITLE
Delayed strokes with xf86-input-libinput driver [upstream: it's gtk 3.18.9, problem fixed with newer GTK]

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#680] opened 2016-05-14 11:04 UTC
#### Description of the problem

Just switched from evdev xorg input driver to libinput driver, and noticed this:

When receiving events from libinput driver, the strokes are not processed until after a fixed delay.
This color-coded image should illustrate:
![stroke-delay-s](https://cloud.githubusercontent.com/assets/115782/15267961/823977f2-1a0f-11e6-8bdf-5eaae1205333.png)
Each individual color was written to the end before the start of it appeared on the screen (so, for example, I wrote all of the strokes of 'all' before the first stroke of the 'a' actually appeared on screen)

It may also illustrate that there may be some interaction with stroke splitting (the fact that S, W, B started rendering before the following letter was drawn)

This is in contrast with Krita and GIMP; they each respond immediately to tablet events.

#### Basic system details
MyPaint version: 1.3.0-alpha+git.b1325b6
Operating system: Arch Linux x86_64
Desktop environment: QTile git
GTK3: 3.18.9
Device: Monoprice 12" (lsusb says `UC-Logic Technology Corp. Tablet PF1209`)
libinput:  1.3.0
xorg:  1.18.3
xorg-input-libinput: 0.19.0
linux: 4.5.3

#### Steps to reproduce

0. Install libinput and xorg-input-libinput if not already installed.
1. Configure your tablet (or touchpad, etc..) to use libinput, by creating a rule file in /etc/X11/xorg.conf.d/ with contents like this :

```
Section "InputClass"
  Identifier    "input-"
 MatchProduct "Name of device, as provided by libinput-list-devices"
 # or alternatively a direct device name match, if you know what it is..
 # MatchDevicePath "/dev/input/event2"
  Driver "libinput"
EndSection
```
I cannot comment on exactly what is compatible with libinput, except that if it worked on evdev, wacom, or synaptics driver, it should probably work here.
3. Test in Krita or GIMP, verify that strokes render near instantly
4. Start MyPaint
5. Execute a quick series of strokes, for example a set of lines drawn towards a single point. Note the time delay between making a stroke and it being rendered.

#### Notes

* Might be (mostly) upstream GTK; unclear
* I cannot personally test on evdev; I migrated to libinput due to a currently unresolved issue with evdev tablet input not providing any pressure information.
* Another painting application that uses GTK3 would be good to know for comparison purposes (determining how much of this behaviour is Gtk3 and how much is Mypaint). I don't currently know of one (Krita uses its own code, GIMP uses Gtk2)
* [This page](https://wayland.freedesktop.org/libinput/doc/latest/tablet-support.html) may be relevant.

**Comment by achadwick** [comment] 2016-05-14 13:21
Thank you for the great start with this report!

Can you let me know what libinput version, kernel version, and XOrg version you are using please?

**Comment by achadwick** [comment] 2016-05-14 13:47
@0ion9 
What brush is that, and what zoom?

**Comment by achadwick** [comment] 2016-05-14 14:06
I cannot reproduce any lag with biggish normal brushes and a Huion H610 Pro. Debian testing/unstable, with

* `libgtk-3-0:amd64`                       3.20.4-1
* `xserver-xorg-input-libinput`            0.18.0-1
* `uname -a`: `Linux spatula 4.5.0-2-amd64 #1 SMP Debian 4.5.3-2 (2016-05-08) x86_64 GNU/Linux`

Here is what happens at setup, trimmed to tablet and stylus:

```log
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (II) config/udev: Adding input device HUION PenTablet Pen (/dev/input/event16)
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) HUION PenTablet Pen: Applying InputClass "evdev tablet catchall"
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) HUION PenTablet Pen: Applying InputClass "input-huion-pen"
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (II) systemd-logind: got fd for /dev/input/event16 13:80 fd 38 paused 0
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (II) Using input driver 'libinput' for 'HUION PenTablet Pen'
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) HUION PenTablet Pen: always reports core events
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) Option "Device" "/dev/input/event16"
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) Option "_source" "server/udev"
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (II) input device 'HUION PenTablet Pen', /dev/input/event16 is tagged by udev as: Tablet
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (II) input device 'HUION PenTablet Pen', /dev/input/event16 is a tablet
May 14 14:33:59 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:256C:006E.0006/input/inp
ut24/event16"
[...]
May 14 14:34:19 spatula /usr/lib/gdm3/gdm-x-session[4633]: (II) XINPUT: Adding extended input device "HUION PenTablet Pen Pen (0)" (type: STYLUS, id 22)
May 14 14:34:19 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) Option "AccelerationScheme" "none"
May 14 14:34:19 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) HUION PenTablet Pen Pen (0): (accel) selected scheme none/0
May 14 14:34:19 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) HUION PenTablet Pen Pen (0): (accel) acceleration factor: 2.000
May 14 14:34:19 spatula /usr/lib/gdm3/gdm-x-session[4633]: (**) HUION PenTablet Pen Pen (0): (accel) acceleration threshold: 4
```

My config snippet (this is overly verbose, it just needs the Pen device really). File name is `/etc/X11/xorg.conf.d/01-mypaint-issue680.conf`.

```xorg
Section "InputClass"
  Identifier    "input-huion-sctl"
  MatchProduct "HUION PenTablet System Control"
  Driver "libinput"
EndSection

Section "InputClass"
  Identifier    "input-huion-cctl"
  MatchProduct "HUION PenTablet Consumer Control"
  Driver "libinput"
EndSection

Section "InputClass"
  Identifier    "input-huion-pen"
  MatchProduct "HUION PenTablet Pen"
  Driver "libinput"
EndSection

Section "InputClass"
  Identifier    "input-huion-mouse"
  MatchProduct "HUION PenTablet Mouse"
  Driver "libinput"
EndSection

Section "InputClass"
  Identifier    "input-huion-keyboard"
  MatchProduct "HUION PenTablet Keyboard"
  Driver "libinput"
EndSection
```

Quick test:

![image](https://cloud.githubusercontent.com/assets/61299/15268821/cd724ebe-19e3-11e6-9399-d5f5d25f8a61.png)

All at Z: 25% as reported in the footer.

Scribble test for the annotation brush `deevad/liner` shows ~250 events/sec when MyPaint is run with MYPAINT_DEBUG=1.

**Comment by achadwick** [comment] 2016-05-14 14:19
@0ion9 (and any anyone else suffering from this)

Please can you try running `gtk3-demo` and trying the *Event Axes* and *Drawing Area* tests expanded to the fill size of the screen. Note the device name, it should end in ` Pen (0)`, I guess. Do you see pressure in the first test? Does the second test keep up acceptably?

Try looking at the terminal while drawing, when running with **MYPAINT_DEBUG=1**?

It will reveal checkpoint events ("yo, everyone! save your stuff") and device changes in great detail. Checkpoints happen every ~8 seconds or so when drawing continuously with pressure, and every < 0.5 seconds when drawing without pressure. Checkpoints drive stroke splitting and undo stack entries in freehand mode: each tiles_changed=True bit of captured brushwork below should make an undo stack entry.

```
DEBUG: gui.device: Device change: name='HUION PenTablet Pen Pen (0)' source=GDK_SOURCE_PEN
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.freehand: Processing at 246 events/s (t_avg=0.004s)
DEBUG: gui.freehand: Processing at 243 events/s (t_avg=0.004s)
DEBUG: gui.freehand: Processing at 250 events/s (t_avg=0.004s)
DEBUG: gui.freehand: Processing at 245 events/s (t_avg=0.004s)
DEBUG: gui.freehand: Processing at 249 events/s (t_avg=0.004s)
DEBUG: gui.freehand: Processing at 249 events/s (t_avg=0.004s)
DEBUG: gui.freehand: Processing at 249 events/s (t_avg=0.004s)
DEBUG: lib.command: Stopped recording <Brushwork 0x7fe55a652b90 7.013s None>: tiles_changed=True
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: lib.document: autosave_countdown: autosave will run in 10s
DEBUG: lib.document: autosave: updates detected, doc marked autosave-dirty
DEBUG: gui.freehand: Processing at 251 events/s (t_avg=0.004s)
DEBUG: gui.brushmanager: Loading <ManagedBrush u'history_0' p=None>...
DEBUG: gui.brushmanager: Loading <ManagedBrush u'history_1' p=None>...
DEBUG: gui.brushmanager: Loading <ManagedBrush u'history_2' p=None>...
DEBUG: gui.brushmanager: Loading <ManagedBrush u'history_3' p=None>...
DEBUG: gui.brushmanager: Loading <ManagedBrush u'history_4' p=None>...
DEBUG: lib.command: Stopped recording <Brushwork 0x7fe55be1be10 1.091s None>: tiles_changed=True
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
```

Please try with a newer GTK if you can. The latest stable release is 3.20.4.

**Comment by achadwick** [comment] 2016-05-14 14:33
**SPECULATION AHOY**: It would be bad (and incorrect) if MyPaint was only updating the screen at a checkpoint event. The `<Brushwork>` object is where active stretches of painting are recorded by the freehand mode/tool, but the mode is supposed to update the screen as you paint.

It does it in an idle routine though, for *capture* speed. Idle routines only run when the GLib main loop has nothing to do. So if or something else is genuinely swamped, you could theoretically get really patchy drawing with a rhythm akin to the checkpoints' beat.

There is a long-standing Windows bug with a similar pattern: #390. There are videos there and everything. The idle routine was suggested as a possible cause over there too, but our testers tried a threaded delivery backend there, and it didn't fix anything.

Maybe we should give the user a prefs toggle to turn off the idle routine and deliver input directly anyway. It's one more thing to rule out for testers.

**Comment by achadwick** [comment] 2016-05-14 14:50
The blame probably cannot be attributed to libinput or the xorg driver, if GIMP and Krita suffer. It might be MyPaint's silly input handling, or it might be an old GTK.

**Comment by 0ion9** [comment] 2016-05-14 15:02
I think the brush was deevad/fill. But it *isn't* a performance bug, because it occurs for every brush.. eg. the 1pixel brush gets exactly the same amount of 'lag'.
Zoom level similarly has no effect on lag (but IIRC it was 100% zoom -- the image I posted is actually scaled down from 2500px to 800px after exporting). IMO the bug presents fairly clearly as 'I COULD be rendering, the CPU is not busy, but I'm waiting for (unknown) events before I start rendering'.
(BTW, the 'pen up' idea I started with is false; the delay appears to be the same regardless of whether the pen is near the tablet)

>  please make sure you are actually using a libinput driver, actually verify it as above by looking at Xorg.0.log or /var/log/messages

This is a good point, and is something I specifically did.

Additional versions as requested:

* libinput 1.3.0
* xorg 1.18.3
* linux 4.5.3

Now that issue #643 is fixed, I'm willing to try a newer GTK.

I presume you mean 'GIMP and Krita do **not** suffer'.

**Comment by achadwick** [comment] 2016-05-14 15:08
Wait, libinput is versioned independently of the driver. And ywah, you have been finding that GIMP and Krita do **not** suffer from this, corrected :smile: 

I'm using `libinput10:amd64` 1.2.4-1 on mine right now, and `xserver-xorg-core` 2:1.18.3-1.

**Comment by 0ion9** [comment] 2016-05-14 15:11
Yes, I updated OP with the versions above, and also the version of xorg-input-libinput (1.9)

EDIT: Updating to GTK 3.20.4 fixes this. Marking as upstream.

**Comment by achadwick** [comment] 2016-05-14 15:20
Thanks for the confirmed workaround! :tada:

I just failed to reproduce it with `libinput10` 1.3.0-1 out of unstable, with the rest of the system unchanged. So definitely not anything down at the base of the stack.

**Comment by achadwick** [comment] 2016-05-14 15:21
Retitled and closing. Thanks!

**Closed by achadwick** 2016-05-14 15:21 UTC
Labels: glitch, needs-info, performance, upstream, works-for-me
