### ISSUE TITLE
Document' object has no attribute 'stroke_to

### ISSUE THREAD

**Issue by kensully** [mypaint/mypaint#307] opened 2015-04-30 20:10 UTC
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 1.2.0-alpha.20150430+git.52a7a61
System information: Linux-3.13.0-33-generic-i686-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/drawwindow.py", line 621, draw_sat_spectrum_cb(self=<DrawWindow object at 0xb28978ec (MyPaintDrawWindow at 0xa0ba1c8)>, action=<Action object at 0xa3c00194 (GtkAction at 0xa045e20)>)
            column_limit = 8
            draw_palette(self.app, g, self.app.scratchpad_doc, columns=column_limit, grid_size=grid_size)
  variables: {'column_limit': ('local', 8), 'draw_palette': ('global', <function draw_palette at 0xb290480c>), 'g': ('local', [[153, 153, 153], [133, 148, 153], [114, 144, 153], [95, 140, 153], [76, 136, 153], [57, 132, 153], [38, 128, 153], [19, 124, 153]]), 'self.app.scratchpad_doc': ('local', <gui.document.Document object at 0xb272136c>), 'self.app': ('local', <gui.application.Application object at 0xb27fbfac>), 'columns': (None, []), 'grid_size': ('local', 30.0)}
  File "/usr/local/share/mypaint/lib/scratchpad_palette.py", line 92, draw_palette(app=<gui.application.Application object>, palette=[[153, 153, 153], [133, 148, 153], [114, 144, 15..., [57, 132, 153], [38, 128, 153], [19, 124, 153]], doc=<gui.document.Document object>, columns=8, grid_size=30.0, scale=13.0, offset_x=0.0, offset_y=0.0, swatch_method=<function squiggle>)
                x, y = doc.tdw.display_to_model(x, y)
                doc.model.stroke_to(0.008, x, y, pressure, 0.0, 0.0)
            doc.model.sync_pending_changes()
AttributeError: 'Document' object has no attribute 'stroke_to'
```

**Comment by achadwick** [comment] 2015-04-30 22:24
Duplicate of #109.

**Closed by achadwick** 2015-04-30 22:24 UTC
Labels: duplicate

**Comment by stephanezoa** [comment] 2022-08-07 19:38
i have same trouble
