### ISSUE TITLE
Problen install brushes (Al instalar nuevos pinceles y de versiones anteriores falla). 

### ISSUE THREAD

**Issue by vendettaboom** [mypaint/mypaint#405] opened 2015-08-10 22:56 UTC
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 1.2.0-beta.1+gitexport.a7012b4
System information: Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.2-rafaela
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/filehandling.py", line 932, _recentfilter_func(self=<gui.filehandling.FileHandler object>, rfinfo=<void>)
            """
            if "mypaint" not in rfinfo.applications:
                return False
  variables: {'rfinfo.applications': ('local', <void at 0x7ffeb1aa67f0>)}
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by achadwick** [comment] 2015-08-11 13:54
Thank you for reporting this!

I need to know more about what you were doing when you encountered this error (I read "problem installing brushes", and some reference to an earlier version's error?) Please write in Spanish if it's easier and I'll use Google Translate to attempt an understanding. More detail is better than less detail.

The `_recentfilter_func()` could be made more robust, but I need to know this information so that I can try to reproduce the error myself.

**Comment by vendettaboom** [comment] 2015-08-12 01:51
Ok escribire en español:

El problema se presento al colocar brochas que no eran de la pagina oficial de Mypaint o al menos las recomendadas. Se instalaron brochas de fuentes como Deviant art y de otras paginas, algunas de estas brochas eran de versiones anteriores a Mypaint. Por otro lado instale unas brochas de un programa llamado paintSAI que se usa para dibujar manga. En general con todas esas instalaciones al reiniciar me origino el error que reporte anteriormente. Se aclara que en las versiones de desarrollo también presentaron el mismo problema. Sospecho que las brochas de otras versiones ocasionan problemas con la nueva linea de Mypaint.

**Comment by achadwick** [comment] 2015-08-12 09:25
What pages did you use? // Por favor, puede copiar y pegar las direcciones de Internet que utilizaste?

* MyPaint does not support brushes for Paint Tool Sai™
* MyPaint may have difficulties when loading brushpacks intended for older versions of MyPaint.

**Comment by vendettaboom** [comment] 2015-08-18 00:18
http://atsusakaneytza.deviantart.com/art/Anime-CG-MyPaint-brush-pack-410719720
Todas las de la pagina de Githut
http://corvocollorosso.deviantart.com/art/Brushes-for-mypaint-281981370
http://www.deviantart.com/art/shameless-Paint-Tool-SAI-MyPaint-Brush-Pack-370633532 (presiento que es aqui el problema).

**Comment by achadwick** [comment] 2015-10-11 22:52
This looks like a duplicate of #439, which was fixed recently. @vendettaboom - can you confirm that it is now fixed please, when convenient (the patch will be present in the next beta!)

**Closed by achadwick** 2015-10-11 22:52 UTC
Labels: bug, duplicate, needs-info

**Comment by vendettaboom** [comment] 2015-10-13 01:49
Si todo va bien en la actualización de Mypaint. Gracias

2015-10-11 17:52 GMT-05:00 Andrew Chadwick <notifications@github.com>:

> Closed #405 <https://github.com/mypaint/mypaint/issues/405>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mypaint/mypaint/issues/405#event-432490811>.
>



-- 
Irwin Manuel Boom Gamez
Sociólogo Universidad Popular del Cesar
Estudiando Especialización en Administración de la informatica Educativa
Diplomado en gestión de proyectos de investigación
Activista Cultura Libre
Cel 3107390536

**Comment by MarioPhillips** [comment] 2016-01-29 03:24
I'm not sure if this is the right place to report a bug, but I'm having problems with some brushes in MyPaint. This is the issue: I have windows 10 64 bits, I downloaded MyPaint 1.0.0 32 bits and it worked just fine. I downloaded the last available version for windows and when I ran the program, it asked me something about the brushes, I think some of them were duplicated and asked me to overwrite them, I think, I clicked yes and those brushes are now damaged. I uninstalled and reinstalled both versions several times with no effect. When I install the new version, the brushes get back to normal and it also keeps the damaged duplicates. I kind of like the new version but it works slower than 1.0.0. Thank you.

**Comment by achadwick** [comment] 2016-01-29 14:26
@MarioPhillips 
Thank you for the comment, but it is off topic. This is a closed bug thread. It is not the place to report a new bug.

Please read the [CONTRIBUTING](https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md) file, and the [Reporting Bugs](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs) page in the wiki before reporting. I've just updated the wiki page with a step-by-step guide.

(Apologies for the insistence on not piggybacking issues, but issues need to be kept on topic so that they can marked closed meaningfully.)
