### ISSUE TITLE
KDE/kwin: 1.2.1-beta.0 config sliders do not work, only straight lines in freehand tool

### ISSUE THREAD

**Issue by YAFU** [mypaint/mypaint#665] opened 2016-04-25 22:34 UTC
I have installed MyPaint since a long time from the following ppa:
https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing

I do not use MyPaint frequently, but from some update in these months I have begun to have the following problem:

1- Configuration sliders does not work in the GUI
2- When drawing on the canvas, only straight lines are drawn. The first point of that line corresponds to when you start to draw, and the last point of the line to when you release the button. All this in painting mode (P) selected.

I tried deleting the MyPaint configuration files, but that does not solve the problem.

Using Kubuntu Linux 14.04. I have installed gtk 2.24 and gtk 3.12

**Comment by achadwick** [comment] 2016-04-26 09:24
2. is almost certainly a duplicate of #158. Please remove the Oxygen theme and try again.

1. might also be. Please try the workaround for 2 and report back :smile:

**Comment by achadwick** [comment] 2016-04-26 09:27
This issue tracker is not for direct user support really. We try to limit it so that each thread is a single fixable issue which can be closed by changing the MyPaint code. I won't close this report straight away though because sometimes we can help. Often the feedback is useful too, and sometimes support requests can turn into stuff programmers can actually do something about!

We may not be able to help you straight away here, but don't be discouraged if we can't. Issue trackers don't get that many views, sadly. You may find you get more useful feedback from the [MyPaint Community Forums](http://community.mypaint.org/) - and if our suggested workaround actually works, please share it there.

**Comment by achadwick** [comment] 2016-04-26 09:29
**TRIAGE NOTE:** looks like a user support request, but also like a duplicate of an older configuration issue with a workaround. This issue should be closed after one week if no further information is forthcoming that would allow it to be progressed to a unique `bug` or `enhancement` status.

**Comment by YAFU** [comment] 2016-04-26 12:54
Ok, I had done a very bad google search. And I should not restrict the search to only the last year. Sorry for that.
I'm pretty sure the problem in my system is not as old as that report, it started from just a few months ago (always using the same system and oxygen-gtk engine). I will investigate about what changes have occurred in my system for this to happen.

So yes,  the problem is the same as that report. Changing the gtk engine it works. And if you want to continue using oxygen-gtk engine, the workaround to go to fullscreen and then un-fullscreen every time you open MyPaint also works.

Thank you very much for everything, and I will share this in the forum (with better thread title this time :) )

**Comment by odysseywestra** [comment] 2016-04-27 18:21
Thread moved to: https://community.mypaint.org/t/kde-kwin-workaround-for-1-2-1-beta-0-config-sliders-and-feehand-tool/336

Please continue the conversation there.

**Closed** 2016-04-27 18:21 UTC
Labels: duplicate, user-support
